### ISSUE TITLE
(GraphService) Deserialization Exception When Querying Products with Media in ShopifySharp 6.13.0

### ISSUE THREAD

**Issue by AnandPrabha** [nozzlegear/ShopifySharp#1027]
Hello,

I've encountered an issue with ShopifySharp version 6.13.0 when trying to query products along with their media information. Specifically, the problem arises when I execute a GraphQL query to fetch products and their associated media.
Here is the query I am using:
{
    products(first: 1)
    {
        nodes
        {
            id
            title
            media(first: 1)
            {
                nodes
                {
                    alt
                    id
                    mediaContentType
                    preview
                    {
                        image
                        {
                            id
                            url
                        }
                    }
                }
            }
        }
    }
}
Upon executing this query, I receive the following exception:
One or more errors occurred. (Deserialization of interface types is not supported. Type 'ShopifySharp.GraphQL.IMedia'. Path: $.nodes[0].media.nodes[0] | LineNumber: 0 | BytePositionInLine: 36.)
seems that the library struggles to handle the deserialization of interface types correctly, particularly when fetching media nodes associated with products.
I would appreciate any guidance on how to resolve this issue or if there are any workarounds available

**Comment by nozzlegear** [comment]
Thanks for the report @AnandPrabha! Could you show me the code you're using to send the Graph query?

**Comment by AnandPrabha** [comment]
The suggested code didn't work initially. However, after trying to add __typename to the media nodes, the issue was resolved. Here's the updated and working structure:
{                
products(first: 1)
{
nodes
{
id
title
media(first: 1)
{
nodes
{
__typename
alt
id
mediaContentType
preview
{
image
{
id
url
}
}
}
}
}
}
}

**Comment by clement911** [comment]
Ah yes, I had it at the wrong place.
