### ISSUE TITLE
(GraphService) How to Deserialize JSONL Content from BulkOperation to .NET Classes

### ISSUE THREAD

**Issue by AnandPrabha** [nozzlegear/ShopifySharp#1035]
Hello,

Successfully created and executed a bulk query. After fetching the results, I received a URL pointing to a JSONL (JSON Lines) file containing the data. Here's a snippet of my code to fetch the bulk operation result:
var bulkOperationStatusQuery = @"
                        query
                        {
                            node(id: """ + bulkOperationId + @""")
                            {
                                ... on BulkOperation
                                {
                                    id
                                    status
                                    partialDataUrl
                                    createdAt
                                    rootObjectCount
                                    objectCount
                                    errorCode
                                    fileSize
                                    url
                                }
                            }
                        }";
bulkOperation = await svc.SendAsync<ShopifySharp.GraphQL.BulkOperation>(bulkOperationStatusQuery);
bulkOperationStatus = (BulkOperationStatus)bulkOperation.status;
var resultUrl= bulkOperation.url;

I'm now looking to deserialize the JSONL content from the resulting file into .NET classes for further processing.Specifically, I would like to understand how to:
**1)** Deserialize each line of the JSONL file into appropriate .NET classes, considering the file contains different types of objects (variants, media, metafields, product information).
**2)** Handle the relationships between these objects, as they reference each other using a parent ID.

Is there an existing utility within ShopifySharp, or would I need to implement a custom solution?
Any advice or pointers to resources would be greatly appreciated.

Thank you!

**Comment by clement911** [comment]
As of today, ShopifySharp doesn't offer any way to parse JSONL results from bulk queries.

So I'm afraid that you'll have to implement something custom

Reference to docs: https://shopify.dev/docs/api/usage/bulk-operations/queries#the-jsonl-data-format

**Comment by AnandPrabha** [comment]
Thank you for the help! I've crafted a custom solution for JSONL parsing
