### ISSUE TITLE
Add product into Exising Channels

### ISSUE THREAD

**Issue by shafaqat-ali-cms365** [nozzlegear/ShopifySharp#1039]
Hi
When adding/updating a product, is there any option to provide a list of sale channels?
I have 4 sales channels but by default product is being added into 1 channel. I am currently manually adding products into different channels.

**Comment by mbaugus** [comment]
The only option in the Product API involving a Sales Channel is the "published_scope" property of Product, and it only accepts two values.

> web: The product isn't published to the Point of Sale channel.
> global: The product is published to the Point of Sale channel.

I would try setting the Product.PublishedScope to "web" and see what happens.

If that doesn't work,  an upload file will add them to all channels.

**Comment by mbaugus** [comment]
> What does "upload file" means?

Importing the products using the Shopify website, uploading them via a .CSV file.
