### ISSUE TITLE
webhooks parse data

### ISSUE THREAD

**Issue by vladimirGI** [nozzlegear/ShopifySharp#104]
hi there,
Webhooks subscriptions work well. After Shopify calls a webhook, i need to parse manually the request (JSON object). I need to work with Order object (https://help.shopify.com/api/reference/webhook) & the properties of ShopifyOrder & the order update webhook request objects are completely different. So I had to create a new object to parse the data. I wonder if there is something built-in in the library that I miss

**Comment by nozzlegear** [comment]
Thanks for reporting this! Do you have a sample of the data that's getting sent with the webhook? I've got the order update webhook running in one of my own apps and it seems to parse into a ShopifyOrder without any problems.

**Comment by vladimirGI** [comment]
hey, thanks for a quick look. I was able to find a problem on my end. The library works great. Thanks for a great job!!!

**Comment by marek-benes** [comment]
@vladimirGI  Vladimir, I have the same problem. Could you tell me how did you solve it?
