### ISSUE TITLE
API get checkout by token not working

### ISSUE THREAD

**Issue by concua1111** [nozzlegear/ShopifySharp#1046]
hm.. I'm integrating Shopify sharp with .net API.  I'm facing this error. I think the checkout has some problem: "Error converting value \"51e23315cc62d53897c9e151815986bb\" to type 'System.Nullable`1[System.Int64]'. Path 'checkout.line_items[0].id'."

**Comment by concua1111** [comment]
key and id should be strings. I pulled out checkout and saw that the line item id was a string like "51e23315cc62d53897c9e151815986bb". but in the code the id is being inherited with type long.

**Comment by concua1111** [comment]
![image](https://github.com/nozzlegear/ShopifySharp/assets/62086665/18e19ce9-8752-4e73-be34-f43e62c83860)

**Comment by nozzlegear** [comment]
Hey! Thanks for the bug report. I should be able to fix this right away. Which version of ShopifySharp are you using here?

**Comment by concua1111** [comment]
hi. thanks for your response, I'm using ver 6.13.0.

**Comment by nozzlegear** [comment]
Okay, thanks! I’ll get a new version published with a fix for this right away.--Joshua HarmsOn Mar 27, 2024, at 20:26, sunglv ***@***.***> wrote:﻿
hi. thanks for your response, I'm using ver 6.13.0.

**Comment by concua1111** [comment]
hi @nozzlegear . And also missing some fields in "line_item" and "applied_discounts" of the checkout object. kindly update this also. thank you
![image](https://github.com/nozzlegear/ShopifySharp/assets/62086665/463574ea-8e77-45a9-942a-fd24cf79825d)
