### ISSUE TITLE
Refresh Scriptag

### ISSUE THREAD

**Issue by Saquibadil** [nozzlegear/ShopifySharp#105]
How can we force scripttag to refresh from the server. One way to do it is to add version as querystring but how can we do that for the script tags. 

Thank you!

**Comment by nozzlegear** [comment]
Hi @Saquibadil, I'm not sure I understand the question. Setting a version parameter in the querystring is the recommended way to refresh a ScriptTag once you've updated your script. If you want the tag to always load the latest version no matter what, you could set your server to [add a No-Cache header to the script response](https://msdn.microsoft.com/en-us/library/system.web.httpcachepolicy.setmaxage(v%3Dvs.110).aspx):

```cs
Response.Cache.SetCacheability(HttpCacheability.Public);
Response.Cache.SetMaxAge(new TimeSpan(0, 0, 0)); // max-age=0
```

**Comment by Saquibadil** [comment]
I am looking for a way to add/change version number for the merchants that have already installed the app. So it loads the script from the server right after I change the script.

**Comment by nozzlegear** [comment]
Okay, I think I understand what you want to do! The best way to change the ScriptTag version for merchants that have already installed your app is to use the `ShopifyScriptTagService.UpdateAsync` method, which will let you modify an existing ScriptTag's `Src` property and switch it to your new version.

If you have more than one tag per shop you'll need to keep track of each tag's id after you create it, but if you only have one script tag you could just list the script tags and modify the only one that gets returned:

```cs
var service = new ShopifyScriptTagService(shopDomain, accessToken);
var tags = await service.ListAsync();
var tag = tags.First();

// Update the tag's Src to use the newest version
int version = 2;
tag.Src = $"https://example.com/scripts/my-script.js?version={version}";
tag = await service.UpdateAsync(tag);
```
