### ISSUE TITLE
ShopifyOrder is missing the 'refunds' property

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#107]
The ShopifyOrder object is missing the [documented 'refunds' property](https://help.shopify.com/api/reference/order#refunds-property).

All fields are document on the Refund API page: https://help.shopify.com/api/reference/refund

**Comment by darkstar74** [comment]
I've been working on this a bit this evening and will try to get it worked up and tested over the weekend.

Let me know if anyone else is in the process of implementing this property so we do not overlap efforts.

**Comment by clement911** [comment]
Hi,

I was considering starting on this, but if you've started already I'll let you finish up.

Just one thing, be sure to re-use the existing _ShopifyTransaction_ (for _refunds.transactions_) and _ShopifyLineItem_ (for _refunds.refund_line_items.line_item_).

Thanks!

**Comment by darkstar74** [comment]
Howdy. We'll have a RefundLineItem entity that includes the ShopifyLineItem and the Refund entity utilizes the ShopifyTransaction. That should handle the refunds property on the order.

In addition I reckon we'll need a RefundService. The main item there is getting the transaction(s) correct via the API. Isn't there some issues with getting Shopify to deal with them correctly? 

I recall reading something in the Shopify forums about transactions via the API not acting right - though it might just pertain to creating orders.

**Comment by clement911** [comment]
I'm not aware of any issues. With the order api, I don't believe you can attach transactions while creating an order, as you need to create them with the transaction api...

**Comment by clement911** [comment]
Pull request submitted https://github.com/nozzlegear/ShopifySharp/pull/110

**Comment by nozzlegear** [comment]
Thanks for the pull request! Changes should be available on Nuget with version 3.5.2.

**Comment by clement911** [comment]
Thanks!
