### ISSUE TITLE
Investigate moving from RestSharp to another HTTP package.

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#108]
The biggest blocker on adding .NET Core support (#58) is our RestSharp dependency not supporting it itself. If we can move to a different HTTP lib that supports all runtimes, we should then be able to add Core support. This would be a breaking change, so I'm scheduling it for v4.

**Candidates**

- [ ] [Fubar Portable RestSharp](https://github.com/FubarDevelopment/restsharp.portable)
- [ ] [.NET's HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx)
- [x] [Flurl](https://github.com/tmenier/Flurl)

**Comment by vinhch** [comment]
I have a suggest: [Fubar Portable RestSharp](https://github.com/FubarDevelopment/restsharp.portable)
It have some differents compared to original RestSharp, ex: don't support RootElement in RestRequest, but it can be easily solved by using Newtonsoft Json.

**Comment by nozzlegear** [comment]
Thanks for the suggestion! I've used that one before with a couple of UWP apps and had a pretty good experience with it. If anyone happens to read this and has their own suggestion, I'm open to hearing them all!

**Comment by clement911** [comment]
Is it an option to use HttpClient directly?

**Comment by nozzlegear** [comment]
I'm not sure, to be honest! I know I had originally wanted to use either HttpClient or WebClient, but it had some kind of limitation that made me choose RestSharp. I don't remember which one was limited though, and it's been a long time since I've used anything other than RestSharp. Will definitely add to the list of clients to look at.

**Comment by nozzlegear** [comment]
Adding [Flurl](https://github.com/tmenier/Flurl) to the list.

**Comment by nozzlegear** [comment]
I've played around with some of these and right now I'm thinking Flurl is a great match. It's got some nice and simple methods that are similar to RestSharp, works on .NET Core, and it lets us drop down to the .NET HttpClient when we need to. I'll probably start work on the next major release of ShopifySharp this weekend or next weekend, aiming for .NET Core support!

**Comment by clement911** [comment]
Looking forward to the .net core support!
