### ISSUE TITLE
1 issue one queston

### ISSUE THREAD

**Issue by NormTheThird** [nozzlegear/ShopifySharp#109]
When i make this call:

                var filters = new ShopifyProductFilter { Title = _title.Trim() };
                var task = Task.Run(async () => await this.ShopifyProductService.ListAsync(filters));

it returns every product that contains the _title text instead of the exact title text.  Is there a way to specify a field that says the title should contain or be specific?  Is there a way to look up a product by a metadata field?

How can i look up an order by the number or the name?

Thanks

**Comment by nozzlegear** [comment]
Hey Trey, sorry I didn't get a chance to reply to your email. My inbox is super full right now and I'm having trouble getting through it. As far as I know there's no way to tell the Product API to only return the specific title; I get the same thing when I try to search for a product, so I think the behavior you're getting is what they intended. 

The answer on looking up an order by the name/number is a little different: technically it was possible at some point, may no longer be possible now (it isn't documented or supported by Shopify), and it isn't supported by ShopifySharp. According to [this answer on StackOverflow](http://stackoverflow.com/a/29955343/7086074) from 2015, you might be able to add `name=123456` to your list API call to get what you're after. 

Unfortunately that's not documented by Shopify anywhere, which means it isn't supported and might not even work anymore.

**Comment by NormTheThird** [comment]
Ok thanks for the help.  I ended up making an http call to get the order information which gives me the order id and then I just parse out the id and call your api call to get the order with the id.  Seems to work and doesn’t add much time to the call.

Thanks.
Trey
