### ISSUE TITLE
StoreCredit Implementation - question

### ISSUE THREAD

**Issue by dmequus** [nozzlegear/ShopifySharp#1102]
Hi,

Any plans to implement the relatively new StoreCredit create/update from the GraphQL Admin API?

If it's not something 'on the list', I'll look at rolling my own as it's just for a 'one off' data upload for a new store.

Thanks!

**Comment by clement911** [comment]
The entire graphQL api is supported, via the `GraphService` class.

**Comment by dmequus** [comment]
Excellent - I was only looking in the wiki pages and with your help, I've now found it in the code. Should be good from here. Thanks!
