### ISSUE TITLE
Does GraphService use the extension DI execution policies?

### ISSUE THREAD

**Issue by amcroce** [nozzlegear/ShopifySharp#1105]
Is not clear to me, I guess I should handle the rate limit myself when using GraphService but right now I will start using it multiple products and collections metafields (`metafieldsSet` mutation) and would like to avoid doing extra work if possible.

I define the policy like this:
`services.AddShopifySharp<RetryExecutionPolicy>();`
And it works perfect with REST API requests.

**Comment by nozzlegear** [comment]
Hey! It will indeed handle the rate limit policies. The `LeakyBucketExecutionPolicy` is the best one for GraphQL requests (in my opinion), as it has a lot of logic built specifically for GraphQL requests; but you can use any policy including the `RetryExecutionPolicy` that you use right now.

**Comment by amcroce** [comment]
Excellent!

Thank you for your quick response 🙌🏼
