### ISSUE TITLE
Error Attempting to create customer.

### ISSUE THREAD

**Issue by alexew1959** [nozzlegear/ShopifySharp#1116]
I am attempting to create a new customer using the model code at https://github.com/nozzlegear/ShopifySharp/wiki/Customers.  I am getting the error 'Object reference not set to an instance of an object.'.  The error details are:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ShopifySharp
  StackTrace:
   at ShopifySharp.Infrastructure.Serializer.DeserializeWithNewtonsoft[T](String json, String rootElementPath, Nullable`1 dateParseHandlingOverride)
   at ShopifySharp.Infrastructure.Serializer.Deserialize[T](String json, String rootElementPath, Nullable`1 dateParseHandlingOverride)
   at ShopifySharp.ShopifyService.<>c__DisplayClass27_0`1.<<ExecuteRequestCoreAsync>b__0>d.MoveNext()
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
   at ShopifySharp.ShopifyService.<ExecuteRequestCoreAsync>d__27`1.MoveNext()
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__29`1.MoveNext()
   at ShopifySharp.CustomerService.<CreateAsync>d__8.MoveNext()
   at ExpresswayAPI.EndPoints.SignCustomerEndpoints.<>c__DisplayClass0_0.<<MapSignCustomerEndpoints>b__11>d.MoveNext() in C:\Users\alexew\source\repos\ExpresswayAPI\ExpresswayAPI\EndPoints\SignCustomerEndpoint.cs:line 132

  This exception was originally thrown at this call stack:
    [External Code]
    ExpresswayAPI.EndPoints.SignCustomerEndpoints.MapSignCustomerEndpoints.AnonymousMethod__11(ExpresswayAPI.DTOs.CustomerListDTO) in SignCustomerEndpoint.cs

Since the error implies the issue is with serializing with Newton Soft, I have added an explicit call to perform that action independent of ShopifySharp and the class is deserialized without issue.  

The class is created as
                    Customer custadd = new Customer()
                    {
                        FirstName = cust.firstname,
                        LastName = cust.lastname,
                        Email = cust.email,
                        Addresses = new List<Address>()
                        {
				new Address()
 		                {
                                       Address1 = cust.address1,
                                       Address2 = cust.address2,
                                       City = cust.city,
                                       Province = cust.province,
                                       ProvinceCode = cust.provincecode,
                                       Zip = cust.postalcode,
                                       Phone = cust.phone,
                                       FirstName = cust.firstname,
                                       LastName = cust.lastname,
                                       Company = cust.company,
                                       Country = cust.country,
                                       CountryCode = cust.countrycode,
                                       Default = true
                                }
                        }
                        VerifiedEmail = true,
                        Note = cust.website,
                        State = "invited",
                        Tags = "signs",
                  }

**Comment by nozzlegear** [comment]
Interesting, thanks for reporting this! Do you know which property exactly was causing the issue? If not, would you be able to copy the problematic json (stripping out sensitive customer data) so I can test it?

**Comment by alexew1959** [comment]
[TestCustomer.zip](https://github.com/user-attachments/files/18080935/TestCustomer.zip) contains a project running the Create example found at https://github.com/nozzlegear/ShopifySharp/wiki/Customers.  It generates the same error. I have removed my url and key.

**Comment by alexew1959** [comment]
I have created a second test project with nothing but ShopifySharp referenced in the project - same issue.

**Comment by alexew-exp** [comment]
downloaded shopifysharp project to debug
In Serialize.cs
![image](https://github.com/user-attachments/assets/4f76000d-eacc-4343-86c9-c28496e55c07)
The SelectToken is returning null

**Comment by alexew-exp** [comment]
further followup - in the return I have rootElementPath should be customers and not customer.   Not sure if there is a valid situation where it should be customer.

**Comment by alexew1959** [comment]
Upon some further reading I ran across a post that indicated that unless you used a URL in the  form {storename}.shopify.com for post, put and delete methods for any rootelement, it would simply do nothing and return a list of everything for the root element. Once I adjusted my URL  your code worked.  Not sure who though up the "Feature" (grrr), but might I suggest you add a check and generate an error if the check fails until an adult at shopify either  rethinks this feature or at least explains it.

**Comment by nozzlegear** [comment]
Ah, glad you got it figured out @alexew1959! I'd been planning on looking at this today. It's a really dumb "feature", I have no idea why their API works like that. The branch I'm working on right now is introducing support for true dependency injection, which is going to let me add support for logging. We'll finally be able to add warnings for this bug after that.
