### ISSUE TITLE
Page Title and Handle list filters are "long?"

### ISSUE THREAD

**Issue by rocky1983** [nozzlegear/ShopifySharp#112]
Why they are "long?" fields?
I think they should be stringa

  //
    // Summary:
    //     Options for filtering ShopifySharp.ShopifyPageService.CountAsync(ShopifySharp.Filters.ShopifyPageFilter)
    //     and ShopifySharp.ShopifyPageService.ListAsync(ShopifySharp.Filters.ShopifyPageFilter)
    //     results.
    public class ShopifyPageFilter : ShopifyPublishableListFilter
    {
        public ShopifyPageFilter();

        //
        // Summary:
        //     Filter by page handle.
        [JsonProperty("handle")]
        public long? Handle { get; set; }
        //
        // Summary:
        //     Filter by page title.
        [JsonProperty("title")]
        public long? Title { get; set; }
    }

**Comment by nozzlegear** [comment]
Yeah those should definitely be strings. Good catch!

**Comment by nozzlegear** [comment]
The fix should be available on Nuget with version 3.5.3. Thanks for reporting this!
