### ISSUE TITLE
OrderService.ListAsync returns 50 orders, not 250

### ISSUE THREAD

**Issue by swood712** [nozzlegear/ShopifySharp#113]
This code:

var orderService = new ShopifyOrderService(myShopifyUrl, shopAccessToken);
IEnumerable<ShopifyOrder> orders = await orderService.ListAsync(new ShopifyOrderFilter() {Status = "open"});

My store has > 50 open orders. This method returns 50 orders max, not 250 as documented.

Am I missing something?

Shopify returns "pages" of orders in blocks of 50. So do you need to get the total number of "pages" of orders as follows:

note, required Json is: "orders.json?limit=50&page={pageCount}"

var service = new ShopifyOrderService(myShopifyUrl, shopAccessToken);
int orderCount = await service.CountAsync();

double pageCount = orderCount/50;
int remainder = orderCount%50;

then

for (i < pagecount) { get orders by page }

if (remainder > 0) { get remaining orders by final page }

pseudo code:

             var service = new ShopifyOrderService(myShopifyUrl, shopAccessToken);
             int orderCount = await service.CountAsync();

            double pageCount = orderCount/50;

            int remainder = orderCount%50;

            List<Order> orders = new List<Order>();

            for (int i = 0; i < pageCount; i++)
            {
                orders.AddRange(GetOrdersByPage(i + 1));
            }

            if (remainder > 0)
            {
                orders.AddRange(GetOrdersByPage(pageCount + 1));
            }

            return orders;

**Comment by nozzlegear** [comment]
Hey @swood712, you're looking for the `Limit` property on the `ShopifyOrderFilter` class. Shopify's API defaults all list calls to a 50 object limit, but you can increase it to 250 by adding `Limit=250`.
