### ISSUE TITLE
Better test tooling for v4.

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#118]
One of the reasons it can sometimes take so long for me to merge a pull request is because tests can only currently be run in Visual Studio with a special MSpec test extension. For v4, I'd like to add PowerShell and Bash scripts for running MSpec tests from the command line. Every test will need to be updated with the `Tags('TestSubjectName')` attributes, which lets the CLI runner filter tests instead of running the entire suite at once:

```bash
mspec.exe --include "TestSubjectName" ShopifySharp.Tests/bin/debug/ShopifySharp.Tests.dll
```
or
```bash
mspec.exe --exclude "Cannot-Be-Tested" ShopifySharp.Tests/bin/debug/ShopifySharp.Tests.dll
```

We'll also need documentation for both creating tests and running those tests. Finally, I want to add automated testing via Travis-CI like [Shopify Prime](https://github.com/nozzlegear/shopify-prime).

**Comment by nozzlegear** [comment]
I'm thinking I'll rewrite the tests to use NUnit, xUnit or MSTest, which can all be run from the dotnet command line (and are probably more familiar to most C# devs).

**Comment by alectec** [comment]
I'm just now getting back to finishing the AbandonedCheckouts piece and I noticed the test setup.  I became familiar with it but certainly am more familiar with MSTest and NUnit.  I mostly use those for mocked tests and integration tests.
If you are planning to rewrite; would it be appropriate for me to write the AbandonedCheckout entity test in MSTest or whatever you decide?

**Comment by nozzlegear** [comment]
I'll probably definitely rewrite them, not sure to which one yet as I haven't used anything but MSpec. For now you should probably just write them in MSpec and I'll make sure they get converted to whatever we decide in 4.0.

**Comment by nozzlegear** [comment]
Will use [Davenport.Net](https://github.com/nozzlegear/davenport.net) for reference when configuring automated testing with AppVeyor.

**Comment by mobbsie** [comment]
Hi @alectec 
How are you getting on with the AbandonedCheckouts?  I need to get this integrated quite quickly for a requirement I have now but don't want to replicate work if you are already close to having it committed.  I am happy to test it if you are ready for me to do so.
