### ISSUE TITLE
Consider dropping the `Shopify` prefix from all classes, interfaces, services, etc.

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#119]
Prefixing every single object in this library with `Shopify` can make things grossly verbose. For v4 I'm considering removing all of those prefixes, so e.g. `ShopifySharp.ShopifyShop` would just become `ShopifySharp.Shop`. C# namespace should already prevent most name conflicts, and for everything else developers can just use namespaces or aliases.

**Comment by clement911** [comment]
I see.
Have you considered using 'Sp' for the prefix? ShopifySharp.SpShop?
Without the prefix there just could be ambiguities if your own code has classes with the same names, for example you may have a Customer or Order class already and so you would have to use the fully qualified name (ok I admit I do have a Customer and Order class in my own code so i kind of have selfish motives here :) But it's true :)

**Comment by alectec** [comment]
Both are good points.  I'm personally anti-prefix but also understand the name clashing is going to happen.     For coders using the SS library, you could resort to using an alias directive such as using ShopifyOrder = ShopifySharp.Order or vice versa.

**Comment by nozzlegear** [comment]
I've also got Customer and Order classes in my own app. 😁 This certainly isn't set in stone, just something I wanted to put out here and see how other people using the lib feel about it. Like @alectec said, the easiest way to prevent clashes while still shortening the names would be to use the new C# using aliases where you need them:

```cs
using ShopifyOrder = ShopifySharp.Order;
using ShopifyShop = ShopifySharp.Shop;
```

**Comment by clement911** [comment]
Yeah for sure. I don't mind and don't feel very strongly about this...

**Comment by ernestogutierrez** [comment]
I agree that having the Shopify prefix is not necessary (or any prefix), but I also have some classes named as Order, Customer and so on.

I vote to remove the prefix in v4 and let the developers to choose if they want to use "using aliases" or use namespace.class as ShopifySharp.Order if they want.

**Comment by nozzlegear** [comment]
Shopify prefixes have been dropped in the 4.0 branch.
