### ISSUE TITLE
DateTime properties should be replaced by DateTimeOffset

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#120]
The problem with DateTime is that they are expressed in the timezone of the server.

DateTimeOffset is nice because it stores the utc offset, which will match the time zone of the Shopify store. I just ran a couple of tests by changing the store time zone (this is set by the merchant in the Settings/General/TimeZone of the Shopify admin) and Shopify always returns the offset that is set by the store in the json serialized date.

DateTimeOffset also plays nice with json.net and can be converted to a DateTime.

What do you think?

**Comment by clement911** [comment]
The alternative I'm looking at with ShopifySharp v3 is to get the timezone from the ShopifyShopService and then do the conversion manually. If ShopifySharp objects returned DateTimeOffset in the first place, I wouldn't need to do that because the offset would already be included in the date.
In my scenario I need to format some dates on the server, and I want them to be expressed in the store's timezone...

**Comment by clement911** [comment]
And if we are going to do this we should also update the properties of Filter objects...

**Comment by alectec** [comment]
Good thought.  This would be useful when comparing dates against transaction logs or such.

I'm working on the AbandonedCheckout object right now.  If we all agree, I will go ahead and used DateTImeOffset going forward.  I plan to work on Province and Refund next.

**Comment by nozzlegear** [comment]
This looks like a good solution to me. I haven't used DateTimeOffset before, so I was worried that it would be somewhat difficult to convert it to DateTime where necessary. It looks like you can just do `offset.DateTime` though, so I don't have any problems with this! I'll mark it for v4.

**Comment by nozzlegear** [comment]
This has been implemented in the v4 branch 👍

**Comment by clement911** [comment]
Great.
On the filer side, does it mean that datetime filters will be serialized with timezone info instead of utc?
e.g

`/admin/orders.json?status=any&limit=50&page=1&order=created_at%20asc&created_at_min=2014-12-31T00:00:01-06:00`

instead of currently

`/admin/orders.json?status=any&limit=50&page=1&order=created_at%20asc&created_at_min=2014-12-31T00:00:01Z`

Not necessarily an issue but I am wondering what would be the impact. Maybe none at all but it seems to me that the utc way is less ambiguous. When you start considering Daylight savings and the fact that the offset can change throughout the year it gets interesting. It's possible it will be just fine and but I just want to get that thought out of my head and see if anyone knew more that I do about this!
