### ISSUE TITLE
Error: Oauth error invalid_request: The authorization code was not found or was already used

### ISSUE THREAD

**Issue by sharad225** [nozzlegear/ShopifySharp#121]
Hi,

I am trying to install our public app on a Shopify store and the `code` returned in the redirect URL is used for generating the access token.
But our call to Shopify API for generating access token is always resulting in the following error:
"oauth error invalid request the authorization code was not found or already used"

We did this exercise of installing, uninstalling and reinstalling with our Shopify store owner, but kept getting the same error.
How do we get this error resolved and be able to generate the Shopify access token?
Please help.

Regards,
Sharad

**Comment by clement911** [comment]
Auth codes can only be used once. Anytime you install the app you must request access again by redirecting the user with ShopifyAuthorizationService.BuildAuthorizationUrl

**Comment by sharad225** [comment]
Hello Clement911, Thank you for your reply.

We are using the auth code only once and that too for generating the access token. 
Let me explain what I am doing:

As soon as the Shopify show onwer clicks to accept the installation of our app, he gets redirected to the following URL:

http://mywebsite.com/?code=d119551fb7cdd820012c6b2cb7b12495&hmac=10976937c09a1f1e3db6275d12cae8fbd43415a6d5b031ec14a70128b8fe9dfe&shop=<shopifysite>.myshopify.com&state=11122777&timestamp=1478065253

mywebiste.com is our website which integrates with the Shopify Shop and accesses various APIs through the access token and <shopifysite>.myshopify.com is the actual Shopify Shop.

This redirected URL is being provided to us by the Shopify Shop owner in an email.

This URL contains the `code `parameter. We take this `code `parameter and hit another Shopify API for generating the access token - using the following URL:
https://<shopifysite>.myshopify.com/admin/oauth/access_token and pass the following 3 POST parameters : client_id, client_secret and code

We haven't yet written the program for the creation of access token, instead we do this process of generating the access token through POSTMAN, which is a manual process. We are planning to write the script which will automatically parse the redirected URL and generate the access token, but as of now we are doing this manually.

Let me know any other details you will require and I will provide it.
Regards,
Sharad

**Comment by ernestogutierrez** [comment]
If you are not actually using ShopifySharp yet but using the API with other tools, I would suggest you to ask in [StackOverflow ](http://stackoverflow.com) or [the Shopify forums](https://ecommerce.shopify.com/forums). You should get a lot of people looking to your question.

**Comment by nozzlegear** [comment]
Hey @sharad225, I'd definitely look over what your process in Postman to make absolutely sure that you're only using the OAuth code once. This error will only happen when a code is being reused, as you can only use it one single time to get an access token. Once you've got the access token, you should only ever be using that to make requests to the Shopify API.

If you're absolutely sure that you are only using it once, I would agree with @ernestogutierrez that StackOverflow or the Shopify forums might be better equipped to help you out with this. If you start using ShopifySharp and run into any problems, we'd be happy to help with that!

**Comment by sharad225** [comment]
Hello to all who contributed here!
With all those inputs I understood that the problem might be that the generated code is being used before actually being used for generating the access token.
I called my customer and asked him to share screen to see he is not doing anything which is making the `code` getting used before we get to use it.

He installed our app and then he pressed the browser back button and then I realised this action of his is actually making the code go back to his store and in turn getting used and this is what the error said when we tried to use it for generating the access token.
I stopped him from hitting the browser back button and asked him to send over the `code` to us.
We hit the access token generating API and we got the access token. 

Thanks to all who helped me see into the problem and helped me in resolution.

Kind Regards,
sharad

**Comment by nozzlegear** [comment]
Glad to hear you got it working!

**Comment by ajaysaini99** [comment]
Hi,  can anyone please guide me to get the permanent Access token ( access_token as per docs ) in react and node embedded app. Where and how do I have to make  post request ( like proper code cause I am not getting any way to make a post request in koa with request params ) in the code generated by shopify cli .

**Comment by nozzlegear** [comment]
Hey @ajayak, this repository is for a C# Shopify package, but it sounds like you're using JavaScript. Since you mentioned Koa too, I'd recommend asking your question on [Shopify's official Koa auth middleware repository here](https://github.com/Shopify/koa-shopify-auth). You'll probably find somebody who's more knowledgeable about using Shopify with JS/Node there!

**Comment by ajayak** [comment]
> Hey @ajayak, this repository is for a C# Shopify package, but it sounds like you're using JavaScript. Since you mentioned Koa too, I'd recommend asking your question on [Shopify's official Koa auth middleware repository here](https://github.com/Shopify/koa-shopify-auth). You'll probably find somebody who's more knowledgeable about using Shopify with JS/Node there!

@ajaysaini99 this is for you 😄

**Comment by hashhesh** [comment]
> Hello to all who contributed here! With all those inputs I understood that the problem might be that the generated code is being used before actually being used for generating the access token. I called my customer and asked him to share screen to see he is not doing anything which is making the `code` getting used before we get to use it.
> 
> He installed our app and then he pressed the browser back button and then I realised this action of his is actually making the code go back to his store and in turn getting used and this is what the error said when we tried to use it for generating the access token. I stopped him from hitting the browser back button and asked him to send over the `code` to us. We hit the access token generating API and we got the access token.
> 
> Thanks to all who helped me see into the problem and helped me in resolution.
> 
> Kind Regards, sharad

@sharad225 , many thanks sharad, this explanation helped a lot
