### ISSUE TITLE
Add Filter or Service to retrieve Store order by Display Id (Order Name) rather than Shopify Order Id

### ISSUE THREAD

**Issue by ZubyH** [nozzlegear/ShopifySharp#127]
The ShopifyOrderService isn't yet able to retrieve an order by the Order Display Id, which is the only Id that a store owner would know an order by.

This would be extremely helpful in diagnosing bad orders which a customer would expect to be imported into my app. The rationale is that the Store Owner would provide me an Order Display Id for an order which they expect to be imported, or to be in a certain state - and I can run the ShopifyOrderService to retrieve the order details and diagnose any possible data issues

**Comment by clement911** [comment]
I don't think the api can do that.
That being said, the owner can easily grab the order id from the url...

**Comment by ZubyH** [comment]
I managed to do this by creating my own order filter which extends ShopifyOrderFilter, and adding a new `[JsonProperty("name"]` to the filter.

```
public class ExtendedOrderFilter : ShopifyOrderFilter
    {
        //
        // Summary:
        //     The Display Id of an order as seen in a Shopify Storefront
        //     
        [JsonProperty("name")]
        public string Name { get; set; }
    }
```

Thanks for noting the Shopify Order Id shows in the URL, didn't think to look there!

**Comment by nozzlegear** [comment]
Thanks for the suggestion! This has been possible for a while, but it's completely undocumented by Shopify which is why I've been hesitant to include it in the lib. It's probably the most common question I get though, and there's even several issues filed here on GitHub from people wondering how to do this. It's probably time we add support for this, so I'll schedule it for v4 and just make sure there's a warning about it being unsupported by Shopify and liable to change at any time.

**Comment by ZubyH** [comment]
No problemo, however I would warn - when I've been testing this against various stores, it seems each store can change the Display Id prefix. The default seems to be #, but I've also seen some stores with ORDER and other order number prefixes.

Including it may just cause a lot more issue than success. I can't find a way of checking the Store's Order prefix programatically either.

Just a note.

**Comment by nozzlegear** [comment]
Thanks for the warning, I was wondering about that myself. It's probably best to just send whatever the developer passes to the method instead of trying to figure out the prefix. It'll be up to the dev to determine what to pass to the search method.

**Comment by ZubyH** [comment]
After thorough testing I find that actually this doesn't work! It was a fluke that I initially found the right results! 

The Shopify API seems to completely ignore order_number being passed in either as a filter, or a direct parameter to the REST request. Bit of a shame!

Closing this issue

**Comment by nozzlegear** [comment]
That's too bad, I was hoping it was still working. I haven't had the need for it myself so never had a chance to test it out. Thanks for letting us know!

**Comment by ZubyH** [comment]
Yeah would have been nice. It's purely for debugging/support purposes if user's have issues with data on their Shopify orders - much easier for our side to investigate using the display ID as user's rarely send Shopify ID's along with their issue. 

May just implement a GetAll function and filter the returned list by Display Id. Let's see.

**Comment by HakanL** [comment]
I tried this just now and it works great with adding a query parameter called Name, so I think this should get implemented.
