### ISSUE TITLE
ShopifyMetafield is missing properties

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#130]
Hi,

It looks like the ShopifyMetafield class is missing the `created_at `and `updated_at` properties.

Also, I'm not sure why the `Namespace` property is an object and not a string?

**Comment by nozzlegear** [comment]
Ha, I'm getting deja vu from this. I swear this was already reported and fixed not that long ago! I think the namespace was set as an object because the documentation at the time didn't make it clear what kind of value it could be. I'll switch `Namespace` to a string in 4.0, and I'll add the missing date properties today.

**Comment by ernestogutierrez** [comment]
Right, I reported the issue about the namespace not as an issue but as a question. I think it could be a breaking change for some people who are using some casting, so for the 4.0 I think it will be better.

[Issue reported here](https://github.com/nozzlegear/ShopifySharp/issues/95)

**Comment by nozzlegear** [comment]
I knew that sounded familiar! I'd agree that it's probably a breaking change, so to be safe I'm scheduling it for 4.0. If anybody using less than 4.0 reads this in the future, you can get the `Namespace` value by casting it to a string: 

```cs
string namespaceVal = (string) metafield.Namespace;
// or
string namespaceVal = metafield.Namespace as string;
```

**Comment by nozzlegear** [comment]
`UpdatedAt` and `CreatedAt` have been added in version 3.6.1.

**Comment by clement911** [comment]
Why thank you sir.

**Comment by nozzlegear** [comment]
Closing this in favor of #135 .
