### ISSUE TITLE
ShopifyMetaFieldFilter.Order does not work

### ISSUE THREAD

**Issue by Saquibadil** [nozzlegear/ShopifySharp#131]
Hello Nozzlegear,
"created_at desc" does not work at least for products.
I am doing this. It fetches same list without the Order and with "created asc"

`ShopifyMetaFieldFilter metaFilter = new ShopifyMetaFieldFilter();
metaFilter.Namespace = "mynamespace";
metaFilter.Order = "created_at desc";
metaFilter.Limit = 10;
metaFilter.Page = 1;
var metaFieldsList = await metaService.ListAsync(myprodid, "products", metaFilter);`

**Comment by clement911** [comment]
That's a limitation of the shopify api unfortunately they only honor the created_at on certain entities and certain fields :(

**Comment by Saquibadil** [comment]
Oh no. That's a bummer.
Would you be able to direct me to a link where they specify which entities and fields they honor created_at for.

Thank you for quick response.

**Comment by clement911** [comment]
As far as I know they don't document that but I know that Order and Product honor order by created_at. I don't think Customer does.

**Comment by Saquibadil** [comment]
I am trying to order Product MetaFields.

**Comment by clement911** [comment]
I haven't tried ordering those by why don't you order in your own code?

**Comment by Saquibadil** [comment]
I could only get maximum of 250 metafields per request. It won't work if there are more than 250 of them. That's why I want them in reverse order.
If there is a new metafield added, I would want it to be first in the list.
