### ISSUE TITLE
[Critical] Must remove TotalPriceUsd property from order

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#136]
I found a pretty severe bug.
I just had a customer sign up and my app immediately started throwing errors because the `total_price_usd`
is null on some orders apparently.
Json.net is trying to deserialize this property into a double, and fails.

It's not a documented property so **I would suggest we remove immediately**.
Yes it would be a breaking change but at the same time this bug has a massive impact.

If you're reticent to remove the property altogether I think we should at least make it nullable to avoid this problem happening.
Considering this property is obsolete, it is possible Shopify will set it to null for more shops, which could cause errors.
Actually, this makes me wonder if all obsolete / undocumented properties should be made nullable, or removed.
Yes, a breaking change, but I think for the best.

**What do you think?**

Here is the top of the stack trace:

```
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'orders[19].total_price_usd'. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at ShopifySharp.RequestEngine.CheckResponseExceptions(IRestResponse response)
```

**Comment by nozzlegear** [comment]
Yes I would agree that the fix should be pushed out right away even though it could be a breaking change. I haven't seen this yet in my own apps so wasn't aware of it.

I'd also like to remove all undocumented props, since that's been my "official stance" for all new objects for some time, but will wait until 4.0 for that unless we discover more broken ones in the meantime.

**Comment by clement911** [comment]
What do you think about making undocumented properties optional to mitigate this issue?

**Comment by clement911** [comment]
By optional I mean nullable...

**Comment by nozzlegear** [comment]
That would be fine, I'll just have to put some kind of warning in the release notes. Better to break in development than have a deserialization exception break an app in production. Although to be honest, I don't have a list of properties that are undocumented except for the ones that happen to have a warning in the `<summary>`. I can at least start with those.

**Comment by nozzlegear** [comment]
Okay, this should be fixed in version 3.7.0! `TotalPriceUsd` was the only undocumented prop that needed to be made nullable; all of the rest were strings or classes, which are nullable by default.

**Comment by clement911** [comment]
Thanks @nozzlegear. You're so quick!
If ShopifySharp was a Shopify app I'd give you a 5-start review :+1:

**Comment by nozzlegear** [comment]
Ha, thank you!
