### ISSUE TITLE
Redirect URL shouldn't be optional in ShopifyAuthorizationService.BuildAuthorizationUrl

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#137]
The redirectUrl parameter of the ShopifyAuthorizationService.BuildAuthorizationUrl is optional at the moment, I guess it is based in the old behaviour but now the Redirect URL should be required as the documentation says:  

[Shopify OAuth](https://help.shopify.com/api/getting-started/authentication/oauth)
> {redirect_uri} - (Required) substitute this with the URL where you want to redirect the users after they authorize the client. The complete URL specified here must be identical to one of the Application Redirect URLs. Note: in older applications, this parameter was optional, and redirected to the Application Callback URL when no other value was specified.

Shopify does not allow a oauth URL without the Redirect URL parameter so I think it will be a good idea to have that parameter required for the Shopify 4.0 realease.

This is the current method signature in ShopifySharp 3
`public static Uri BuildAuthorizationUrl(IEnumerable<ShopifyAuthorizationScope> scopes, string myShopifyUrl, string shopifyApiKey, string redirectUrl = null, string state = null, IEnumerable<string> grants = null);`

**Comment by ernestogutierrez** [comment]
It should be good as well to update the readme.md so it includes the redirectUrl in the OAuth example.

**Comment by nozzlegear** [comment]
Good catch! The redirect url was still optional at the time I wrote the auth service. I'll make sure this gets marked as required in 4.0.

**Comment by nozzlegear** [comment]
`redirectUrl` is now required in the 4.0 branch 👍

**Comment by ernestogutierrez** [comment]
Great, thank you! 👍
