### ISSUE TITLE
Better comments in ShopifyAuthorizationService.IsValidMyShopifyUrl

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#138]
**Problem**

The `ShopifySharp.ShopifyAuthorizationService.IsValidMyShopifyUrl` should have some changes in the  comments.

A developer calling this method can guess wrongly these points:
- There is no remote calls in the method so there is no performance or delay penalty
- The method can ensure 100% that the shop url is valid. (But  a fake website can also return a X-ShopId in the header parameters, so the method IsValidMyShopifyUrl will return true). 

The original comment is:
```
 /// <summary>
/// A convenience function that tries to ensure that a given URL is a valid Shopify store by checking the response headers for X-ShopId.
/// </summary>
```
**Solution**

I propose to explain that the method actually make a request to the shop url.  This is important because the caller of this method can know that will be a small time penalty becauseof the http request. And also explain about faking the headers.

This is just an example.

```
/// <summary>
/// A convenience function that tries to ensure that a given URL is a valid Shopify store by making a request to the shop url and checking the response headers for X-ShopId.
/// Take into account that a fake website could return the X-ShopId header.
/// </summary>
```

I would like to hear from you what do you think.

Thanks.

**Comment by clement911** [comment]
I have to agree.
It is a best practice to name async methods with a name ending in 'Async'.
Renaming the method to `IsValidMyShopifyUrlAsync` would follow that best practice and give a hint to the developer that this is an asynchronous and therefore there must be a network call or at least a performance penalty.
Regarding the fake website, one way the method could be enhanced is to check that the url ends with 'myshopify.com', which would rule out fake websites since this domain is owned by shopify.

**Comment by nozzlegear** [comment]
Great suggestion! It should definitely be renamed with the `Async` suffix, and the documentation should be clear that it's going to make an external request. I don't know that I want to check that the url ends with 'myshopify.com', though. Right now any domain, .e.g www.example.com, is also perfectly valid and will work for API calls as long as it's a Shopify store, so making that change could break something that should work. 

The method is poorly named for sure, and doesn't reflect that at all. It should probably be renamed to `IsValidShopifyUrlAsync`

**Comment by ernestogutierrez** [comment]
My first thought when I started using it, was that the method would do some verification as validating the myshopify.com domain, that was many months ago, but I was starting a new project this week and wanted to see why I was using that validation so I went to the shopifysharp source code and I understood that I was using it in the wrong way.

I don't usually like to change the names of things in a library because it breaks other's people software but  a name as `HasShopIdHeaderAsync` would clarify the purpose of the method.

Not for the 3.0 version for sure :)

**Comment by nozzlegear** [comment]
That sounds like a better name, and if we did that we could also add another method for validating that the URL is also a *.myshopify.com domain (and just note that regular domains can also be Shopify endpoints). I'll schedule it for v4.

**Comment by ernestogutierrez** [comment]
I have found an alternative way of validating the URL, but the use could be different because we will validate that a domain is currently valid for a specific store instead of validating the domain in general. I find it as an alternative way of validating the URL.

So, the if we use the [Shop api](https://help.shopify.com/api/reference/shop#show), we can get the domain and the myshopiy.com sub domain of a shop and verify if our url is one of those.

For example my shop has mygreatshop.com and mygreatshop.myshopify.com. 

I can do something like :

```
public async Task<bool> IsValidDomainAsync(string url, string myShopifyUrl, string shopAccessToken)
{
var service = new ShopifyShopService(myShopifyUrl, shopAccessToken);
var shop = await service.GetAsync();

return shop.Domain == url || shop.MyShopifyDomain == url)

}

```
This can be improved to use case insensitive comparison.

If I use it I can do this:
```

var myShopifyDomain = "mygreatshop.myshopify.com";
var isValidMyShopifyDomain = await IsValidDomain(myShopifyDomain);

var myDomain = "mygreatshop.com";
var isValidDomain = await IsValidDomain(myDomain);
```

I think this is more useful to validate a custom domain as mygreatshop.com instead of validating a myshopify.com subdomain because you are sure that the domain correspond to a specific shop. Perhaps is not useful at all! What do you think?

**Comment by nozzlegear** [comment]
That sounds like a good solution! Or at least another method we can add to help validate. We could make it lightweight call by using the fields prop to only return the shop's domain instead of the entire shop object, too.

**Comment by ernestogutierrez** [comment]
Sorry for the late response. You can decide if this is useful to include in the library or could be part of the documentation. Thank you.

**Comment by nozzlegear** [comment]
I'm working on pushing through the final changes for v4 right now, and after reviewing this again I think I'm going to go with your original suggestion to improve the documentation and rename the function to `IsValidMyShopifyUrlAsync` @ernestogutierrez. 

I liked your idea for pulling in the Shop's `Shop` object to check its domain or myshopify domain property, but it didn't occur to me at the time that we would need an access token to do so, at which point we already know that the URL must have been correct.

I'll make sure I add documentation to the current function that the domain could fake the shop id header.

**Comment by nozzlegear** [comment]
Renamed to `IsValidShopDomainAsync` in c982781.
