### ISSUE TITLE
Possible problem with MetaFields

### ISSUE THREAD

**Issue by tomeo** [nozzlegear/ShopifySharp#139]
I have created a few products with MetaFields using ProductService.CreateAsync. I can see that the MetaFields are there using https://apps.shopify.com/metafields-editor.

However, when retrieving the products using ProductService.ListAsync the MetaFields field is null on all my products.

Am I not supposed to get the MetaFields of each product using ProductService.ListAsync?

**Comment by clement911** [comment]
You need to usr the MetafieldService. See https://github.com/nozzlegear/ShopifySharp/issues/135

**Comment by nozzlegear** [comment]
Hey @tomeo, @clement911 is correct. MetaField properties were added to objects before the MetaField service itself was created, so they're kind of an old vestigial property that doesn't work the way it seems they *should* work. To boil it down, the MetaField prop is only used when creating a product, but the Shopify API never returns it unless you're using the MetaField service.
