### ISSUE TITLE
ShopifyTransaction.Test should be nullable

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#141]
Today I encountered an issue with a new customer, similar to https://github.com/nozzlegear/ShopifySharp/issues/136.
Even though `ShopifyTransaction.Test` is documented to be either `true `or `false`, I had a scenario where it had a null value, causing the transaction to fail to deseralize:

```
Exception: Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type ‘System.Boolean’. Path ‘transactions[0].test’. ---> System.InvalidCastException: Null object cannot be converted to a value type.

at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---
at ShopifySharp.RequestEngine.CheckResponseExceptions(IRestResponse response)
at ShopifySharp.RequestEngine.<>c__DisplayClass6_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
...
```

The impact is quite critical obvisouly. I suggest that we make it nullable immediately.
Technically this is a breaking change, but I think it's the best course of action.

**Comment by clement911** [comment]
It's a bit scary by the way. It makes you wonder if all properties should be nullable!

**Comment by nozzlegear** [comment]
Thanks for reporting this! This is a big problem, especially since it can take down apps and there's not really anything the dev can do about it. One of the big changes in v4 is to make *all* properties nullable; mainly that change was to make it possible to send partial objects for update requests, but it will also have the huge benefit of preventing these types of errors!

**Comment by clement911** [comment]
Thanks for the release and good to hear about the nullability in v4!
