### ISSUE TITLE
ShopifyException should include XRequestId property

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#143]
Apparently each response from Shopify contains a 'X-Request-Id' header with a unique identifier.
This can be very useful when you need to ask Shopify support to investigate why a particular request failed.

What do you think about adding a XRequestId string property to the ShopifyException?

It should be a matter of changing https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Infrastructure/RequestEngine.cs#L150 to inspect the response headers and pass the value to the ShopifyException constructor.

**Comment by nozzlegear** [comment]
Great idea! I'll get this in within the next day or two.

**Comment by nozzlegear** [comment]
Available in version 3.9.0!

**Comment by clement911** [comment]
Thanks!
