### ISSUE TITLE
The Shopify Development Handbook Link is broken

### ISSUE THREAD

**Issue by MattRhoades** [nozzlegear/ShopifySharp#146]
The link to the developer handbook is broken on the main page.  URL = https://nozzlegear.com/shopify-development-handbook?ref=ShopifySharp

**Comment by nozzlegear** [comment]
Good catch! I'm actually in the middle of making some changes to my site, so the whole thing is down right now. Should be back up soon!

**Comment by nozzlegear** [comment]
Site should be up and that link should now be working again 👍
