### ISSUE TITLE
Phone Number in ShopifyCustomer entity

### ISSUE THREAD

**Issue by hawkeandrew** [nozzlegear/ShopifySharp#149]
Hello

    "phone" doesn't seem to be available in the ShopifyCustomer entity.

    Will it be available in Version 4?

Regards

**Comment by nozzlegear** [comment]
Thanks for the heads up! It's difficult to know when Shopify adds properties to their API objects, so the most reliable way to learn of them is from people reporting it. I'll make sure it's available in the next release.

**Comment by nozzlegear** [comment]
`Customer.Phone` has been added in v4 which will be released shortly!
