### ISSUE TITLE
Inventory Behavior in ShopifyOrderCreateOptions

### ISSUE THREAD

**Issue by Redm4x** [nozzlegear/ShopifySharp#150]
Hello,

Looking at the doc for the [order create endpoint](https://help.shopify.com/api/reference/order#create) it looks like shopify expect the `inventory_behaviour` attribute to be spelled with a "u" and ShopifySharp spells it without (`inventory_behavior`). This is causing shopify to use the default value "bypass: Do not claim inventory". This is in [ShopifyOrderCreateOptions.cs](https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Services/Order/ShopifyOrderCreateOptions.cs)

**Comment by nozzlegear** [comment]
Good catch! I'll get this published in the next version.

**Comment by nozzlegear** [comment]
I've fixed this in v4 which will be published shortly!
