### ISSUE TITLE
Update method GetListProductsAsync(int limit, int page)

### ISSUE THREAD

**Issue by olexandrman** [nozzlegear/ShopifySharp#152]
Please add method GetListProductsAsync(int limit, int page) that get filter parameters, like this  GetListProductsAsync(int limit, int page, ShopifyProductFilter options).  I need to implement pagination of products on shopify api side.

**Comment by nozzlegear** [comment]
Hey @olexandrman, this should already be possible:

```cs
var productList = await productService.ListAsync(new ProductFilter()
{
    Limit = 100,
    Page = 2
});
```

**Comment by olexandrman** [comment]
Thanks, it works.
