### ISSUE TITLE
Issue: Forgot to tag the realease

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#155]
I have seen that previous realeases have a version tag on the repository but 4.0 and 4.0.1 don't have a version tag.

**Comment by nozzlegear** [comment]
Thanks for reminding me! I've been messing with releasing from AppVeyor once a build passes tests, but I forgot to get the GitHub releases set up to release from there too.

**Comment by nozzlegear** [comment]
Still having some issues with automated GH releases, so I've created manual ones for the last two versions. Thanks again for the reminder!
