### ISSUE TITLE
Discount obtaining

### ISSUE THREAD

**Issue by olexandrman** [nozzlegear/ShopifySharp#156]
Hi. When customer enter discount code on our site, we need to identify this code in shopify system. How can I get Discount object by DiscountCode? Thanks.

**Comment by ernestogutierrez** [comment]
You can get the discount codes used in an order with the [Order API](https://help.shopify.com/api/reference/order#show).

You retrieve the order and get this section:

```
"discount_codes": [
      {
        "code": "TENOFF",
        "amount": "10.00",
        "type": "percentage"
      }
    ],
```
I strongly recommend you to take a look of all the [APIs provided by Shopify](https://help.shopify.com/api/reference). ShopifySharp is a wrapper around those APIs so you should look the documentation on Shopify first and next see what is the related services to use in ShopifySharp.

**Comment by olexandrman** [comment]
Thanks for advice.
