### ISSUE TITLE
Shopify Payments

### ISSUE THREAD

**Issue by olexandrman** [nozzlegear/ShopifySharp#157]
I want to use Shopify Payments (for credit cards) on my site. How can I make payments through api? Thanks.

**Comment by ernestogutierrez** [comment]
@olexandrman I think that is out of the scope of the Shopify Admin API. You can configure Shopify Payments in your store, but for using Shopify Payments as a normal payment gateway (like those that have an API) I think it's not possible. 

You can use the [Transaction API](https://help.shopify.com/api/reference/transaction) but that is independent of the payment gateway so it's not related directly to Shopify Payments.

**Comment by olexandrman** [comment]
Thanks, we redirect user to checkout  shopify page for payment.
