### ISSUE TITLE
Update order

### ISSUE THREAD

**Issue by olexandrman** [nozzlegear/ShopifySharp#160]
I have tried update order. But my attempt was failed. On the first screen https://snag.gy/tqyThf.jpg (before update) financial status of order equals to 'pending'. On the second screen https://snag.gy/dFABnE.jpg (after update) financial status of order equals to 'pending' too, but I expected - 'paid'. What have I done wrong?

**Comment by nozzlegear** [comment]
Hey @olexandrman, I've been trying to debug this myself and I'm not getting any closer to a solution. As far as I can tell it's not possible to update an order's financial status via API, the status just doesn't seem to change at all. That doesn't seem correct, but that's my best theory at the moment. It might be a good idea to reach out to the support team at Shopify and see if this is actually possible and what we might be doing wrong.

**Comment by olexandrman** [comment]
Thanks. I also can not update field FulfillmentStatus.

**Comment by ernestogutierrez** [comment]
@olexandrman, you should use the [Fulfullment API](https://help.shopify.com/api/reference/fulfillment) instead of trying to change the fulfillment status of the order.

**Comment by ernestogutierrez** [comment]
@olexandrman for chaging the financial status, have you tried the [Transaction API](https://help.shopify.com/api/reference/transaction#create)?. I guess you cannot change the status, what I think you should do is to create a transaction with the full amount of the order. I also guess Shopify changes the status acording to these transactions and also acording to any refund.

**Comment by olexandrman** [comment]
Great, it works! I wonder if you know. Why when I create order, total inventory quantity of product do not decrease? For example: Store has 100 items of product. I ordered 5 items of product (through ShopifySharp). I expected that quantity should decrease to 95 items. But total quantity still 100 items. When I create test order through Shopify store in browser, all works properly.

**Comment by alingarnwelay-thesis** [comment]
> 
> 
> Great, it works! I wonder if you know. Why when I create order, total inventory quantity of product do not decrease? For example: Store has 100 items of product. I ordered 5 items of product (through ShopifySharp). I expected that quantity should decrease to 95 items. But total quantity still 100 items. When I create test order through Shopify store in browser, all works properly.

==> I also encounter above issue.what I need to follow to decrease and increase quantity for new order creation or update event?
And second question is I would like to do refund money and quantity auto restock after refund.If there any functions for that?

**Comment by dkershner6** [comment]
The best order creation flow to mimic Shopify admin would be to use the draft orders API and then complete the order. The order API is more like importing an order from another source.

You can refund and auto stock, it's part of the Orders area as well.
