### ISSUE TITLE
How to pass the Request.Body to the IsAuthenticWebhook method in Asp.Net Core 1.1

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#165]
How do you use the `ShopifyAuthorizationService.IsAuthenticWebhook` method with a `Stream`?

I'm using ASP.NET Core 1.1. When passing the `Resquest.Body` from the controller action to the `IsAuthenticWebhook` I get a "NotSupportedException: Specified method is not supported" becuase the Stream doesn't suppor the seek method. When you see the `IsAuthenticWebhook`'s source code,  there is a `inputStream.Position = 0;` call but the stream doesn't support it.

> NotSupportedException: Specified method is not supported.
> 
> Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestStream.set_Position(long value)

**Comment by nozzlegear** [comment]
Thanks for bringing this up. I'm trying to figure this out myself, it looks like the recommended way is to actually replace the stream with a stream that *can* use seeking and positioning using custom middleware: https://stackoverflow.com/a/31680535

In ShopifySharp we could check if the stream is seekable with `stream.CanSeek`, but it's probably best to keep throwing the current exception as we want devs to know that something was wrong with the stream and not necessarily with the webhook.

**Comment by ernestogutierrez** [comment]
@nozzlegear thanks for taking time to solve this. As the post you shared says there are two solutions, could be replacing the stream or using the `EnableRewind` extension method.

So, using a custom middleware you can activate the seeking function of the stream, although I 
don't know the implications of that.

In the startup.cs file you we should add this:
`using Microsoft.AspNetCore.Http.Internal;`

Next,  in the Configure method of the Startup class before adding MVC and probably other middleware we have to add this:
```
app.Use(next => context => 
            {
                context.Request.EnableRewind();
                return next(context);
            });
```

Now, when calling `IsAuthenticWebhook`  from a controller or probably from a action filter we can pass the Request.Body to the `IsAuthenticWebhook` without problems.

When I started to use ShopifySharp a year ago I was using another solution with ASP.NET WebApi, I didn't like it but it worked in that moment.  It was based on this post: [Accepting Raw Request Body Content with ASP.NET Web API](https://weblog.west-wind.com/posts/2013/Dec/13/Accepting-Raw-Request-Body-Content-with-ASPNET-Web-API). I won't use that solution anymore.

**Comment by clement911** [comment]
This is what I use:

```
var memoryStream = new MemoryStream();
            await Request.Body.CopyToAsync(memoryStream);
            bool isValidRequest = await AuthorizationService.IsAuthenticWebhook(Request.Headers, memoryStream, _shopifyLibOptions.SecretKey);
            if (!isValidRequest)
            {
                throw new UnauthorizedAccessException("This request is not an authentic webhook request.");
            }
            memoryStream.Position = 0;
            string body = new StreamReader(memoryStream).ReadToEnd();
            string topic = Request.Headers[ShopifyHelper.WEB_HOOK_TOPIC_NAME_HEADER].First();
            string shop = Request.Headers[ShopifyHelper.WEB_HOOK_SHOP_HEADER].First();
            string hmac = Request.Headers[ShopifyHelper.WEB_HOOK_HMAC_HEADER].First();
...
```

**Comment by HorjeaCosmin** [comment]
Hi people,

All above approaches are useless in my net core 3.1 webapi project. Any solution tested had finished in the same way, request.body is empty. Does anyone have an example on how a shopify webhook controller have to look like, or any other related changes should be done?

Look forward for good news.

Regards.

**Comment by clement911** [comment]
We also use asp.net core 3.1 now and read the body with `await new StreamReader(Request.Body, Encoding.UTF8).ReadToEndAsync()`

**Comment by HorjeaCosmin** [comment]
Using the following code:

        [HttpPost]
        public async Task<IActionResult> ProductUpdate(dynamic payload)
        {
            var data = await new StreamReader(Request.Body, Encoding.UTF8).ReadToEndAsync();
            Console.WriteLine(data);

            Console.WriteLine(payload.ToString());
            return Ok();
        }

I get an empty data and a valid payload object.

Any clue?

**Comment by nozzlegear** [comment]
@HorjeaCosmin This happens because ASP.NET will only allow reading the request body once until you modify a setting. In your example, it's reading the body before it executes your action because you're using `(dynamic payload)`, so the framework will read the body and dump it into that value, leaving the request body stream empty. 

To fix it, you just need to enable request buffering and then rewind the stream. The key is using `Request.EnableBuffering()`, I usually just put it all in an HttpRequest extension like this:

```cs
public static class HttpRequestExtensions
{
	public static async Task<string> ReadBodyToStringAsync(this HttpRequest req)
	{
		req.EnableBuffering();

		// The stream can now be read multiple times, but using a streamreader will automatically dispose it which we don't want. 
		// Copy it to another stream before reading instead. 
		using (var buffer = new MemoryStream())
		{
			await req.Body.CopyToAsync(buffer);

			// Move the buffer to the beginning of the stream before reading
			buffer.Position = 0;

			// Do the same for the original request stream
			if (req.Body.CanSeek && req.Body.Position != 0)
			{
				req.Body.Position = 0;
			}

			// Now read the body and return it
			using (var reader = new StreamReader(buffer))
			{
				return await reader.ReadToEndAsync();
			}
		}
	}
}
```

Then in your action you can just call `Request.ReadBodyToStringAsync()` to get the request body as a string.

**Comment by HorjeaCosmin** [comment]
Hi,


I found the problem:

    [Route("api/[controller]/[action]")]
    public class HooksController : Controller

instead of

    [Route("api/[controller]/[action]")]
    [ApiController]
    public class HooksController : ControllerBase


Thank you very much,
Cosmin.

**Comment by HorjeaCosmin** [comment]
@nozzlegear,

Any plan to switch on Shopify GraphQL api?

Tks
