### ISSUE TITLE
Missing fields in ShopifySharp.Filters.OrderFilter

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#167]
The `OrderFilter ` has some missing fields that are accepted by the `/admin/orders.json` endpoint:

- processed_at_min
- processed_at_max
- attribution_app_id

Please see the [Shopify Order API](https://help.shopify.com/api/reference/order#index).

**Comment by nozzlegear** [comment]
Should be available in 4.1.1. Thanks for reporting this!
