### ISSUE TITLE
SmartRetryExecutionPolicy issue with IFlurlClient.Clone

### ISSUE THREAD

**Issue by bartcoppens** [nozzlegear/ShopifySharp#174]
Hi,

I run ShopifySharp v4.4 on .NET Framework 4.6.1.
My projects in clude Flurl (v2.5) and Flurl.Http (v1.2).
When I execute a call on a service that has a SmartRetryExecutionPolicy the following Exception is thrown:

Method not found: 'Flurl.Http.FlurlClient Flurl.Http.IFlurlClient.Clone()'.

   at ShopifySharp.SmartRetryExecutionPolicy.<Run>d__4`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at ShopifySharp.SmartRetryExecutionPolicy.Run[T](IFlurlClient baseRequest, JsonContent bodyContent, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Any idea what I might be missing here?

Regards,
Bart

**Comment by nozzlegear** [comment]
Hey Bart, which version of ShopifySharp are you running? I believe I fixed this a couple of releases ago because I ran into the same problem.

**Comment by bartcoppens** [comment]
Hi Joshua,

I first ran into this issue on a previous version.
I was trying on version 4.4.0.0 now though.

Regards,
Bart

**Comment by nozzlegear** [comment]
Oh shoot, sorry I thought this was a case where the `Clone` method was broken because the request content was disposed, but it looks like your exception is actually saying there's no `Clone` method in the first place? To be honest, I have no idea how to fix version conflicts in .NET projects, which is what this *appears* to be.

**Comment by nozzlegear** [comment]
Digging a little deeper it does look like Flurl has decided to drop the `Clone` method and anything else related to auto-disposing requests, so unfortunately we've got to irreconcilable versions of Flurl.Http here. 

https://github.com/tmenier/Flurl/issues/205

**Comment by bartcoppens** [comment]
Thanks Joshua, decided to revert to version 2.3.0 of Flurl.
Works fine.

**Comment by nozzlegear** [comment]
Glad to hear it's working! I'll take a look at replacing the `Clone` methods at some point in the future which would let us upgrade Flurl dependencies, but for now they'll probably remain the same.

**Comment by bartcoppens** [comment]
I was too soon to confirm that it worked. It turns out it didn’t. Maybe I need to roll back to a previous version of Flurl.Http as well. No time to test that at the moment though.

**Comment by nozzlegear** [comment]
Yeah I think Flurl.Http is the one that needs to be rolled back, it's the one that deals with web requests. As far as I know the Flurl package itself only deals with formatting URLs or something.

**Comment by bartcoppens** [comment]
Confirmed. Now it works.
