### ISSUE TITLE
DiscountCode Class Properties

### ISSUE THREAD

**Issue by nxp2910** [nozzlegear/ShopifySharp#175]
I was looking at the DiscountCode class. Seems like it's missing a few properties. According to Shopify documentation, it takes price_rule_id and usage_count. And "Discount" method seems to be deprecated.

https://help.shopify.com/api/reference/discountcode

**Comment by nozzlegear** [comment]
Thanks for reporting this! I'll get the missing props in as soon as possible. Regarding the deprecation, we do have support for the new `PriceRules` API, but we still need to get the `PriceRuleDiscount` support in there too before devs can replicate the behavior of discounts with price rules.

**Comment by nycbauer** [comment]
Hey there!

What is the status on this? I actually need this for my project. Perhaps I can give a hand with it?

**Comment by nozzlegear** [comment]
Hey @nycbauer, if you want to take a shot at this I'd be happy to merge a pull request! Normally I'd get this in by now but I'm in the middle of a big project and haven't had the time yet.
