### ISSUE TITLE
Product not loading in vs 2015

### ISSUE THREAD

**Issue by sanghreaajit** [nozzlegear/ShopifySharp#182]
When i trying to load this project in vs 2015 it showing load failed

error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by nozzlegear** [comment]
Hey @sanghreaajit, this is probably because we switched the project over to the new dotnet standard format. It's possible that VS2015 can't handle the new format and just fails to load it. It should work fine in VS2017 or VSCode.
