### ISSUE TITLE
Add Support for the metafields_global_title_tag and metafields_global_description_tag fields in the Product object

### ISSUE THREAD

**Issue by jfb112697** [nozzlegear/ShopifySharp#186]
It would be great if when I was creating a Product if I could set the value of the metafields_global_title_tag and the metafields_global_description_tag as they can be quite useful for SEO on the product listings, and Shopify's automatically generated description isn't the best.

**Comment by nozzlegear** [comment]
I agree we need to get this in. I think I'm going to end up adding an overload to the `CreateAsync` methods that will let you pass in metafields for every object that supports them:

```cs
public async Task<Product> CreateAsync(Product product, IEnumerable<MetaField> metaFields)
```

**Comment by jfb112697** [comment]
Thanks very much! I look forward to the update.

**Comment by jeremysimmons** [comment]
suggestion for MetaField class...
class MetaField
{
public MetaField() { }
private MetaField(string namespace, string key, string value) { .. }
public static MetaField GlobalDescription(string description) => new MetaField("global", "description_tag", description);
public static MetaField GlobalTitle(string title) => new MetaField("global", "title_tag", title);
}

usage await service.CreateAsync(product, MetaField.GlobalTitle("mytitle"), MetaField.GlobalDescription("my description"));

**Comment by dkershner6** [comment]
Can be handled with https://github.com/nozzlegear/ShopifySharp/pull/265 . Could add the extensions if desired and just add em to the array.

**Comment by nozzlegear** [comment]
You can now do this in 4.15.2. I'm happy with just creating them through the object for now.

**Comment by pantherpan** [comment]
Hi Guys, is there an example of set metafields_global_title_tag and the metafields_global_description_tag with the product creating?
THANKS!!!

**Comment by jeremysimmons** [comment]
@pantherpan open a new issue, this one is already closed. Reference this issue if necessary for context...
