### ISSUE TITLE
Missing field app_id on Order object

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#188]
I just checked the latest docs and there is now an _app_id_ field on the order object.

https://help.shopify.com/api/reference/order

**Comment by clement911** [comment]
There is also a _customer_locale_ field

**Comment by nozzlegear** [comment]
Good catch! Are you willing to do a pull request for this?

**Comment by clement911** [comment]
Oh sure, I just put it out there to remember...
