### ISSUE TITLE
Fields missing from 'ProductImages' table

### ISSUE THREAD

**Issue by kirti-bhardwaj-onebcg** [nozzlegear/ShopifySharp#193]
Fields 'height' & 'width' of 'ProductImages' table are missing from dll and are present in api.

Fields 'attachment' & 'filename' of 'ProductImages' table are missing from api and are present in dll.

**Comment by nozzlegear** [comment]
Thanks for letting me know about all of these, and sorry I've been quiet on them. I'm still in the middle of a huge project that's taking up all my time, but I'm aiming to get many issues closed this weekend and next.
