### ISSUE TITLE
add order.json support to smart_collections

### ISSUE THREAD

**Issue by jeremysimmons** [nozzlegear/ShopifySharp#195]
when a smart collection has a default_sortby of manual, you want to update the order of the collects that belong to it.

PUT https://YOUR_STORE.myshopify.com/admin/smart_collections/COLLECTION_ID/order.json HTTP/1.1
Content-Type: application/json
X-Shopify-Access-Token: TOKEN
Host: YOUR_STORE.myshopify.com

{"products":[id1,id2,id3,id4]}

on the SmartCollectionService class, I want a method like this.
public virtual async Task UpdateOrderAsync(long collectionId, params long[] productIds)

**Comment by nozzlegear** [comment]
I've added `UpdateProductOrderAsync` in version 4.7.0, but was unable to create a test for it. Try it out and let me know if you run into any problems.
