### ISSUE TITLE
ShopifySharp.ShippingLine is missing fields

### ISSUE THREAD

**Issue by jeremysimmons** [nozzlegear/ShopifySharp#198]
carrier_identifier: string
discounted_price: decimal

there are others, but it's critical that discounted price be available.

**Comment by jeremysimmons** [comment]
have commit with this small modification available. will send PR soon.

**Comment by nozzlegear** [comment]
Great! Let me know when you've sent the PR and I'll get it merged as quickly as possible.

**Comment by jeremysimmons** [comment]
@nozzlegear letting you know

**Comment by nozzlegear** [comment]
Thanks! Your changes should be available in 4.7.2 on nuget within the next 30 minutes.
