### ISSUE TITLE
getting only 50 products

### ISSUE THREAD

**Issue by kaikubadBS23** [nozzlegear/ShopifySharp#204]
i have build an app using this sdk and the app is live now.Suddenly i noticed that i am getting only 50 products.
var service = new ProductService(user.MyShopifyDomain, user.ShopifyAccessToken);
int productCount = await service.CountAsync();
IEnumerable product = await service.ListAsync();
this is the code i used to fetch all product.
please help

**Comment by nozzlegear** [comment]
Hi @kaikubadBS23, I get this question a lot. The Shopify API is designed to only return 50 objects of anything at a time, whether it's products, orders, etc. You can increase that limit by using the `Limit` property on a `ProductFilter`:

```cs
var filter = new ProductFilter()
{
    Page = 1,
    Limit = 250 // Maximum is 250
}
var products = await service.ListAsync(filter);
var count = products.Length; // 250
```

To get the next set of 250 products you would set `Page = 2` and so on.

**Comment by kaikubadBS23** [comment]
thanks a lot.
