### ISSUE TITLE
change the limit of productes returned in IEnumerable<Product> products = await service2.ListAsync();

### ISSUE THREAD

**Issue by cmfsantos** [nozzlegear/ShopifySharp#205]
Hello 
By default shopify only returns 50 products. In Shopify API documentation there are a limit that cam be used.
How can i use it in here?
Regards,
Carlos

**Comment by cmfsantos** [comment]
answer in #194

**Comment by Thieum** [comment]
The code has been updated, as the lower limit for the page index should be 1 instead of 0.
