### ISSUE TITLE
Consider an F# wrapper

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#208]
I'm personally using F# much more than C# these days, but using a C# lib from F# is a little bit awkward (not impossible or even difficult). I'm thinking about writing an F# wrapper for this package:

```fs
let service = 
    AccessToken "myToken"
    |> ShopifyDomain "shop.myshopify.com"
    |> OrderService

let! order = service.get orderId
```

At a minimum the wrapper would wrap the constructors for all services as above, along with each services' methods so they become F# async functions. In an ideal world the wrapper would also wrap all entities, changing them to records with options instead of classes with nullables which can't be pattern matched.

No ETA on this.

**Comment by nozzlegear** [comment]
An example of an F# wrapper would be the one I wrote for Davenport at [https://github.com/nozzlegear/davenport.net](https://github.com/nozzlegear/davenport.net).

**Comment by nozzlegear** [comment]
I'm a huge fan of F#, it's such a cool language and makes me feel way more productive than C# especially. I love how terse it is compared to C# where everything must be a class or interface, and every class should have it's own file and so on. F# is definitely Microsoft's "red-headed step child", it's obvious that F# is only an afterthought in most of their official libs/packages such as ASP.NET. 

The community for F# is great though a huge part of the F# ecosystem. The Ionide plugin, which adds support for F# to VS Code, is 100% developed by the community and is (in my opinion) better than the support Visual Studio itself has for the language. Web frameworks like Suave and Giraffe are much more popular in F# than ASP.NET (Giraffe actually wraps ASP.NET and makes it functional). 

It's definitely true though that most of the tooling and libraries out there are written for C#. Luckily F# is a dotnet language and can fully interop with C# libraries without any extra steps, so if there's a library or tool you really need to use you'll be able to use it without any problems. 

But C# code can be awkward to use from F#. For example, this method written in C#

```cs
public string SomeMethod(string arg1, bool arg2, int arg3) { ... }
public bool GetArg3(int i) { return i * 2; }
```

Would be used from F# like this:

```fs
let result = SomeMethod("foo", true, GetArg3(5))
```

Which looks completely normal from a C# perspective, but in F# you'd rather use it like this:

```fs
let result = 
    getArg3 5
    |> someMethod "foo" true
```

Essentially, using C# code and libraries from F# is totally possible, but it's awkward and makes things like currying and piping difficult or even impossible. Luckily F# has its own standard lib built for the language, so unless you're using a 3rd-party package built for C# you don't have to mess with C#-y code very often.

I think the coolest thing F# has going for it though is Fable, which is a tool the community has built to compile F# code to JavaScript. My web projects and Shopify apps are now 100% F# on both the server and the browser, and they share the same types and much of the same code. Fable is the reason I started using F#, I was getting super tired of the JS ecosystem and this language has been so cool I can't see myself going back to C# or TypeScript or JS anytime soon.

**Comment by clement911** [comment]
Woo that Fable thing sounds craaazy!

Although it sounds very cool, another concern of mine is when frameworks do too much magic.
I'm pretty happy with Typescript. Most libraries have types files these days and the generated js is easy to read. The tooling is great too.

I would need to research Fable more to understand it properly.
