### ISSUE TITLE
Product Image extension change

### ISSUE THREAD

**Issue by kaikubadBS23** [nozzlegear/ShopifySharp#211]
hi,
I want to update product image which is currently on .jpg format.I want to  update the image in png.
Currently its updating but not in png format.So image transerency is gone.it it possible to replace .jpg image with .png image.I have also updated the filename property.but its not working
thanks

**Comment by nozzlegear** [comment]
Hey @kaikubadBS23, I haven't seen this problem before. Could you provide a small bit of sample code that I can write a test for to see if I can reproduce it?

**Comment by kaikubadBS23** [comment]
`var service = new ProductImageService(user.MyShopifyDomain,
                                            user.ShopifyAccessToken);
                                        var image = await service.UpdateAsync(order.ProductId, order.ImageId, new ProductImage
                                        {
                                            Attachment = Helper.GetImageBytes(imagedir),
                                            Filename=$"{order.ImageName.Split('.').FirstOrDefault()}.{uploadedExtension}",
            
                                        });`

my original image extension is jpg.I am updating with .png image.image is replacing but extension is not changing
