### ISSUE TITLE
Newbie -- Is there a way to use UpdateAsync as a Sync Update 

### ISSUE THREAD

**Issue by ljrain** [nozzlegear/ShopifySharp#216]
Is there a way to use UpdateAsync on Product or ProductVariant as an Sync call or to monitor to see if the tasks are all completed?

**Comment by bartcoppens** [comment]
Hi,

Yes you can use standard .NET techniques to run async methods synchronously.
Cf. https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

Example:
var success = await object.SomeMethod(someValue);
becomes
var success = object.SomeMethod(someValue).Result;

Regards,
Bart

**Comment by nozzlegear** [comment]
Like Bart said, you should be able to run the async methods in a synchronous fashion by doing `service.MethodName().Result`. You might have to use `service.MethodName().ConfigureAwait(false)`; I'm not 100% clear on that as I've always used async where possible and I'm not super sure what `ConfigureAwait` actually does! 😆
