### ISSUE TITLE
Allow to update Fulfillment property notify_customer

### ISSUE THREAD

**Issue by noamberda** [nozzlegear/ShopifySharp#217]
Hi,
In the current ShopifySharp library i can see I can set the notify_customer via the create fulfillment but not on the update. On the Shopify portal they allow to update the customer notification when changing the tracking information.

I think you should allow to change the property via the update fulfillment as well.

Any thoughts?

Thanks,
Noam

**Comment by nozzlegear** [comment]
Thanks for letting me know about this! I wasn't aware you could set the `notify_customer` flag when updating a fulfillment. I'll add an overload to the function.
