### ISSUE TITLE
BuildAuthorizationUrl should not use an enum

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#218]
To be consistent with the fate of previous enums, the AuthorizationScope enum should be removed and strings should be used instead.

As of today already there are several missing scopes from the enum:

https://help.shopify.com/api/getting-started/authentication/oauth#scopes documents these:

read_product_listings, read_collection_listings
read_draft_orders, write_draft_orders
read_marketing_events, write_marketing_events
read_resource_feedbacks, write_resource_feedbacks
and more...

There will probably be more scopes in the future too...

**Comment by nozzlegear** [comment]
I don't disagree that it's weird to have them in when all the other enums were removed. My reasoning was that the authorization scopes were far more likely to be used than anything else. We clearly still run into the problem where the enum values can change, though. In this case, new values are added. 

However, removing them would be a breaking change and I wouldn't want to do that until a 5.0 release, which I don't currently have planned. I think our best case scenario is to just add the new enums as we learn of them, and to add an overload for the methods that use them to also accept strings.

**Comment by clement911** [comment]
That sounds like a good compromise to me.

**Comment by nozzlegear** [comment]
I'm going to close this for now and revisit when we start planning a 5.0 release. I'd like to remove enums and replace them with string constants, so we'll be able to hardcode known values but developers will be able to pass their own custom strings where necessary.

**Comment by clement911** [comment]
Actually I just realized there was an overload that takes a `string[]`.
