### ISSUE TITLE
build shopify public app with .net c#

### ISSUE THREAD

**Issue by dilipdeveloper14** [nozzlegear/ShopifySharp#219]
Hi,

I want to build shopify public app with .net c#. Is it possible?. If yes, can anyone help how to create an app with .net and how to host it on shopify store.

Thanks!

**Comment by nozzlegear** [comment]
Hi @dilipdeveloper14, building a public Shopify app with C# is very possible! This library should get you there, it includes everything you'll need for oauth authentication, creating subscription cards, working with your users' orders/fulfillments/customers and so on. 

I've written a fair deal of content on building Shopify apps with C# over on my blog: [https://nozzlegear.com/shopify](https://nozzlegear.com/shopify). I've also written a free PDF that guides you through creating your first Shopify app with C#. It's actually taken from a premium course that I sell on building Shopify apps. You can get the free guide by signing up for the mailing list at [https://nozzlegear.com/shopify-development-handbook](https://nozzlegear.com/shopify-development-handbook), and you can buy the full book [on Gumroad (https://gum.co/shopify-development-handbook)](https://gum.co/shopify-development-handbook).
