### ISSUE TITLE
Checkout API

### ISSUE THREAD

**Issue by tuochuynh** [nozzlegear/ShopifySharp#220]
Hi,

Great work team. The library is very helpful.
I am looking to create an app to calculate shipping rate at checkout but couldn't find checkout API as shown here https://help.shopify.com/api/reference/checkout.
PLease if you can give me a heads up when will this happen, it would be much appreciated.

Thanks

**Comment by nozzlegear** [comment]
Hey @tuochuynh, I'd love to get this in but I'm very busy for at least the next couple of weeks. If you want to take a shot at this I'd be happy to offer advice and merge any pull requests. Otherwise it might be a couple weeks or more until I can get this done and merged.

**Comment by tuochuynh** [comment]
I am currently tied up with other works. Will let you know if I have a chance. Thanks anyway. Your library saves me heaps of time. Well done.

**Comment by nozzlegear** [comment]
I need this for an upcoming project, so I'm planning to get it in soon!

**Comment by olliehuynh** [comment]
Great to hear. Thanks heaps

**Comment by ohizkiya** [comment]
@nozzlegear Any update on Checkout API support? If you point me in the right direction I can possibly cook up a pull request...

**Comment by nozzlegear** [comment]
Published in 4.18.0!
