### ISSUE TITLE
Working Example project?

### ISSUE THREAD

**Issue by webmasterbbc** [nozzlegear/ShopifySharp#224]
Hello,

This looks awesome, Is there a full working example project that can be downloaded to see how to use the features of this library?

**Comment by nozzlegear** [comment]
Thanks @webmasterbbc! I do have an example project that you can get by joining the mailing list I've set up on my website at nozzlegear.com. While the book I sell has up-to-date projects, the free one on that mailing list still uses ShopifySharp v3 so it's a bit outdated though should still work.

I'd love to get it updated though and put it on GitHub. I'm currently working on an F# version that uses F# on both the server *and* the frontend thanks to Fable, and I plan to make the repo public when it's done, but I realize most devs using this lib are probably much more comfortable with C#.

**Comment by webmasterbbc** [comment]
Thanks, I tried to signup for your mailing list but go an error. I tried about 4-5 times and gave up. can you please help?

**Comment by nozzlegear** [comment]
Sorry, I keep losing track of issues now that they don't appear on the GitHub dashboard anymore. Thanks for letting me know about this, did you ever get it working?
