### ISSUE TITLE
Fix casing on 'MetaField'

### ISSUE THREAD

**Issue by MisinformedDNA** [nozzlegear/ShopifySharp#225]
'MetaField' and 'MetaFieldService' should be 'Metafield' and 'MetafieldService'. This reflects Shopify's [documenation](https://help.shopify.com/api/reference/metafield) and the .NET Design Guidelines. It's a small, but breaking change. (Added just in case the stars align.)

**Comment by nozzlegear** [comment]
This is a good suggestion, but changing the name of a class would break builds, so I'm going to hold off on it until we start gearing up for a 5.0 release.
