### ISSUE TITLE
Invalid request exceptiion

### ISSUE THREAD

**Issue by kaikubadBS23** [nozzlegear/ShopifySharp#228]
i have 1901 product in my test store.I am trying to get all product in a single request.My code is as following.

                var pService = new ProductService("my-test-store.myshopify.com", "My access token");

                int productCount = await pService.CountAsync();

                IEnumerable<Product> products = await pService.ListAsync(new ShopifySharp.Filters.ProductFilter { Limit = productCount, Page = 1 });

this gives me following axception.in this case productCount=1901

ShopifySharp.ShopifyException: Error: Invalid request parameters
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)

**Comment by clement911** [comment]
The maximum limit is 250

**Comment by kaikubadBS23** [comment]
then how can i list all product?

**Comment by clement911** [comment]
You ll have to page through all pages.

**Comment by foxandrewj** [comment]
this extension method will return all products.

```
public static async Task<IEnumerable<Product>> ListAllAsync(this ProductService service, ProductFilter filter)
        {
            try
            {
                List<Product> products = new List<Product>();
                List<Product> productsPage = null;
                filter.Limit = filter.Limit ?? 250;
                var pageCount = 1;

                do
                {
                    filter.Page = pageCount;
                    productsPage = (await service.ListAsync(filter)).ToList();
                    products = products.Concat(productsPage).ToList();
                    pageCount++;
                } while (productsPage?.Count() == filter.Limit);

                return products;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw e;
            }
        }
```
