### ISSUE TITLE
Trouble with Fulfillment API calls

### ISSUE THREAD

**Issue by untether-llc** [nozzlegear/ShopifySharp#231]
Hello.   Love the ShopifySharp library!  I've been using it to pull order and product data, but I'm having an issue in using the API to access or create Fulfillments.

Any time that I attempt the call on the 2nd line, my application simply exits without any returned results:

FulfillmentService servicef = new FulfillmentService(url, token);
var fulfillment = await servicef.ListAsync(339351011351);     // where this is the order key.

I also have a similar result if I attempt to create a new fulfillment as shown here:

fulfillment = await service.CreateAsync(nOrderKey, fulfillment, false);  // where order key is 339351011351

Any ideas?  I've used similar calls very effectively in pulling products and orders.

Thanks,
JB

**Comment by nozzlegear** [comment]
Interesting, I wonder if there's an error when deserializing whatever gets returned by Shopify. What happens when you add a try/catch around the two calls that are throwing errors? Can you post the exception that gets caught?

**Comment by thedonmon** [comment]
It might be similar to the Checkout API where the Id field is no longer a long value and is now a token/string value. @nozzlegear

**Comment by nozzlegear** [comment]
That's what I'm afraid of! Hopefully that isn't the case and Shopify didn't just decide to change the type of the id field without announcing it.

**Comment by thedonmon** [comment]
I will do some postman requests to fulfillment data to see if I notice anything different. It seems like they do these small changes quite often without announcing. The carrier service app I wrote for them started using fields that weren't required all of the sudden and caused a bunch of issues.

**Comment by thedonmon** [comment]
@untether-llc Try wrapping it in a try catch. I am not noticing any exceptions or issues when I query the Fulfillment API

**Comment by nozzlegear** [comment]
I've been continuously frustrated by their unannounced changes since I started work on this package a couple years ago. In fact it's lead to at least two major version releases and I have no doubt there will be more. It would be really nice if we could pin requests to a specific version of their API but that's wishful thinking at this point.

**Comment by untether-llc** [comment]
I actually tried that and an exception is not thrown at all.  The application simply attempts to make the Fulfillment API request and terminates…

**Comment by nozzlegear** [comment]
Hmm, that's very strange. I'm not seeing it in any of my tests, but it's possible the shop you're using it on has some unsupported json being sent with the fulfillment apis. My next suggestion would be to clone this repo into your package and try to step through the deserialization procedure to see if you get an exception thrown there. Or, if you're able to get the json that's being returned by Shopify and post it here I could try to help.

**Comment by nozzlegear** [comment]
Were you ever able to debug this further @untether-llc?

**Comment by untether-llc** [comment]
Yes.  Meant to follow-up in the thread and let you know that this was resolved.  Debugging this code helped show me that the issue here was in my own code and in the way that I was handling the asynchronous methods for the Fulfillment object.  I’m good to go on this and do appreciate the help and suggestions!

Thanks,
Jonathan

**Comment by nozzlegear** [comment]
Great to hear, thanks!
