### ISSUE TITLE
Add inventory_item_id to ProductVariant

### ISSUE THREAD

**Issue by richbeales** [nozzlegear/ShopifySharp#234]
Please can the ProductVariant entity be updated to include inventory_item_id as per the documentation?
In these cases would it be beneficial to make the entities partial classes so we can extend them without a release?

I need the inventory_item_id to call Adjust on the InventoryLevelService which i've written

https://help.shopify.com/api/reference/product_variant

P.S. Thanks for this library it's working great.

**Comment by clement911** [comment]
I don't think that partial classes can be spread over multiple assemblies so I don't think it would work.
You should feel free to send a PR to add missing documented properties though.

**Comment by nozzlegear** [comment]
Added in #235 by @clement911!
