### ISSUE TITLE
Create one service to create the rest

### ISSUE THREAD

**Issue by MisinformedDNA** [nozzlegear/ShopifySharp#237]
Right now, if we want to use multiple services, we have to instantiate each one separately.

        private static MetaFieldService metafieldService = new MetaFieldService(ShopDomain, ApiKey);
        private static ProductService productService = new ProductService(ShopDomain, ApiKey);
        private static ProductVariantService variantService = new ProductVariantService(ShopDomain, ApiKey);
        private static CustomCollectionService collectionService = new CustomCollectionService(ShopDomain, ApiKey);

I would prefer to do something like:

    private static ShopifyService shopifyService = new ShopifyService(ShopDomain, ApiKey);
    private static MetaFieldService metafieldService = shopifyService.GetMetaFieldService();
    private static ProductService productService = shopifyService.ProductService();
    private static ProductVariantService variantService = shopifyService.ProductVariantService();
    private static CustomCollectionService collectionService = shopifyService.CustomCollectionService();

Pros:
 - One place to enter API key
 - Easy to find related services

**Comment by vleontyev** [comment]
I can implement it if @nozzlegear will agree that it will be nice to have

**Comment by nozzlegear** [comment]
I'm open to this! If you want to take a shot at it @vleontyev I'd be happy to review and merge a pull request. Let's call the class `ScopedServices` to help differentiate it from regular services.

**Comment by MisinformedDNA** [comment]
The problem with `ScopedServices` is that it's vague and has no obvious connection to Shopify. When someone adds `ShopifySharp`, the most obvious first step is to see what classes contain the word `Shopify`, like `ShopifyService` or `ShopifyClient`.

**Comment by vleontyev** [comment]
I agree with @MisinformedDNA that `ScopedServices ` will be a bit confusing. My vote for `ShopifyClient`

**Comment by nozzlegear** [comment]
Sure, ShopifyClient works!




--


Josh Harms







From: Victor


Sent: Saturday, April 14, 05:33


Subject: Re: [nozzlegear/ShopifySharp] Create one service to create the rest (#237)


To: nozzlegear/ShopifySharp


Cc: Joshua Harms, Mention






I agree with @MisinformedDNA that ScopedServices will be a bit confusing. My vote for ShopifyClient
