### ISSUE TITLE
Carrierservice

### ISSUE THREAD

**Issue by khushbooprajapati** [nozzlegear/ShopifySharp#239]
Hello,

I want to use carrier service API for one of my shopify app. I have already use shopifysharp for other apps. 
And now need to use carrier service.

Can you help me ?

**Comment by nozzlegear** [comment]
Hey @TechnologyFeed, I don't have any personal experience with the Carrier API, but I'll try to help! What are you trying to do with the Carrier service?

**Comment by dkershner6** [comment]
Keep in mind that the Carrier Service API only requires basically a single call to create the service, and then Shopify calls you for the actual rates (completely separately).

It's not a difficult API, but not likely to be high on folks priority list.
