### ISSUE TITLE
Can we add another field to Fulfillment APIs

### ISSUE THREAD

**Issue by olliehuynh** [nozzlegear/ShopifySharp#240]
I need to make the option to disable notification emails available to the users of my app. Can we please add this into the Fulfillment object?

namespace ShopifySharp
{
    public class Fulfillment : ShopifyObject
    {
        public Fulfillment();
        [.......]

        [JsonProperty("notify_customer")]
        public bool NotifyCustomer { get; set; }

    }
}

Thanks

**Comment by olliehuynh** [comment]
Will try the latest version this week, the app was working fine so was lazy to update. Thanks very much.

**Comment by nozzlegear** [comment]
No problem! Let me know if it doesn’t fit your use-case.

--
Josh Harms

**Comment by olliehuynh** [comment]
Thanks heaps, looks like working now. Will upload new code after business hours and test it live.
Btw, Have you done any thing about the fulfillment migration listed below?
https://help.shopify.com/api/tutorials/inventory-migration-guide/fulfillment-migration-guide?utm_source=exacttarget&utm_medium=email&utm_campaign=multilocation1

**Comment by nozzlegear** [comment]
Thanks for the link! I wasn't aware of that, but I'll make sure we get set up to handle the changes.




--


Josh Harms







On Mon, Apr 23, 2018 at 7:33 PM -0500, "olliehuynh" <notifications@github.com> wrote:












Thanks heaps, looks like working now. Will upload new code after business hours and test it live.

Btw, Have you done any thing about the fulfillment migration listed below?

https://help.shopify.com/api/tutorials/inventory-migration-guide/fulfillment-migration-guide?utm_source=exacttarget&utm_medium=email&utm_campaign=multilocation1

**Comment by olliehuynh** [comment]
Thanks heaps

**Comment by olliehuynh** [comment]
Hey, Just run a full test on this case. Works perfectly. Also, updated the latest version 4.12 without any problem. Great work.

**Comment by nozzlegear** [comment]
Awesome, glad to hear it!

--
Josh Harms
