### ISSUE TITLE
ProductVariant inventory deprecation/obsolete notice

### ISSUE THREAD

**Issue by TonyBurnettSchoola** [nozzlegear/ShopifySharp#241]
This is a minor issue...

If I am reading the Shopify API notes correctly, as of 1-July-2018, the affected inventory fields on ProductVariant will still be available for 'read'.  IOW, only the 'setter' is being deprecated. As you can't apply an [Obsolete] attribute to a property's get/set, maybe the obsolete message should be updated?

https://help.shopify.com/api/tutorials/inventory-migration-guide

**Comment by clement911** [comment]
You're right.

I added the obsolete attribute because it is marked as obsolete in the Shopify docs but it's since become clear it can still be read so we should remove the attribute.

https://help.shopify.com/api/reference/product_variant#inventory-quantity-property

**Comment by TonyBurnettSchoola** [comment]
Just plan on removing the setter from the InventoryQuantity and InventoryQuantityAdjustment properties when 1-July-2018 rolls around.

**Comment by nozzlegear** [comment]
I can't remember, is it possible to mark just the setter as obsolete? I'd prefer to do that and then remove the setter in 5.0 which I'm planning to start toward the end of June.

**Comment by TonyBurnettSchoola** [comment]
I don't think you can.  I tried placing an attribute on a setter but failed.

**Comment by TonyBurnettSchoola** [comment]
For now you could change the obsolete 'message' to read "As of 1-July this will become a read-only property' or something like that.

then remove the setter later?

**Comment by clement911** [comment]
If you remove the setter will json.net be able to deserialize the property?
I suppose we could have a private setter.

**Comment by nozzlegear** [comment]
That's a good point, I don't think it would be able to deserialize without special handling. Thinking more about this, I'm not sure I want to get in the business of removing setters for obsoleted props. In an ideal world that would be good, but it could potentially break builds when things are removed (even if the API call itself might be broken later). For now I consider obsolete props something the developer should keep up with, but I'm happy to continue adding the Obsolete attribute when an entire property is obsoleted.
