### ISSUE TITLE
ShopifySharp for .net framework doesn't work in Web API project. 

### ISSUE THREAD

**Issue by aimarkov1** [nozzlegear/ShopifySharp#247]
Hi,
I'm trying to make simple call to Shopify with ShopifySharp. My sample code:
 ProductService service = new ProductService("MyUrl", "MyPassword");
 int count = service.CountAsync().Result;

While it works perfectly find in .Net console application and in Core Web Api, it doesn't work under .Net Framework Web Api project.
Request got stuck and "service.CountAsync().Result;" call doesn't return. 
When I try to run it with Fiddler, I can see the request and correct response, but call doesn't return to caller and my int count newer gets the value returned from Shopify.
 
Any ideas?
Thanks in advance.

**Comment by nozzlegear** [comment]
Hey @aimarkov1, it sounds like it's getting in a deadlock somewhere. The easiest way to fix this would be to use `await` if possible: `int count = await service.CountAsync()`. If that's not possible, I *think* you need to use `ConfigureAwait(false)` on the task, although I'm not :100: on that. 

```cs
var countTask = service.CountAsync();
countTask.ConfigureAwait(false);
int count = countTask.Result;
```

Let me know if that works.

**Comment by aimarkov1** [comment]
int count = await service.CountAsync() worked.
Configure await didn't.

Thanks.

**Comment by nozzlegear** [comment]
Great!
