### ISSUE TITLE
Shippingline needs a phone field

### ISSUE THREAD

**Issue by MortenKL** [nozzlegear/ShopifySharp#248]
When creating rates through the carrier service, you have the option of specifying that the customer must enter a phone number for that rate (which may be needed by the carrier), If that phone number is filled during checkout it will appear on the shippingline, it doesen't need to be the same as the phone number on the shipping address. 
So.. the issue is:
{  
            "id":12345678910,
            "title":"Some title",
            "price":"0.00",
            "code":"Some code",
            "source":"Some source",
            "phone":"01 12 23 34 45 56", <--- missing
            "requested_fulfillment_service_id": null,
            "delivery_category":null,
            "carrier_identifier":"dsf987sf98dsfssdf879sdf9sd8f",
            "discounted_price":"0.00",
            "tax_lines":[   ]
}
Really great job btw... Thanks!

**Comment by nozzlegear** [comment]
Thanks! I'll get this in soon and update here when it's published.

**Comment by nozzlegear** [comment]
Released in 4.13.0 👍
