### ISSUE TITLE
Rename services in 5.0

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#252]
I'd like to rename all of the services we have right now to remove the `Service` suffix. There's no real reason to have it, plus it makes the `FulfillmentServiceService` sound kinda silly. I'm thinking of just pluralizing the name of the object they deal with, so `OrderService` would become `Orders` and `FulfillmentServiceService` would become `FulfillmentServices`.

**Comment by clement911** [comment]
Personally I prefer with the `Service` suffix. It makes it clear that it makes remote calls. I'm not so sure about `Orders`.
Here are a couple of other suggestions: `OrderResource`, `OrderEndpoint`.

**Comment by nozzlegear** [comment]
Yeah if people like the Service suffix we can also think about keeping that! Nothing is set in stone yet. I'm just trying to brainstorm some way to make the `FulfillmentServiceService` and `FulfillmentServiceEntity` less awkward.




--


Josh Harms







On Tue, May 22, 2018 at 5:41 PM -0500, "Clement Gutel" <notifications@github.com> wrote:












Personally I prefer with the Service suffix. It makes it clear that it makes remote calls. I'm not so sure about Orders.

Here are a couple of other suggestions: OrderResource, OrderEndpoint.

**Comment by clement911** [comment]
Got you. I don't mind `FulfillmentServiceService`. It's fine :)
My thinking is that it's better to keep all other names intuitive even if one of them is weird, rather than makes them all confusing just to avoid a single weird `ServiceService`

**Comment by foxandrewj** [comment]
I agree with @clement911.  It is the service that works with FulfillmentServices.  It is awkward, but not unclear as it conforms to the semantics of the project.  And definitely not worth such a breaking change.

**Comment by nozzlegear** [comment]
Sure, I don't mind the `FulfillmentServiceService` so much, but `FulfillmentService` and `FulfillmentServiceEntity` are a little confusing when none of the other entities have an "Entity" suffix. Maybe a better solution would be namespacing the services and entities to `ShopifySharp.Services` and `ShopifySharp.Entities`.

**Comment by nozzlegear** [comment]
Those are good suffixes too. I'll think more on this, but right now I'm leaning toward leaving the Service suffix and possibly namespacing the Entities instead.

**Comment by davron12** [comment]
If you're going to change or remove the suffix, I'd lean towards a different suffix rather than pluralized. I can foresee the following if you go the pluralized route:

```
var orders = new Orders();
var orders = await orders.ListAsync();

```

Namespacing would remove the FulfillmentService problem as well, and would follow the folder-namepace best practice. The problem is, it's going to break a lot of existing code. Well, any of these suggested changes are going to break existing code.
