### ISSUE TITLE
Missing property in Fulfillment entity

### ISSUE THREAD

**Issue by kgrvr** [nozzlegear/ShopifySharp#254]
As per Shopify docs here: https://help.shopify.com/api/reference/shipping_and_fulfillment/fulfillment

A warning specifies: After July 1st, 2018, apps will be required to specify a location_id when creating fulfillments.

Fulfillment entity don't contain **location_id**.

**Comment by nozzlegear** [comment]
Good catch! I'll get this in one of the next releases.

**Comment by davron12** [comment]
@nozzlegear - I already got this, as well as an undocumented destination property. I'll be sending a pull request soon.
