### ISSUE TITLE
SmartCollection doesen't have a published property

### ISSUE THREAD

**Issue by MortenKL** [nozzlegear/ShopifySharp#258]
When creating a SmartCollection, you can choose to hide it on creation, for instance if it is used by an app and not for public display.
To create a hidden SmartCollection you need to create it with the published property set to false.
https://help.shopify.com/api/reference/products/smartcollection#create

It seems, if I'm not mistaking, that the property is not in ShopifySharp ?

**Comment by nozzlegear** [comment]
Thanks for bringing this to my attention. I did a little investigating and it looks like the `published` property doesn't exist on the object itself, it's just one that needs to be added when creating or updating a collection. I've added an extra parameter to `SmartCollectionService.CreateAsync` which lets you set it as published or not, and I've also added a `SmartCollectionService.PublishAsync` and `SmartCollectionService.UnpublishAsync`. These changes are available in 4.15.0 on Nuget.
