### ISSUE TITLE
Cannot read orders older than 60 days

### ISSUE THREAD

**Issue by olliehuynh** [nozzlegear/ShopifySharp#260]
Hi Team,

I have no idea what this is, can you please help. Obviously when we GET an order without delivery details, it works fine but when getting an orders with all details, it return the below
![image](https://user-images.githubusercontent.com/37202494/41263053-9cc01c00-6e38-11e8-8535-00617cef3cff.png)
[ShopifyException: Error: Not Found]
   ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse) +799

Code was 

order = await service.GetAsync(i);

Please help urgent please. Thanks heaps

**Comment by olliehuynh** [comment]
Just realised that they won't allow us to access orders that are older than 60 days. Will have to re-auth the app with read-all-orders scope to get this works

**Comment by nozzlegear** [comment]
Very interesting, I wonder when they made that change.

**Comment by olliehuynh** [comment]
Most customers won't leave their orders for too long but they might need to sometimes and won't be really handy for testing. Need to create new orders all the time. Now will have to get all customers to re-auth the apps. F###!

**Comment by nozzlegear** [comment]
Don't worry, I feel your pain! One of my apps got hit with it too, but at least my "main" one was grandfathered in. But even with it grandfathered I still have to ask for the new permission and reissue tokens before July 9th. What a pain.

**Comment by clement911** [comment]
I got bitten by that too. Total pain.
