### ISSUE TITLE
Cookie Auth Fails in Embedded App

### ISSUE THREAD

**Issue by valmont** [nozzlegear/ShopifySharp#262]
I am creating an app using .NET Core 2.1

When the app loads in the iFrame, the auth cookie is never set or read. Auth works fine outside of the iFrame. What am I missing?

I am running ngrok using: `ngrok http -subdomain=mydomain -host-header=localhost:62754 62754`

Here is my `AuthorizationHandler.HandleRequirementAsync` method 👍 

```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
      SubscribedRequirment requirement) {
      // Get the context       
      if (!(context.Resource is AuthorizationFilterContext redirectContext)) {
        context.Fail();
        return Task.CompletedTask;
      }
      var isAuthenticated = _signInManager.IsSignedIn(context.User); // <-- This is always false in embedded iFrame
      if (isAuthenticated) {
        var userId = context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value; 
        //Get the shop's status from the CacheEngine.
        var status = _cacheEngine.GetShopStatus(userId);
        if (status.BillingIsConnected && status.ShopIsConnected) {
          context.Succeed(requirement);
          return Task.CompletedTask;
        }
        if (status.BillingIsConnected == false) {
          //User has connected their Shopify shop, but they haven't accepted a subscription charge.
          redirectContext.Result = new RedirectToActionResult("register", "charge", null);
          context.Succeed(requirement);
          return Task.CompletedTask;
        }
        //User has created an account, but they haven't connected their Shopify shop.
        redirectContext.Result = new RedirectToActionResult("register", "connect", null);
        context.Succeed(requirement);
        return Task.CompletedTask;
      }
      //User has created an account, but they haven't connected their Shopify shop.
      redirectContext.Result = new RedirectToActionResult("index", "home", null);
      context.Succeed(requirement);
      return Task.CompletedTask;
    }
```

In Start up
```
services.Configure<CookiePolicyOptions>(options =>
      {
        options.CheckConsentNeeded = context => false;
        options.MinimumSameSitePolicy = SameSiteMode.None;
      });
```

**Comment by clement911** [comment]
Are you testing with Safari?
Safari doesn't allow iFrame to set cookies so you must redirect out of the iFrame to set the cookies.
Also browser settings can be configured to reject third party cookies unless the site is explicitely whitelisted.

**Comment by StriveDen** [comment]
I've been struggling with this for few days, but I manage to solve this problem.

Change your Startup.cs part to this:

```
 services.ConfigureApplicationCookie(options => {
                options.Cookie.SameSite = SameSiteMode.None; 
});

```

**Comment by valmont** [comment]
@StriveDen I will give this a try tonight. Hoping this works. What version of .NET Core are you using?

@clement911 No, using chrome.

**Comment by StriveDen** [comment]
.NET Core 2.0

**Comment by valmont** [comment]
@StriveDen That worked. Thank you very much for sharing your solution and saving me a bunch of time.

**Comment by valmont** [comment]
This seems to have resurfaced. Is there something else that needs to be changes? Currently I have this cookie options set:

```
services.ConfigureApplicationCookie(options => { 
        options.Cookie.SameSite = SameSiteMode.None;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        options.Cookie.HttpOnly = true;
      });

      services.Configure<CookiePolicyOptions>(options => {
        options.CheckConsentNeeded = context => false;
        options.MinimumSameSitePolicy = SameSiteMode.None;
        options.Secure = CookieSecurePolicy.Always;
        options.HttpOnly = HttpOnlyPolicy.Always;
      });
```

**Comment by Matt-Kaminski** [comment]
Which version of .Net are you using?

**Comment by valmont** [comment]
.NET Core 2.1

**Comment by valmont** [comment]
> Which version of .Net are you using?
> 
> I've had this problem with .NET Core 2.1. It turns out that there is a bug caused by SameSiteMode.None not sending any attribute. For me, this was the solution:
> 
> Does not work:
> 
> > myCookie.Path = "/";
> > myCookie.SameSite = SameSiteMode.None;
> 
> Do work:
> 
> > myCookie.Path = "/; SameSite=None";
> 
> Source:
> https://stackoverflow.com/a/58817862/4590784

Thank you for your reply. Did you change something in your `startup.cs` to make this work in `.NET Core 2.0` or did you upgrade to a newer versions of .NET Core?

**Comment by Matt-Kaminski** [comment]
> > Which version of .Net are you using?
> > I've had this problem with .NET Core 2.1. It turns out that there is a bug caused by SameSiteMode.None not sending any attribute. For me, this was the solution:
> > Does not work:
> > > myCookie.Path = "/";
> > > myCookie.SameSite = SameSiteMode.None;
> > 
> > 
> > Do work:
> > > myCookie.Path = "/; SameSite=None";
> > 
> > 
> > Source:
> > https://stackoverflow.com/a/58817862/4590784
> 
> Thank you for your reply. Did you change something in your `startup.cs` to make this work in `.NET Core 2.0` or did you upgrade to a newer versions of .NET Core?

I have updated framework to the newest version of 2.1, but it didn't work. Chrome DevTools was still showing that Auth cookie SameSite attribute wasn't set to None. It was quite an old App, so I didn't want update it to .NET Core 3.1.

Luckily, the hack with a Path did work. I have updated the app before the Chrome 80 update, but everything still works now, so this could work in your case as well.

**Comment by valmont** [comment]
Does your app also configure:

```
services.Configure<CookiePolicyOptions>(options => {
      options.CheckConsentNeeded = context => false;
});
```

**Comment by Matt-Kaminski** [comment]
> Does your app also configure:
> 
> ```
> services.Configure<CookiePolicyOptions>(options => {
>       options.CheckConsentNeeded = context => false;
> });
> ```

No, I do not configure this.

**Comment by valmont** [comment]
Still no luck. Do you mind showing me your `startup.cs`? So I can look for anything out of place?

**Comment by Matt-Kaminski** [comment]
> Still no luck. Do you mind showing me your `startup.cs`? So I can look for anything out of place?

Does your Auth cookie has SameSite attribute set to "None"? You can test your app outside Shopify Admin panel when it's not in an Iframe.

![image](https://user-images.githubusercontent.com/38296259/78170764-bb32d600-7453-11ea-872a-105d1bfbd992.png)

Regarding Startup.cs, I've noticed that I also have AddAuthentication configuration in ConfigureServices method, so it looks like it:

```
            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders(); //AddIdentity before the rest

//..

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.Cookie.SameSite = SameSiteMode.None;
                });

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
                options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
                options.Cookie.Path = "/; SameSite=None";
            });
```


Also, I have this piece of code in Configure method:
```
           app.UseCookiePolicy(new CookiePolicyOptions
            {
                MinimumSameSitePolicy = SameSiteMode.None,
                Secure =  CookieSecurePolicy.Always
            });
     //...
    services.AddMvc();   //AddMvc after the rest
```
However, I'm not sure if it will help. If remember correctly, I've tried adding above code and only the trick with Path worked.

**Comment by valmont** [comment]
Perfect. Found the issue. Thank you.

**Comment by elegault** [comment]
This post solved a major headache for me. THANK YOU!

**Comment by VishavP** [comment]
I have the same problem but my Blazor app directs to a page, not an iframe. I have tried all the solutions above but I'm still getting the same error -> The app couldn’t be loaded
This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser. 

This is what I have in my startup: 

services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(ConfigureCookieAuthentication);
services.AddAntiforgery(c =>
{
    // All embedded apps are loaded in an iframe. The server must not send the X-Frame-Options: Deny header
    c.SuppressXFrameOptionsHeader = true;
    c.Cookie.SameSite = SameSiteMode.None;
    c.Cookie.SecurePolicy = CookieSecurePolicy.None;
});
services.Configure<CookiePolicyOptions>(options =>
{
    options.CheckConsentNeeded = context => false;
    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
    options.Secure = CookieSecurePolicy.Always;
    options.OnAppendCookie = cookieContext => CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
    options.OnDeleteCookie = cookieContext => CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
});
services.ConfigureApplicationCookie(options => {
    options.Cookie.SameSite = SameSiteMode.None;
    options.ExpireTimeSpan = TimeSpan.FromHours(24);
    options.SlidingExpiration = true;
    options.Cookie.IsEssential = true; // Important for GDPR compliance
});

private bool DisallowsSameSiteNone(string userAgent)
{
    if (string.IsNullOrEmpty(userAgent))
    {
        return false;
    }

    if (userAgent.Contains("CPU iPhone OS 12") || userAgent.Contains("iPad; CPU OS 12"))
    {
        return true;
    }

    if (userAgent.Contains("Macintosh; Intel Mac OS X 10_14") &&
        userAgent.Contains("Version/") && userAgent.Contains("Safari"))
    {
        return true;
    }
    if (userAgent.Contains("Chrome/5") || userAgent.Contains("Chrome/6"))
    {
        return true;
    }

    return false;
}

private void CheckSameSite(HttpContext context, CookieOptions options)
{
    if (options.SameSite == SameSiteMode.None)
    {
        var userAgent = context.Request.Headers["User-Agent"].ToString();

        if (DisallowsSameSiteNone(userAgent))
        {
            options.SameSite = SameSiteMode.Unspecified;
        }
    }
}

My browser (Chrome) is set to allow all cookies.
