### ISSUE TITLE
Issue with IsValidShopDomainAsync

### ISSUE THREAD

**Issue by noamberda** [nozzlegear/ShopifySharp#266]
Since two days ago this method always return an invalid response.
I have tried to make the HEAD call manually and i can see that shopify header is "x-shopid" (Small letters)

looking at the source code the ShopifySharp i can see the following line
return response.Headers.Any(h => h.Key == "X-ShopId");

looks to me that its case sensitive!.

Could you please take a look ASAP

Thanks,
Noam

**Comment by nozzlegear** [comment]
Strange, I swear we had a pull request that addressed this already. I'll get it in the next release.

**Comment by nozzlegear** [comment]
The function will now ignore case when searching for the header. This change is published on Nuget in version 4.15.2. Thanks for bringing it to my attention!

**Comment by noamberda** [comment]
Thx
