### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by Hipstere** [nozzlegear/ShopifySharp#268]
When I try to use CancelAsync, it doesn't come back with an exception, but doesn't cancel the order either.
I am running it with parameter Restock = true.

Additional note: I've noticed that if you make a mistake in the API call, Shopify loads Login page with HttpOK (200), not sure if this helps at all.

**Comment by nozzlegear** [comment]
Interesting, what do you mean by making a mistake in the API call? Do you have an example I could look at that would make it return the login page?




--


Josh Harms







From: Hipstere


Sent: Tuesday, June 26, 06:40


Subject: [nozzlegear/ShopifySharp] Cancel Order (#268)


To: nozzlegear/ShopifySharp


Cc: Subscribed






When I try to use CancelAsync, it doesn't come back with an exception, but doesn't cancel the order either.


I am running it with parameter Restock = true.


Additional note: I've noticed that if you make a mistake in the API call, Shopify loads Login page with HttpOK (200), not sure if this helps at all.

**Comment by Hipstere** [comment]
Ok, I might be making this too confusing - it just doesn't work, I can't really tell why.
But I can give you an example (it's my test account):
https://huedash.myshopify.com/
ApiKey: 170cb05d5de28ca5bb61c6a5f8148a22
Password: 13ce667a8c1d0f6a75dd70720cbf05e5
Shared Secret: 613cb3339387ffb78090493b3d4afd15

Order No. 520784150613

**Comment by Hipstere** [comment]
Please hold, it might be a problem in my code after all (what would make sense to me too).

**Comment by Hipstere** [comment]
Sorry about this - all works, my mistake. Many thanks for quick response!

**Comment by nozzlegear** [comment]
No problem, glad you got it figured out!




--


Josh Harms







On Tue, Jun 26, 2018 at 9:18 AM -0500, "Hipstere" <notifications@github.com> wrote:












Sorry about this - all works, my mistake. Many thanks for quick response!
