### ISSUE TITLE
Product Filter with sku and inventory

### ISSUE THREAD

**Issue by kaikubadBS23** [nozzlegear/ShopifySharp#270]
Is there any way to filter product with sku and inventory?
thanks in advance

**Comment by dkershner6** [comment]
There is not.  Shopify does not provide this functionality.  It would be at the variant level, but most of the filters are at the product level and can be seen here: https://help.shopify.com/en/api/reference/products/product#endpoints

If you wanted to implement this, you would first need to get all products and variants, and then use linq or similar to filter your list.  Not difficult, but would use a lot of API calls, so only want to do it once.

**Comment by nozzlegear** [comment]
Correct, there's sadly no way to filter to that without pulling in the entire product list or using the GraphQL API.

**Comment by carrocon** [comment]
It seems to be possible now (see [ProductVariantUpdate](https://help.shopify.com/en/api/graphql-admin-api/reference/mutation/productvariantupdate) that admits a [ProductVariantInput!](https://help.shopify.com/en/api/graphql-admin-api/reference/input_object/productvariantinput) as argument).
