### ISSUE TITLE
Simplify the Update calls.

### ISSUE THREAD

**Issue by raboud** [nozzlegear/ShopifySharp#273]
Example 

` 
        public virtual async Task<Product> UpdateAsync(long productId, Product product)
`

would become 

`
        public virtual async Task<Product> UpdateAsync(Product product)
`

since the Product Class contains the Id.

this could be a replacement method or an overload to not break existing code.

**Comment by dkershner6** [comment]
Seems like a good idea to me, I'm always just pulling it out of the object anyway.

**Comment by raboud** [comment]
personally i like the overload....i actually wrote my own wrappers to do it and you could assert or (forgive me for saying) throw an exception if the Id is not set. Not a huge fan of exceptions but this case may warrant it.

**Comment by nozzlegear** [comment]
I'm closing this for now just because I haven't had the time to implement it myself. I'd be happy to accept a pull request for it if somebody wants to contribute it! In the meantime, you might be able to create your own extensions that will achieve this for you:

```cs
public static class OrderServiceExtensions
{
    public static async Task<Order> UpdateAsync(this OrderService service, Order order) => await service.UpdateAsync(order.Id.Value, order);
}
```
