### ISSUE TITLE
Target netstandard2.0

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#275]
Had a very brief discussion with David Fowler on Twitter about targeting netstandard2.0 in packages. There's nothing really blocking this as far as I know, and since netstandard2.0 simplifies the dependency graph it seems like an easy win for those targeting it. We'd still continue to specifically target net45 and netstandard1.4, I see no reason to remove those targets.

**Comment by clement911** [comment]
That's great to know. Asp.net core 3.0 will not run on .net framework so I will probably have to migrate to .net core at some point too!
I guess it was a good idea to use the HttpClient instead of a third party REST lib since HttpClient is fully supported on .net core.

**Comment by dkershner6** [comment]
No doubt that contributed to the easy transition, although I just had a look, and all the RestSharp's of the world appear to be supported too.

In fact, I find it hard to find libraries that don't, unless they are something very windows specific (System.Drawing comes to mind).

**Comment by clement911** [comment]
Ok that's good.
Hopefully migrating is not too hard. Not only for libraries but also the project files are different...

**Comment by dkershner6** [comment]
Migrating my apps from .Net Framework 3.6.1 to .Net Core took about...40 find and replaces, and a bit of cleanup.  For the one app that used System.Drawing, it took some doing, found a good replacement though.

My apps are pretty dependency light though, really just use ShopifySharp and some EntityFramework stuff.

I thought it would be much tougher than it was.

**Comment by dkershner6** [comment]
This issue can be closed.
