### ISSUE TITLE
Customer service does not retrieve all customers

### ISSUE THREAD

**Issue by snugglesftw** [nozzlegear/ShopifySharp#276]
I notice that the api calls retrieve only 50 items. Is there a way to get all the full list?
I am aware that shopify api has paging feature, but i cannot find anything in your api.

any insight will be appreciated.

**Comment by dkershner6** [comment]
There's a limit in listfilter. You can set it up to 250. https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Filters/ListFilter.cs

**Comment by snugglesftw** [comment]
im a idiot, just realized it after scanning the source code. lol
it will be nice if it's mentioned in the document? (unless im blind again)
