### ISSUE TITLE
Help OrderService is returning 0

### ISSUE THREAD

**Issue by snugglesftw** [nozzlegear/ShopifySharp#277]
HELP, I am really baffled here. 
I am using latest ShopifySharp to connect to the shop via private app (token). 
I have given read access to all the permissions.
For reason, when i issue a ListAsync order call, i get 0 results. 

Am i doing something wrong?
![image](https://user-images.githubusercontent.com/3228334/43041190-64369d2a-8d0d-11e8-9f84-ea72c5b02559.png)
![image](https://user-images.githubusercontent.com/3228334/43041195-8bddb480-8d0d-11e8-9153-f9da100ae060.png)

**Comment by dkershner6** [comment]
Maybe there are no open orders, use status = any

**Comment by snugglesftw** [comment]
oh i assumed the OrderService will retrieve everything. Let me give it a try

**Comment by nozzlegear** [comment]
Hey @snugglesftw, let me know if it's still not working for you after using `status = "any"`.
