### ISSUE TITLE
Inventory Level

### ISSUE THREAD

**Issue by S-Rahemi** [nozzlegear/ShopifySharp#281]
is there any implementation about shopify new feature inventory level ??
 based on this link : https://help.shopify.com/en/api/guides/inventory-migration-guide
many apis about variants will be deprecated after 1 August, and you can not use variant to update quantity
plz help how can i update inventory quantity?

Thanks

**Comment by dkershner6** [comment]
https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Services/InventoryLevel/InventoryLevelService.cs

It's used similarly to the other services in this library.  The one in question here is SetAsync, I believe.
