### ISSUE TITLE
Best practice for authenticating third party API

### ISSUE THREAD

**Issue by thivy** [nozzlegear/ShopifySharp#287]
I am building an external API to store data that is related to my Shopify application. This API will be called using the embedded app that i've build using ReactJS.

What is the recommended way to authenticate my API?

**Comment by nozzlegear** [comment]
Sorry, just to be clear, you want to know the best practice for having a Shopify merchant install your app and then log into it, correct? They need to log in to use your app?

**Comment by thivy** [comment]
[https://photos.app.goo.gl/vbwz6RYJe7qaheSd9](url)
This is what i am trying to figure. What is the best practice to protect "My API" where i have to store data related to only my app based on store domain name.

**Comment by dkershner6** [comment]
If your API calls are made from within Shopify admin or as an app proxy, you can use authorization service of this library to authenticate.

If you are creating an outside API called by merchants directly, you will need to use standard API auth methods.

If you are calling from the Shopify front end, it's difficult to protect anything. I'd recommend only having public information and not protecting or some kind of rapidly rotating credential.
