### ISSUE TITLE
Can not get orders...

### ISSUE THREAD

**Issue by nlevos** [nozzlegear/ShopifySharp#289]
Hi! I can not list orders past around page 25... it stops bringing more orders...

and if I try to get an order by id directly (around that range back) past this I get order not found..

id there a limit to the orders you can get with the shopifysharp api?

Same code used to work great for over a year now.. but now it does not..

::

     var count = await orderService.CountAsync(new ShopifySharp.Filters.OrderFilter()
            {
                Status = order_status
            });
            while (page <= count/250)
            {
                page += 1;
                var filterOptions = new ShopifySharp.Filters.OrderFilter()
                {
                    Limit = 250,
                    Status = order_status,
                    Page = page
                };
                importedOrders.AddRange(await orderService.ListAsync(filterOptions));
       ........

after around page 25 no new orders are coming in...

**Comment by bartcoppens** [comment]
You need a specific permission for your app to be able to get all orders. Contact Shopify.

**Comment by nlevos** [comment]
Hey Bart!

Is this new?

**Comment by nlevos** [comment]
Actually I just checked and I have permissions..

So it's not that!

"Your app can access the full order history for a store."

Does anybody know what could be the problem??

**Comment by bartcoppens** [comment]
So your app has this permission (check in App Setup)?:
[cid:image001.png@01D45511.B402E2C0]

**Comment by nlevos** [comment]
I can not see the image, but the app has the permission as I said..

don't know why it stopped listing all orders..

**Comment by nlevos** [comment]
Basically I can not get orders more than 2 months old

**Comment by nozzlegear** [comment]
I think this is indeed what @bartcoppens suspects. There's a special permission you need to ask for to get orders that are older than 60 days. It's not the same permission that you use when getting an access token from the merchant during OAuth. You have to check the box in your app settings in your Shopify partner dashboard, and then get approved by Shopify:

![image](https://user-images.githubusercontent.com/2417276/46038048-a98aa880-c0cf-11e8-8696-b76f7a0169d6.png)

Once you are approved, you *do* need to add that permission to the ones asked for during OAuth installation.

**Comment by nlevos** [comment]
I have permissions needed - don't know what is wrong..

![untitled-1](https://user-images.githubusercontent.com/34457545/46038278-9defaf80-c0d8-11e8-89b8-78f0eef51083.jpg)

**Comment by nozzlegear** [comment]
Okay, and just to be sure, the access token you're using was granted with the `read_all_orders` permission? It's not the same as the `read_orders` or `write_orders` permissions. If you're sure it was granted with that permission, could you show the code you're using to list all orders?

**Comment by StriveDen** [comment]
I suspect that you just requesting "read_orders",  but not "read_all_orders" permission.

**Comment by nlevos** [comment]
wait - i will check

**Comment by nozzlegear** [comment]
Glad you got it working!
