### ISSUE TITLE
Wrong Data Type

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#29]
in the ShopifyProductFilterOptions class

        [JsonProperty("title")]
        public **long**?Title { get; set; } = null;
        [JsonProperty("vendor")]
        public **long**? Vendor { get; set; } = null;
        [JsonProperty("handle")]
        public **long**?Handle { get; set; } = null;
        [JsonProperty("product_type")]
        public **long**? ProductType { get; set; } = null;

these should be string type.
thanks

**Comment by mooglegiant** [comment]
I already ran into this testing a product search, and already added it to my pull request #27.

**Comment by ishahrier** [comment]
Great!!
I don't know how to commit or give you guys my changes...I have worked on CustomCollection and Smart Collection I just don't know how to put it back into git hub ..I am just not familiar with git hub :S

**Comment by mooglegiant** [comment]
You would fork your own version from GitHub, Edit in visual studio, Commit it to your fork, then from your fork, you have to create a pull request. Then Nozzle can see it as a pending change and commit it to his main branch.  GitHub has a decent walkthough on the step by step process.

**Comment by nozzlegear** [comment]
Thanks for pointing this out! Not sure how I missed this, looks like a copy-paste gone wrong. I've got @mooglegiant's changes merged into the master branch.
