### ISSUE TITLE
Grams in a product variant can overflow an int32

### ISSUE THREAD

**Issue by nico159** [nozzlegear/ShopifySharp#291]
Hi,
Shopify allows for the grams property to have a value larger than an int32. This property and the associated json converter NullToZeroConverter should use int64 as type instead.

**Comment by clement911** [comment]
The shipping cost is going to be very high ;)

**Comment by nozzlegear** [comment]
Looks like this was fixed at some point and the issue didn't get closed. ProductVariant.Grams is a long as of 4.21.7!
