### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#292]
Hey everyone! If it isn't obvious by the slowly rising issue count and lack of any commits since August, I'm finding it pretty difficult to maintain this project by myself lately. It's not that I don't want to, I just don't have the time at the moment with all of my client work. 

I'm looking for somebody to help maintain the project by helping with issues/questions, pushing bugfixes and even writing new services or features if you have the will. Not asking anybody to make this their job, but if you've got some spare time and think you could lend a hand every now and then, I would be supremely grateful. I don't have any strict requirements or guidelines for potential maintainers, just that you be kind to people interacting with the project, and that you run major changes by me before implementing some kind of crazy rework or breaking change. 

If you're interested, reply here or send me an email at joshua@nozzlegear.com if you want to discuss it further. 

(And just to dispel any potential fear, this doesn't mean the end of the project if no maintainers are found. I still use this package every day personally, I'm just finding myself strapped for time to do much beyond bugfixes at the moment. I'll still be actively involved in the project and writing new features/services when I have the time.)

**Comment by clement911** [comment]
Hi Josh,
I've also been trying to send PRs as often as my time permits.
I understand it can be quite time consuming.
I feel like the library is quite stable overall, and whoever desperately needs a feature/bug fix should be able to submit their own PRs.

I'm not familar with owning a project on github.
Is it mainly about vetting the PRs? Are you thinking to share those merging rights with someone?

I'm not opposed to the idea, but I won't always be able to be super responsive...

**Comment by nozzlegear** [comment]
@bartcoppens Thanks Bart, I appreciate all of the help you've been offering already!

@clement911 Yes, I would share merge rights with maintainers. In my mind it would mostly be responding to issues (which you do already -- thank you!), labeling them, closing them, and vetting/merging PRs. With merge access you'd be able to get new features in if you wanted to or needed it, but like you said the project is pretty stable so maintenance would largely be about issue management and PRs. Please don't feel obligated to do it if you don't want to! You're already super helpful!

**Comment by clement911** [comment]
Thanks @nozzlegear.
I personally feel that vetting/managing PRs is the single most important part to ensure the project stay stable, and I don't believe there is any bottleneck there.
As I said, if someone needs a bug fix or enhancements, then they should submit a PR if they really need to, but of course this doesn't seem to happen too often...

**Comment by clement911** [comment]
Is it appveyor that provides build and nuget publishing? I'm not familiar with it...

**Comment by nozzlegear** [comment]
Yep, it’s AppVeyor. It’s not as fully automated as I’d like, it still requires writing release notes, creating a GitHub release and pressing the publish button, but it’s better than having to build it and run tests on my own machine.

--
Josh Harms

**Comment by nozzlegear** [comment]
If everyone's okay with the current pace of releases (I was worried it was too slow), then I'm happy with the way things are! The slow pace won't last forever either, once I have more spare time I'll get back to this project with a more regular release rate. So I'll close this issue for now, but if anyone reads this and is interested in becoming a maintainer just let me know!

**Comment by clement911** [comment]
Thanks @nozzlegear.
I think you're doing great. You've been very responsive actually, especially compared to most other open source projects I use.
I'm also hoping to start contributing again on this library once I finish my current project...
