### ISSUE TITLE
GDPR Webhooks - something not quite right?

### ISSUE THREAD

**Issue by Panksy** [nozzlegear/ShopifySharp#293]
Hi, I'm probably being stupid but I'm implementing my shopify GDRP webhook responses and using the shopify test data to test it with and something is not going quite right. When I send the following Json to my customers redact webhook, the customer data is fine but the shop id and shop domain are blank. What am I doing wrong? Or is something amiss.

Code: 
```
public string Redact([FromBody]CustomerRedactedWebhook data)
{
Log.InfoFormat("Customer Redact Shop={0} Customer:{1}",data.ShopDomain, data.Customer.Email);
return "true";
}
```

![image](https://user-images.githubusercontent.com/5558648/46691093-530b8700-cc04-11e8-8fe0-81c747e2e227.png)

Posting a payload from the Shopify Docs:
{
  "shop_id": 954889,
  "shop_domain": "snowdevil.myshopify.com",
  "customer": {
    "id": 191167,
    "email": "john@email.com",
    "phone": "555-625-1199"
  },
  "orders_to_redact": [299938, 280263, 220458]
}

**Comment by Panksy** [comment]
I should also see that my shop redact is also returning blank data. So I guess there is something going on here:
```
public string Redact([FromBody]ShopRedactedWebhook data)
{
	Log.InfoFormat("Shop Redact request {0} : {1}",data.ShopId, data.ShopDomain);
	return "true";
}
```
{
    "shop_id": 954889,
    "shop_domain": "snowdevil.myshopify.com"
}

**Comment by nozzlegear** [comment]
Hmm interesting! The first thing I would check is that the ShopRedactedWebhook entity has the correct [JsonProperty] attribute set on it. I’m writing from email right now though, so not able to check the repo to see what they look like. 

--
Josh Harms

**Comment by nozzlegear** [comment]
Looking at the ShopRedactedWebhook, it seems like the `JsonProperty` attributes are correctly set. This is going to require a little more digging as I don't see anything obvious jumping out at me.

**Comment by dkershner6** [comment]
I can't reproduce the issue, so it is something in the way you are calling your method.

Test data:
`{
"shop_id": 954889,
"shop_domain": "snowdevil.myshopify.com"
}`

Test code:
`log.Info("C# HTTP trigger function processed a request.");            

            string data = await req.Content.ReadAsStringAsync();

            try
            {
                ShopRedactedWebhook hook = JsonConvert.DeserializeObject<ShopRedactedWebhook>(data);

                log.Info(hook.ShopDomain);
                log.Info(hook.ShopId.ToString());

                return req.CreateResponse(HttpStatusCode.OK);
            }`

Log:
`2018-10-09T21:25:57.502 [Info] C# HTTP trigger function processed a request.
2018-10-09T21:25:57.843 [Info] snowdevil.myshopify.com
2018-10-09T21:25:57.843 [Info] 954889
`

**Comment by dkershner6** [comment]
Same results when using:
```
{
"shop_id": 954889,
"shop_domain": "snowdevil.myshopify.com",
"customer": {
"id": 191167,
"email": "john@email.com",
"phone": "555-625-1199"
},
"orders_to_redact": [299938, 280263, 220458]
}
```

**Comment by clement911** [comment]
The entity looks correct to me.
I personally deserialize manually with `JsonConvert.DeserializeObject` so I wonder if it's something to do with Web API not treating IEnumerable<> members specially.
You should probably consider deserializing manually as well so that you can call `IsAuthenticWebhook`.

**Comment by nozzlegear** [comment]
I also wonder if it's something to do with Web API deserializing. @Panksy can you try taking the `[FromBody] CustomerRedactedWebhook data` out of your action parameter and instead read the body string/deserialize manually? I suspect that this might be that thing where ASP.NET will only read a body once and then all future attempts at reading it (even in an Action parameter) will just return an empty string instead.

**Comment by Panksy** [comment]
Hi all,

Yes @nozzlegear you are correct. The below code works fine. so it is something to do with the reading it directly with FromBody. I actually have no filters or decorations in this controller so far though so I'm not sure what is messing with it. Its also really weird that it could read the customer object contained within. 
```
public async Task<string> Redact()
		{
			string data = RequestBody(System.Web.HttpContext.Current);
			ShopRedactedWebhook hook = JsonConvert.DeserializeObject<ShopRedactedWebhook>(data);
```
But anyway I would have put in the isAuthenticWebhook check next so I guess I would probably have had to change to manually deserialising anyway. Thanks for you help.

**Comment by nozzlegear** [comment]
That is definitely strange now that I think about it. I don't know why the customer would deserialize but the rest wouldn't.

**Comment by 0983210321** [comment]
Good
