### ISSUE TITLE
AuthorizationService.IsAuthenticRequest fails when querystring contains special url characters

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#294]
Raising this for reference.
I discovered this issue when I stored a url in state parameter, which contained a "&".

`AuthorizationService.IsAuthenticRequest` returned false even though the request was authentic.

I believe the code incorrectly escapes uri characters.

        private static string EncodeQuery(StringValues values, bool isKey)
        {
            string s = values.FirstOrDefault();

            if (string.IsNullOrEmpty(s))
            {
                return "";
            }
      
            // use standard url decoding, to match ruby Rack::Utils.parse_query(query_string)
            string output = Uri.UnescapeDataString(s);

            if (isKey)
            {
                output = output.Replace("=", "%3D");
            }

            return output;
        }

Shouldn't it be `Uri.EscapeDataString(s)` instead?

Also not sure why there is a special encoding of '=' characters, applied only to keys?

The raw version also seems to have a bug. Why is it unescaping the raw query string?

        public static IDictionary<string, string> ParseRawQuerystring(string qs)
        {
            // Must use an absolute uri, else Uri.Query throws an InvalidOperationException
            var uri = new UriBuilder("http://localhost:3000")
            {
                Query = Uri.UnescapeDataString(qs)
            }.Uri;
            var match = _querystringRegex.Match(uri.PathAndQuery);
            var paramaters = new Dictionary<string, string>();
            while (match.Success)
            {
                paramaters.Add(match.Groups[1].Value, match.Groups[2].Value);
                match = match.NextMatch();
            }
            return paramaters;
        }

**Comment by nozzlegear** [comment]
Thanks for opening this issue! It looks like that should definitely be `Uri.EscapeDataString`, that must have been a typo that wasn't caught by tests. Regarding the special encoding of = for keys, I want to say that was part of Shopify's own instructions for validating the request, but I'm not 100% sure on that and would have to look it up again.

**Comment by clement911** [comment]
Right, I think this commit broke it as it changed from encoding to decoding.
https://github.com/nozzlegear/ShopifySharp/commit/6cab8c10b564349d134cfa2bcb8f709b316ea612#diff-efd0e1e9b21e24919164274aff2035c8

**Comment by clement911** [comment]
This should be good to go!

**Comment by nozzlegear** [comment]
Published in 4.16.3, thank you!

**Comment by clement911** [comment]
And thank you for the quick release!
