### ISSUE TITLE
Request Validation Fails everytime

### ISSUE THREAD

**Issue by Uffman** [nozzlegear/ShopifySharp#296]
Did Shopify change verification Request, because my request verification fails since 17th October.

**Comment by clement911** [comment]
For webhook requests?

**Comment by Uffman** [comment]
No, Shopify Request

**Comment by zfteo** [comment]
There are extra variable(protocol) at App URL now.

https://testapps.com/app/Install?hmac=f12f020f8935ee645893dlkll782cba604e1f840f62ce5fdb94d17cee&locale=en&**protocol=https%3A%2F%2F**&shop=testapp.myshopify.com&timestamp=1539940422

If I remove the protocol, it's able to call the function. 

Currently I'm using 

 **public async Task<ActionResult> Install(string shop, string signature, string timestamp,string locale,string protocol)**

but it doesn't work.

Any advice?

**Comment by nozzlegear** [comment]
Could you show the code for how you're validating the request? As far as I know nothing has changed with the authorization scheme, and it appears to be working for all of my own apps still.

**Comment by zfteo** [comment]
public async Task<ActionResult> Install(string shop, string signature, string timestamp,string locale,string protocol)
        {                      
            var qs = Request.QueryString;
            if (AuthorizationService.IsAuthenticRequest(qs.ToString(), SecretKey))
            {              
                //Request is authentic.
                if (await ShopifyUserValidation(shop))
                {                 
                    string r = BuildAuthUrl(shop) + "&shop=" + shop;
                    return Redirect(r);               
                }
                else
                {
                    return Redirect(AppUrl);
                }
            }
            else
            {     
                return Redirect(AppUrl);
            }
        }

This is my code to validate the request.

**Comment by Uffman** [comment]
I have similar. I contacted Shopify Twitter support and they said they are experiencing this issue across some apps

**Comment by nozzlegear** [comment]
Interesting. I don't see anything wrong with your code @zfteo. I've got my own apps running that use almost identical code for request validation and everything is still working fine.

**Comment by StriveDen** [comment]
Look here guys:
https://ecommerce.shopify.com/c/shopify-apps/t/hmac-verification-546128?fbclid=IwAR1YcXkPNwwGnV1LlcZWtWClkUgdxZ48_XSo_kPSZXUuwRlBflbFSPPhF4Y

It's a problem on their end.

**Comment by Uffman** [comment]
This is how I remove the protocol and locale from url, because I am not sure if protocol and local are fixed parameters:

var http = UrlEncodeUpperCase(protocol); 
var queryString = Request.QueryString.Value.Replace($"&protocol={http}", string.Empty).Replace($"&locale={locale}", string.Empty);

and the method:
   private string UrlEncodeUpperCase(string stringToEncode)
        {
            var reg = new System.Text.RegularExpressions.Regex(@"%[a-f0-9]{2}");
            stringToEncode = System.Web.HttpUtility.UrlEncode(stringToEncode);
            return reg.Replace(stringToEncode, m => m.Value.ToUpperInvariant());
        }

**Comment by Uffman** [comment]
We got this message from Shopify Developer Support

> We've rolled back the changes that introduced the issue. You should be back to normal. Sorry for any headaches this might have caused.

**Comment by nozzlegear** [comment]
Good to hear!

**Comment by zfteo** [comment]
Do they rolled back the changes? I still having the same issues.
