### ISSUE TITLE
Services no longer work for private app

### ISSUE THREAD

**Issue by moduIo** [nozzlegear/ShopifySharp#297]
Hi, I've been using ShopifySharp for a project at work and I found the API to be fantastic.  Today Services suddenly stopped working and halted Visual Studio with no errors.  I found that Postman needed configuration changes to work again for the same commands while it worked fine yesterday.

I ended up writing a custom Python script to handle my needs, however my company is a C# shop and I would love to be able to use my old ShopifySharp solution again.

Thanks.

**Comment by dkershner6** [comment]
I just sent a command through postman mimicking how ShopifySharp uses the key (password), and it worked fine...

I only have 1 private app, and it seems to be working OK...but I only monitored it for a few minutes.

By "Services", I assume you mean like ProductService, ArticleService, etc...or do you mean something else?  What is the error you are getting?

**Comment by moduIo** [comment]
Thanks for responding, it must be a local issue.
