### ISSUE TITLE
Update InventoryLevel

### ISSUE THREAD

**Issue by justinrumpf** [nozzlegear/ShopifySharp#299]
I understand that you can not update the inventory level through the ProductVariant service anymore, but can someone provide an example of the new way? Is there a new way through ShopifySharp?

Thanks, jr

**Comment by nozzlegear** [comment]
I believe you need to use the Locations API to do it, I just used it recently and it worked well, but I don't have an example unfortunately.




--


Josh Harms







On Wed, Oct 24, 2018 at 10:44 AM -0500, "justinrumpf" <notifications@github.com> wrote:












I understand that you can not update the inventory level through the ProductVariant service anymore, but can someone provide an example of the new way? Is there a new way through ShopifySharp?


Thanks, jr

**Comment by dkershner6** [comment]
I happened to have it open.  apiCall.InventoryLevel is just a ShopifySharp.InventoryLevel object.

```
public static async Task UpdateAsync(string shop, string token, ShopifyApiCall apiCall, ILogger log)
        {
            InventoryLevelService invService = new InventoryLevelService(shop, token);

                inventory = await invService.SetAsync(apiCall.InventoryLevel);            
        }
```

**Comment by justinrumpf** [comment]
Thanks.
