### ISSUE TITLE
Private App usage bad url formation?

### ISSUE THREAD

**Issue by Radigeco** [nozzlegear/ShopifySharp#308]
Hi,
I've recently stumbled upon this wrapper and tried to set it up with a shopify private app.
I have tried to connect to our shopify store, but it seems to me that the private app API usage samples and the wrapper is outdated. Based on shopify's guides, you should be forming the API url by using the password, api key and the store's url. But all the services inside this wrapper only require the password and store url as parameters. When I only pass those 2 I get a hanging request.
Am I missing something or has Shopify updated their private app API's ?

I've attached a screenshot to showcase how their guidelines show the url formation:
![shopify private app](https://user-images.githubusercontent.com/24960418/48785569-a4bc2c80-eced-11e8-9384-dde162610961.jpg)

Regards,
Attila

**Comment by dkershner6** [comment]
I was just working on a private app yesterday to no I'll effect. The Shopify instructions are just for ease, but you can actually pass only the password as well.

That being said, you are the second person to mention this, so maybe there is something out there preventing this in some cases. Are you able to use the API correctly elsewhere for the same call?

Derek Kershner

________________________________

**Comment by nozzlegear** [comment]
Hey Attila, I'm using this wrapper for several private apps and can confirm that it still works. Shopify's example does indeed make it look like the url needs to be formatted with the password and key, but it also works by passing it in the header like the wrapper does. One thing that might be confusing is that when you create a private app, you're given an API key and two other strings. I think one is called password and one is called shared secret. Password is the one you want.




To use this wrapper, your code should look like `var service = new OrderService("my-shop-with-private-domain.myshopify.com", "private-app-password")`




Sorry for the formatting, I'm on mobile. Let me know if that still doesn't work and I'll dig a little deeper.




--


Josh Harms







On Tue, Nov 20, 2018 at 9:50 AM -0600, "Attila Gál" <notifications@github.com> wrote:












Hi,

I've recently stumbled upon this wrapper and tried to set it up with a shopify private app.

I have tried to connect to our shopify store, but it seems to me that the private app API usage samples and the wrapper is outdated. Based on shopify's guides, you should be forming the API url by using the password, api key and the store's url. But all the services inside this wrapper only require the password and store url as parameters. When I only pass those 2 I get a hanging request.

Am I missing something or has Shopify updated their private app API's ?


Regards,

Attila

**Comment by Radigeco** [comment]
I've just tried hitting the products endpoint via Postman and it seems to be working okay.
After getting the confirmation from you guys that the wrapper should work only by using the password I tried to do some more debugging. It turns out I was missing an await call, the function being async. 
My bad, sorry for the topic :).
Thank you for your effort on developing this wrapper and the guides!

**Comment by nozzlegear** [comment]
No problem, glad you got it working!
