### ISSUE TITLE
How to perform a search based on Barcode?

### ISSUE THREAD

**Issue by anubhavranjan** [nozzlegear/ShopifySharp#316]
I am trying to find a product based on the Barcode. Is there a correct way to achieve this?

**Comment by nozzlegear** [comment]
Hey @anubhavranjan, it depends on how you're reading the barcode and what exactly the barcode contains. I've created my own applications that used barcodes as they were scanned by a barcode scanner, it was as easy as listening to a "value changed" event on a text field; users would select the text field, scan a barcode with the scanner, and the scanner would just enter that in the field. It was literally like the barcode scanner was pasting text into the field. If you're not using a barcode scanner and instead you're reading barcodes from e.g. an image, you'd need some kind of barcode reading package from Nuget. 

Whatever way you're doing it, the important part is what text the barcode represents. Think of it like a base64 hash, it's just representing text in another method. So if a barcode is just a product ID, you can easily use the Shopify API to look up the product with that ID: `productService.GetAsync(idFromBarcode)`. If the barcode is instead an order ID, you'll need to look up the order from Shopify -- and make sure you know the difference between a Shopify order's ID and an order's name.
