### ISSUE TITLE
Support GraphQL variables in GraphService

### ISSUE THREAD

**Issue by ghost** [nozzlegear/ShopifySharp#317]
It should be possible to send variables in the request via GraphService (see [this](https://help.shopify.com/en/api/graphql-admin-api/reference/mutation/inventorybulkadjustquantityatlocation) for an example).

This can be done setting the content-type to application/json and including and object with the query and variable properties or including the variables as query parameters.

**Comment by dkershner6** [comment]
It's pretty easy to fill in variables anyway in c# using the $ operator on a string, but...

I was under the impression that content-type had to be set to "application/graphql" on this API, am I wrong on that?  Can you just set it to Json and include an extra {} and some extra quotes (to make it valid json rather than graph)?  I haven't tested that, have you?

**Comment by carrocon** [comment]
I suppose it is possible to replace the $variable with the actual content but i'm not sure.

Regarding application/json, yes, it is supported and I have tested it.

**Comment by dkershner6** [comment]
Interesting...I would've just been doing that the whole time...sheesh.  Where'd you find this in the docs?  Or is this more of a "it's always this way in Graph" thing?

**Comment by carrocon** [comment]
This is a GraphQL thing. The expected JSON has this structure:
``{
  "query": "mutation <operationName> ...",
  "variables": {
    "myVar": {
      "myVarProp": "<myValue>"
    }
  },
  "operationName": "<operationName>"
}``

Note that variables can be any object.

**Comment by dkershner6** [comment]
https://github.com/nozzlegear/ShopifySharp/pull/318

**Comment by carrocon** [comment]
That approach should be enought. I was also thinking of using one of the well-developed GraphQL clients for C#. See [link](https://github.com/graphql-dotnet/graphql-client).

**Comment by dkershner6** [comment]
It would certainly be nice to have an actual non-string way to write GraphQL, but the extra dependency would need to be approved by the likes of @nozzlegear , and was outside the scope of my original goal (to leverage the auth and request sending of this library, and nothing more).

@nozzlegear - see the link directly above for a GraphQL .NET example library.  Using this would create an additional dependency, but would make Graph writing much easier.

@carrocon - you could always use that library externally, then .ToString() into this library as a workaround (I am presuming they have a ToString or something near to it).

**Comment by clement911** [comment]
Interesting indeed.
I was going to say it might be better to just create a GraphQLRequest class in ShopifySharp, but as stuff gets added we might end up recreating something very similar to Graphql.Client so it might be a better option to simply add the dependency. This library seems quite minimal..

**Comment by clement911** [comment]
What about the ability to deserialize into a class or a dynamic? That seems useful.

**Comment by dkershner6** [comment]
Always true, if you are getting an output of the object...but Graph queries are input only.  The outputs are just JSON (and the data portion of the response is custom to the query - hence my struggles).

**Comment by carrocon** [comment]
Another possiblity would be to include the actual mutations and queries within the GraphService as functions. It is of course a lot of work and very difficult to maintain (the same as it happens with the REST API) but it would make life easier to the ones using the library.

I would proceed splitting REST/Graph services into two subfolders and making GraphService the base class from which the rest of Graph query and mutation services inherit. I understand this is major refactor but again I'm thinking as a consumer that wants to minimize the job in his side. Furthermore, as far as i'm concerned I don't think we have a generic postAsync for making a REST API call to Shopify.

Anyway, i'm currently working in a similar solution myself, so if you think that this may be nice to have I can always share it and make a PR.

**Comment by karrocon** [comment]
Hi again. This is my alter ego account. I just wanted to share with you my experience these past 5 days.

Regarding GraphQL and Shopify, they are using the [Relay specification](https://facebook.github.io/relay/) for the Graph API. As you know, the main issue with this is that whenever you want to query for a connection (name for an any-to-many association) you have to include how many of the items you want to retrieve and you get a paginated response as a result.

There is a graphql-relay client for javascript but I was checking the status of the graphql-client for dotnet and there was no Relay implementation. So, I created [an issue](https://github.com/graphql-dotnet/graphql-client/issues/88) and an [small repository](https://github.com/karrocon/GraphQlClient) for simplifying Relay requests and for building GraphQL queries in an expression-based manner (similar to Linq).

Regarding Shopify, I tried to automatically download the schema using GraphQL introspection and then to extract the C# classes from it. It seems to work just ok.. but requires a lot of work to properly generate the code (maybe I will spend some time in the near future but not now). So, I'm just creating the classes/connections that I need to make queries and mutations. The main drawback of this approach is that, same as it happens with the REST API, these classes will be deprecated whenever Shopify changes the Graph API schema. However, on the other hand, it makes way easier the communication with strongly typed variables.

My idea is to create a new repository to hold an example about how to use the GraphQL Relay client together with the Shopify model to make these requests. If it is okay with you, I can share it whenever is done.

**Comment by nozzlegear** [comment]
That would be great @karrocon, please let me know when you're ready to share it and I'll add a link in the readme!

**Comment by dkershner6** [comment]
This sounds like what I was trying to do, but you are much further along and have a better idea. +1

Derek Kershner

________________________________

**Comment by nozzlegear** [comment]
By the way, I just want to quickly say sorry that I'm not very active in the graphql discussion, I still haven't had a chance to try it out myself -- not just in ShopifySharp but GraphQL in general! I've recently reduced my client workload though so after the holidays I'm going to sit down and get acquainted with it, then I'll be able to offer my own opinion on how this package should handle it.

**Comment by nozzlegear** [comment]
Does #318 close this @dkershner6?

**Comment by dkershner6** [comment]
It does, just barely according to @karrocon 9 days ago...but I am guessing we see more from @karrocon as he has time.

@nozzlegear

**Comment by nozzlegear** [comment]
Alrighty, I'm going to close this one then and we can open further issues to improve the functionality if necessary.
