### ISSUE TITLE
Shipping Line Id

### ISSUE THREAD

**Issue by wfterry** [nozzlegear/ShopifySharp#320]
Hello,
Our company is getting started with Shopify, and I have been going through all the documentation and looking at example orders that we have placed.

My question is that in our examples, I've noticed that the Shipping Line Items has an Id property on it, but I don't find it documented, or available within the Shopify Sharp project.  Is this a new field that has been added, or could it be a field that has been deprecated?  

Thanks,
Bill

**Comment by nozzlegear** [comment]
Hey Bill, thanks for bringing this up! It's possible that this is a new field, and it's also possible that it is an older field that has been deprecated. Shopify isn't the best at documenting the changes they make to their APIs, and I've found that it's generally not a good idea to rely on properties that they haven't documented; sometimes those properties will stick around and eventually become "official", but other times they'll be pulled with no warning, suddenly change their type (#226), become nullable, and so on. 

We try to play it safe with this project to make sure we're not using any properties or features that aren't officially documented by Shopify, as I try to make this package as reliable as possible (given the circumstances) for anyone using it.

With that said, are you using the Id property for Shipping Lines in your project? It *should* be possible to create your own class that extends Shipping Line, and then deserialize into that by using a wrapper class over the ShopifyService.

**Comment by wfterry** [comment]
So we are just getting started with Shopify, so still looking into what I get for data to determine what we use and don't use.
