### ISSUE TITLE
Enhance of GraphService to support strongly typed calls

### ISSUE THREAD

**Issue by karrocon** [nozzlegear/ShopifySharp#321]
Following [this discussion](https://github.com/nozzlegear/ShopifySharp/issues/317) about the current state of the GraphService I have created [a fork of this repository](https://github.com/karrocon/ShopifySharp) to make an initial proposal for strongly typed communication through Shopify GraphAPI. It only features some of the entities that Shopify supports but should be good to check how it works. Note that i'm making use of a dependency to GraphQlClient which greatly simplifies pagination for Relay-based communications (like the one we need to establish against Shopify). It also features a mechanism to automatically avoid throttling based on the response but i'm missing a better way to handle unexpected throttling errors.

Hereafter you can find two examples of use for both a query and a mutation.

```
// Example of a Query
// Gets the inventory items including the inventory level at a given location with 250 inventory items per page (to avoid throttling).

var shop = "myshop.myshopify.com";
var accessToken = "MY-TOKEN";
var locationId = 123456789;

var graphService = new GraphService(shop, accessToken);

var results = await graphService.QueryAsync(queryBuilder => queryBuilder
    .AddConnection(query => query.InventoryItems, 250, inventoryItemBuilder => inventoryItemBuilder
        .IncludeAllScalars()
        .AddObject(inventoryItem => inventoryItem.InventoryLevel, inventoryLevelBuilder => inventoryLevelBuilder
            .AddArgument("locationId", $"gid://shopify/Location/{locationId}")
            .IncludeAllScalars()
        )
    )
);

// As of now, we have to merge all pages all together. I would like to move this logic to the GraphQlRelayClient
var inventoryItems = return results
    .Select(x => x.InventoryItems)
    .SelectMany(x => x.Edges)
    .Select(x => x.Node);
```

```
// Example of a Mutation

IEnumerable<InventoryAdjustItemInput> items; // items are loaded somehow (e.g. via query)
var shop = "myshop.myshopify.com";
var accessToken = "MY-TOKEN";
var locationId = 123456789;

var graphService = new GraphService(shop, accessToken);
var results = await graphService.MutateAsync(new InventoryBulkAdjustQuantityAtLocationMutation
{
    InventoryItemAdjustments = items,
    LocationId = $"gid://shopify/Location/{locationId}"
});
```

So this is basically it. As you can see, i'm not totally sastisfied with the proposal yet and I'm eager to read your comments about it.

PS: Merry xmas!

**Comment by dkershner6** [comment]
This looks like an improvement, but I'm getting the impression that objects and graph are a tough mix. Sorry for delay in response.
