### ISSUE TITLE
Customer Service count method doesn't have filter parameter

### ISSUE THREAD

**Issue by ashah-kaira** [nozzlegear/ShopifySharp#322]
I can make REST Call & get total customers' count with filters.

https://##STORENAME##.myshopify.com/admin/customers/count.json?created_at_min=2001-01-01 00:00:00&created_at_max=2018-12-19 00:00:00

But I couldn't find any method in customer service to achieve same.
Please inform if someone know how to do that.

**Comment by nozzlegear** [comment]
Hey! Thanks for filing this issue. I understand you're trying to filter the count result for customers. Unfortunately, this feature is undocumented, so I'm hesitant to add support for this -- if Shopify were to stop supporting this filtering in the future, people using this undocumented feature would start receiving errors. If Shopify adds support in the future, I'll happily add this feature to the package!

However, that doesn't mean you can't make the CustomerService do what you're looking for. Each service can be extended, and each method is virtual which means you can override it or add an overload. You can do that like this:

```cs
namespace MyApp
{
    public class MyCustomerService : ShopifySharp.CustomerService
    {
        public MyCustomerService(string domain, string accessToken) : base(domain, accessToken)
        {
            
        }

        public async Task<int> CountAsync(MyFilterObject filter = null)
        {
            ...
        }
    }
}
```
