### ISSUE TITLE
Cancel or refund sinfle item

### ISSUE THREAD

**Issue by biodtl916** [nozzlegear/ShopifySharp#328]
First off, thank you for the incredible resource.

I am attempting to remove a single item from an existing order that will not be fulfilled. I am able to fulfill items, however I cannot figure out how to refund (or cancel) a single item. It appears from the documentation that the RefundService has not yet been implemented. Am I just missing something obvious or is this just something that needs implemented?

Thank you!

**Comment by jeremysimmons** [comment]
@biodtl916 it appears the [Orders > Refund](https://help.shopify.com/en/api/reference/orders/refund) is not part of ShopifySharp as of Release 4.18.1

**Comment by nozzlegear** [comment]
#400 Will implement the Refund service!
