### ISSUE TITLE
Can´t set meta field for product variant

### ISSUE THREAD

**Issue by rokka** [nozzlegear/ShopifySharp#334]
Hi,

when I am trying to set a metafield for a product I get the following exceptiom message:

"value: can't be blank"

This is how i have filled the object:

![2019-02-15 12_06_11-system3 debugging - microsoft visual studio preview](https://user-images.githubusercontent.com/533290/52854166-f3773800-311d-11e9-9f87-a78c8e4c6e1b.png)

Can you give me a hint what I am doing wrong?

**Comment by foxandrewj** [comment]
The only valid values for ValueType are "string", "integer", "json_string".
It's probably throwing the error about the Value because it doesn't know what to do with it based on the ValueType you specified.

**Comment by rokka** [comment]
Thanks. That works
