### ISSUE TITLE
The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by zhaozhao2018** [nozzlegear/ShopifySharp#337]
Hi, 
I had a question when I development the shopify get orders. When I use below:
 ```
       [Authorize]
        public async Task<ActionResult> Index()
        {
           var service = new OrderService("https://shopname.shopify.com", accessToken);
           IEnumerable<Order> orders = await service.ListAsync();
           .......
            return View();
        }
```
The web page show: The remote certificate is invalid according to the validation procedure. I don't know why. The shopifysharp sdk is the newest(4.18.1.0).  Thanks.

**Comment by nozzlegear** [comment]
I'm not sure what the issue might be here, as I'm not seeing anything like this when I test it myself. My first guess would be something to do with the TLS changes made in 2018. Does the solution in #267 do anything to resolve this?

**Comment by zhaozhao2018** [comment]
> I'm not sure what the issue might be here, as I'm not seeing anything like this when I test it myself. My first guess would be something to do with the TLS changes made in 2018. Does the solution in #267 do anything to resolve this?

Thanks. I fixed it just now. The mistake was: shopname.shopify.com, the right one is: shopname.myshopify.com, I missed the "my" , Thanks again.

**Comment by nozzlegear** [comment]
Glad you got it fixed!
