### ISSUE TITLE
Create Product not working

### ISSUE THREAD

**Issue by ciberloja** [nozzlegear/ShopifySharp#339]
Hello, I'm not able to implement the product creation method. Can you help me?

`Dim service = New ProductService(shopifyUrl, apiPassword)
        Dim product = New Product() With
        {
            .Title = "Burton Custom Freestlye 159",
            .Vendor = "Ciberloja",
            .BodyHtml = "<strong>Good snowboard!</strong>",
            .ProductType = "Snowboard",
            .Images = New List(Of ProductImage) From
            {
                New ProductImage With
                {
                .Attachment = "R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
                }
            }
        }
        service.CreateAsync(product)`

**Comment by nozzlegear** [comment]
Hey @ciberloja, I'll need more information before I'm able to help here. What's happening when you try to do this? Is an error being thrown?

**Comment by ciberloja** [comment]
It does not make any error, it simply does nothing.

**Comment by nozzlegear** [comment]
Oh I see, I'm thinking you probably need to await it. All of the service methods are async, so they need to be awaited or your program will continue on before they're done. In C# that looks like `var product = await service.CreateAsync(product)`. It might be the same in VB, I'm not sure.

**Comment by ciberloja** [comment]
But I'm creating customers in the same way, is there a difference? Do you know how I use await in VB?

**Comment by nozzlegear** [comment]
I think the fact that creating customers is working is probably just a fluke, it's probably just happening to finish in time before it gets cancelled. I'm not super familiar with VB, but it looks like you need to first make whatever function you're _using_ the service in async by marking it with `Async`, and then you need to use `Await` on the service call:

```vb
Async Function MyFunction() As Task(Of Product)
   Dim service = New ProductService(shopifyUrl, apiPassword) 
   Dim newProduct = New Product() With { .Title = "Burton Custom Freestlye 159", .Vendor = "Ciberloja", .BodyHtml = "<strong>Good snowboard!</strong>", .ProductType = "Snowboard", .Images = New List(Of ProductImage) From { New ProductImage With { .Attachment = "R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" } } } 
  Dim product = Await service.CreateAsync(product)

  Return product
End Function
```

I think that's at least close to what you want to do but I'm not super familiar with VB so there might be a syntax error or two. You can read more about async functions in VB right here: [https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)

**Comment by ciberloja** [comment]
I tested it this way and it still does not work ... Can you test it and tell if it worked, please?

**Comment by clement911** [comment]
are you definitely awaiting the result? If you do you should get an exception or it should succeed.

**Comment by ciberloja** [comment]
How do I know if I'm expecting the result? How am I supposed to call the function? Sorry but this is the first time I work with asynchronous functions ...

**Comment by nozzlegear** [comment]
Could you give us a little more code to look at @ciberloja? Specifically it would help if you show us the entire function that contains the call that's not working. Is this an ASP.NET program, or a desktop program, or something else?

**Comment by ciberloja** [comment]
Currently the function is exactly as you showed in the previous comment and is called in load. It is a desktop program.

**Comment by clement911** [comment]
I'd suggest you do some research into await/async...

**Comment by clement911** [comment]
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/await-operator

**Comment by nozzlegear** [comment]
@ciberloja I'm thinking it's because you're not awaiting `MyFunction ()` when you call it. Any async function must be awaited except in very specific circumstances. So if you mark a function as `Async`, you can await inside it but any _other_ function calling your function must also await. It becomes a chain of awaits:

```vb
Async Function StepTwo() As Task(Of Int)
    // Do something here like call the Shopify API and get a count of orders
    Return 5
End Function

Async Function StepOne() As Task(Of Int)
    // Since this function is async, it can await the StepTwo() function
    Dim result As Int = Await StepTwo()
    Return result
End Function

Async Function StepZero() As Task
   // Again, because this function is async, it can await StepOne() function
   Dim result As Int = Await StepOne()

   // Do something with result
End Function
```

I would agree with @clement911 though, you should definitely look into working with async functions in VB with the link he posted. Unfortunately there's no way around it at least with ShopifySharp, the service methods are async and they _must_ be awaited or they may not complete.
