### ISSUE TITLE
ChargeResult from Shopify does not contain shop url?

### ISSUE THREAD

**Issue by chadwixk** [nozzlegear/ShopifySharp#340]
In the example code, you have this action for shopify to call. In my testing the shop url is always null. The charge_Id is populated. 

`public async Task<ActionResult> ChargeResult(string shop, long charge_id)`

In viewing their [documentation] (and [here](https://help.shopify.com/en/api/app-store/charging-for-your-app/guides/implement-billing-model#implement-the-recurringapplicationcharge-resource))(https://help.shopify.com/en/api/reference/billing/recurringapplicationcharge#create), it seems the return url only contains the `charge_id`, at least that is if I am understanding that they are posting back using the decorated_url in the below, which is `http://super-duper.shopifyapps.com/?charge_id=1029266952`....note id just has `charge_id` and not `shop`.

```
HTTP/1.1 201 Created
{
  "recurring_application_charge": {
    "id": 1029266952,
    "name": "Super Duper Plan",
    "api_client_id": 755357713,
    "price": "10.00",
    "status": "pending",
    "return_url": "http://super-duper.shopifyapps.com/",
    "billing_on": null,
    "created_at": "2018-11-15T16:23:38-05:00",
    "updated_at": "2018-11-15T16:23:38-05:00",
    "test": true,
    "activated_on": null,
    "trial_ends_on": null,
    "cancelled_on": null,
    "trial_days": 0,
    "decorated_return_url": "http://super-duper.shopifyapps.com/?charge_id=1029266952",
    "confirmation_url": "https://apple.myshopify.com/admin/charges/1029266952/confirm_recurring_application_charge?signature=BAhpBAheWT0%3D--26689f6850f3c4e70a83e5dfa0634e65fd164d5e"
  }
}
```

 Are we to populate the shop query string in the `ReturnUrl` when we post the recurring charge to shopify?
```
var charge = new ShopifyRecurringCharge()
            {
                Name = "Pro Plan",
                Price = 29.95,
                TrialDays = 14,
                Test = true,
                ReturnUrl = "http://localhost:62211/shopify/chargeresult?shop=test.myshopify.com"
            };
```

**Comment by nozzlegear** [comment]
Hey @chadwixk, you should indeed populate the querystring with the shop, this is what I do in my own Shopify apps. You could also alternatively store a record of each charge you create in a database along with some data about which user it's tied to, then you'd look up the charge using `charge_id`.
