### ISSUE TITLE
"Userless" Shopify App

### ISSUE THREAD

**Issue by dementic** [nozzlegear/ShopifySharp#348]
Most of Shopify apps do not require you to create account/login if its running within the Shopify admin.
How can one achieve that?

**Comment by dkershner6** [comment]
You are likely referring to "public" apps versus "private" apps.

Private apps credentials are manually created in the admin, as you suggest.  Public apps generate their own credentials through an OAuth handshake, and have things like a Settings UI inside Shopify Admin.

If this sounds like it correctly identifies the question you are asking, let us know, and we can point you to the OAuth docs.

**Comment by dementic** [comment]
Yes, i do refer to a "public" app.
The demo project supplied with the first chapter of the handbook includes a public app (ShopifyBilling).
Deploying the ShoppifyBilling project as a public app, requires the user to login to the ShoppifyBilling app within the admin app running.
It would be nice if the user can be automaticly logged in since it is running from within Shopify admin and the user is already logged in (to shopify, therefore, to our app).
A reference to code/documentation on how this could be achieved would be much appreciated.

**Comment by dkershner6** [comment]
You can achieve this by using the URL of your settings app as the Redirect URI of the OAuth token handoff.

If you are using the React Shopify Polaris library or any other Embedded App SDK, the app can automatically redirect the user to the shopify admin app page.

In React, this looks like this:
`<AppProvider apiKey={apiKey} shopOrigin={shopOrigin} forceRedirect={true}>`
with the important bit being that last one.

So, if you are hosting your single page settings app at https://portal.dementic.com/index.html, you can redirect the user there, and there will be a shop query parameter when they arrive that you can use to identify which shop it is (shopOrigin above), your apiKey is the app clientId, and with forceRedirect=true, your user will be automatically logged in (or be prompted to login) to Shopify admin and land on your app page.
