### ISSUE TITLE
ArticleListFilter and PageFilter can't actually use "Ids"

### ISSUE THREAD

**Issue by dkershner6** [nozzlegear/ShopifySharp#349]
https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Filters/ArticleFilter.cs
Inherits from PublishableListFilter and ListFilter, which contains the Ids filter.

https://help.shopify.com/en/api/reference/online-store/article#index

Not actually supported.

I'll let you decide the best approach to remove it while I fix my app!

**Comment by nozzlegear** [comment]
Thanks for the report! So does this throw an error if you try to use it, or just silently "fails" and returns a list?

**Comment by dkershner6** [comment]
The latter.  From what I can tell, the list is unaffected from if the parameter were not present.

To be honest, I just assumed Shopify had that parameter, and when ShopifySharp had it, I just assumed it would work.  It took a weird bug where things weren't getting updated, besides the first 250, to surface it.

**Comment by nozzlegear** [comment]
I decided to mark this property as obsolete, and will remove it in 5.0

**Comment by nozzlegear** [comment]
Marked obsolete in 4.20.0
