### ISSUE TITLE
A new 429 type - breaks smartexecutionpolicy into endless loop

### ISSUE THREAD

**Issue by dkershner6** [nozzlegear/ShopifySharp#350]
This took me hours to track down.  When this error occurs, it looks exactly like any other 429 error in ShopifySharp (ShopifyException, Too many calls).

When I manually re-created the call in Postman, I received:

"Daily variant creation limit reached. Please try again later. See https://help.shopify.com/en/api/getting-started/api-call-limit for more information about rate limits and how to avoid them."

The SmartExecutionPolicy model loops for a day until the limit is lifted.  This is definitely new, no idea when it was created, but I havent experienced it previously.

**Comment by clement911** [comment]
Hi Derek,
I rely on the policy (I wrote it) so I'm keen to make this work.

Looking at the Shopify API changelog, these limits are definitely new: https://developers.shopify.com/changelog
https://developers.shopify.com/changelog/api-call-limits-will-be-applied-to-variant-creation
https://developers.shopify.com/changelog/paginated-requests-may-now-be-subject-to-additional-api-throttling

I noticed in the docs at https://help.shopify.com/en/api/getting-started/api-call-limit that there is a new header Retry-After:
> a Retry-After header is also included with the response. It contains the number of seconds to wait until you can make a call again. Any API call made before the wait time has elapsed is throttled.

That header didn't exist at the time I wrote the policy. Back then it was simpler, as the rate was the same for all API endpoints.

Now, it may be a better idea to read this header and wait for the appropriate amount of time instead.
See:

https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Infrastructure/Policies/SmartRetryExecutionPolicy.cs#L66-L75

**Comment by dkershner6** [comment]
Since the time could also be up to 24 hours, I would recommend setting a cap and failing if above as well.

I was very disappointed to find this out, and found it out the very hard way.  I think its a way to push borderline stores into plus, which is unfortunate, since its 7x the cost.

**Comment by clement911** [comment]
As far as I can see at https://help.shopify.com/en/api/getting-started/api-call-limit#resource-based-api-call-limits they haven't documented when the limit kicks in and for how long.
Have you seen the 24 hours documented anywhere? When does it kick in? After a certain number of creation I assume...

**Comment by dkershner6** [comment]
I guess I am interpreting from the actual error message suggesting "Daily variant creation limit reached.", but this may be inaccurate I suppose.

Because the error looks identical to other 429's, it is really hard for me to nail this down.  My apps do 429 on occasion, and they just hold off for a minute, then go back to work.  In this case, I hit it every minute, for several hours, on a shop with 200K+ products with lots of changes.

So, might not be 24 hours, but it seems longer than "minutes".

**Comment by nozzlegear** [comment]
Interesting, they also introduced limits on fulfillments last year that broke a bunch of tests for this package and my other TS package. I wonder if this change has broken tests again.

**Comment by dkershner6** [comment]
I ran a "test" (not unit) using a console app and a SmartExecutionPolicy.  I stopped waiting for it after about 20 minutes.

**Comment by clement911** [comment]
In your test, can you check the value of the Retry-After header?
If I understand this new header correctly, this will tell you how long you should wait for (in seconds).

**Comment by dkershner6** [comment]
Oh...that would have been a good idea indeed...

Let me see if I still have one open from the other day.

**Comment by dkershner6** [comment]
Here is a dump of all of the headers it returned to me on that call, with some xxxxx out for privacy.

`
Server →nginx
Date →Mon, 01 Apr 2019 23:09:31 GMT
Content-Type →application/json; charset=utf-8
Transfer-Encoding →chunked
Connection →keep-alive
X-Sorting-Hat-PodId →72
X-Sorting-Hat-ShopId →xxxxxx
Referrer-Policy →origin-when-cross-origin
X-Frame-Options →DENY
X-ShopId →xxxxxx
X-ShardId →72
X-Stats-UserId →
X-Stats-ApiClientId →xxxxxx
X-Stats-ApiPermissionId →64368455
X-Shopify-API-Terms →By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms
HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT →1/40
X-Shopify-Shop-Api-Call-Limit →1/40
Strict-Transport-Security →max-age=7889238
X-Request-Id →8f69fa69-3744-4cbf-a547-7ae02eb63582
X-Shopify-Stage →production
Content-Security-Policy →default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://dme0ih8comzn4.cloudfront.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=update&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=8f69fa69-3744-4cbf-a547-7ae02eb63582
X-Content-Type-Options →nosniff
X-Download-Options →noopen
X-Permitted-Cross-Domain-Policies →none
X-XSS-Protection →1; mode=block; report=/xss-report?source%5Baction%5D=update&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=8f69fa69-3744-4cbf-a547-7ae02eb63582
X-Dc →chi2,gcp-us-east1
`

No Retry-After.  That might be limited to the normal 429.

Note that I normally call using public keys (OAuth), but this particular call is made using a completely unused private key (hence the 1/40), just to make things as simple as possible.  Not sure any of that makes a difference.

**Comment by clement911** [comment]
But I don't think this request was throttled since it says 1/40. Right?
I'm guessing the Retry-After header is only present if you are throttled.

**Comment by dkershner6** [comment]
Same request:

![image](https://user-images.githubusercontent.com/25798427/55593972-b5949a00-56f2-11e9-8dad-283e17190c10.png)

**Comment by clement911** [comment]
That one was throttled, no Retry-After header?

**Comment by dkershner6** [comment]
All of the information in my last 2 posts is the exact same request.  The headers are a full dump, with only some privacy values XXXXX-d out.

It is really hard to replicate the issue, as timing must be right, and I don't reliably receive it on all calls, but I have an example open and will leave it there.

**Comment by clement911** [comment]
So they return a 1/40 limit with a 429 status? Weird, they really need to update their docs...

**Comment by clement911** [comment]
Might be worth asking at https://github.com/Shopify/shopify_api

**Comment by dkershner6** [comment]
Yes, I don't really think they thought this one through.

**Comment by nozzlegear** [comment]
Any update on this, or suggestions for how best to handle this within the execution policy? Should we be looking for the header and trying to figure out when to retry?

**Comment by dkershner6** [comment]
The error is so hard to re-create, its very tough to find a solution, as the solution cant really be tested.

I did, however, find what the limit was: 1000 variant creates/day.

**Comment by clement911** [comment]
Related to https://github.com/nozzlegear/ShopifySharp/issues/455

**Comment by clement911** [comment]
PR ready: https://github.com/nozzlegear/ShopifySharp/pull/466

**Comment by nozzlegear** [comment]
PR merged, should be fixed in 5.0.1 on nuget!
