### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by Fashionepaul** [nozzlegear/ShopifySharp#354]
Shopify are going to be introducing API versioning.

Can you please add a way of specifying the Shopify API version?

**References**
https://developers.shopify.com/changelog/introducing-admin-api-versioning-and-developer-preview
https://www.shopify.com/partners/blog/api-versioning-at-shopify

**Comment by clement911** [comment]
See https://github.com/nozzlegear/ShopifySharp/pull/355

**Comment by nozzlegear** [comment]
Closed in #355 thanks to @clement911! ShopifySharp will support one specific version of the API, but if anybody _really_ wants to use a different version they can override one of the ShopifyService classes and manually set the API version.
