### ISSUE TITLE
Accounts and permissions

### ISSUE THREAD

**Issue by lantram** [nozzlegear/ShopifySharp#357]
Is it possible to get a list of shop staff accounts? (usernames  & email addresses)

**Comment by nozzlegear** [comment]
Hey Larry! I don't _think_ there's a way to get a list of staff accounts. I think the closest thing you can do is use the per-user access token which gives you additional information about the user and session, but that's only for users actively using your app. I might be wrong, they may have introduced a way to do this, but to the best of my knowledge it isn't currently possible.

(By the way, I got your emails! I'll respond soon, just been super busy.)

**Comment by clement911** [comment]
Actually, you can use the User Service: https://github.com/nozzlegear/ShopifySharp/blob/9057c20da6c7a841c69c30d38ebd3f9456073d6f/ShopifySharp/Services/User/UserService.cs#L27

However, this only works if the store is a Shopify Plus store AND the app is a private app.

**Comment by nozzlegear** [comment]
Ah the user API crossed my mind but I had it confused with something else and thought it wasn't for staff accounts. Good catch!

**Comment by lantram** [comment]
Thanks for the info. I was hoping to access the list of Staff accounts as part of enhanced security, but if the information can only be obtained via a private app in conjunction with a Shopify Plus or greater plan - well, then that's a non-starter. Thanks Shopify! /s ; )

**Comment by lantram** [comment]
Hey @clement911 - How did you post that code example above with the pretty syntax highlighting?

**Comment by clement911** [comment]
@lantram  I just opened the file and then used the 'Copy lines', which generates a link like this:

`https://github.com/nozzlegear/ShopifySharp/blob/9057c20da6c7a841c69c30d38ebd3f9456073d6f/ShopifySharp/Services/User/UserService.cs#L27`

Then just copy this line and Github prettifies it.

![image](https://user-images.githubusercontent.com/3426504/56773786-13546780-6803-11e9-9913-1cc91f38e8b2.png)
