### ISSUE TITLE
Online ShopifySharp Community?

### ISSUE THREAD

**Issue by lantram** [nozzlegear/ShopifySharp#359]
I don't know where else, so I'm posting this question here.

I was wondering if there is a recommended public community or forum to discuss some of the larger issues that developers may encounter while specifically using ShopifySharp? Ones that are outside the scope of the library itself.

I know there are places for discussing Shopify App Development in general, but I'm a C# developer, using ShopifySharp, and don't do Ruby - so I don't want to deal with the non-relevant issues and extra noise other platforms bring with them.

Perhaps Reddit? I would create a ShopifySharp subreddit, however, I never really got into using the site until recently, and don't currently have enough "positive karma" to create a community there. Perhaps someone else could do so? Or point to or suggest an alternative location.

Any thoughts or ideas?

**Comment by nozzlegear** [comment]
Good question! I've been thinking about this myself recently and haven't come to a decision yet. My first thought would be an "official" Discord server for this package. I use Discord a ton and have found it to be really, really great for managing small communities. My guess is a subreddit for a single package like this would probably not take off, or at least would be very inactive.

**Comment by nozzlegear** [comment]
I'm going to close this for now, but I do plan to set up a community for this package soon! I'll update here when it's ready.
