### ISSUE TITLE
Disable HttpClient cookies to mitigate CSRF errors

### ISSUE THREAD

**Issue by Kirlac** [nozzlegear/ShopifySharp#360]
I have been working through an issue with Shopify support recently where our POST requests (eg. completing a fulfillment via ShopifySharp) are sometimes being rejected. It seems the cause of this is a Shopify policy to reject POST requests with cookies set, resulting in CSRF errors. Allowing customization of the HttpClient would mean we could set the client to disable cookies etc to help mitigate this (and allow for more flexibility), or this could even be disabled directly within ShopifySharp if you have reasons for not exposing this.

Shopify support have replied to my email with the following information regarding this:
> I've still been poking around here and there trying to find out where the cookies were coming from, no one on the teams that own the endpoints really knew why, but I think I finally found out what was causing it. We just recently migrated some of our edge to Cloudflare, and it looks like that's caused cookies to be included with responses. I don't know many of the details to be honest, but I don't think that was expected, and is probably just a configuration issue. We actually migrated back using Edgescale while we sort it out, but I do know the intention is use Cloudlfare going forward, and I think that the move back might happen later in the week.
> 
> I couldn't find any official announcements about it, but I did come across this forum post in my searches: https://community.shopify.com/c/Shopify-APIs-SDKs/Inventory-For-security-reasons-requests-using-HTTP-Basic/m-p/502888?advanced=false&collapse_discussion=true&filter=location&location=category:en&q=http%20client%20cookies&search_type=thread
> 
> That couldn't sum up our conversation any better. CSRF errors, inexplicable cookies, and even expiring your cookies on each request like you mentioned possibly doing. And right there in a persistent HTTP Client. It just all seems to cover everything here.

**Comment by clement911** [comment]
I think this is definitely a good idea for users to be able to customer HttpClient settings in some way.
I wonder if the [IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2) would be a good idea.
If we had a [named client](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#named-clients) 'Shopify' then any app could configure it as needed.
But I'm not sure if this only for asp.net core apps.

Regarding your specific issue, do you know why this is only affecting some apps and not all apps using ShopifySharp?

**Comment by Kirlac** [comment]
Sorry for the delay, my schedule's been all over the place with the holidays lately.

If I had to guess at a few potential reasons why it's not affecting everyone (it's only intermittently affecting us):

1. The cookies may be only getting set from specific calls which not everyone may be making
2. It may be dependent on the server - different locations/routing may not hit the affected server setting the cookies
3. It may be the result of some kind of transient error resulting in a cloudflare response (which could include the set-cookie header) instead of a shopify one (which wouldn't)

The core of this issue is still valid however - shopify's policy is to reject POST requests which have a cookie set. It would be best practice in this case to disable them, or at least provide a way for users to do so - currently the HttpClient appears to be abstracted away with no means of customization and last I checked was not disabling cookies.

I agree that using the IHttpClientFactory with a named shopify client may be a good solution, although the dependencies may cause issues for a lot of users - this appears to be for dotnet core 2.1 or newer which I could see being problematic for some people. That said, research suggests [this may be able to be added for any netstandard 2.0 compliant applications](https://stackoverflow.com/questions/51474776/how-do-i-implement-ihttpclientfactory-in-net-framework-apart-from-net-core)

**Comment by Kirlac** [comment]
Just had another update from Shopify support regarding this:

>  So, a bit of communications with our team overlooking the new Cloudflare edge, and that cookie was definitely part of the problem, but last week we actually deployed a fix for that, and basically whitelisted it on any API request. There really wasn't any other workaround going forward since we couldn't make use of the security features if we stripped it during any other step.
>
> So that's basically the 411 there. Looking at the timeline of it all, this probably was the source of the original issue too. If you did decide to expire all your cookies, you might want to leave an exception for `__cfduid` given this.

It seems the Cloudflare cookie is required for their security features so Shopify are now whitelisting this and contrary to their initial suggestion it should not be removed

**Comment by clement911** [comment]
Thanks for the update. The ability to customize the HttpClient might still be useful but I guess it should be another ticket.

**Comment by Kirlac** [comment]
No problem. This can probably be closed in that case - unless anyone wants to take action here. The cookies problem SHOULD be solved - Shopify shouldn't be adding any cookies themselves and have whitelisted the cloudflare one being added so we shouldn't need to do anything for this.

I agree a customizable client would be a "nice to have" and should Ideally still be on the roadmap - I think #310 probably already covers this in greater detail yeah?

**Comment by nozzlegear** [comment]
I also agree on customizing the client, even if this specific issue is fixed. Somebody had mentioned using "named" http clients, could anyone give me a quick rundown on what that is? I've been deep in the JavaScript world lately and haven't been able to read up on all the fancy new http client stuff yet.

--
Josh Harms

**Comment by clement911** [comment]
You might want to take a look here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#named-clients

**Comment by nozzlegear** [comment]
You can now set a custom `HttpClient` for each instance of a ShopifySharp service in version 5.14.0 on nuget. Thanks for the feedback!
