### ISSUE TITLE
VS 2019 and "Response did not indicate success. Status: 422 Unprocessable Entity."

### ISSUE THREAD

**Issue by mb-smartcookie** [nozzlegear/ShopifySharp#361]
Hi there, I'm getting a 422 Unprocessable Entity when trying to fullfill, on line:
fulfillment = await fulfillService.CreateAsync(shopifyId, fulfillment, notifyCustomer);
Shopify does not like what I am posting, any one else had this?

On a lighter note, how are people finding VS 2019 (16.0.2)?  Got this project to run on it by changing v15.0 to v16.0 in csproj:
Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets"

Thank you
Mark

**Comment by nozzlegear** [comment]
Hey! Fulfillments can be tricky to do, Shopify has made several changes to them over the life of this package and I've had to update the automated tests each time to fix it. You should have some additional information on the exception's `Errors` property, or you can also look at the `RawBody` property. Either of those will hopefully give you a hint about what's going on and should point you in the right direction. 

As far as VS2019, I actually haven't had a chance to use it yet! I do almost all of my dev work in VS Code these days and have enjoyed that a lot.

**Comment by mb-smartcookie** [comment]
Hello, many thanks, yes, it is the location_id that is needed to complete the fulfillment.  Was made compulsory last year by Shopify by the looks of it.  Any planned update to ShopifySharp for this?
Cheers

**Comment by dkershner6** [comment]
I used vs2019 for all.net Dev from the first day of general availability. I use .Net core and every app and package worked out of the box, exactly the same as 2017, with a few nice UI features, mainly the welcome menu. I haven't really noticed a difference besides that.

**Comment by dkershner6** [comment]
https://github.com/nozzlegear/ShopifySharp/blob/1f7239181a4cf9f467c9edf68b758739fc012723/ShopifySharp/Entities/Fulfillment.cs#L47

That's the location id ok a fulfillment.

**Comment by dkershner6** [comment]
One thing that is very nice about 2019 actually is the AI-assisted intellisense.  It really helps find the one you want faster.

**Comment by mb-smartcookie** [comment]
Don't get as much time on this project as I would like, just back to this now, and I found the below works well for me for the LocationId:
```C#
 var ShopifyLocationId = new LocationService(shop.MyShopifyDomain, shop.ShopifyAccessToken);
            var ShopifyLocations = System.Threading.Tasks.Task.Run(() => ShopifyLocationId.ListAsync());
            ShopifyLocations.Wait();
            var getShopifyLocations = ShopifyLocations.Result;
            long? locationId = 0;
            foreach (var location in getShopifyLocations)
            {
                locationId = location.Id;
                break;
            }
```
