### ISSUE TITLE
Why is product PublishedAt NullValueHandling as Include?

### ISSUE THREAD

**Issue by moxplod** [nozzlegear/ShopifySharp#367]
https://github.com/nozzlegear/ShopifySharp/blob/dd7fb28c579aa29b225cbcd5c7bd2a9ea8209c63/ShopifySharp/Entities/Product.cs#L44

NullValueHandling = NullValueHandling.Include

Means it's being included in JSON blob as null even when all I am trying to do is update the product title or any other field. 

**Which unintentionally unpublishes the product on any product update.** 

Is there a reason for this as this is the only property in the entire library that has that attribute?

**Comment by nozzlegear** [comment]
Unfortunately this is one of those damned if you do, damned if you don't kind of things. The NullValueHandling is set to include because it would be impossible to unpublish a product at all without it. If we were to set the NullValueHandling to ignore, the package wouldn't serialize or send the null value and then you can't unpublish the product. I'm open to any suggestions on how to better handle this, but for the time being, being able to send null values for `PublishedAt` is intentional.

**Comment by dkershner6** [comment]
I am wondering if we should also enforce returning that field on ProductService.Get/List, so that no one could pull a product, change some stuff, then send back the product and have it pause.

**Comment by dkershner6** [comment]
I guess that wouldn't have helped this particular scenario though...no ideal solution unfortunately.

**Comment by clement911** [comment]
It is a tricky one.
The `ListFilter` has a `fields` property to include fields that should be included in the response. I wonder if we could use a similar mechanism on request.

**Comment by moxplod** [comment]
My recommendation would be to use the separate publish and unpublish product methods that you already have written in the product service if you need to unpublish a product. So the developer knows they need to be explicit when doing that. 

With the way, it is in the SDK right now with any updates I need to make to the product it *unintentionally* unpublishes the product. Which ended up causing a significant bug for me and had a lot of my users complaint.

**Comment by clement911** [comment]
Not a bad idea but ShopifySharp is a lightweight library and is intentionally designed to be a very thin layer over Shopify's REST api.
Adding additional logic like a publish/unpublish would be a departure from this goal.

**Comment by moxplod** [comment]
Those methods already exist in this SDK library

**Comment by clement911** [comment]
Oh I had totally missed that!

**Comment by dkershner6** [comment]
I believe those used to be the only way, and we switched to also using nulls due to a request.

This is just one of those things that is 6 of one, half dozen of another.

**Comment by clement911** [comment]
Related issue: https://github.com/nozzlegear/ShopifySharp/issues/284

**Comment by SeanoNET** [comment]
I encountered this today, i resolved it by checking the `PublishedAt` in Shopify before updating the given product. This is not ideal as it requires an extra API call before updating the product.

I do like @moxplod idea of removing the ability to set `PublishedAt` in `ProductService.UpdateAsync()` and instead call `ProductService.UnpublishAsync()` to unpublish a product.

> My recommendation would be to use the separate publish and unpublish product methods that you already have written in the product service if you need to unpublish a product. So the developer knows they need to be explicit when doing that.

If i am not missing anything, a possible solution could be to add a `[JsonIgnore]` to `published_at` when serializing the product update request and use `published = true` instead in `ProductService.UnpublishAsync()`?
