### ISSUE TITLE
Missing ProductVariant Cost

### ISSUE THREAD

**Issue by lantram** [nozzlegear/ShopifySharp#370]
How do we get cost ("cost per item") out of a ProductVariant? I don't see it in there. :?

**Comment by dkershner6** [comment]
Here's a good article from Shopify on Cost:
https://help.shopify.com/en/api/guides/supporting-product-cost#retrieve-an-inventory-items-cost

Inventory Item API:
https://help.shopify.com/en/api/reference/inventory/inventoryitem

You can find InventoryItemId in the product variant object.

**Comment by lantram** [comment]
Thanks. I didn't realize we needed to use InventoryItemService to find that info.
