### ISSUE TITLE
ShopifyPaymentsDispute NetworkReasonCode Typo

### ISSUE THREAD

**Issue by PaulThomasRowe** [nozzlegear/ShopifySharp#377]
In ShopifySharp, under public class ShopifyPaymentsDispute, the property 'NetworkReasonCcode' appears to have a typo 'Ccode' instead of 'Code'. Suggest changing this to 'NetworkReasonCode'

**Comment by clement911** [comment]
Thank you for reporting that. PR welcome :)

**Comment by nozzlegear** [comment]
I had some spare time and took care of this. Should be fixed in 4.21.0 on nuget.
