### ISSUE TITLE
2019-07 breaking change for pagination

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#380]
It looks like the `page` parameter is not supported on some endpoints in version 2019-07.

See https://help.shopify.com/en/api/guides/paginated-rest-results

Might need to extract the new `Link` header and deprecate the `page` param for the affected endpoints.

**Comment by nozzlegear** [comment]
Hmm that's an interesting change. So instead of returning the list of items, we'd have to return a new object with both the list and a property pointing to the next "link". 

```cs
class ListResult<T>
{
    public IEnumerable<T> Items { get; set; }
    public string NextPageLink { get; set; }
}
```

**Comment by clement911** [comment]
Yes, it's similar to cursor-based paging with GraphQL.
This change will be touching quite a few files in ShopifySharp I'm afraid...

**Comment by mattxo** [comment]
Hi @clement911 

Thanks for those references on #382. That certainly complicates things!

I can only speak for myself but it would be a triviality for me to implement IListAsync across all services. I could do a PR for that today no problem. 

As a balance of effort vs reward, for me personally it's absolutely worth it, but how it would affect the project more broadly? I'm not sure... 

That said, 2019-04 is supported until 2020-04 and only 7 services will be modified to use cursor-based pagination in 2019-07. 

Orders, most notably, is absent from the list of services that will get cursor-based pagination in 2019-07 which inclines me towards thinking an implementation of IListAsync which covers the rest of the services may quite useful for quite some time.

Specifically in regards to implementing cursor based pagination, my initial thoughts are that one would remove ListAsync() from the relevant services and add PageAsync() (or perhaps more specifically PageAsync.

Something like this perhaps?

```
public class PaginatedRequest 
{
    public string PageInfo { get; set; }
    public int? Limit { get; set; }        
}

public class PaginatedResponse<T>
{
    public IEnumerable<T> Items { get; }        
    public string Link { get; }
    public PaginatedRequest NextPage { get; }
    public PaginatedRequest PreviousPage { get; }
}

public class ProductService : ShopifyService
{
    public ProductService(string myShopifyUrl, string shopAccessToken) : base(myShopifyUrl, shopAccessToken) { }

    public async Task<PaginatedResponse<Product>> PageAsync(PaginatedRequest request)
    {
        var result = new PaginatedResponse<Product>(); // Do magic

        return await Task.FromResult(result);
    }
}
```

**Comment by clement911** [comment]
I think you make some good points, I hadn't realized that the orders endpoint was absent from the list. Are there many others?

There are more than 7 services using cursor pagination,  see [here](https://help.shopify.com/en/api/versioning/release-notes/2019-07).

Based on this, I think it would indeed make sense to have two interfaces, maybe `IList<>` and `IPage<>`, depending on whether the endpoint uses cursor based pagination or the old pagination mechanism.

I think your `PaginatedResponse<T>` is also good (I had not realized there were both a Next AND Previous  link in the response). 
The only thing is I'm not sure is whether we really need the raw `Link` property but this is a minor details...

Are you suggesting to do a first pass to implement `IList<>` immediately (and keep 2019-04), and then another pass will need to be done to implement `IPage<>` and increment the pinned version to 2019-07?

**Comment by mattxo** [comment]
Ooo! Yeah you're right! https://help.shopify.com/en/api/guides/paginated-rest-results states 7 services under **Supported Endpoints**, but the changelog https://help.shopify.com/en/api/versioning/release-notes/2019-07 has rather more than that. 

That said, the majority of them are for XXXSavedSearch. 

I went through and correlated the 2019-07 changelog vs the services that are implemented in ShopifySharp and found this

  | 2019-07 (Cusor-based pagination)
-- | --
AccessScope |  
ApplicationCredit |  
Article |  
Asset |  
Authorization |  
Blog |  
Carrier |  
Charge |  
Checkout |  
Collect | YES
CustomCollection |  
Customer |  
CustomerAddress |  
CustomerSavedSearch | YES
Discount |  
DiscountCode |  
DraftOrder |  
Event | YES
Fulfillment |  
FulfillmentEvent |  
FulfillmentService |  
GiftCard |  
Graph |  
InventoryItem |  
InventoryLevel |  
Location |  
MetaField | YES
Order |  
OrderRisk |  
Page |  
Policy |  
PriceRule |  
Product | YES
ProductImage |  
ProductVariant | YES
RecurringCharge |  
Redirect |  
ScriptTag |  
ShippingZone |  
Shop |  
ShopifyPayments |  
SmartCollection |  
Theme |  
Transaction |  
UsageCharge |  
User |  
Webhook |  

Ie, 6 of the current services need cursor-based pagination implemented for 2019-07. Guess a broken clock is right twice a day after all.

Many of the rest of the existing services do have a ListAsync method though I haven't counted them. A quick scan shows the first half dozen *do* have an implementation but will not get cursor-based pagination in 2019-07. 

CustomCollection, Customer, Discounts, Order and SmartCollection at least would benefit from the IListAsync interface imo. It would certainly benefit me at least ;)

And yes, I should imagine IListAsync and IPageAsync would both be implemented on the applicable services.

**Comment by mattxo** [comment]
And yep, in the implementation I suggested above, you could do 

```
var response = await products.PageAsync(request);
var nextPage = await products.PageAsync(response.NextPage);
var previousPage = await products.PageAsync(response.PreviousPage);
```

Which is kinda neat I suppose. 

And yeah, I was on the fence about Link. On the one hand, all of the data is transmuted into NextPage and PreviousPage, and, it's part of the response header not the response body. On the other, it doesn't really get in the way of anything and I suppose there's some edge case where someone, somewhere might want to get at it. Dunno.

**Comment by clement911** [comment]
Thank you for your analysis.
I think I'm sold that these two interfaces would both be useful.

**Comment by nozzlegear** [comment]
I agree, I think the interfaces would be useful. Would we be able to make this work with the class interfaces for all services that I'm planning?

```cs
interface IListAsync<T> { ... }
interface IProductService : IListAsync<Product> { ... }
```

I can't remember off the top of my head if one interface can extend another.

**Comment by clement911** [comment]
Hi @nozzlegear , are you working on this issue by any chance?

The deprecation of 2019-04 is coming pretty quickly so it would be fantastic to move ShopifySharp to a new version. As far as I know, this is the biggest change that needs to be implemented.

https://help.shopify.com/en/api/versioning/release-notes

**Comment by nozzlegear** [comment]
Ah, right! Thanks for the reminder. I have some changes I haven't committed yet, but I want to get this published as quickly as possible so everyone can start updating and switching over before the deprecation.

**Comment by nozzlegear** [comment]
I'm going to bump the major version to 5.0 once published. Any thoughts on adding an `[Obsolete]` to the current list implementations in the 4.X branch before I do so? I don't want to annoy everyone with compiler warnings four months before the method actually becomes obsolete, but I also want to make sure everyone using 4.X is aware of the deprecation coming in April.

**Comment by clement911** [comment]
Personally I would definitely recommend applying the `[Obsolete]` attribute very soon.

Some folks may not be aware that the deadline is coming quickly and a warning is not that annoying.
I think it's best to be safe otherwise apps will definitely break.

**Comment by 1jmj** [comment]
+1 for [Obsolete]

**Comment by gambit823** [comment]
+1 for [Obsolete]

**Comment by ctrl-d** [comment]
isn't that what [Obsolete] is meant for? (but, we should have another version to offer very soon, otherwise we worn without offering solution)

**Comment by nozzlegear** [comment]
@ctrl-d In my opinion yes, but I've seen people get unreasonably salty about obsolete warnings for whatever reason. But I'm going to add them anyway and push a new 4.X version right before I publish 5.0 with the new pagination changes.

**Comment by SeanoNET** [comment]
@nozzlegear do you have an ETA on v5? April is approaching fast!

**Comment by clement911** [comment]
I'm already starting to get nervous about this.
@nozzlegear  are you close to merging this? Can we help?

**Comment by nozzlegear** [comment]
Sorry, my holiday season has been hectic but I'm coming out of the woods finally. I need to work through these issues and see which critical changes need to be included for v5, and then I'll have a release date for it. Aiming for end of January/beginning of February for v5!

(Side note, I might start streaming my open-source work on Twitch or Mixer every week. Just as a way to keep myself accountable and make sure progress is happening at a steady pace.)

**Comment by SeanoNET** [comment]
@nozzlegear no problem.

Re side note: Twitch needs more science/technology live-streamers (pretty much non-existent on Mixer at the moment), ill be sure to tune in!

**Comment by clement911** [comment]
@nozzlegear thank you for your massive contribution on this.
I'm really looking forward to v5!
Which version are you targeting next? 2019-07? or later?

**Comment by Powellze** [comment]
@nozzlegear 
Do you need some help with testing & any development support on this?
We're pretty familiar with the repo, feel free to reach out to me

**Comment by nozzlegear** [comment]
@clement911 Most likely the latest version, since that will give us the most time before the next need to release a major new release. 

@Powellze Sure! I could use a little bit of help going through the API changelogs to figure out which methods/objects have been removed. For example, my own Shopify application has warnings for `Order.PaymentDetails` being obsolete and removed in a future version.

**Comment by clement911** [comment]
I was hoping you'd say that :)

**Comment by clement911** [comment]
Note that if you pin to the latest version (2020-01), there is another breaking change related to Collects for smart collection. See https://help.shopify.com/en/api/versioning/release-notes/2020-01#rest-admin-api-changes.
If it's too tight to fix, an option would be to pin to 2019-10 first, just to handle the pagination breaking change, and then release again with a pinned version of 2020-01 at a later point.

I'm just trying to save a bit of time here because April 1st is coming really soon.

@nozzlegear  How far are you to releasing?
Sorry to be pushy on this but I'd really like to get started on the testing asap.
Happy to help if you have a dev branch or pre-release package.

**Comment by nozzlegear** [comment]
Thanks for the heads up on the smart collection! I'm going to be working on this tomorrow and will for sure push a pre-release package for 5.0.

**Comment by nozzlegear** [comment]
I'm going to be streaming my open source work -- mostly on ShopifySharp -- every Thursday at 2pm central US/3pm eastern US. I'll probably stream it on Twitch for now, where I've done a few programming streams in the past. https://twitch.tv/nozzlegear

Not trying to get internet famous or make that sweet streamer cash. I'm just going to use it as a way to ensure I'm making steady progress on this and my other projects each week, and maybe use it as a way to make the sometimes boring tedious work a tiny bit more interesting.

**Comment by Powellze** [comment]
@nozzlegear I've pinged you an email.

**Comment by nozzlegear** [comment]
Alright, I've pushed a branch to GitHub containing the first steps to releasing version 5.0! My goal for 5.0 is to update the API to target at least version `2020-01`, update all of the `ListAsync` methods to use the new paginated listing scheme, and add interfaces for all services. 

I've also published version 4.25.0 to nuget, which marks every existing `ListAsync` method as obsolete and warns developers using them that the method will cease to work after April 2020.

**Comment by clement911** [comment]
Thanks for the 4.25.0 release :)

Regarding 5.0, did you mean **at most** version 2020-01?
By the time 2020-04 is released, the current version used by ShopifySharp, 2019-04, will already be deprecated and will stop working. Unless I'm missing something?

**Comment by nozzlegear** [comment]
@clement911 Correct, what I wrote about the version was a little confusing! I'm planning to target version 2020-01, since 2020-04 will still be in the RC stage by the time I want to release v5 in the next couple of weeks.

**Comment by clement911** [comment]
Good to hear v5 is two weeks away.

I just received this 😱 

   ![image](https://user-images.githubusercontent.com/3426504/73912523-faf69a80-48b4-11ea-8bb3-41e7b4b298f7.png)

**Comment by nozzlegear** [comment]
I got the same thing! Publish is coming soon, I'm about halfway through rewriting all the list async methods. Then it's just a matter of refactoring the tests and we should be good for at the very least a prerelease publish.

**Comment by clement911** [comment]
That's good to hear. I'm happy do do some testing if you do a pre-release.

**Comment by ctrl-d** [comment]
Thanks for all the work, we are getting hammered by customer getting emails that we are making calls the a deprecated api, & we need to get resolved as soon as possible.
Shopify keeps sending email to notify the customers that there are depreciated calls & that there app will stop working soon. 
And we have to keep explaining them that we know about it & will have it updated soon.

Cant wait to get the final update!

**Comment by clement911** [comment]
That's a worry. Our customers haven't mentioned anything. My understanding was that Shopify wouldn't notify customers until April 1st.

**Comment by richbeales** [comment]
We've been getting the emails for a couple of months now. I think you only get notified if they have identified that you are using a deprecated api call - perhaps you aren't?

**Comment by clement911** [comment]
I did get a couple of emails from Shopify regarding our use of deprecated calls but I think what @ctrl-d is saying is that his customers are getting emails too. This probably doesn't inspire much confidence.

**Comment by nozzlegear** [comment]
I'm going to finish up the remaining work today on converting the services to use the new list API method. Fingers crossed, I'll have a prerelease published on nuget either this evening or tomorrow, but it's important to note that the tests are _not_ running yet. 

--
Josh Harms

**Comment by clement911** [comment]
Great!
@nozzlegear have you seen my [comment above](https://github.com/nozzlegear/ShopifySharp/issues/380#issuecomment-574648877) ?

Given the breaking change for the collection service, my suggestion is to pin v5.0 to 2019-10.
The paging change is fairly risky on its own. Implementing the collection service breaking change at the same time would increase risk even more.

We could release v6.0 shortly after, to implement the new collection API (and potentially the fulfillment orders API). What do you think?

**Comment by clement911** [comment]
Implementing the collection breaking change would also take additional time, which would delay the v5 release further...

**Comment by nozzlegear** [comment]
I'm not quite clear on what the breaking changes for the collection services are, can you explain what breaks in 2020-01? I'd prefer to just publish and support one major release per year, so targeting 2020-01 would be ideal. That said, I know everyone is getting anxious to get their apps updated, so I don't want to delay the v5 release any longer than strictly necessary.

**Comment by clement911** [comment]
See https://shopify.dev/concepts/about-apis/versioning/release-notes/2020-01 for the breaking  change.
Excuse the brevity, I'm on my phone..

**Comment by clement911** [comment]
So, the issue is that the Collect service used to work for smart collections before 2020-01 but doesn't anymore from 2020-01 onwards.
There is a new [CollectionService](https://shopify.dev/docs/admin-api/rest/reference/products/collection#products-2020-01) for it that could be implemented but I'm started to get really nervous about the time.

> I'd prefer to just publish and support one major release per year, so targeting 2020-01 would be ideal.

It's a shame IMO. v5 is big and painful because of the core change to pagination, but all other changes to 2019-07/2019-10/2020-01 are quite minor. If following versions are similarly minor, it would be quite easy to keep upgrading to the latest version to benefit from new features.

**Comment by nozzlegear** [comment]
> It's a shame IMO. v5 is big and painful because of the core change to pagination, but all other changes to 2019-07/2019-10/2020-01 are quite minor. If following versions are similarly minor, it would be quite easy to keep upgrading to the latest version to benefit from new features.

That's a good point, my desire to target one major release per year is under the assumption that every API version update is going to be as painful as the one we're doing now.

**Comment by clement911** [comment]
If you have a quick look at https://shopify.dev/concepts/about-apis/versioning/release-notes you can see that the pagination change is the big breaking change.
All other changes are either trivial/minor or non breaking (e.g new API or new fields).
(I'm looking mostly at the REST API and webhooks and not really considering GraphQL or Storefront APIs since they are not really used in ShopifySharp)

**Comment by nozzlegear** [comment]
A prerelease version of 5.0 is now available on Nuget. The full release will be published as soon as we get tests refactored and passing. The pagination change itself has been implemented in the prerelease, so I'm going to close this issue. 

There's a lot of discussion in here that is not strictly related to the pagination change, so feel free to open a new issue regarding each item specifically, or move general talk about v5.0 to #462. Thanks everyone!

**Comment by clement911** [comment]
@ctrl-d is you app a private app?

**Comment by ctrl-d** [comment]
> @ctrl-d is you app a private app?

We just use the api for multiple separate clients (all private)

@nozzlegear Thanks so much for all the work

**Comment by ctrl-d** [comment]
Is there any sample code on how to do the paging the new way?

**Comment by clement911** [comment]
See https://github.com/nozzlegear/ShopifySharp/issues/462#issuecomment-592939273

**Comment by ctrl-d** [comment]
> See [#462 (comment)](https://github.com/nozzlegear/ShopifySharp/issues/462#issuecomment-592939273)

Thanks i did
```

                ListResult<Order> result = null;
                do
                {
                    result = await service.ListAsync(result.GetNextPageFilter());
                    if (!result.HasNextPage)
                        break;
                    orders.AddRange((await service.ListAsync(filter)).Items);

                } while (result.HasNextPage);
```

**Comment by clement911** [comment]
`result.GetNextPageFilter()` would fail since it is null on the first iteration. Right?

**Comment by ctrl-d** [comment]
> `result.GetNextPageFilter()` would fail since it is null on the first iteration. Right?

yup i have added null handling for first time

**Comment by StriveDen** [comment]
> > `result.GetNextPageFilter()` would fail since it is null on the first iteration. Right?
> 
> yup i have added null handling for first time

Still, I don't think you will be getting results from the first page.

I would go with:

```
            var orders = new List<Order>();

            var list =  await service.ListAsync(new OrderListFilter {Limit = 250 });

            while (true)
            {
                orders.AddRange(list.Items);

                if (list.HasNextPage)
                    list = await service.ListAsync(list.GetNextPageFilter(250));
                else
                    break;
            }
```

**Comment by ctrl-d** [comment]
> > > `result.GetNextPageFilter()` would fail since it is null on the first iteration. Right?
> > 
> > 
> > yup i have added null handling for first time
> 
> Still, I don't think you will be getting results from the first page.
> 
> I would go with:
> 
> ```
>             var orders = new List<Order>();
> 
>             var list =  await service.ListAsync(new OrderListFilter {Limit = 250 });
> 
>             while (true)
>             {
>                 orders.AddRange(list.Items);
> 
>                 if (list.HasNextPage)
>                     list = await service.ListAsync(list.GetNextPageFilter(250));
>                 else
>                     break;
>             }
> ```

not sure why not, i have it running in production already with no issues.

**Comment by Powellze** [comment]
@nozzlegear I've spotted an issue on orders.
The returning filter is encoded and gets pushed through encoded to the 'new filter'
![image](https://user-images.githubusercontent.com/34938196/75828356-8de6ff80-5da3-11ea-9bb4-286dcc25eb71.png)

See code i've used which works in production right now:
`
            while (hasNextPageResults)
            {
                ListResult<Order> result = null;
                    result = await service.ListAsync(listFilter);
                if (result.LinkHeader?.NextLink != null)
                {
                    var newFilter = result.LinkHeader.NextLink.GetFollowingPageFilter();
                    // NOTE: For now, you must set the limit and fields property for further page filters manually.
                    newFilter.Limit = filter.Limit;
                    // Set the filter to the following page filter, which will grab the next page.
                    // Failure to do this will result in an infinite loop as the Shopify API returns the first page over and over

                    // bug with fields being encoded by shopify
                    **newFilter.Fields = newFilter.Fields.Replace("%2C", ",");**

                    listFilter = newFilter;
                }
                else
                {
                    hasNextPageResults = false;
                }

                items.AddRange(result.Items);
                page++;

            }
`
