### ISSUE TITLE
How to add product in Add to cart

### ISSUE THREAD

**Issue by vinayakelex** [nozzlegear/ShopifySharp#381]
I have add products and their variants and would like to add the items to add to cart for purchase but didn't see any method to add product in cart. Can you please provide some pointers related to manage cart.

**Comment by vinayakelex** [comment]
@nozzlegear Can you please provide some input on the same.

**Comment by dkershner6** [comment]
Cart is a frontend process, and must be managed on the site itself, using JavaScript: https://help.shopify.com/en/themes/development/getting-started/using-ajax-api#add-to-cart

If you just want to make a draft order, use the draft order functionality.

**Comment by vinayakelex** [comment]
@dkershner6 In this case, can we use checkout functionality ? When trying to create checkout then it return error code 406 (ShopifyException: Response did not indicate success. Status: 406 Not Acceptable.).

Does it mean that add cart functionality can only handled from frontend and not from backend ?

**Comment by dkershner6** [comment]
Checkout and cart are functionally the same. If you want to create an order, create an order. Otherwise handle inside the site itself, where the session is.

**Comment by vinayakelex** [comment]
@dkershner6 @nozzlegear Thanks for details. Do you have any idea why create checkout method throwing exception with Status code 406 (ShopifyException: Response did not indicate success. Status: 406 Not Acceptable.). Below is the code snippet :   var service = new CheckoutService(commerceStoreURL, accessToken);
            var checkout = await service.CreateAsync(new Checkout
            {
                Email = "vinayak@gmail.com"
            });

**Comment by vinayakelex** [comment]
@dkershner6 @nozzlegear I have checked the other services createAsync methods and found a difference in the way we are passing the body to request. Below is the modified code which might fix this issue because the error clearly says that the problem is with the header of request.


                var req = PrepareRequest("checkout.json");
                var body = checkout.ToDictionary();
                **var content = new JsonContent(new
                {
                    checkout = body
                });**
                return await ExecuteRequestAsync<Checkout>(req, HttpMethod.Post, new JsonContent(body), rootElement: "checkout");

**Comment by nozzlegear** [comment]
Hey @vinayakelex, I think there might be a little confusion here. The checkout API only works if you're creating a completely custom storefront that's not hosted by Shopify. If you're trying to modify a cart on somebody's Shopify store, it's sadly not possible via the API or via ShopifySharp. Even though the checkout API seems very similar, the only way you get or modify somebody's cart is by using JavaScript that runs on the storefront.
