### ISSUE TITLE
add custom filter

### ISSUE THREAD

**Issue by sharairi** [nozzlegear/ShopifySharp#385]
[JsonProperty("order_no")]
 public string OrderNumber { get; set; }

I tried to filter the orders by adding above filed even if I add currency the same thing it retrieve all orders.

the only name attribute working if we add using the same custom filter.

anyone can help, please !

**Comment by nozzlegear** [comment]
Hey @sharairi, we get this question a lot so I wrote an article about how you can do this. Keep in mind this isn't officially supported by Shopify and could break at any time. 

https://nozzlegear.com/shopify/looking-up-a-shopify-order-by-its-name

**Comment by sharairi** [comment]
Thanks for the prompt response.

So I cant add any filter attribute like this :

  public class MyCustomOrderFilter : OrderFilter
        {
            [JsonProperty("order_no")]
            public int? o_no { get; set; }

        }

Sincerely,


Mohammad T. Al Sharairi

M +962 (79) 6228979

________________________________

**Comment by sharairi** [comment]
sorry the property is order_number

Sincerely,


Mohammad T. Al Sharairi

M +962 (79) 6228979

________________________________
