### ISSUE TITLE
Cannot set meta fields of product variant at creation

### ISSUE THREAD

**Issue by mhamzarazzaq97** [nozzlegear/ShopifySharp#387]
Hi,
I am trying to create a product with multiple variants(with meta field information as shown in screenshot). But when the product is created the meta information of variant is not set and it return null. Can you help me in this issue where i am wrong ? 
![image](https://user-images.githubusercontent.com/52797825/62497560-c9adec80-b7f5-11e9-88c1-8edf981c53bd.png)
![image](https://user-images.githubusercontent.com/52797825/62497678-1265a580-b7f6-11e9-96c2-558caaa67352.png)

**Comment by nozzlegear** [comment]
Hey @mhamzarazzaq97, I think you've run into a confusing behavior with ShopifySharp. While the product and variant classes have a `Metafields` property on them, Shopify never actually returns those metafields. They solely exist just to use when creating and updating the product or variant so you can save yourself some time by skipping a second API call to the metafields API. 

So to put it more simply, my guess is that the metafields have indeed been created, but they will never be returned with the product. You need to use the MetafieldService to look them up. It's annoying and tedious, but that's the way Shopify does it so there's no way around that. 

In 5.0 I'm going to remove the metafields property from all objects and instead add a second parameter to create or update calls, which will accomplish the same thing.

**Comment by nozzlegear** [comment]
Please let me know if they still don't exist after using the MetafieldService to look them up. If that's the case, this is indeed a bug and I'll re-open the issue!
