### ISSUE TITLE
NOT ACTUAL ISSUE: Just saying Goodbye

### ISSUE THREAD

**Issue by dkershner6** [nozzlegear/ShopifySharp#390]
Hey guys,

I am taking on a new job, and it won't involve C# or Shopify.  No real better place to do so, but wanted to say it's been a pleasure working with you all, especially @nozzlegear and @clement911 .

Thanks! ...and apologies if I missed anyone in my shout-out.

(Feel free to close this near immediately)

@dkershner6

**Comment by nozzlegear** [comment]
Awesome, congrats on the new job!! I can't express how helpful you've been on this project. If there's anything I can do to help you in the future, please let me know. I'm wishing you well!

**Comment by clement911** [comment]
All the best @dkershner6 and thank you for your contributions.
