### ISSUE TITLE
Returning all customers (more than 100,000 customers)

### ISSUE THREAD

**Issue by yellowz06** [nozzlegear/ShopifySharp#391]
So we have over 100,000 customers in shopify, we found out the hard way that the Shopify API has a hard limit of 100,000.  What is a workaround for this go be able to get the full list of customers?  We are using Limit of 250 and as soon as we reach page 400 we stop getting data.

https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits

There is an additional rate limit for GET requests. When the value of the page parameter results in an offset of over 100,000 of the requested resource, a 429 Too Many Requests error is returned. For example, a request to GET /admin/collects.json?limit=250&page=401 would generate an offset of 100,250 (250 x 401 = 100,250) and return a 429 response.

**Comment by clement911** [comment]
Using SinceId is the right way to load all customers. This will load customers by ascending Id.

**Comment by clement911** [comment]
If you have a lot of pages to load, issuing queries in parallel will not be of much help since the leaky bucket is per app.

**Comment by clement911** [comment]
I see.
As you said I don't see how you can parallelize with SinceId though, since you need to know the value in the response before you can send the next request.
