### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by lantram** [nozzlegear/ShopifySharp#392]
I received this email from Shopify. Is the latest ShopifySharp calling version 2019-07 (or 2019-04)??

Do I need to set that somewhere? As far as I know, I don't use the page filter. I use cursor-based pagination. So I'm confused.

Thanks for any insight.

---

Hello there, 

Earlier this year we announced API versioning to ensure that future changes to our APIs are predictable, clearly communicated, and easy to adopt. For a quick refresher on API versioning at Shopify, visit our versioning guide.

We’re sending you this email to let you know that one or more of your apps are calling deprecated APIs on a version that is scheduled to be removed. If you’ve never specified an API version, your apps have been automatically calling version 2019-04. This means that your apps may stop functioning correctly if you don’t update to version 2019-07 and replace any deprecated API calls. 

Below you’ll find the deprecation timeline and apps using APIs that are subject to breaking changes. To learn more about deprecated APIs, see this guide.

Shopify API version 2019-04

Version 2019-04 will be removed on April 1, 2020. Update to version 2019-07 and replace the following deprecated API calls to avoid breaking changes. 

[APP_NAME] (#####################)

•	The page filter has been removed. Please use cursor-based pagination instead.

To learn how to migrate your app to a new API version, read our migration guide and explore the release notes from our latest API versions. 

If you have any questions, reach out to us in the API forums or from the Support section of the Partner Dashboard. 

Shopify Apps Team

**Comment by nozzlegear** [comment]
Hey! One of my clients got this same message. We're planning out the changes for this in #380. I'll take some time to get things squared away and then push an update to support the newest API version as soon as I can.

**Comment by clement911** [comment]
Got the same one too.
As @nozzlegear  mentioned, I think the main blocker is #380.
It's a fairly big breaking change...
