### ISSUE TITLE
Question:Exception Handling

### ISSUE THREAD

**Issue by mahrukhgull** [nozzlegear/ShopifySharp#398]
Hi,

How can I get that exact exception which was actually thrown by the Shopify? 
I want to store that exception for reporting purpose.

Thanks,

**Comment by nozzlegear** [comment]
Hey! Are you talking about catching the exceptions thrown by ShopifySharp, or reading the raw message returned by Shopify? In either case, you should be able to do it with a simple try/catch:

```cs
try 
{
    await DoSomethingWithShopifySharp();
}
catch (ShopifySharp.ShopifyRateLimitException ex)
{
    // Thrown when the app hits the rate limit
}
catch (ShopifySharp.ShopifyException ex)
{
    // Base exception thrown by ShopifySharp. This block will be active when the exception
    // was not a ShopifyRateLimitException
    // Use ex.RawBody to view the raw, unparsed message returned by Shopify
}
```
