### ISSUE TITLE
using ShopifySharp for Private Apps

### ISSUE THREAD

**Issue by felixtjung** [nozzlegear/ShopifySharp#40]
Hi,

I have been struggling with finding a way to use this great library for private apps.

I always get the message "Invalid API key or access token (unrecognized login or wrong password)"

I'm pretty new to this library, so I wouldn't know if i'm doing it right or not. I ended up adding following method to class "ShopifyService":

        public void SetPrivateAppsAuth(string apiKey, string password)
        {
            _RestClient.Authenticator = new HttpBasicAuthenticator(apiKey, password);
        }

So, I can use it like:

            string myShopifyUrl = "https://your-store.myshopify.com";
            ShopifyProductService service = new ShopifyProductService(myShopifyUrl, null);
            service.SetPrivateAppsAuth(api_key, password);
            Task<IEnumerable<ShopifyProduct>> task = service.ListAsync();
            task.Wait();
            var products = task.Result;

**Comment by nozzlegear** [comment]
Thanks for pointing this out! It should be possible to use the library with a private app by passing in the private app's password as the access token:

```cs
var service = new ShopifyProductService(myShopifyUrl, password);
```

[This blog post](https://nozzlegear.com/blog/generating-shopify-authorization-credentials) goes into that a bit more, but I'll make sure to update the docs with the same information.

**Comment by nozzlegear** [comment]
Docs were updated in 9fa8b7a with guidelines for using the library with a private app.
