### ISSUE TITLE
GraphQL Admin API rate limits

### ISSUE THREAD

**Issue by andre719mv** [nozzlegear/ShopifySharp#403]
Hi!
I am successfully use SmartExecutionPolicy to handle call limits in the REST admin API. But it seems that GraphQL return API limit usage in different format and their docs does not say anything about 429 response for GraphQL https://help.shopify.com/en/api/graphql-admin-api/graphql-admin-api-rate-limits. Is it possible to implement proper limit handling for GraphQL?

**Comment by clement911** [comment]
No unfortunately this has not been implemented yet in ShopifySharp.

**Comment by andre719mv** [comment]
It will be very useful. The reason I want to use GraphQL is to make less of API calls and to not reach limits. But without limit handling I can not use it. Thanks for response.

**Comment by clement911** [comment]
I agree totally.
I wanted to start on this but got side tracked.
ShopifySharp has very limited support for GraphQL.

**Comment by andre719mv** [comment]
I implemented leaky bucket for Graph API in my project. Will try to share some code later.

**Comment by andre719mv** [comment]
Hi!
I created some PR so you can see my idea https://github.com/nozzlegear/ShopifySharp/pull/486
I already use it well in my project.

**Comment by clement911** [comment]
I submitted a PR with a new policy to handle GraphQL rate limits.
https://github.com/nozzlegear/ShopifySharp/pull/667

**Comment by clement911** [comment]
This is now released
