### ISSUE TITLE
Create a products with variants and images

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#405]
How I create a product with multiple variants and images using for loop?

**Comment by nozzlegear** [comment]
You'll have to be more specific about the for loop, I'm not sure what you're looping through. Checkout out #406 for how to create a product with multiple variants. You can follow the same pattern to create images for the product by setting the product's Images property:

```cs
var product = new ShopifySharp.Product
{
   Title = "My product",
   Images = new List<ShopifySharp.ProductImage>
   {
     new ShopifySharp.ProductImage
     {
       Src = "https://example.com/my-image.png"
       Alt = "Describe the image"
     }
   }
};
```

That only works for general product images. If you want to assign a specific image to a specific variant, you need to first create a ProductImage using the ProductImageService, get the image's id, then assign that to a product variant's ImageId property and update the variant using the ShopifySharp.ProductVariantService.

**Comment by zafar1700017** [comment]
main reason for the loop is. I didn't know the exact number of variants
which I want to add in products. Can you tell me best solution how we add
variants
