### ISSUE TITLE
how we add a product variant in product 

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#406]
can you help to solve the problem 
scope:-read_products,write_products;

            var servce = new ProductService(shopify_url, access_token);

            var variant = await servce.CreateAsync(4308720222304, new ProductVariant()
            {
                Option1 = "blue",
                Price = (decimal)123.45,
            });

Error:-Argument1:-cannot convert a long into shopifysharp.Product

Argument2:-cannnot convert shopifysharp.ProductVariant to shopifysharp.ProductCreateOption

**Comment by nozzlegear** [comment]
You need to use the ShopifySharp.ProductVariantService to create product variants, or you can create variants at the same time as you create a product by adding them to the product's variants list:

```cs
var product = new ShopifySharp.Product
{
  Title = "My product",
  Variants = new List<ShopifySharp.ProductVariant>
  {
    new ShopifySharp.ProductVariant
    {
      Option1 = "blue",
      Price = (decimal)123.45
    }
  }
}
```

**Comment by zafar1700017** [comment]
i didn't know how many variants are in product whether it is two
variants and 4 variants what i will do
