### ISSUE TITLE
Obsolete Checkout

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#409]
When using the Abandoned checkouts (Checkoutservice) it states that this is obsolete and may be removed by Shopify at any point.

So I guess this connects to the wrong Shopify API ?

The Shopify Abandoned checkouts is very much alive: https://help.shopify.com/en/api/reference/orders/abandoned-checkouts

**Comment by nozzlegear** [comment]
The checkout service was originally built for [the sales channel checkout](https://help.shopify.com/en/api/reference/sales-channels/checkout), not for abandoned checkouts. At some point Shopify added Abandoned Checkouts, but they both use the same endpoints. Looking at the endpoints, the list/count methods on CheckoutService will list/count abandoned checkouts, and the other methods will work for sales channel checkouts. I'll need to split them into two separate services it seems.
