### ISSUE TITLE
Shopify Gift Card Adjustment Endpoint Implementation

### ISSUE THREAD

**Issue by SeanoNET** [nozzlegear/ShopifySharp#414]
Hi,

There is a Gift Card adjustment endpoint that can be accessed from a private app once the stores Shopify plus launch manager has grated access on a specific Shopify store also the store needs to be on the Shopify plus plan (Needed for GiftCards).

There is public documentation for this endpoint however it's not documented in the [GiftCard api reference](https://help.shopify.com/en/api/reference/plus/giftcard).

[Gift Card Adjustment api reference](https://help.shopify.com/en/api/reference/plus/gift_card_adjustment)

Is this something you would like to support in ShopifySharp?

Testing this service will be little more difficult - the endpoint will need to be enabled on the store that the integration tests are running against.

Thanks,
Sean

**Comment by nozzlegear** [comment]
Hey @SeanoNET! I'd absolutely like to add this and support it in ShopifySharp. It's impossible to test these endpoints without a Shopify Plus plan, so unit tests are out the window. But it wouldn't be the first Plus-only endpoint we support in this package. If you've got the time and inclination to create a pull request for this, I'd be happy to review and merge it!

**Comment by SeanoNET** [comment]
Hi @nozzlegear Great - I will get onto this when i have some time available.

**Comment by clement911** [comment]
Nice one @SeanoNET , I'm curious how you found the documentation url for this endpoint?
@nozzlegear  to your point, there is now Shopify Plus partner sandbox stores.
See https://help.shopify.com/en/partners/dashboard/plus-sandbox-store
Maybe that can be used to test Shopify Plus endpoints...

**Comment by SeanoNET** [comment]
Hi @clement911 - this was provided to me by our Shopify partner manager as we required this functionality in our service.

Great find, I was not aware you could spin up Plus stores. I will be sure to include integration tests similar to [GiftCard ](https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp.Tests/GiftCard_Tests.cs)

**Comment by nozzlegear** [comment]
@clement911 Wow, awesome! Thanks for the link, I had no idea they had those sandbox stores available.

**Comment by nozzlegear** [comment]
Merged in #418
