### ISSUE TITLE
Metafields Service Not Returning All Metafields

### ISSUE THREAD

**Issue by leikelman** [nozzlegear/ShopifySharp#415]
I am attempting to retrieve all metafields assigned to variants.  I am using the metafield service and calling the following I would expect to return all of the metafields (realize not just variants, but everything):

metaServce.ListAsync();

However, this appears to only be returning a single "settings" service, which is not what I expected.  I tried using a MetaFieldFilter with no success as well.

**Comment by nozzlegear** [comment]
Hey! Thanks for filing this. Unfortunately, this is just the default behavior of the Shopify API. If you don't enter a parent resource type/id, you'll get a list of metafields on the shop itself instead. As far as I know, it's impossible to list all of the metafields across all resource types using the REST API. 

https://help.shopify.com/en/api/reference/metafield

**Comment by leikelman** [comment]
> Hey! Thanks for filing this. Unfortunately, this is just the default behavior of the Shopify API. If you don't enter a parent resource type/id, you'll get a list of metafields on the shop object instead. As far as I know, it's impossible to list all of the metafields across all resource types using the REST API.
> 
> https://help.shopify.com/en/api/reference/metafield

Is it possible to get a list of all metafields associated to variants?

**Comment by nozzlegear** [comment]
Sorry for the late reply, but no I don't think there's an easy way to get that. You'd have to loop through every single variant, which would be very time consuming. You _might_ be able to do it with the GraphQL API, but I don't have a lot of experience with that so I can't say for sure.
