### ISSUE TITLE
how i create a invoice using shopifysharp

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#416]
how i create a invoice using shopifysharp

**Comment by nozzlegear** [comment]
What kind of invoice are you trying to create? Depending on what you need, you might want to take a look at the [Draft Order API](https://www.youtube.com/watch?v=VIPUCPMd_nA&feature=youtu.be), which ShopifySharp supports with the DraftOrderService.

**Comment by zafar1700017** [comment]
I want to generate an invoice for pending orders, not draft orders. Can you help me with how we generate an invoice for pending orders?

Thank you

**Comment by zafar1700017** [comment]
I want to generate an invoice for pending orders, not draft orders. Can you
help me with how we generate an invoice for pending orders?

Thank you

**Comment by zafar1700017** [comment]
how we add line-item in the existing order, not in the new order. So please
me how I add new line-item in the existing order

Thank you

**Comment by zafar1700017** [comment]
also please tell me how I move the order into the drafts order using
Shopify sharp

Thank you

**Comment by nozzlegear** [comment]
Hey! Unfortunately I can't offer enough support on this. I would strongly recommend reading Shopify's API docs on the things you're trying to do, and then play around with the services in ShopifySharp. This package supports almost all of the calls you'll find in their API docs, and they'll also tell you what is and isn't possible (like adding a line item to an existing order).

Here's a good place to start: https://help.shopify.com/en/api/reference/orders

I'm sorry I can't be more help!
