### ISSUE TITLE
When the Shopify Dev Handbook for .Net Core

### ISSUE THREAD

**Issue by orney21d** [nozzlegear/ShopifySharp#417]
Hi,

I just bought your book "Shopify Development Handbook" and would like to know if you have already some estimated date for update it with .Net Core content ?.

Thanks in advance.

**Comment by nozzlegear** [comment]
Hey! I'm working on the update right now, but it's a near total rewrite so it's taking a lot longer than anticipated. I'm hoping to release the first bit of the changes within the next 30 days or so. If you've already purchased the book you'll get all of the updates for free.
