### ISSUE TITLE
Regarding strong name signing

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#419]
I found a solution to your strong name signing troubles.

Use this to sign dll with strong name:

https://github.com/brutaldev/StrongNameSigner

Youi dont need a certificate because the StrongNameSigner has its own.

It's best if nozzlegear sign with strong name in the nuget package since if the users of the nuget has to sign, it creates more problems that they have to sign it in every project they use the nuget package.

**Comment by nozzlegear** [comment]
Awesome, thank you for the link! I'll investigate this and see if I can get it going when I have free time.
