### ISSUE TITLE
merchant approval for write_inventory scope

### ISSUE THREAD

**Issue by malthemorsing** [nozzlegear/ShopifySharp#422]
How do i fix this??
Also, do you have any example code for updating inventory? :I 

![Udklip](https://user-images.githubusercontent.com/57196060/69740877-647e5e00-113a-11ea-8b1f-bf04cce9b625.PNG)

**Comment by nozzlegear** [comment]
Hey, this error is telling you that you need to request the `write_inventory` permission from the merchant when they install your app. So when you're sending the user through the OAuth installation process, you can request a list of permissions for the access token. You need to add `write_inventory` to that list or you won't be able to make changes to inventory levels on the store. 

--
Josh Harms

**Comment by malthemorsing** [comment]
I'm note sure i send the user through OAuth? That is some behind the scenes stuff in shopifysharp, right?

**Comment by nozzlegear** [comment]
That depends, are you using a private app, or an app you're going to publish on the app store? If it's a private app, you can just go in to the private app settings in the store admin dashboard and change the permissions. If it's an app you're going to publish on the app store, you would have to use OAuth to get an access token from a user.

**Comment by malthemorsing** [comment]
Oh yeah, it's a private app. I'll look into tha -, thank you very much!

**Comment by nozzlegear** [comment]
No problem! When you're looking at the private app permissions, I think it only shows like 5-10 permissions by default, but there's a little arrow you can click at the bottom to show the entire list of permissions.

**Comment by nozzlegear** [comment]
Oh, unfortunately I don't have any example code on hand for updating inventory. Shopify has made the process more convoluted than I feel is necessary with their levels and locations APIs, but it's possible to update inventory and I have done it before using ShopifySharp.

**Comment by malthemorsing** [comment]
No problem, i think i'm getting the hang of it.
