### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by malthemorsing** [nozzlegear/ShopifySharp#424]
How do i update the product description?

**Comment by malthemorsing** [comment]
Just figured it out.
Why is it called BodyHtml and not Description though?

**Comment by foxandrewj** [comment]
In order to match the field name on Shopify's API
[https://help.shopify.com/en/api/reference/products/product#properties-2019-10](https://help.shopify.com/en/api/reference/products/product#properties-2019-10
)

**Comment by nozzlegear** [comment]
Correct, thanks @foxandrewj!
