### ISSUE TITLE
How to search customer using date filters

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#428]
Can you please help me how we get customers using date filters.

For example all customers (on before date(02-dec-2019))

can you help please how we get customers by date filters?

**Comment by nozzlegear** [comment]
You can use a `ShopifySharp.Filters.ListFilter` for that:

```cs
var filter = new ShopifySharp.Filters.ListFilter
{
	CreatedAtMax = new DateTimeOffset("2019-12-02")
}
```
