### ISSUE TITLE
Serching for products/variants using wildcard

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#430]
Hi

How can I find products and variants using a wildcard ?

Like in Shopify admin where you can search for products "car" that will find everything that contains car including title, tags, vendor etc.

**Comment by nozzlegear** [comment]
Unfortunately I don't think there's any way to search for products or variants. Whatever method Shopify is using to search the admin, they're not exposing it in the APIs. You'd probably have to implement this yourself, or use some kind of search service that you can feed product/variant titles into.
