### ISSUE TITLE
How to enable Track Quantity?

### ISSUE THREAD

**Issue by Waqas2641995** [nozzlegear/ShopifySharp#431]
The Question is how to enable track quantity which type is **bool**? without enable this property i can't see inventory quantity in shopify store.

**Comment by nozzlegear** [comment]
Sorry, I'm not sure I understand. Which service/endpoint are you trying to use? Can you give me a link to the Shopify docs where this bool is documented?

**Comment by Waqas2641995** [comment]
We have a boolean property Track Quanitty in shopify admin panel which is by default false so our stock not mantain until we enable Track Quantity, so my question is that how we can enable this property with using shopify sharp library?

` var inventoryItem = new ShopifySharp.InventoryItem()
            {
                Tracked = true,
                SKU = input.SKU,
                Id = 1
            };
            await inventoryService.CreateAsync(inventoryItem);`

Actually in Inventory Service not have CreateAsync() Method, it have only GetAsync(id) and UpdateAsync(id,Object) method.
So we need  CreateAsync() method for enable TrackQuantity Property.
Please we need your suggestion.
