### ISSUE TITLE
line item in product page

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#435]
hi 
Can you help me how we add a line item in product page also show these line item shown in order details

thank you

**Comment by zafar1700017** [comment]
any reply please

**Comment by nico159** [comment]
Hi, I think that you're asking about the cart line item's properties
If so, this is isn't something that you can do with the Shopify's Admin API
Instead you will need to add one or more input in the add to cart form with its name that follow the format:
`properties[Engraving]`
So something like:
```
<label for="engraving">Engraving</label>
<input id="engraving" type="text" name="properties[Engraving]">
```
Or use the Storefront API (GraphQL) or the [Shopify Ajax API](https://help.shopify.com/en/themes/development/getting-started/using-ajax-api#add-to-cart) to handle the add to cart with these additional properties
