### ISSUE TITLE
Intent to drop .NET Framework 4.5 as target framework

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#438]
Hey everyone, I'm opening this issue to let you know about my intent to drop .NET Framework 4.5 as a target framework. It's my understanding that .NET Standard packages can be used from .NET Framework now, which means there's no reason to target .NET Framework any longer. It's not a huge deal, but targeting .NET Framework means that I can't restore or build the package on Linux (without modifying the project file on every restore/build). 

If I'm wrong about this, please let me know!

**Comment by nozzlegear** [comment]
Just a quick update for my plans, I'm going to keep targeting .NET Framework 4.5 for ShopifySharp 5.0, just to make sure nobody on the framework is left hanging when we upgrade to the new API version. ShopifySharp 5.1 and onward will drop the framework as a target.

**Comment by skhan-nacmgit** [comment]
I'd vote to keep. If one is using this for SSIS ETL, it wont work with some older versions of SQL Server.

**Comment by davidkdb** [comment]
I vote for dropping 4.5. One day we all must let the past go :-)

**Comment by waxtell** [comment]
Would love to see support for netstandard 1.x, 2.0 and 2.1 which, in theory, should cover just about everything!

[.NET Standard Versions](https://github.com/dotnet/standard/blob/master/docs/versions.md)

I love the library, but the lack of core 3.1 support is preventing my team from upgrading our AWS lambdas from core 2.1 to 3.1.

**Comment by clement911** [comment]
@waxtell I've been using ShopifySharp on .net core 3.1 for a while.

**Comment by waxtell** [comment]
@clement911 - were you able to get it to work in a core 3.1 AWS Lambda function?

**Comment by clement911** [comment]
I haven't tried. I'm on Azure.

**Comment by waxtell** [comment]
No worries!  I *expected* it to work, but alas no.  I'm going to try and build the library as netstandard2.1 just to see if it plays nice with AWS :)

Thanks for the feedback!

**Comment by ThatBrianK** [comment]
It looks like .NET Framework 4.6 has also been dropped as of 5.3.0? really threw a monkey wrench into my whole program! I didn't see any documentation of it either. Am I missing something?

**Comment by nozzlegear** [comment]
Good catch! I did not mean to drop the framework yet, and didn’t realize it wasn’t being included in the last few builds. 

--
Josh Harms

**Comment by nozzlegear** [comment]
Since I'm on Linux I often remove .NET Framework as a build target when I'm working on the project. [Looks like I accidentally committed that change](https://github.com/nozzlegear/ShopifySharp/commit/71aa974ae9c08a1834d29519bdec6203357cb17f) at some point and didn't realize it. I'll add .NET Framework back and publish to Nuget soon.

**Comment by ThatBrianK** [comment]
Thanks! I really appreciate all your effort on this project! I recognize that eventually I'll have to force the users of my software to have .NET 4.7 or higher but we're just not there yet.

**Comment by clement911** [comment]
Where are we standing on dropping .net framework support.
Can we require netstandard2.1 minimum?

**Comment by clement911** [comment]
In particular, I'd really love to use c#8 and 9 features but currently we can't.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults

**Comment by nozzlegear** [comment]
It's been just under 2 years since I first announced intent to drop .NET Framework 4.5 support. I'm doing that now with ShopifySharp **v5.14.0**. If you're using .NET Framework, you should begin the work to upgrade to at least .NET Framework 4.7 which supports .NET Standard 2.1 (our new framework target), or .NET 5.0 if possible! 

ShopifySharp v5.13.1 -- the last version with .NET Framework 4.5 as a target -- is using the `2021-10` version of Shopify's API, which becomes deprecated on **October 1st, 2022**. You'll want to have your projects upgraded to .NET Framework 4.7 or above before that date, or else you won't be able to update ShopifySharp before the API gets deprecated.

**Comment by nozzlegear** [comment]
My mistake, ShopifySharp v5.13.1 [actually targets API version `2021-07`](https://github.com/nozzlegear/ShopifySharp/blob/36de3a0ddcdd4bb03bc34dcdefa4f1dcba6a05e1/ShopifySharp/Services/ShopifyService.cs#L18), which means you'll want to upgrade to a framework that supports .NET Standard 2.1 before **July 1st, 2022**.

**Comment by clement911** [comment]
Hmm I'm not sure if I'm missing something but .NET framework doesn't seem to support .NET Standard 2.1.
Not even .NET Framework 4.7. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard
Personally I don't mind since I'm on .NET 5 already. The question is, how many ShopifySharp users still use .NET framework?

**Comment by clement911** [comment]
It might be warranted to increment the major version of the lib.

**Comment by StevePritchard** [comment]
Yep - I can't perform the update. I am targetting .Net Framework 4.7.2, and ShopifySharp 5.14.0 looked like it would fix my Newtonsoft.Json versioning issue, but it won't install -->

Could not install package 'ShopifySharp 5.14.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

😭

**Comment by clement911** [comment]
@StevePritchard  I'm guessing there is a good reason why you are not on .Net core or .Net 5/6?

**Comment by StevePritchard** [comment]
> @StevePritchard I'm guessing there is a good reason why you are not on .Net core or .Net 5/6?

It depends upon your definition of "good". It's a Windows Service in .Net Framework 4.7.2 that references a few other libraries too, so it's a non-trivial exercise to switch over. Legacy, legacy, same old, same old.

**Comment by nozzlegear** [comment]
Darn, I swear I had read that .NET Framework 4.7 was compatible with .NET Standard

**Comment by ThatBrianK** [comment]
I was not able to update either. My project is targeting .NET framework 4.8

Update-Package : NU1202: Package ShopifySharp 5.14.0 is not compatible with net48 (.NETFramework,Version=v4.8). Package ShopifySharp 5.14.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)

As StevePritchard said: Legacy, legacy, legacy. It's a significant job to migrate from .NET Framework to .NET 5 or .NET 6, especially if you are a small company with limited resources.
Also, Microsoft has stated that it will continue to be supported:
.NET Framework 4.8 is the latest version of .NET Framework and will continue to be distributed with future releases of Windows. As long as it is installed on a supported version of Windows, .NET Framework 4.8 will continue to also be supported.

**Comment by nozzlegear** [comment]
I see, I'll look into adding support for .NET Framework 4.7+ as long as it's compatible with the HTTP client factory stuff that was introduced in 5.14.0.

**Comment by judah4** [comment]
It might need to be for Dotnet Standard 2.0, not 2.1. This chart shows N/A support for Framework with Standard 2.1.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by Zikoat** [comment]
Same here. We've looked into migrating to .net 5, but it's a big job.

**Comment by lorenpaulsen** [comment]
> It might need to be for Dotnet Standard 2.0, not 2.1. This chart shows N/A support for Framework with Standard 2.1.
> 
> https://docs.microsoft.com/en-us/dotnet/standard/net-standard

That's correct. Targeting Standard 2.1 eliminates support for any .NET Framework version, even 4.8. Please consider targeting .NET Standard 2.0, so those with legacy .NET Framework apps can keep using new versions of the package.

**Comment by ThatBrianK** [comment]
> > It might need to be for Dotnet Standard 2.0, not 2.1. This chart shows N/A support for Framework with Standard 2.1.
> > https://docs.microsoft.com/en-us/dotnet/standard/net-standard
> 
> That's correct. Targeting Standard 2.1 eliminates support for any .NET Framework version, even 4.8. Please consider targeting .NET Standard 2.0, so those with legacy .NET Framework apps can keep using new versions of the package.

I just tried the latest build, it still is not installing for my .NET Framework 4.8 project.
I would pay money to have this added back in at this point! Thanks again for everyone's hard work on this amazing project!

**Comment by nozzlegear** [comment]
I’m pretty sure I’ll be able to add support for .NET 4.8! I’m aiming to test it soon.

--
Josh Harms

**Comment by lanthonyneville** [comment]
Similar to what @StevePritchard said - I am using ShopifySharp inside a .NET Framework - based integration platform, which has no roadmap for conversion to .NET 5/6 yet (way too dependant on .NET Fmk features).

Agree with others - if SS could target .NET Standard 2.0, rather than 2.1, that would be a big deal for us.

**Comment by nozzlegear** [comment]
I think we can add support for .NET Standard 2.0, but it would come with the caveat that it won't support some of the features that the .NET Standard 2.1 version supports. Specifically you wouldn't be able to use the `HttpClientFactory` stuff.

**Comment by RichardD2** [comment]
`HttpClientFactory` **is** supported in .NET Standard 2.0 - you just need to reference [the `Microsoft.Extensions.Http` NuGet package](https://www.nuget.org/packages/Microsoft.Extensions.Http).

+1 for .NET Standard 2.0 support. Aside from the lack of SQL Server Reporting Services support in .NET Core/5/6, we have too much code in our application to justify rewriting everything every three years.

**Comment by jeroenbai** [comment]
Would be great to add support for this, as I'm about to integrate a .NET 4.7 app with Shopify and would love to use this project.

**Comment by ThatBrianK** [comment]
I'm just wondering if there's any update on the .NET Framework stuff?
I'm concerned that the Shopify API version is going to go out of support, and then will be forced to manually compile the libraries of the last .NET framework-supported version and just change the API version. Since it seems I'm not the only one in this boat, perhaps it might be worth building a parallel project so that all us .NET framework users can stay updated.  and we won't all have to manually do this work.

**Comment by nozzlegear** [comment]
Okay, a prerelease version of ShopifySharp has been published to Nuget targeting .NET Standard 2.0, which adds support for .NET Framework 4.6.1+. All tests pass without issue, but before I publish the full release can anyone here please try installing the prerelease version  `5.15.0-b00503` from Nuget and let me know if you have any issues with it?

```sh
# Visual Studio Package Manager:
Install-Package ShopifySharp -Version 5.15.0-b00503
# Dotnet CLI:
dotnet add package ShopifySharp --version 5.15.0-b00503
```

Thanks to @ChaoticIke for the pull request that made this possible!

**Comment by sletmoep** [comment]
I'm also in the .NET Framework boat - adding new functionality to an older app that uses .NET Framework for a bunch of different reasons that I don't have any control over. I was able to download and run the prerelease version from Nuget without problems. I tried both 4.6.1 and 4.6.2 and in both cases it installed without errors. I'll be doing some testing over the next couple of weeks.

**Comment by sletmoep** [comment]
I have no problems to report. Everything seems to work fine. As I previously stated, I am targeting 4.6.2 as my primary use case. I've been able to download the prerelease version and connect to Shopify without issue. For the sake of completeness, I also spun up a Windows 11 Hyper-V and tried the prerelease version on 4.8. It seems to work well there also. Note that the scope of my work is fairly limited - customers, products, inventory, orders, and metafields. So there are areas of the library I haven't used. But in a basic "will it go" sense, it gets a pass from me.

**Comment by paulhusted** [comment]
Can confirm that prerelease 5.15.0-b00503 works without issue with .NET Framework 4.8 on Windows 11.

**Comment by nozzlegear** [comment]
ShopifySharp version 5.16.0 has been released on Nuget and should bring back full support for .NET Framework 4.6.1 and above! Let me know if you have any issues using it.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/2417276/183197944-3fd188cf-31cb-46d3-a75e-0cde5021370f.png">

**Comment by nozzlegear** [comment]
Awesome, thanks for the help everyone! I’ll be deploying a full release to nuget this week.

--
Josh Harms

**Comment by venkatrao201** [comment]
![image](https://github.com/nozzlegear/ShopifySharp/assets/141213463/81d0af8f-69e2-4b56-b44b-0bc9090813a7)

for v4.6.1 also not installing the shopifysharp

**Comment by RichardD2** [comment]
@venkatrao201 4.6.1 has extremely dodgy support for .NET Standard 2.0 libraries:

[.NET Standard | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)

Are you able to update your project to target at least 4.6.2 _(preferably 4.7.2 or later)_?
