### ISSUE TITLE
ShopifyOrder.NoteAttributes deserialized incorrectly

### ISSUE THREAD

**Issue by zhershds** [nozzlegear/ShopifySharp#44]
I tried to get NoteAttributes of ShopifyOrder. But "key" is always empty.
Shopify return NoteAttributes as:
```
"note_attributes": [
        {
            "name": "test",
            "value": "test"
        }
    ]
```
But library try to deserialize it into the `IEnumerable<KeyValuePair<string, string>>`.
`KeyValuePair` class has two properties `Key` and `Value`.
So only `Value` can be deserialized correctly.

**Comment by nozzlegear** [comment]
Thanks for the report! I've got this fixed in v2.0 (#43) by changing NoteAttributes to a list of `ShopifyNoteAttribute`. As part of this change, you'll also be able to use any kind of object (string, int, another object) for the `Value` prop.
