### ISSUE TITLE
GDPR webhooks

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#445]
hi

Can you please how we add GDPR webhooks

1; shop/redact
2: customers/redact
3:customers/data_request

**Comment by nozzlegear** [comment]
Hey @zafar1700017, you need to set these webhooks up in your Shopify app settings, which can be found in the Shopify Partner dashboard. It's the same place you edit your public app store listing, get your API/secret keys, etc. You can't create these GDPR webhooks via API.
