### ISSUE TITLE
Urgent: update to ShopifySharp v2.0.0 before June 1st, 2016

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#45]
I'm going to open this issue and leave it open until June. This is a PSA for everybody using `ShopifyAuthorizationService.IsAuthenticRequest` on ShopifySharp v1.17.1 and below. 

I strongly recommend updating to 2.0.0+ before June 1st, 2016. Shopify will completely remove the method for verifying authentic requests used in `ShopifyAuthorizationService.IsAuthenticRequest` on June 1st, 2016. After that date, this method will always return false in v1 builds.

[See the section on 'MD5 Signature Validation' here](https://docs.shopify.com/api/guides/authentication/oauth#md5-signature-validation) for more details on the auth method used in v1.17.1 and below.

--

For those who've purchased [The Shopify Development Handbook](https://nozzlegear.com/shopify-development-handbook), I'm working on an update right now that will use ShopifySharp 2.x. You'll get it for free as soon as it's released in the next few weeks.

**Comment by victorgpacheco** [comment]
Thanks
