### ISSUE TITLE
how we get asset_id ??

### ISSUE THREAD

**Issue by zafar1700017** [nozzlegear/ShopifySharp#451]
how we get asset_id from assets themes ??

**Comment by nozzlegear** [comment]
There is no asset_id. You can get the theme, then use the theme id to list all of the assets under it. Assets use keys rather than ids.

**Comment by zafar1700017** [comment]
then how i update the assets ???
 at your documentation when i want to update the assets we need asset_id??

**Comment by nozzlegear** [comment]
It looks like the documentation needs to be updated, I'll get that done tomorrow. You need to use the `Asset.Key` property when you're trying to get, update or delete an asset:

```cs
var service = new AssetService(domain, accessToken);
var myAsset = new Asset
{
	Key = "templates/test.liquid",
    // ...
};

await service.CreateOrUpdateAsync(themeId, asset);

var updateAsset = await service.GetAsync(themeId, asset.Key);
```

**Comment by zafar1700017** [comment]
it overrides the date when I use CreateOrUpdare() function it will remove
the previous data and add current data
