### ISSUE TITLE
Embedded apps and the SameSite attribute

### ISSUE THREAD

**Issue by cupelapps** [nozzlegear/ShopifySharp#453]
Hi guys,
Is anything needed to be done for the Shopify Embedded apps and the SameSite attribute issue?

**Comment by clement911** [comment]
Yes, your cookies will need to be delivered with SameSite = None for modern browsers to be able to load them.
Here are some resources:
https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies
https://github.com/GoogleChromeLabs/samesite-examples
https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1

**Comment by clement911** [comment]
Can we close this?

**Comment by cupelapps** [comment]
Hi
Thank you for the answer. Yes. We can close this
Regards
CupelApps
