### ISSUE TITLE
Un-Archived order

### ISSUE THREAD

**Issue by skhan-nacmgit** [nozzlegear/ShopifySharp#454]
After an order is fulfilled its marked as "Archived" on the Shopify platform. On the backend, one can mark it as "Unarchive" in order to edit or make minor changes to the order.

When an order is marked as Unarchive and one wants to exclude "Unarchive" orders, the FulfillmentStatus filter doesnt work e.g.

`IEnumerable<Order> orders = await service.ListAsync(new MyOrderFilter() { FulfillmentStatus = "" });`

The work-around would be to check the Order.FulfillmentStatus during iteration e.g.

`
foreach (var order in orders)
{
   if(String.IsNullOrEmpty(order.FulfillmentStatus)
   //new order
     else
   //unarchive order
}
`

**Comment by nozzlegear** [comment]
Hey @skhan-nacmgit, can you give this a try in ShopifySharp v5+ and let me know if this still doesn't work for you?
