### ISSUE TITLE
Please can you confirm when is ShopifySharp version 5 going to be released?

### ISSUE THREAD

**Issue by HoomanBahreini** [nozzlegear/ShopifySharp#459]
Please are you able to confirm when will Shopify Sharp version 5 be released?

My current app is using `ListAsync` method, which will no longer work after 1st if April. Shopify Sharp version 5 was supposed to be released before Feb 20th 2020 [according to maintainers of the library](https://github.com/nozzlegear/ShopifySharp/issues/448)...

Once ShopifySharp version 5 is released, I still need some time to update my program and test it... The deadline is very close and I need to make the decision of removing the library from my app or not... which is really frustrating as I have already built everything using this library... I wish I had never bought your book and used this library at the first place... now I am stuck.

**Comment by nozzlegear** [comment]
A prerelease version will be published tomorrow, which you’ll be able to download and start migrating over. We need to refactor the tests before I can release the full version 5. It’s a lot of refactoring, which slows me down. I’m always happy to accept pull requests from those who want to contribute and speed this along, the current changes are in the v5.0 branch and that’s what needs to have it’s tests refactored. 

--
Josh Harms

**Comment by nozzlegear** [comment]
A prerelease version is now available on Nuget. The full release will be published as soon as we get tests refactored and passing.

Closing in favor of #462
