### ISSUE TITLE
Transaction object inside of orders always null

### ISSUE THREAD

**Issue by joseph3114** [nozzlegear/ShopifySharp#469]
I'm refactoring my code to the 5.0 release, and I'm having an issue with all transactions inside of the order returning as null, even though in Postman the order has the appropriate transactions associated with them.

This is the previous code I was using: 
List<Transaction> alltransactions = allorders.SelectMany(x => x?.Transactions).ToList();     

I didn't post this in the 5.0 thread because I'm not sure if this is intentional anticipating some other API change in the future or if my usage is wrong unrelated to 5.0.

**Comment by clement911** [comment]
I believe this `order.Transactions` was deprecated a while ago.
Are you using version 2019-10 in Postman?

**Comment by nozzlegear** [comment]
Yes I’m pretty sure I remember specifically removing the transactions property for 5.0 because it was deprecated. The Shopify docs recommend using the transaction api instead, which ShopifySharp supports through the TransactionService class.

--
Josh Harms

**Comment by joseph3114** [comment]
Yes i checked 2019-10 in Postman. The Shopify docs for 2020 still have
transactions as part of order, I’ll keep searching for a post from them
about changing this in the future.

Thanks for the reply, that’s what I was afraid of, at 2 calls a second it’s
looking like it will take a few hours to pull all transactions.

**Comment by clement911** [comment]
> The Shopify docs for 2020 still have transactions as part of order.

I don't see it (only on refunds...)
Am I missing something?

**Comment by joseph3114** [comment]
Nope you’re absolutely right, that’s only on the refund portion.
Please delete this issue and end my shame.
