### ISSUE TITLE
ShopifyService injection

### ISSUE THREAD

**Issue by andre719mv** [nozzlegear/ShopifySharp#478]
Hi!

I really like this library but I have some difficulties on using it. In my project I need to do some overrides in ShopifyService class (logging, headers and API limits handling). To use my new overriden class I need to copy every service that I use just to be interhited from my new ShopifyService. I do a lot of copy paste and I need to repeat all updates from your lib to not miss important changes in services. Is it possible to make ShopifyService injectable as property or something like that? Many thanks!

**Comment by nozzlegear** [comment]
Hey! I'd like to do this at some point, but it requires a lot of tedious boilerplate changes, so it really depends on when I can get some free time to do so. #362 would be the first step to making ShopifySharp work with dependency injection.
