### ISSUE TITLE
Published scope (channels) for products

### ISSUE THREAD

**Issue by Manuki** [nozzlegear/ShopifySharp#479]
I have not found any way to, from the API, publish a product on the Facebook, Pinterest and other sales channel.

The variable product.publishedScope only affects online store and PoS. Products, by default, are not published on facebook.
I have not found another variable to do this on the products, even if I had the channel ID I'd have nowhere to put it.

Is there any way to manage the availability of products on the different channels from the API ?

Thank you

**Comment by aztekweb** [comment]
The API does not provide this ability.  It's a long-standing complaint in their support forums.

**Comment by Manuki** [comment]
> The API does not provide this ability. It's a long-standing complaint in their support forums.

Any work-arounds for bulk-enabling visibility on those channels ?

**Comment by aztekweb** [comment]
There's a bulk product editor in the admin UI.  It's a manual process unfortunately.
