### ISSUE TITLE
Shopify API version migration

### ISSUE THREAD

**Issue by madushann** [nozzlegear/ShopifySharp#480]
We have shopify private apps build where it uses shopifysharp, due to recent shopify version upgrade requirements we need to update our API version of the apps, when we change the version from shopify admin to newest version ("Webhook API version") how does it impact the shopifysharp and where we need to change the version for shopifysharp ?

I have seen version a reference in code as below, 
https://github.com/nozzlegear/ShopifySharp/blob/e1a09d1544de3188ddd00caeb8ae15a636aaae64/ShopifySharp/Services/ShopifyService.cs#L17
        public virtual string APIVersion => "2019-10";

**Comment by clement911** [comment]
Assuming that you use ShopifySharp to deserialize your webhook requests, you should keep your Shopify webhook version in sync with ShopifySharp's version, which is indeed 2019-10 as of the current latest nuget package.

**Comment by madushann** [comment]
Thank you for the clarification.

Could you please clarify below,
![image](https://user-images.githubusercontent.com/40527502/76651989-a4bfeb80-6533-11ea-8de1-81aef1001a2f.png)

Above message appear on shopify admin under the app, by updating the shopifysharp version from 4.x to 5.0.4 would solve the issue. 

I hope shopify detect this because we are using webhook service,
`WebhookService webhookService = new WebhookService(shop, token);`

"admin_graphql_api_id" property is not used openly in our code so hope just upgrade the version should solve the issue.

**Comment by clement911** [comment]
Have you updated your webhook version in your app's settings?
