### ISSUE TITLE
ProductCountFilter

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#481]
Hi
In previous version (before the paging thing) I can pass product filter to productService.CountAsync() and count the result of against the supplied filter. And one of the filter I need is to search & count products by product title (or part of the title). But now with this new update i have that **title**  property in the **ProductListFilter** but it is no more in the **ProductCountFilter** !! 

Can we bring it back ?? 

Thanks

**Comment by clement911** [comment]
In v5 we try to only expose documented fields and filtering the count of product by the product title is not documented.
That being said, you could try inheriting the `ProductCountFilter` class to add this property yourself.
Beware though the Shopify might actually have stopped considering this non documented field between the earliest version that ShopifySharp used (2019-04) and the current one (2019-10)

**Comment by ishahrier** [comment]
Thanks!
