### ISSUE TITLE
Product Pagination

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#485]
Hi Guys
Before I would use page and limit in the product list filter and that would help me render nice bootstrap pagination on the client side. Now that the "page" property is gone from the product list filter ; how do you suggest to render page numbers for product listing on client side ??

Thanks

**Comment by nozzlegear** [comment]
Hey! I wrote a little bit about this [in the v4 to v5 migration guide](https://nozzlegear.com/shopify/shopifysharp-version-5-migration-guide) (which I haven't linked yet in the readme). As far as I can tell, there's no way to make it work with specific page numbers any longer; the best we can get is to add simple [Next Page] and [Previous Page] links by storing the list result's `NextLink.PageInfo` property in the link querystring. The only alternative would be importing all of the orders into a database you control so you can do pagination yourself.

**Comment by drovani** [comment]
I had this same issue with needing to implement page-specific selection of products - it's not ideal, but what I did is write a loop that iterates from page 1, getting the Next Page until I get to the page specified. If you set the `fields` property to just `id`, it returns quickly enough.

Mind you, it is nowhere near ideal, and it is a O(n) scale, but it gets the job done.

**Comment by ishahrier** [comment]
@nozzlegear  THANK YOU! I will read that document you wrote. 
@drovani got it. thanks.
