### ISSUE TITLE
API Key Error updating metafields

### ISSUE THREAD

**Issue by connde** [nozzlegear/ShopifySharp#488]
Hi, I'm trying to update meta fields of a product, but for some reason using this service always gives me an invalid key error. If I use other services such as update products or inventory it works without issues so it is not related to the token. 

Error: [API] Invalid API key or access token (unrecognized login or wrong password)
I tried adding the metafields to the product and using Product.UpdateAsync also but I also get the same message.

What am I doing wrong?

Thanks, great development by the way!

**Comment by clement911** [comment]
That is very weird / concerning.
And you're using the same access token / shop id?

**Comment by connde** [comment]
> That is very weird / concerning.
> And you're using the same access token / shop id?

Hi, my mistake, was working until late hours, today I saw that I added key instead of secret, that was the issue, metafields got updated now as expected.
