### ISSUE TITLE
Serializable objects

### ISSUE THREAD

**Issue by malthemorsing** [nozzlegear/ShopifySharp#494]
Any chance you could make the product object serializable?

**Comment by nozzlegear** [comment]
Hey! The product object should already be serializable with Newtonsoft.Json:

```cs
var product = new Product()
{
  //...
};
var json = Newtonsoft.Json.JsonConvert.SerializeObject(product);
```

**Comment by nozzlegear** [comment]
Let me know if that's not what you meant and I can reopen the issue.
