### ISSUE TITLE
Question: Can we consume admin graphQL using ShopifySharp ?

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#503]
Thanks in advance

**Comment by nozzlegear** [comment]
Hey @ishahrier! Are you talking about the graphQL API that Shopify is using in their admin dashboard, or are you talking about the official graphQL API [documented here](https://shopify.dev/docs/admin-api/graphql/reference)?

If you're referring to the first, I don't believe it's possible, it seems like they're using a private graph endpoint. If you're referring to the official graph API, you can use that with ShopifySharp! We support that with the GraphService, although it's kind of difficult to make graphQL work with .NET in general so the experience isn't as smooth as I'd like.

**Comment by ishahrier** [comment]
> Hey @ishahrier! Are you talking about the graphQL API that Shopify is using in their admin dashboard, or are you talking about the official graphQL API [documented here](https://shopify.dev/docs/admin-api/graphql/reference)?
> 
> If you're referring to the first, I don't believe it's possible, it seems like they're using a private graph endpoint. If you're referring to the official graph API, you can use that with ShopifySharp! We support that with the GraphService, although it's kind of difficult to make graphQL work with .NET in general so the experience isn't as smooth as I'd like.

Got it. THANK YOU!
