### ISSUE TITLE
Order object does not include `gateway` property

### ISSUE THREAD

**Issue by johndowns** [nozzlegear/ShopifySharp#506]
When retrieving an order, the `Order` response from Shopify includes a string property called `gateway` ([source](https://shopify.dev/docs/admin-api/rest/reference/orders/order#index-2020-04)). ShopifySharp does not seem to map this property.

**Comment by drovani** [comment]
Of note, the `gateway` property has been marked as deprecated.
This information now comes from the [Transaction](https://github.com/nozzlegear/ShopifySharp/blob/ad93fdb05975ab9c8e1d789dea690c5d2f14f198/ShopifySharp/Entities/Transaction.cs#L45) object.

**Comment by johndowns** [comment]
Fair enough! I'll close this request in that case. Thanks.
