### ISSUE TITLE
ShopifyAuthorizationService.BuildAuthorizationUrl should have a state parameter

### ISSUE THREAD

**Issue by ernestogutierrez** [nozzlegear/ShopifySharp#51]
The Shopify documentation (https://help.shopify.com/api/guides/authentication/oauth STEP 2) says that there is a parameter that can be added to the url so the app can generate a random number and verify that number later when the user returns with the access token.  The BuildAuthorizationUrl method should have that parameter as an option so developers can use that security mechanism.

The documentation says: 

> To show the prompt, redirect the user to this URL:
> 
> https://{shop}.myshopify.com/admin/oauth/authorize?client_id={api_key}&scope={scopes}&redirect_uri={redirect_uri}&state={nonce}
...

> {nonce} - a randomly selected value provided by your application, which is unique for each authorization request. During the OAuth callback phase, your application must check that this value matches the one you provided during authorization. This mechanism is important for the security of your application.

**Comment by nozzlegear** [comment]
Thanks Ernesto! This should be pretty quick, I'll make sure it gets implemented and pushed to Nuget over the weekend.

**Comment by nozzlegear** [comment]
The state parameter is now available on Nuget with ShopifySharp v2.0.3. Thanks for reporting it!

**Comment by ernestogutierrez** [comment]
Thank you.
