### ISSUE TITLE
Create a order have error in Order_Tests.cs

### ISSUE THREAD

**Issue by yinghualuowu** [nozzlegear/ShopifySharp#511]
`System.NullReferenceException:“Object reference not set to an instance of an object.”`
rootElement is `order`,but rawResult is `orders`. Finally, the order was not created....
![image](https://user-images.githubusercontent.com/22371568/81579686-0808b580-93df-11ea-84f5-b2f290fc6bf9.png)

**Comment by nozzlegear** [comment]
Which version of ShopifySharp are you using here?

**Comment by yinghualuowu** [comment]
the version is 5.1.0.  also tried to create products,It gets the same error.
`getOrder`,`getProduct`  without any problems.
 API permissions 

![image](https://user-images.githubusercontent.com/22371568/81590583-984df700-93ed-11ea-9e1b-0adb075fd0b2.png)

**Comment by nozzlegear** [comment]
Thanks! Just so I'm clear, you're trying to run the order test suite from this repo and it's giving you this error? Or are you seeing this in production?

**Comment by yinghualuowu** [comment]
In my WPF production.Actually, I want to use `FulfillmentService` and `ProductVariantService`.Unfortunately, it can't work. So i run the order test suite,and then found this exception。。

**Comment by yinghualuowu** [comment]
I found the reason,` MyShopifyUrl` should written `https://xxxx.myshopify.com`,instead of `https://xxxx.com`.
maybe I need to be more careful......

**Comment by nozzlegear** [comment]
Ah interesting! I don't think I've run into that before, but I'm glad you got it working!
