### ISSUE TITLE
Extend Article object to have a URL field

### ISSUE THREAD

**Issue by max-carroll** [nozzlegear/ShopifySharp#513]
According to the [documentation ](https://shopify.dev/docs/storefront-api/reference/object/article?api[version]=2020-04) Articles have a Url field, however this is not exposed on the Article object, when creating an article it is useful to know where it has been created.

Has this been left out for a reason? I can create a PR and add some of the missing fields if you like?

**Comment by nozzlegear** [comment]
Hey! It looks like you're looking at the wrong Articles documentation. The one you've linked is for the storefront API, not the REST API that ShopifySharp is using. It's kind of confusing but Shopify has three different APIs (REST, Graph, Storefront), and they objects don't match up one-to-one. 

[According to their documentation](https://shopify.dev/docs/admin-api/rest/reference/online-store/article?api[version]=2020-04), the Article object for the REST API does not have a URL field unfortunately.
