### ISSUE TITLE
Checkout Get from a token - is it possible?

### ISSUE THREAD

**Issue by kjlibsol** [nozzlegear/ShopifySharp#516]
First: Thank you very much for the work on ShopifySharp! 

Using the storefront API, you can get the cart of a user - and do things like adding, removing etc. Works great in javascript in the browser.

The user has a local token/reference, that is held in localstorage. 

I want to list the contents of the cart using serverside code.

Is there a way to use that user checkout Id/token and then using ShopifySharp get the checkout/cart before the user completes the checkout? 

As far as I can read from the documentation, we can only access it once the user has initiated a real checkout (ie. entered address) - so I think the answer is no - but I just want to make sure before I dive into doing things with javascript, that I would much prefer doing with C#... ;)

If I try the below code with a token....:

```
string domain = _configuration["ShopifyDomain"];
string accessToken = _configuration["ShopifyAccessToken"];
var svc = new CheckoutService(domain, accessToken);
Checkout checkout = await svc.GetAsync(token);
```

..I get an error. 

> ShopifyException: (403 Forbidden) [API] This action requires merchant approval for read_checkouts scope.

And it does not seem to be possible to add this scope to a private app...

**Comment by nozzlegear** [comment]
Hey! Sorry it took so long for me to get back to you, things have been crazy with the whole pandemic thing. So if I understand correctly, you want to list the contents of a Shopify customer's cart? As far as I know, doing this isn't actually possible with the REST API, although it would be really nice if it was!

The checkouts API itself is sort of confusing. I haven't personally used it, but I believe it's for the storefront API, which is only intended for those who use Shopify as a backend and build their own custom storefront. It wouldn't be enabled on most stores, unless I'm mistaken.

**Comment by kjlibsol** [comment]
Building a custom frontend is actually exactly what I'm doing, including using the checkout api from storefront in js. I don't think it's possible from any other api, so i think we can close this. 🙂

**Comment by nozzlegear** [comment]
Oh, interesting! I've wanted to dig into that custom storefront stuff myself but just haven't had a chance yet. Good luck!
