### ISSUE TITLE
OrderService  ListAsync and CountAsync Get Counts Not Same

### ISSUE THREAD

**Issue by fleeghost** [nozzlegear/ShopifySharp#520]
var service = new OrderService(store.StoreName, store.AccessToken);
var orders = await service.ListAsync();
var orderCount = await service.CountAsync();

Why orders.Item.Count not same as orderCount ?

**Comment by nozzlegear** [comment]
Hey! The list method can only return up to 250 items in one call, and only returns 50 by default. This is not a design choice on ShopifySharp's part, it's the way the Shopify API works. The count method on the other hand will count all of the orders on the shop. If you want to list all of the orders, you need to walk through each list page until you reach the end:

```cs
var allOrders = new List<Order>();
var service = new OrderService(domain, accessToken);
var list = await service.ListAsync(new OrderListFilter 
{ 
    Limit = 250 
});

while (true)
{
    allOrders.AddRange(list.Items);

    if (!list.HasNextPage)
    {
        break;
    }

    list = await service.ListAsync(list.GetNextPageFilter());
}
```

**Comment by fleeghost** [comment]
but  my apps is not be approved now ,I find my allOrders count is 264, but I get count is 4 by ListAsync method , And these four records  Test are True ，why？？？

**Comment by clement911** [comment]
You probably need to a filter status = any as if I recall by default Shopify only return open orders.
