### ISSUE TITLE
storefront api

### ISSUE THREAD

**Issue by zafar170017** [nozzlegear/ShopifySharp#525]
kindly please tell me how i used storefront api in private app.

its urgent please tell me 
how we storefront api in shopify sharp

**Comment by nozzlegear** [comment]
Hi Zafar, unless I'm misunderstanding you, you cannot use the storefront API with ShopifySharp, because the storefront API cannot be used via the REST API. As far as I understand it, the Storefront API is _only_ for building custom Shopify storefronts.

**Comment by zafar170017** [comment]
kindly tell me how change the shippment price in private app??
