### ISSUE TITLE
checkout scope in private app

### ISSUE THREAD

**Issue by zafar170017** [nozzlegear/ShopifySharp#526]
kindly tell how i get checkout scope in private app

**Comment by nozzlegear** [comment]
Hi Zafar, can you link to the checkout API endpoint you're trying to use? There are several checkout APIs, and the one you want may not be available for the REST API. In particular, if you're looking to get access to read/modify customer carts on the storefront, you cannot do this via the REST API.

**Comment by zafar170017** [comment]
can you tell me how i access checkout scope in private app??
