### ISSUE TITLE
ShopifyShop object missing a properties

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#53]
I don't see the "force_ssl" or "source" property inside the ShopifyShop object. May it is missing some more..

thanks
ishtiaque

**Comment by nozzlegear** [comment]
Thanks for the report! Looks like these are some new properties that were added after I had written the ShopifyShop object. I'll make sure they get in there.

**Comment by cafeasp** [comment]
Hello,
Great project. One question.  The ShopifyCustomer Object does not have the id.  Can you add it?

Thanks

**Comment by cafeasp** [comment]
Please disregard my request. I do see the id but it's coming null for some reason. I added a CustomerId pro as string since the id is so big and it work.

**Comment by nozzlegear** [comment]
Glad to hear you got it working, @cafeasp. If possible, could you post one of those CustomerIds? I'd like to investigate this a little further just to see if there's a change I'll need to make to the library.

**Comment by cafeasp** [comment]
Hi,
All I did was add this to the ShopifyCustomer class and now the value is good.

        [JsonProperty("id")]
        public long CustomerId { get; set; }

**Comment by nozzlegear** [comment]
Thanks for clearing that up, @cafeasp. I misunderstood you the first time and thought you had converted a property to a string instead. Sorry for the confusion!

**Comment by nozzlegear** [comment]
Thanks again for opening this issue, @ishahrier. I've added the `ForceSSL` property to the `ShopifyShop` class and it should be available on Nuget with v2.1.0. 

Just as a side note, it looks like the `Source` property was already there, but there's no documentation on it and I can't get it to actually return a value on any of my stores. Not sure what that prop is for.

**Comment by nozzlegear** [comment]
Looks like the `ForceSSL` property I added last week wasn't de/serializing properly. I've just pushed a fix for it to Nuget in 2.1.1 and added a test specifically for this prop.
