### ISSUE TITLE
IsAuthenticRequest is not working when the query string contains array parameters and the value has only one element.

### ISSUE THREAD

**Issue by mohamedhussain** [nozzlegear/ShopifySharp#530]
This is related to #437 

When the query string contains array parameters like ids[] and the value for those parameter has only one value then the IsAuthenticRequest fails to generate the correct HMAC. 

Sample query

GET /xxxx/xxxxxx?hmac=b63470b593885527be43c4ebdbfa2d66d9862ea69208d292ea4cafaeb7911357&ids[]=2544739451040&locale=en&session=cf0f2004fb006d2ec33810114105416a5d34172ad831185e31e8b136a86232f1&shop=xxxxx.myshopify.com&timestamp=1593490902
#
I have modified the EncodeQuery method to fix this issue

private static string PrepareQuerystring(IEnumerable<KeyValuePair<string, StringValues>> querystring, string joinWith)
{
	var kvps = querystring.Select(kvp => new
	{
		Key = EncodeQuery(kvp.Key, kvp.Key, true),
		Value = EncodeQuery(kvp.Key, kvp.Value, false)
	})
		.Where(kvp => kvp.Key != "signature" && kvp.Key != "hmac")
		.OrderBy(kvp => kvp.Key, StringComparer.Ordinal)
		.Select(kvp => $"{kvp.Key}={kvp.Value}");

	return string.Join(joinWith, kvps);
}

private static string EncodeQuery(string key, StringValues values, bool isKey)
{
	//array parameters are handled differently: see https://community.shopify.com/c/Shopify-APIs-SDKs/HMAC-calculation-vs-ids-arrays/td-p/261154

	string s = "";
	if (!isKey && key.Contains("[]"))
	{
		s = '[' + string.Join(", ", values.Select(v => '"' + v + '"')) + ']';
	}
	else
		s = values.Count <= 1 ? values.FirstOrDefault() : '[' + string.Join(", ", values.Select(v => '"' + v + '"')) + ']';

	if (string.IsNullOrEmpty(s))
	{
		return "";
	}

	//Important: Replace % before replacing &. Else second replace will replace those %25s.
	string output = (s.Replace("%", "%25").Replace("&", "%26")) ?? "";

	if (isKey)
	{
		output = output.Replace("=", "%3D").Replace("[]", "");
	}

	return output;
}

**Comment by clement911** [comment]
Thank you @mohamedhussain , I can reproduce the issue.

**Comment by nozzlegear** [comment]
Thanks for letting us know about this @mohamedhussain, and thanks for the pull request @clement911! I can't remember, if I want to reproduce this, how do I get the ids array? Is that when we use per-user authentication?

**Comment by clement911** [comment]
No, it's when you choose multiple products (or orders, customers) and then choose one of the bulk actions.
Any app with app links for bulk actions can be called and the ids of the objects are passed on the url.

For example:
![image](https://user-images.githubusercontent.com/3426504/86141879-d8c71880-baf2-11ea-85af-5f8f5a0b1829.png)

**Comment by nozzlegear** [comment]
Oh woops, thank you! I misread and thought this was for a different method. I'm familiar with the bulk actions thing, I'll try to get some real values to put into the unit tests.
