### ISSUE TITLE
shopify product feed

### ISSUE THREAD

**Issue by zafar170017** [nozzlegear/ShopifySharp#534]
How i make product feed using shopify sharp

**Comment by nozzlegear** [comment]
Can you explain what you mean by product feed?

**Comment by zafar170017** [comment]
https://www.shopify.com/blog/google-merchant-feed#:~:text=Your%20data%20feed%20is%20simply,Google%20can%20read%20and%20understand.&text=Google%20crawls%20your%20feed%20and,for%20a%20particular%20search%20query.

**Comment by zafar170017** [comment]
kindly tell the how i create product feed url. to publish my product in facebook channel

**Comment by nozzlegear** [comment]
Unfortunately I can't tell you how to do that as I've never done it before, and it doesn't seem to be related to ShopifySharp itself. You can always open a thread on Shopify's own forums to ask, where you might find some people who have done this before!
