### ISSUE TITLE
Collects is null?

### ISSUE THREAD

**Issue by joesgedev** [nozzlegear/ShopifySharp#536]
Hi, I'm trying to retrieve the products in my collection using 

```
var service = new CustomCollectionService(shopify.MyShopifyUrl, shopify.PrivateAppPassword);
var collection = await service.GetAsync(tabletCollections[0]);
```

I know that there are two products in this collection as I can visit the admin/collections and see that there are products within this collection.

Problem is (maybe not a problem if I don't properly understand what Collects are).. Collects are null even though products exist in the collection. 

If Collects is not what I'm looking for (to see the products in a collection) what would be the alternative? Other parts of `collection` seem to be correct such as Title, handle, bodyhtml, etc... It's just Collects being empty and no other field for products.

![image](https://user-images.githubusercontent.com/45777570/86844880-8db28580-c05d-11ea-8308-b4a1347dbc3c.png)
As you can see within this collection there are two products.

![image](https://i.imgur.com/DmUp4di.png)
When debugging this is what my collection variable returns. Notice Collects being empty.

Products and Collection do also show on the Online Store.

Thank you.

**Comment by foxandrewj** [comment]
When retrieving a collection the Collects will always be null in my experience (unless there is a trick I am unaware of)
You will need to make a second call to either the CollectService.ListAsync to get the collects, or you can make a call to the ProductService.ListAsync to get the products, and provide the collection Id you already have.

The property exists because it can be used when sending updates.
The Collection object is being used both when pulling down data or sending updates such as in the following:
            await collectionService.UpdateAsync(collection.Id.Value, 
                new CustomCollection()
                {
                    Id = collection.Id,
                    Collects = collects
                });

**Comment by joesgedev** [comment]
> When retrieving a collection the Collects will always be null in my experience (unless there is a trick I am unaware of)
> You will need to make a second call to either the CollectService.ListAsync to get the collects, or you can make a call to the ProductService.ListAsync to get the products, and provide the collection Id you already have.
> 
> The property exists because it can be used when sending updates.
> The Collection object is being used both when pulling down data or sending updates such as in the following:
> await collectionService.UpdateAsync(collection.Id.Value,
> new CustomCollection()
> {
> Id = collection.Id,
> Collects = collects
> });

Thank you for responding, I'll try using your suggested idea of making a call to the ProductService.ListAsync. I appreciate it!
