### ISSUE TITLE
The Collect resource no longer works with smart collections (1st Oct 2020 deadline)

### ISSUE THREAD

**Issue by HoomanBahreini** [nozzlegear/ShopifySharp#539]
Hi

I am getting the following warning: 

> The Collect resource no longer works with smart collections. Migrate your app to use the new Collections endpoints.

![image](https://user-images.githubusercontent.com/32623734/87636223-89404800-c794-11ea-910c-55bffde3f96a.png)

As the deadline is just 2.5 months away, I wanted to check if you have a time frame to migrate this? 

Thanks

**Comment by nozzlegear** [comment]
Hey! I'd love to get this finished as soon as possible, although I don't personally use the collect or smart collection endpoints so I need to review the docs to see what changes need to be made. I'll close this in favor of #532 where I'll start documenting all of the changes we need to make for the next API version.
