### ISSUE TITLE
IEnumerable vs List

### ISSUE THREAD

**Issue by dcastroamg** [nozzlegear/ShopifySharp#54]
Hi Joshua,

I think this is an issue/feature request unless I am doing something wrong. We are utilizing ShopifySharp extensively to update our store by syncing with an internal CMS. While writing the sync code, I am finding it cumbersome to work with the properties defined as IEnumerable<T>. To manage and manipulate the property I invariably must do something like this:

var variants = remoteProduct.Variants.ToList();
currentVariant = variants.SingleOrDefault(x => x.Id == currentVariant.Id);
currentVariant.ImageId = image.Id;
remoteProduct.Variants = variants;

or

var images = remoteProduct.Images.ToList();
images.Add(newShopifyProductImage);
remoteProduct.Images = images;

Is there some inherent architectural reason you chose to go with IEnumerable<T>? Does it make sense to possibly change them to List<T> since at the end of the day we truly are simply manipulating simple JSON lists?

Thank you for your work on ShopifySharp so far!

Dan

**Comment by nozzlegear** [comment]
Thanks for the kind words, Dan! I feel your pain on having to call `.ToList()` constantly, I end up doing that a lot in my own apps and it can get tedious pretty quick. The only reason I prefer to return IEnumerables is to make it as easy as possible for the end users to turn it into whatever they need. In most cases that will be a list like we're used to, but some devs might need to turn it into an IQueryable, a Collection, or some other custom implementation. 

There are some (small) perf improvements when using IEnumerables, though I doubt many Shopify devs will run into that. The biggest advantage is just returning the least-derived interface possible so we can turn it into whatever we need as easily as possible.

That said, I would bet that most of us using this lib are calling `.ToList()` on the results, so I would definitely be open to converting the results to a list in the future. 

It would have to wait for another major release, e.g. 3.0, so if anybody wants to chime in either for or against converting everything to a List between now and then, please do.
