### ISSUE TITLE
Reorder Option Values based on custom comparer 

### ISSUE THREAD

**Issue by danteotero** [nozzlegear/ShopifySharp#540]
Hello community,

We're trying to sort some of the options values using a custom comparer. e.g. we have values for options like Sizes that won't work with a default alphabetical sort (Youth S, Youth M, Adult S, Adult M, XL, 4XL as an example). To achieve this, we have the following custom IComparer:

` 
class SizeComparer : IComparer<string>
        {
            static List<string> OrderedFiles = new List<string> { "Youth XS", "Youth S", "Youth M", "Youth L", "Youth XL", "XS", "S", "S/M", "M", "L", "XL", "L/XL", "2XL", "2XL/3XL", "3XL", "4XL","4XL/5XL",  "4XL/Goalie Cut", "5XL", "6XL" };

            public int Compare(string x, string y)
            {
                int xi = OrderedFiles.IndexOf(x);
                int yi = OrderedFiles.IndexOf(y);

                if (xi > yi)
                    return 1;

                if (xi < yi)
                    return -1;

                return 0;
            }
        }`

And when we try to analyze products and update the order of the values for Size with the following code, nothing happens and no exception is thrown. 

`
if (opt.Name == "Size")
                            {
                                
                                var orderedList = new List<String>((List<string>)opt.Values);
                                orderedList.Sort(new SizeComparer()); //Create a copy of the list and sort it
                                if (!orderedList.SequenceEqual((List<string>)opt.Values)) //if the order of the clone doesn't match the order of the actual list, needs updating
                                {
                                    Console.WriteLine("\tReordering Sizes for: " + p.Handle + "  " + p.Title);
                                    ((List<string>)opt.Values).Sort(new SizeComparer());
                                    needsUpdating = true;
                                }

                            }
`

Do you have a working example of manipulating the values of Option1 an Option2 programatically?

Thanks,

D

**Comment by foxandrewj** [comment]
[This post](https://community.shopify.com/c/Shopify-APIs-SDKs/Reorder-options-variants/td-p/473146) shows how you can update the order of the variants and options with an update to the product. 

In ShopifySharp you can build and send this request like this:
```
            var p = new Product()
            {
                Id = theProduct.id,
                Variants = new List<ProductVariant>() 
                { 
                    new ProductVariant()
                    {
                        Option1 = "S"
                    },
                    new ProductVariant()
                    {
                        Option1 = "M"
                    },

                },
                Options = new List<ProductOption>()
                {
                    new ProductOption()
                    {
                        Name = "Size",
                        Values = new List<string>()
                        {
                            "S",
                            "M"
                        }
                    }
                }

            };
            await productService.UpdateAsync(theProduct.id, p);
```

**Comment by danteotero** [comment]
So will I have to reorder Options AND reorder the variants as well? I guess we were assuming that reordering the options was enough (similar to what the Shopify UI implies)

Thanks!
