### ISSUE TITLE
Adding a new product throws write_products scope exception

### ISSUE THREAD

**Issue by PtrStruct** [nozzlegear/ShopifySharp#543]
```
Project: ASP.NET MVC .NET Core
Library Version: 5.3.0
```

I started off by creating a public app on here [https://partners.shopify.com](https://partners.shopify.com)
And then I set everything up, I managed to generate the access token etc.

And now I'm trying to add a new product but I keep getting this exception
**This action requires merchant approval for write_products scope**

And I'm not sure why, could someone clear this up for me?

```
var service = new ProductService(usersMyShopifyUrl, accessToken);

var product = new Product()
{
    Title = "Test Product Walter",
    Vendor = "Burton",
    BodyHtml = "<strong>Good snowboard!</strong>",
    ProductType = "Snowboard",
    Images = new List<ProductImage>
    {
        new ProductImage
        {
            Attachment = "R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
        }
    },
};


product = await service.CreateAsync(product);
product = await service.CreateAsync(product, new ProductCreateOptions() { Published = false });
```

**Comment by nozzlegear** [comment]
Hey! When you create an OAuth install URL and send the merchant to it, you can ask for a list of permissions that your app will need. Much of the API is off limits unless you specifically ask for the permissions. In this case, you're trying to create a product but did not ask the merchant to grant you the `write_products` permission. 

This should be done when you're asking them to install your app, but if your required permissions ever change you can ask them to accept the new ones by creating another OAuth install request and sending them to the URL again:

```cs
var requiredPermissions = new List<string>
{
	"write_products",
	"read_products"
};
var userShopifyUrl = "users-shopify-url.myshopify.com";
var apiKey = "your-public-shopify-api-key";
var redirectUrl = "some-url-on-your-server-to-finish-oauth-installation.com"
var oauthUrl = AuthorizationService.BuildAuthorizationUrl(permissions, userShopifyUrl, apiKey, redirectUrl);
);

// Send the user to accept the installation/upated permissions
return Redirect(oauthUrl.ToString());
```

**Comment by nozzlegear** [comment]
Here's the list of permissions you can ask for: https://shopify.dev/docs/admin-api/access-scopes

**Comment by PtrStruct** [comment]
Hi! Thank you for the quick answer!
That's strange because when I click my install button, this executes

```
public IActionResult Install()
{

    //string urlFromUser = "https://plsdontbreak.myshopify.com";
    //bool isValidDomain = await AuthorizationService.IsValidShopDomainAsync(urlFromUser);

    // A URL to redirect the user to after they've confirmed app installation.
    // This URL is required, and must be listed in your app's settings in your Shopify app dashboard.
    // It's case-sensitive too!
    string redirectUrl = "https://localhost:44373/";

    //An array of the Shopify access scopes your application needs to run.
    var scopes = new List<AuthorizationScope>()
    {
         AuthorizationScope.ReadCustomers,
         AuthorizationScope.WriteCustomers
    };

    //All AuthorizationService methods are static.
    string authUrl = AuthorizationService.BuildAuthorizationUrl(scopes, usersMyShopifyUrl, apiKey, redirectUrl).ToString();

    return Redirect(authUrl);
}
```

Does it have to be set with a list?

**Comment by nozzlegear** [comment]
What you have there should work, but you're only asking for permission to read and write customers. If you want to read and write products, you'll need to add those permissions to your `scopes` list too!

**Comment by PtrStruct** [comment]
Oh! I see now! I'll try that as soon as I get back from work, thank you! :-)
