### ISSUE TITLE
getting all products

### ISSUE THREAD

**Issue by zafar170017** [nozzlegear/ShopifySharp#545]
var service = new OrderService(domain, accessToken);
var allProducts= new List<Product>();
var page = await service.ListAsync(new ProductrListFilter { Limit = 250 });

while (true)
{
    allProduct.AddRange(page.Items);

    if (! list.HasNextPage)
    {
        break;
    }

    page = await service.ListAsync(list.GetNextPageFilter());
}

whar is !list.HasNextPage

it is giving me error because it !list variable is not created

kindly tell me what list.Has Next page anf List.GetNextPageFilter

**Comment by nozzlegear** [comment]
You need to upgrade ShopifySharp to version 5.0. Please don't open duplicate issues to ask the same question, I can answer this in #544
