### ISSUE TITLE
Adding a product variant title property doesnt change the title

### ISSUE THREAD

**Issue by PtrStruct** [nozzlegear/ShopifySharp#546]
```
Project: ASP.NET MVC .NET Core
Library Version: 5.3.0
```
I'm trying to create a test product with color variables like this.
```
var product = new Product()
{
    Title = "Test Product Walter",
    Id = 100,
    Vendor = "Burton",
    BodyHtml = "<strong>Good snowboard!</strong>",
    ProductType = "Snowboard",
    Images = images,
    
    Variants = new List<ProductVariant>
    {
        new ProductVariant
        {
            Title = "Color",
            Option1 = "Black",
        },
        new ProductVariant
        {
            Title = "Color",
            Option1 = "Green",
        },
    }
};


product = await service.CreateAsync(product);
```
But when I post the product it looks like this.
[https://i.imgur.com/LWd8t9C.png](https://i.imgur.com/LWd8t9C.png)
[https://i.imgur.com/K5IQIqI.png](https://i.imgur.com/K5IQIqI.png)

Am I not using the title properly correctly?

**Comment by nozzlegear** [comment]
If I remember correctly, the `Title` property on a variant is auto-generated by Shopify and will be ignored when you create/update variants. I think there's another property on the parent `Product` object itself that controls the name of those options. It's a comma separated string if I'm thinking of the right thing. I'm positive we've had questions and solutions for this very problem somewhere in this repo, but I'm not at my computer right now and can't search for them easily.

**Comment by PtrStruct** [comment]
Found it! I'll go ahead and create a PR updating the docs a bit! Thank you for such fast answers! Such an MVP!
