### ISSUE TITLE
(400 Bad Request) Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API."

### ISSUE THREAD

**Issue by zhorakiev** [nozzlegear/ShopifySharp#557]
newvar = await VariantService.UpdateAsync((long)pv.Id, new ProductVariant()
                    {
                        Price = pprice,
                        CompareAtPrice = pcompareatprice,
                        **InventoryQuantity = lVariantInventoryQuantity**
                    });
(400 Bad Request) Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API."

**Comment by nozzlegear** [comment]
You need to use the inventory levels API to change quantities, the `InventoryQuantity` property no longer changes it. You can use ShopifySharp's `InventoryLevelService`, and you'll need an inventory location to do that which you can get with the `InventoryLocationService`.

**Comment by zhorakiev** [comment]
Is there a C# example?

**Comment by zhorakiev** [comment]
Here is the piece of code I was looking for:

 private static async Task<bool> TurnOffIfVariantOutOfStock(ProductVariant pv)
        {
            try
            {
               

                bool bOUtofStock = false;

                ProductService ProdServ = new ProductService(StaticVars.ShopifyURL, StaticVars.ShopifyAccessToken);


                List<ShopifyProd> lsproducts = LISTOFPRODUCTS;

                foreach (ShopifyProd pr in lsproducts)
                {
                    foreach (ShopifyProdVariant prv in pr.VARIANTS)
                    {

                        if (OUT OF STOCK)  
                        {
                            
                                bOUtofStock = true;
                                break;
                           
                        }
                    }
                }


                if (bOUtofStock)
                {
                    
                InventoryLevelAdjust adj = new InventoryLevelAdjust();
               
                LocationService ls = new LocationService(StaticVars.ShopifyURL, StaticVars.ShopifyAccessToken);
                List<Location> locations = (List<Location>)await ls.ListAsync();

                InventoryLevelService ilevserv;

                foreach (Location loc in locations)
                {
                  
                    adj.InventoryItemId = pv.InventoryItemId;
                    adj.LocationId = (long)loc.Id;
                    adj.AvailableAdjustment = -1;

                    ilevserv = new InventoryLevelService(StaticVars.ShopifyURL, StaticVars.ShopifyAccessToken);
                    await ilevserv.AdjustAsync(adj);

                }

                }


                return bOUtofStock;
            }               
        
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
}
