### ISSUE TITLE
get null in the asset value property

### ISSUE THREAD

**Issue by zafar170017** [nozzlegear/ShopifySharp#559]
var assets = await service.ListAsync(themeId);

i want to get the  content of the assets but i got null value in that asset kindly tell me the solutio

**Comment by nozzlegear** [comment]
Sorry, I'm not at my machine right now so I can't easily check this, but I think the list method will never return the content of assets by Shopify's design. You need to find the key of an asset, and then use the service to get the asset:

```cs
var assets = await service.ListAsync(themeId);
var asset = await service.GetAsync(assets.First().Key);
```

Something like that should work.
