### ISSUE TITLE
System.Net.Http.HttpRequestException: 

### ISSUE THREAD

**Issue by waynevanrooyen1971** [nozzlegear/ShopifySharp#561]
Hi from an an action inside another framework called XAF in the web version of my app when calling
var shopifyproductslist = await productservice.ListAsync(new ProductListFilter { Limit = 100 });

I get this error
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=An error occurred while sending the request.
  
Inner Exception 1:
WebException: The request was aborted: Could not create SSL/TLS secure channel.

The exact same code in the windows version of app works fine, little lost here as to why

**Comment by nozzlegear** [comment]
Hey, can you give some more details about this exception? Are you using .NET Framework or .NET Core? My first guess is that you're using .NET Framework which does not support modern TLS by default, and to fix it you'd need to add this to your _global.asax.cs_ or _Startup.cs_ file:

```cs
System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

**Comment by waynevanrooyen1971** [comment]
Hi joshua
Was .net standard and ur solution was the exact fix i found on the web so i am all good shot. Much appreciated.
I am busy trying to use xaf framework with yours to make custom apps but my web knowledge is so limited i previously did winforms. If u interested in a consult on hie to achieve what i want to pull off drop me a mail clearly fees can be discussed
Cheers wayne

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nozzlegear** [comment]
Thanks Wayne, glad it's working! I do consulting for Shopify apps as my full time job, but unfortunately I'm booked very full at the moment. Happy to talk about it in the future when my schedule clears up!
