### ISSUE TITLE
Failing in using ShopifySharp in .Net core 3.1

### ISSUE THREAD

**Issue by xiaoxiaoji** [nozzlegear/ShopifySharp#563]
I'm using vscode to build my shopify private app with dotnet core 3.1 but when I call a shopify endpoint with shopifysharp, I got an error named unknow hosts. I tried the same code in dotnet Framework 4.7.2 and it's working fine.  Does shopifysharp supporting dotnet core 3.1 fine?

**Comment by nozzlegear** [comment]
Hey! The package does indeed support .NET Core 3.1, I use it in several projects. I'm not sure about the unknown hosts problem, can you post the full exception and stack trace?
