### ISSUE TITLE
I think by migrating CollectService to 2020-07, Shopify would stop complaining about using this API

### ISSUE THREAD

**Issue by HoomanBahreini** [nozzlegear/ShopifySharp#570]
I have updated my ShopifySharp to version 5.5, but Shopify is showing my the following warning:

![image](https://user-images.githubusercontent.com/32623734/92315448-c6f57a80-f039-11ea-9712-3699bf7d6153.png)

I am using Collect API endpoint to get information about CustomCollections (this is valid request and I understand that SmartCollections won't be retrieved using Collect API)

I think if you migrate the Collect API  to version 2020-07 Shopify might stop showing this warning?

````
namespace ShopifySharp
{
    /// <summary>
    /// A service for manipulating mapping between Shopify products and collections.
    /// </summary>
    public class CollectService : ShopifyService
    {
        public override string APIVersion => "2020-07";
````

**Comment by clement911** [comment]
Yes.
There will be a release shortly with the entire lib pinned to 2020-07.
Waiting on https://github.com/nozzlegear/ShopifySharp/pull/568 to be approved/merged.

**Comment by nozzlegear** [comment]
ShopifySharp v5.6.0 on nuget now targets 2020-07! 

--
Josh Harms

**Comment by HoomanBahreini** [comment]
Awesome, thanks
