### ISSUE TITLE
Unable to reset Shopify API compare at price

### ISSUE THREAD

**Issue by aswanevelder** [nozzlegear/ShopifySharp#577]
I used to be able to set compare_at_price to null after a product was on sale but now I get an error

Example:

Price was: 1000, Compare at 1200

I want to reset it the Price to 1200, with compare at 0.

(422 Unprocessable Entity) compare_at_price: Compare at price needs to be higher than Price

I can neither set it to 0, so how will I disable the compare_at_price to 0 or null or remove it?

```
var variant = await productVariantService.UpdateAsync(product.VariantId.Value, new ProductVariant()
{
      Price = updatePrice,
      CompareAtPrice = updateCompareAtPrice
});
```

**Comment by ThatBrianK** [comment]
I am also experiencing this issue. I've been trying to modify the source code by changing the default value handling to
DefaultValueHandling = DefaultValueHandling.Include

however it still does not include the default value of null.
I don't understand much about serialization but in debugging, I can't even see the raw text being sent

**Comment by ThatBrianK** [comment]
someone coded a workaround here:
https://github.com/nozzlegear/ShopifySharp/issues/373

But I can't get this to compile even.
If anyone can assist that would be amazing!

**Comment by rohanp1903** [comment]
This is based of [#373](https://github.com/nozzlegear/ShopifySharp/issues/373) 

public class ProductVariantServiceEx : ProductVariantService
    {
        public ProductVariantServiceEx(string myShopifyUrl, string shopAccessToken) : base(myShopifyUrl, shopAccessToken) { }

        public virtual async Task<ProductVariant> UpdateAsync(long productVariantId, ProductVariant variant)
        {
            try
            {
                // BUGFIX: If variant.CompareAtPrice is set to 0, then force it to empty
                string json = new JsonContent(new { variant }).ReadAsStringAsync().Result;

                if (json.Contains("\"compare_at_price\":0.00}")
                    || json.Contains("\"compare_at_price\":0.00,"))
                {
                    json = json.Replace("\"compare_at_price\":0.00", "\"compare_at_price\":\"\"");

                    var req = PrepareRequest($"variants/{productVariantId}.json");
                    using var content = new StringContent(json, Encoding.UTF8, "application/json");
                    await Task.Run(() => Thread.Sleep(500));
                    return (await ExecuteRequestAsync<ProductVariant>(req, HttpMethod.Put, default, content, "variant")
                        .ConfigureAwait(false)).Result;
                }

                return await base.UpdateAsync(productVariantId, variant);
            }
            catch (Exception ex)
            {
                return null;
            }
        }
    }

**Comment by ThatBrianK** [comment]
thanks rohanp1903! that was very helpful! in my case the prices weren't 0.00 but 0.0. I modified to handle 0, 0.0, and 0.00:

`
public class ProductVariantServiceEx : ProductVariantService
    {
        public ProductVariantServiceEx(string myShopifyUrl, string shopAccessToken) : base(myShopifyUrl, shopAccessToken) { }
        public virtual async Task<ProductVariant> UpdateAsync(long productVariantId, ProductVariant variant)
        {
            try
            {
                // BUGFIX: If variant.CompareAtPrice is set to 0, then force it to empty
                string json = new JsonContent(new { variant }).ReadAsStringAsync().Result;
                bool bReplace = false;
                if (json.Contains("\"compare_at_price\":0.00}") || json.Contains("\"compare_at_price\":0.00,"))
                {
                    json = json.Replace("\"compare_at_price\":0.00", "\"compare_at_price\":\"\"");
                    bReplace = true;
                }
                else if (json.Contains("\"compare_at_price\":0.0}") || json.Contains("\"compare_at_price\":0.0,"))
                {
                    json = json.Replace("\"compare_at_price\":0.0", "\"compare_at_price\":\"\"");
                    bReplace = true;
                }
                else if (json.Contains("\"compare_at_price\":0}") || json.Contains("\"compare_at_price\":0"))
                {
                    json = json.Replace("\"compare_at_price\":0", "\"compare_at_price\":\"\"");
                    bReplace = true;
                }
                if (bReplace)
                {
                    var req = PrepareRequest($"variants/{productVariantId}.json");
                    using var content = new StringContent(json, Encoding.UTF8, "application/json");
                    //await Task.Run(() => Thread.Sleep(500));
                    return (await ExecuteRequestAsync<ProductVariant>(req, HttpMethod.Put, default, content, "variant")
                        .ConfigureAwait(false)).Result;
                }
                else 
                    return await base.UpdateAsync(productVariantId, variant);
            }
            catch (Exception ex)
            {
                Exceptions.LogError(ex);
                return null;
            }
        }
    }
`

sorry I don't know why it's not formatting properly

**Comment by ThatBrianK** [comment]
Thanks Rohan!
I had to modify it slightly to work for me since my prices showed up as 0.0 not 0.00 but otherwise perfect.  I tried posting in my modified code but it was not formatting correctly

Brian

**Comment by aswanevelder** [comment]
Thanks guys! Great help!
