### ISSUE TITLE
Investigate supporting .NET Core projects.

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#58]
I haven't had a chance to play around with .NET Core at all yet, but would like to migrate this project to it while still supporting .NET 4.X. I'm planning an update to The Shopify Development Handbook that will use ASP/.NET Core, so this is the perfect time to add support to ShopifySharp. 

From my (currently limited) understanding, we'll need to remove the .csproj (:clap:) and replace it with a project.json file, then add `net451` to the `frameworks` list. Not entirely sure yet, will investigate further.

No timetable for .NET Core support, but it's definitely planned.

Edit: We're currently in the middle of buying a house, which is why development on this issue and #62 has slowed. Rest assured, I'm fully committed to bringing .NET Core support to ShopifySharp!

**Comment by nozzlegear** [comment]
Apparently Microsoft has decided to revert the project.json (😖) and go back to .csproj. Not sure exactly when this will happen, though.

**Comment by nozzlegear** [comment]
[Here's a guide](http://bytefish.de/blog/migrating_a_library_to_dotnetcore/) for migrating a library to .NET Core.

**Comment by dcworldwide** [comment]
Yay! This is going to be huge for my startup :smile:  Please keep this thread up to date with how you progress.

**Comment by dcworldwide** [comment]
@nozzlegear Posted a [bounty](https://www.bountysource.com/issues/35613944-investigate-supporting-net-core-projects) to help kick-start this 😄

**Comment by nozzlegear** [comment]
After tinkering with .NET Core and trying to add support to ShopifySharp, it looks like we won't be able to do so until the RestSharp dependency adds support itself. They're tracking that [right here](https://github.com/restsharp/RestSharp/issues/664).

**Comment by tomeo** [comment]
Would also very much like to see this project gain .NET Core/Standard support. Is RestSharp currently the only dependency that doesn't support .NET Standard? Once the dependencies are sorted the process of converting the project to .NET Standard should be quite easy. Also, as I've seen a previous posted raise concearn I just wanted to say that .NET Standard libs can be used from _both_ .NET Core and .NET Framework - so there is no issue of making sure it still supports .NET Framework.

**Comment by nozzlegear** [comment]
Hey @tomeo, thanks for clarifying that! I haven't used any .NET Standard libs (to my knowledge) yet in a Framework project, so wasn't sure if they'd work together out of the box. 

RestSharp was the only dependency that didn't support dotnet standard, and it's already been replaced with Flurl in the 4.0 branch. I've got a list of issues and features that I'm working through before that branch gets merged in and published, but you can track the progress in the [4.0 pull request](https://github.com/nozzlegear/ShopifySharp/pull/133) and even use the current dotnet standard version by [downloading the artifacts from AppVeyor](https://ci.appveyor.com/project/nozzlegear/shopifysharp/build/artifacts).

**Comment by nozzlegear** [comment]
.NET Core support has been merged into the master branch! I'm going to be publishing it on Nuget by Friday evening.
