### ISSUE TITLE
.Net Core update to Book

### ISSUE THREAD

**Issue by dotnetprofessional** [nozzlegear/ShopifySharp#580]
I'm interested in your book, but not interested in going back in time with .NET development :). I wanted to get an update on when you think the .NET Core version of your book will be available. It seems you've been working on this for over a year, so would be good to get a more concrete timeline, even if that's "Its been too hard so I've decided no to do it anymore", or "I don't have the time to finish it".

Here's the last issue I saw that's relevant:
#417

**Comment by nozzlegear** [comment]
Hey! Within the next couple of weeks I'll be sending out updates to the four included sample applications to everyone who has bought the book. The samples have been updated to use .NET Core and ShopifySharp v5. Once those sample applications are out the full update to the book will follow shortly thereafter, but I can't give a concrete time frame for that -- it honestly depends on how busy I am with client work over the holidays. 

Also note that the free sample guide that comes with signing up for the mailing list at [nozzlegear.com/shopify-development-handbook](https://nozzlegear.com/shopify-development-handbook) has already been updated for .NET Core and ShopifySharp v5. It's more than 100 pages long and covers the most important parts of creating a Shopify app like OAuth, permissions, listing things using their new pagination scheme, etc.

**Comment by garrm** [comment]
Thanks for the reply - so I did sign up back in Aug and the sample is v2. It seems to be all .Net 45 and the API version referenced is:

  <package id="ShopifySharp" version="3.4.4.0" targetFramework="net45" />

So not sure if this was updated after I signed up.

**Comment by nozzlegear** [comment]
Ah, you must have signed up before the free guide was updated then. I put that update out in October I think. If you send me an email at joshua@nozzlegear.com I can send you an updated version of that guide and sample project tomorrow!

**Comment by dotnetprofessional** [comment]
So I emailed but haven't had a response. I suspect my emails are going to your SPAM as I emailed you a few months ago too. I'll email you again now so it will be in at the top of your SPAM folder :) Has same subject as this notification email.
