### ISSUE TITLE
Custom Collection Sort Products by available Stock

### ISSUE THREAD

**Issue by shafaqat309** [nozzlegear/ShopifySharp#585]
I have created a custom collection and want to sort product based on stock available, I can see a UpdateSortOrder method for smart collection but there is no similar method available for custom collection.

Question

- How can I convert existing custom collection to smart collection, so I can sort them by product stock?

- How can I sort custom collection by stock without converting to smart collection?

**Comment by foxandrewj** [comment]
Maybe someone has a more efficient way of doing this,  but here is what I have done.
Note that if you have too may products in your collection you may have to call ListAsync multiple times to get additional pages.

```
            //get the collection
            var collection = await collectionService.FirstOrDefaultAsync(new CustomCollectionListFilter()
            {
                Handle = "new-arrivals"
            });

            //get all the products in the collection
            List<Product> allProducts =
                (await productService.ListAsync(new ProductListFilter() { CollectionId = collection.Id }))
                .ToList();

            //sort them
            allProducts = allProducts.OrderBy...();

            //get all the collects
            List<Collect> allCollects = (await collectService.ListAsync(new CollectListFilter() { CollectionId = collection.Id })).ToList();

            //create the collects for the products with their new position
            var collects = allProducts.Select((Product product, int index) =>
            {
                return new Collect()
                {
                    Id = allCollects.Single(collect => collect.ProductId == product.Id).Id,
                    Position = index
                };
            });

            //push the new collects order
            await collectionService.UpdateAsync(collection.Id.Value, 
                new CustomCollection()
                {
                    Id = collection.Id,
                    Collects = collects
                });
```

**Comment by shafaqat309** [comment]
I am getting an exception
One or more errors occurred. ((422 Unprocessable Entity) product_id']: already exists in this collection (and 200 other errors))

Here is my code

`public List<Collect> GetCollectionCollects(long collectionID)
        {
            List<Collect> collectionProducts = new List<Collect>();
            ListResult<Collect> batch = service.ListAsync(new CollectListFilter() { CollectionId = collectionID, Limit = 250 }).Result;
            while (true)
            {
                collectionProducts.AddRange(batch.Items);
                if (!batch.HasNextPage)
                {
                    break;
                }
                batch = service.ListAsync(batch.GetNextPageFilter()).Result;
            }
            return collectionProducts;
        }
public CustomCollection UpdateCollection(long collectionID, List<Collect> collects)
        {
            return service.UpdateAsync(collectionID, new CustomCollection()
            {
                Id = collectionID,
                Collects = collects
            }).Result;
        }

var allShopifyProducts = productServiceController.GetAllProducts();
var collects = productCollectionController.GetCollectionCollects(222575329448);
var sortedCollection = collects.Select(x => new { productID = x.ProductId, Quantity = allShopifyProducts.Where(y => y.Id == x.ProductId).FirstOrDefault().Variants.FirstOrDefault().InventoryQuantity }).ToList().OrderByDescending(z => z.Quantity);
                collects.Clear();
                for (int i = 0; i < sortedCollection.Count(); i++)
                {
                    var item = sortedCollection.ElementAt(i);
                    collects.Add(new Collect() { ProductId = item.productID, Position = i+1, CollectionId= 222575329448, SortValue="manual"});
                }
customCollectionController.UpdateCollection(222575329448, collects);`

**Comment by shafaqat309** [comment]
Any update please.

**Comment by foxandrewj** [comment]
In my example after retrieving and sorting the products, I am retrieving the existing collects associated to the collection.

This way I can lookup the Collect.Id and assign it the Id of the new Collect.
This will tell Shopify that I want to reposition the existing Collect (and therefore the associated Product) within the Collection.

```
           //create the collects for the products with their new position
            var collects = allProducts.Select((Product product, int index) =>
            {
                return new Collect()
                {
                    Id = allCollects.Single(collect => collect.ProductId == product.Id).Id,
                    Position = index
                };
            });
```

In your code you are specifying the ProductId.  When Shopify receives this it assumes you are trying to push a new Product into the collection.  Since the product is already there, it returns the error.
```
for (int i = 0; i < sortedCollection.Count(); i++)
{
var item = sortedCollection.ElementAt(i);
collects.Add(new Collect() { ProductId = item.productID, Position = i+1, CollectionId= 222575329448, SortValue="manual"});
}
```

**Comment by shafaqat309** [comment]
Code works fine now but collection is still saying ordered by best selling

![image](https://user-images.githubusercontent.com/2289283/98454454-55a88400-21b0-11eb-8196-a5199888a709.png)

**Comment by foxandrewj** [comment]
You don't want to set the SortValue on the collect. That is not a value you can set.
To read more on that see : [https://shopify.dev/docs/admin-api/rest/reference/products/collect](https://shopify.dev/docs/admin-api/rest/reference/products/collect)

You want to update the SortOrder on the CustomCollection.
see: [https://shopify.dev/docs/admin-api/rest/reference/products/customcollection](https://shopify.dev/docs/admin-api/rest/reference/products/customcollection)

like this:
`
            await collectionService.UpdateAsync(collection.Id.Value, 
                new CustomCollection()
                {
                    Id = collection.Id,
                    Collects = collects,
                    SortOrder = "manual"
                });
`

**Comment by shafaqat309** [comment]
FIXED, Thanks a lot.
