### ISSUE TITLE
Question: No Order Level Presentment Money Data?

### ISSUE THREAD

**Issue by jvoce** [nozzlegear/ShopifySharp#590]
Afternoon,

Not sure if I'm being blind, stupid or both but I can't see that the presentment money data is available at order level from the Order Service? This includes:

presentment_currency
total_line_items_price_set
total_discounts_set
total_shipping_price_set
subtotal_price_set
total_price_set
total_tax_set

I'm trying to build orders based on the prices the customer was presented with/paid in rather than the store currency (and therefore transactional currency) so I'm guessing I need to calculated all these totals myself from the LineItem objects and likewise derive the presentment Currency from one of the PriceSet objects?

Edit: It also appears that the ShippingLine data is missing price_set and discounted_price_set for the presentment money values?

Cheers,
Jules

**Comment by clement911** [comment]
Hi @jvoce 
It just so happens that no one has needed these so far but feel free to submit a PR to enhance the Order.cs file with these additional properties.
There is already already a `PriceSet` class that exists so it should be pretty easy to add these new properties.

**Comment by jvoce** [comment]
Hi @clement911 
Cheers for the response

I'm importing orders from Shopify to an external OMS/WMS and then performing the fulfilments and outstanding transactions (and refunds) via the Shopify API, so for multi-currency I'm building the order data in the presentment Currency. Hence these properties make my life a lot easier.

I'm wondering now if I'm doing something wrong with regards to order handling then. I'll have to do some more research I guess.

Cool though, I'll have a look at that Order.cs then and get something submitted though.

Cheers,
Jules

**Comment by jvoce** [comment]
Right, got the changes to Order.cs and ShippingLine.cs ready to PR but I don't appear to have permissions to do any of that. Something I'm missing here?

Cheers,
Jules

**Comment by clement911** [comment]
Submitting a PR doesn't require any permission and I believe any one can do it. If it's your first PR you might want to read some of the GitHub docs.

**Comment by jvoce** [comment]
Ah sorry ok yeah I was trying to work directly into core rather than forking.

PR raised. Cheers for the assist.
