### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by RothcoLtd** [nozzlegear/ShopifySharp#593]
Hello

I am a complete newbie to this.

I am trying to write a simple app in Visual Basic (yes, yes, I know) that uses Shopify Sharp

I have translated your sample code and added it to my controller in the Install routine

Friend strApiKey As String = AppSettings.ShopifyApiKey
        Friend strAPISecret As String = AppSettings.ShopifySecretKey
        Friend strAppURL As String = AppSettings.AppUrl

        Friend strNonce As String = "12345"

 Dim usersMyShopifyUrl As String = "https://RothcoLtd.myshopify.com"
            Dim redirectUrl As String = "https://" & strAppURL & "/Shop50/auth"
            Dim scopes = New List(Of AuthorizationScope)() From {
            AuthorizationScope.ReadCustomers,
            AuthorizationScope.ReadAllOrders,
            AuthorizationScope.ReadProducts
                                             }

            Dim shopifyApiKey As String = ""        ' ( I tried it with and without a key)
            Dim authUrl As Uri = ShopifySharp.AuthorizationService.BuildAuthorizationUrl(scopes, usersMyShopifyUrl, shopifyApiKey, redirectUrl, strNonce)

This does not get the install screen displayed but goes to this URL:

https://1c00a606b1bf.ngrok.io/shop50/install?hmac=45aacab31a003f2813654f2d8773de654dd415e8fce03b801c2423da0fe3e695&shop=rothcoltd.myshopify.com&timestamp=1604398214

I have got the necessary auth routine set up ready for the return. But nothing happens

Strangely this works - except I cannot work out how to validate the HMAC

     Dim r As String = String.Format("https://{0}/admin/oauth/authorize?client_id={1}&scope=read_orders,read_customers,read_products&redirect_uri=https://{2}/Shop50/auth&state=" & strNonce, shop, strApiKey, strAppURL)
            Return Redirect(r)

What am I doing wrong?

Thanks 

Roy

**Comment by nozzlegear** [comment]
Hey @RothcoLtd, sorry it took so long to get back to you. Did you manage to get this working?

**Comment by RothcoLtd** [comment]
Hi

Thanks for your email

I have not been able to get it working yet and I got tied up with another project. I will be returning to this tomorrow so if you can give any help it would be much appreciated 

Roy Thompson

**Comment by nozzlegear** [comment]
Okay, no worries! I’ll take a closer look at this when I have some time tomorrow and hopefully get it fixed for you.

--
Josh Harms

**Comment by nozzlegear** [comment]
So based on what you said here:

> This does not get the install screen displayed but goes to this URL:
>
> 1c00a606b1bf.ngrok.io/shop50/install?hmac=45aacab31a003f2813654f2d8773de654dd415e8fce03b801c2423da0fe3e695&shop=rothcoltd.myshopify.com×tamp=1604398214

It seems like the Shop URL you're passing in to `AuthorizationService.BuildAuthorizationUrl` is not correct. I'm guessing it's somehow mixed up with your app's URL. The first step I would do to debug this is add a `Console.WriteLine(usersMyShopifyUrl)` (or whatever the VB equivalent is) and see what comes out of that. Let me know the result!

**Comment by RothcoLtd** [comment]
Hi Joshua

 

 

I have tried it again. It gets as far as asking me to install the app but after the install it never gets back to the redirect and hence the auth code.

 

After the install it goes to

 

https://1b0f9431706e.ngrok.io/Shop50/auth?code=c9bf11b9a680cd29e71c8d588e951f0f&hmac=58f4e6b50ad60204bdc761908a32cae46a3be53c536b9c1801ec9ac7a0aa63f6&shop=rothcoltd.myshopify.com&state=12345&timestamp=1606384661

 

This is my usersMyShopifyURL

 

https://RothcoLtd.myshopify.com

 

and this shows how the app is set up in Shopify

 



 

My code in VB is as follows

 

Friend strApiKey As String = AppSettings.ShopifyApiKey

        Friend strAPISecret As String = AppSettings.ShopifySecretKey

        Friend strAppURL As String = AppSettings.AppUrl

 

        Friend strNonce As String = "12345"

        Friend configuration As OAuthConfiguration = New OAuthConfiguration With {

                 .ApiKey = strApiKey,

                .SecretKey = strAPISecret

    }

 

Function Install(ByVal shop As String, ByVal signature As String, ByVal timestamp As String) As ActionResult

 

            ' Dim service = New ShopifySharp.ProductService(myShopifyUrl, strAPISecret)

 

            Dim usersMyShopifyUrl As String = "https://RothcoLtd.myshopify.com"

            Dim redirectUrl As String = "https://" & strAppURL & "/Shop50/auth"

            Dim scopes = New List(Of AuthorizationScope)() From {

            AuthorizationScope.ReadCustomers,

            AuthorizationScope.ReadAllOrders,

            AuthorizationScope.ReadProducts

                                             }

 

            Dim shopifyApiKey As String = ""

            Dim authUrl As Uri = ShopifySharp.AuthorizationService.BuildAuthorizationUrl(scopes, usersMyShopifyUrl, shopifyApiKey, redirectUrl, strNonce)

 

 

            Dim r As String = String.Format("https://{0}/admin/oauth/authorize?client_id={1}&scope=read_orders,read_customers,read_products&redirect_uri=https://{2}/Shop50/auth&state=" & strNonce, shop, strApiKey, strAppURL)

            Return Redirect(r)

 

        End Function

 

 

Thanks for all your help

 

Kind regards

 

Roy Thompson

Director

Rothco Ltd

Company Registration No. 3125668

Registered in England

VAT Number GB 750 9986 83

 

Registered Address:-

1 London Road

Ipswich

Suffolk

IP4 2HA

U.K.

 

 

P Before printing, please think about the environment

This email, together with any attachments, is for the exclusive and confidential use of the addressee(s) and may contain legally privileged information. Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies

**Comment by RothcoLtd** [comment]
Hi Joshua

 

Did you get this email?

 

Kind regards

 

Roy

 

Roy Thompson

Director

Rothco Ltd

Company Registration No. 3125668

Registered in England

VAT Number GB 750 9986 83

 

Registered Address:-

1 London Road

Ipswich

Suffolk

IP4 2HA

U.K.

 

 

P Before printing, please think about the environment

This email, together with any attachments, is for the exclusive and confidential use of the addressee(s) and may contain legally privileged information. Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies

 

From: Roy Thompson <rothco.co.uk@zen.co.uk> 
Sent: 26 November 2020 11:02
To: 'nozzlegear/ShopifySharp' <reply@reply.github.com>
Subject: RE: [nozzlegear/ShopifySharp] OAuth (#593)

 

Hi Joshua

 

 

I have tried it again. It gets as far as asking me to install the app but after the install it never gets back to the redirect and hence the auth code.

 

After the install it goes to

 

https://1b0f9431706e.ngrok.io/Shop50/auth?code=c9bf11b9a680cd29e71c8d588e951f0f <https://1b0f9431706e.ngrok.io/Shop50/auth?code=c9bf11b9a680cd29e71c8d588e951f0f&hmac=58f4e6b50ad60204bdc761908a32cae46a3be53c536b9c1801ec9ac7a0aa63f6&shop=rothcoltd.myshopify.com&state=12345&timestamp=1606384661> &hmac=58f4e6b50ad60204bdc761908a32cae46a3be53c536b9c1801ec9ac7a0aa63f6&shop=rothcoltd.myshopify.com&state=12345&timestamp=1606384661

 

This is my usersMyShopifyURL

 

https://RothcoLtd.myshopify.com

 

and this shows how the app is set up in Shopify

 



 

My code in VB is as follows

 

Friend strApiKey As String = AppSettings.ShopifyApiKey

        Friend strAPISecret As String = AppSettings.ShopifySecretKey

        Friend strAppURL As String = AppSettings.AppUrl

 

        Friend strNonce As String = "12345"

        Friend configuration As OAuthConfiguration = New OAuthConfiguration With {

                 .ApiKey = strApiKey,

                .SecretKey = strAPISecret

    }

 

Function Install(ByVal shop As String, ByVal signature As String, ByVal timestamp As String) As ActionResult

 

            ' Dim service = New ShopifySharp.ProductService(myShopifyUrl, strAPISecret)

 

            Dim usersMyShopifyUrl As String = "https://RothcoLtd.myshopify.com"

            Dim redirectUrl As String = "https://" & strAppURL & "/Shop50/auth"

            Dim scopes = New List(Of AuthorizationScope)() From {

            AuthorizationScope.ReadCustomers,

            AuthorizationScope.ReadAllOrders,

            AuthorizationScope.ReadProducts

                                             }

 

            Dim shopifyApiKey As String = ""

            Dim authUrl As Uri = ShopifySharp.AuthorizationService.BuildAuthorizationUrl(scopes, usersMyShopifyUrl, shopifyApiKey, redirectUrl, strNonce)

 

 

            Dim r As String = String.Format("https://{0}/admin/oauth/authorize?client_id={1} <https://%7b0%7d/admin/oauth/authorize?client_id=%7b1%7d&scope=read_orders,read_customers,read_products&redirect_uri=https://%7b2%7d/Shop50/auth&state=> &scope=read_orders,read_customers,read_products&redirect_uri=https://{2}/Shop50/auth&state=" & strNonce, shop, strApiKey, strAppURL)

            Return Redirect(r)

 

        End Function

 

 

Thanks for all your help

 

Kind regards

 

Roy Thompson

Director

Rothco Ltd

Company Registration No. 3125668

Registered in England

VAT Number GB 750 9986 83

 

Registered Address:-

1 London Road

Ipswich

Suffolk

IP4 2HA

U.K.

 

 

P Before printing, please think about the environment

This email, together with any attachments, is for the exclusive and confidential use of the addressee(s) and may contain legally privileged information. Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies
