### ISSUE TITLE
Customer entity missing send_email_invite property

### ISSUE THREAD

**Issue by Uffman** [nozzlegear/ShopifySharp#596]
Customer entity is missing property "send_intvite"
[https://shopify.dev/docs/admin-api/rest/reference/customers/customer?api%5Bversion%5D=2020-04#create-2020-04](https://shopify.dev/docs/admin-api/rest/reference/customers/customer?api%5Bversion%5D=2020-04#create-2020-04)

It is strange that Shopify didn't list this property in the Customer properties definition
![image](https://user-images.githubusercontent.com/1281907/99037998-1baaf980-2585-11eb-9bc9-fe6faf17fe6e.png)

**Comment by nozzlegear** [comment]
The email invite can now be sent by using the `CustomerCreateOptions` with `CustomerService.CreateAsync`
