### ISSUE TITLE
Cannot access raw API logs

### ISSUE THREAD

**Issue by YorkshireWill** [nozzlegear/ShopifySharp#602]
Hi all,

Is there any way to access API responses (maybe even requests?) in raw format for logging purposes? Could be triggered as events if this is easiest - as I have no need to tie the API response / request to the object(s) returned - just want to record communication between us and our customer's API to help with support requests

Happy to add this myself to code stream if anyone could give me pointers on setting up test environment for Shopify I can test against

Thanks,
Will

**Comment by nozzlegear** [comment]
Hey @YorkshireWill, thanks for the suggestion! There's no way to do this right now but I can see how it would be useful. What kind of information would you like to access about the request?

**Comment by YorkshireWill** [comment]
We usually log raw API calls for our interfaces - so would be good to get access to the raw POST data and any HTTP status codes returned on a request. And the HTTP status code and response body for any responses. 

This would be absolutely amazing if this could be added.

**Comment by clement911** [comment]
Hi @YorkshireWill you can actually do that today by implementing a custom `IRequestExecutionPolicy` that simply delegates the call to `SmartRetryExecutionPolicy` or `DefaultRequestExecutionPolicy`, but logs the request and response.

![image](https://user-images.githubusercontent.com/3426504/103512977-fdb59300-4e69-11eb-9fae-04e56199713d.png)

![image](https://user-images.githubusercontent.com/3426504/103513007-0c9c4580-4e6a-11eb-82e9-da7e18343ef8.png)
