### ISSUE TITLE
If private app use JWT auth, where to customize code

### ISSUE THREAD

**Issue by lehoangphan** [nozzlegear/ShopifySharp#606]
If Shopify use JWT auth for Private App 
Where to put these code in this source code? For deal with Jwt auth

`request.Header.Add("Autherization","Bearer keytoken"); `

Thanks

**Comment by nozzlegear** [comment]
Hey @lehoangphan, ShopifySharp should work out of the box for private apps, you don't need to add this header yourself. All you need to do is take your private app's password (might also be called a secret key now) and use that wherever ShopifySharp would usually accept an access token:

```cs
var privateAppPassword = "password here";
var service = new ShopifySharp.OrderService(shopUrl, privateAppPassword);
```
