### ISSUE TITLE
2021-01 API Version Breaking changes

### ISSUE THREAD

**Issue by Matt-Kaminski** [nozzlegear/ShopifySharp#607]
Hey all,

Since the new year began, my app started receiving deprecated API calls notification. It turns out that there is a change in Recurring Application Charge endpoint:

> Auto-activate billing charges using the REST Admin API
> We've removed the _accepted_ value for the _status_ field and the _activate_ endpoint on the ApplicationCharge and RecurringApplicationCharge resources.
> 
> As of the 2021-01 API version, when a merchant accepts a charge, the charge immediately transitions from _pending_ to _active_. This means that you no longer need to activate the charge to finalize it.

source: [https://shopify.dev/concepts/about-apis/versioning/release-notes/2021-01](https://shopify.dev/concepts/about-apis/versioning/release-notes/2021-01)

I think that this change does not require any changes in ShopifySharp except bumping the api version, but still imposes big danger for app developers.

For example, I had this code for checking the charge:

```
if (charge.Status != "accepted")
{
   return RedirectToAction("ChargeDeclined");      
}
```

After updating the app to the new API version, it would basically break app installation, as charge would be already in _active_ status.

There are also two more breaking changes that should be addressed:

> **Status field in REST FulfillmentOrder resource**
> As of the 2021-01 API version, we've added a new scheduled value to the status field in the FulfillmentOrder resource.
> 
> For more information, refer to Managing prepaid subscription orders.

> **Cursor-based pagination**
> The /admin/api/{version}/users.json endpoint now supports cursor-based pagination.

There is still 9 months left, so we have plenty of time.

**Comment by clement911** [comment]
Thanks for the heads up.
We carefully review documented breaking changes when we release a new version, but this one is worth calling out.

**Comment by davidfilkins** [comment]
Thanks @Matt-Kaminski / @clement911! I recently noticed the same warning on the upcoming breaking chagne. Glad to see others are already on top of this.

**Comment by nozzlegear** [comment]
Taken care of in #651 and #649!
