### ISSUE TITLE
Question about Listing all Orders (Nozzlegear blog post)

### ISSUE THREAD

**Issue by nosuic** [nozzlegear/ShopifySharp#609]
Hi!

Firstly, thanks so much for writing and maintaining this great library.

I am trying to make the following snippet work, which is from a post on the Nozzlegear Software blog: [Listing all orders, customers, articles or anything else with the Shopify API](https://nozzlegear.com/shopify/listing-all-orders-customers-articles-or-anything-else-with-the-shopify-api):

`
    var service = new ShopifySharp.OrderService(domain, accessToken);
    var total = await service.CountAsync();
    var orders = new List<ShopifySharp.Order>();
    int limit = 250;
    int totalPages = total % limit > 0 ? (total / limit) + 1 : total % limit;
    int page = 1;

    while (page <= totalPages)
    {
        var pageOfOrders = await service.ListAsync(new ShopifySharp.Filters.OrderFilter
        {
            Limit = limit,
            Page = page
        });

        orders.AddRange(pageOfOrders);
        page++;
    }
`

But I get the following error for `OrderFilter`: _CS0234: The type or namespace name 'OrderFilter' does not exist in the namespace 'ShopifySharp.Filters'_

How could I fix that? Should I include something else in addition to the ShopifySharp library?

What I eventually want to do is to fetch all orders for the last 48 hours and I presume I should be able to do it if I get the OrderFilter to work. If there's a better way, I would appreciate it if you could point me to the right direction.

Thanks again,
F.

**Comment by foxandrewj** [comment]
Hi,

That post is outdated.
Here is how you would do the same operation now: https://github.com/nozzlegear/ShopifySharp#user-content-migrating-from-version-4x-to-version-500

Shopify completely changed how paging was implemented in their API version 2019-10 so some ShopifySharp objects were redesigned/replaced (note: OrderFilter is now OrderListFilter) to accommodate the API changes.

**Comment by nosuic** [comment]
Hi @foxandrewj thanks so much for that. That snippet worked indeed, although at start it only returned 4 orders. I discovered that these were the only orders that had not been archived, so by adding a `Status` filter (credit to [this person](https://community.shopify.com/c/Shopify-APIs-SDKs/Order-API-Viewing-ALL-orders-including-archived/td-p/67508)), I managed finally to fetch all orders!

`
            var allOrders = new List<Order>();
            var page = await service.ListAsync(new OrderListFilter
            {
                Limit = 250,
                Status = "any",
            });

            while (true)
            {
                allOrders.AddRange(page.Items);

                if (!page.HasNextPage)
                {
                    break;
                }

                page = await service.ListAsync(page.GetNextPageFilter());
            }


            foreach (ShopifySharp.Order order in allOrders)
            {
                var u = order.OrderStatusUrl;
                Console.WriteLine("url = " + u);
            }
`

**Comment by foxandrewj** [comment]
Glad you were able to figure that out.
Since ShopifySharp is a wrapper around Shopify’s REST API, the documentation here is your best resource: https://shopify.dev/docs/admin-api/rest/reference

Eg, getting orders and all available filters: https://shopify.dev/docs/admin-api/rest/reference/orders/order#index-2021-01



[http://sigs.foxinteractivedesign.com/repo/fox/fox.png]
Andrew Fox
PARTNER / DEVELOPER
FOX INTERACTIVE DESIGN
andy@foxinteractivedesign.com<mailto:andy@foxinteractivedesign.com>
732.718.9526

**Comment by nosuic** [comment]
Oh that's great! I was wondering where the best place to look things up. Thanks for all the help!
