### ISSUE TITLE
Product Metafields

### ISSUE THREAD

**Issue by Skyhighjinks-Dev** [nozzlegear/ShopifySharp#610]
When pulling down a list of all of the products - inside of the product objects contains a meta field property. On top of that inside each of the variants, they also all contain meta field properties. However, these are all null resulting in us having to do a separate call for each product manually. 

Shouldn't those fields be populated?

Apologies if I'm just being stupid, but I cannot find a way to use this library to achieve this goal without having to do tonnes of API calls..

**Comment by foxandrewj** [comment]
Unless something has changed, I don't think there is a way to get Shopify's REST API to give you the metafields when pulling a list of products.

But the GraphQL API can:
this post talks about it and there is an example query on the page as well.
https://community.shopify.com/c/Shopify-APIs-SDKs/Get-all-metafields-for-products/td-p/226534/page/6#

And you can build/test queries using Shopify's own GraphiQL app https://shopify.dev/tools/graphiql-admin-api

And post them from your app using ShopifySharp's GraphService class.

**Comment by nozzlegear** [comment]
@Skyhighjinks-Dev Sorry for the confusion, and sorry I'm so late getting to this issue. @foxandrewj is right, the Shopify REST API doesn't actually return those metafields with its objects. The only reason you find them on some ShopifySharp classes is because they can be sent when creating new objects. That has caused a lot of confusion, so I'm planning to remove those properties entirely in 6.0 and just add the metafield list as an extra parameter for `service.CreateAsync` methods that support.

**Comment by adoconnection** [comment]
dedicated for random person who wasted all evening trying to get product list with metafields 

```cs
WebClient client = new WebClient();
client.Headers.Add("Content-Type", "application/graphql");
client.Headers.Add("X-Shopify-Access-Token", "YOUR_ACCESS_KEY");

string data = @"
{
  products(first: 3) {
    edges {
      node {
        id
        title
        metafields (first: 250) {
          edges {
            node {
              value
              namespace
              key
            }
          }
        }
      }
    }
  }
}
";

var uploadData = client.UploadData("https://YOUR_STORE.myshopify.com/admin/api/2022-07/graphql.json", "POST",
        Encoding.UTF8.GetBytes(data));

var s = Encoding.UTF8.GetString(uploadData);

var deserializeObject = JsonConvert.DeserializeObject(s);

Console.WriteLine(s);

```

**Comment by clement911** [comment]
You can use the GraphService instead, which makes it a bit easier
