### ISSUE TITLE
Authenticating Orders Webhook always fails

### ISSUE THREAD

**Issue by chadwixk** [nozzlegear/ShopifySharp#612]
Using ShopifySharp version 5.8.0 with asp.net MVC5 app.

Hello, I couldn't find any information on authenticating and consuming Shop base webhooks. I am trying to validate and consume a _Shopify shop_ level webhook, i.e. Orders/Create and cannot get the webhook call to pass validation. 

Based on the documentation, I am assuming that the SecretKey parameter of IsAuthenticResult is our App's secret key, not the shop owner's private app Shared Secret Key. However, in the user's store Private App configuration, there is a Shared Secret Key that state's its purpose is to verify webhooks???? So not sure which I am to use to pass to IsAuthenticWebhook...regardless, I've tried them both and it still fails.

![2021-01-28 12_11_40-Shopify](https://user-images.githubusercontent.com/5115308/106199396-a5c13200-6172-11eb-8c33-65f924f18a3d.jpg)

This code is always returning false:
```
var isValidRequest = await AuthorizationService.IsAuthenticWebhook(
                Request.Headers.ToKvps(),
                Request.InputStream,
                appSecretKey);
```

Thanks in advance!
Chad

**Comment by chadwixk** [comment]
Figured it out. The code comments and the Shopify Developer Handbook are just from the context of a Public App. But if you're developing a Shopify Private App, you need to use the customer's store's private app Shared Secret Key, not your app's secret key. 

That seems obvious now (duh), but it would probably help to make this explicit in the code comments and developer handbook.

See my full answer: https://stackoverflow.com/questions/65943823/how-to-validate-shopify-private-app-webhook-using-shopifysharp/65946397#65946397

**Comment by Rajanusa** [comment]
Hi,

I am trying the same but it fails in authentication.

````
NameValueCollection requestHeaders = Request.Headers;
Stream inputStream = Request.InputStream;

if(AuthorizationService.IsAuthenticWebhook(requestHeaders, inputStream, shopifySecretKey))
{
    //Webhook is authentic.
}
else
{
    //Webhook is not authentic and should not be acted on.
}

````
As per sample provided in their site the above code is used.

Request.Headers coul dnot be converted to NamedValueCollection.
There us no InputStream in Request
IsAuthenticWebhook method expect first parameter as Ienumerable<KeyValuePair<string, stringValue>>

I think you used extension method ToKvps()

Please advise.

**Comment by nozzlegear** [comment]
@Rajanusa Which version of .NET are you using?
