### ISSUE TITLE
Clearing Shopify managing inventory by setting null on variant

### ISSUE THREAD

**Issue by paulgreen43** [nozzlegear/ShopifySharp#613]
Hi,

I'm trying to clear on some product variants the inventory being managed by Shopify.

According to the Shopify API docs, it can be set to "shopify", null or the handle of the fulfilment service, so I need to set it to null.  Indeed setting it by PUTting the following JSON directly, it works:

```
{
  "variant": {
    "id": 33114453999715,
    "inventory_management": null,
    "fulfillment_service": "manual"
  }
}
```
Replicating this in my code, I'm doing the following:
```
var service2 = new ProductVariantService(domain, accessToken);
var pv = new ProductVariant { Id=variant.Id, InventoryManagement = null, FulfillmentService = "manual" };
var pv2 = await service2.UpdateAsync((long)variant.Id, pv);
```
I believe ShopifySharp is ignoring the null value as many values are null when a new ProductVariant is instantiated, so how to set the null value? I've tried setting the string "null" which results in a Shopify error: "is Null, so fulfillment service must also be Null"

Thanks,
Paul.

**Comment by paulgreen43** [comment]
Ignore me - setting it to String.Empty works!

**Comment by nozzlegear** [comment]
Awesome, glad you got it working!

--
Josh Harms
