### ISSUE TITLE
VS 2019 (422 Unprocessable Entity) base: You need to add option values

### ISSUE THREAD

**Issue by finalthrill** [nozzlegear/ShopifySharp#614]
Im attempting to create a complex product with several variants.  The product has 2 options: Color and UnitOfMeasure.  When I call the CreateAsync service call for creating the product, I get the following error....

(422 Unprocessable Entity) base: You need to add option values for UofM

Its a very specific error message, however I am passing in a list of values for each option.  The API requires an String enumeration, and I tried passing in a List of Strings, and Array of Strings, and even a hash set.  In all cases, it populates the object with the values but for whatever reason Shopify doesn't recognize the values are there.  

Any advice would be much appreciated.

**Comment by nozzlegear** [comment]
Hi @finalthrill, did you manage to get this working?

**Comment by finalthrill** [comment]
Unfortunately no, but thank you for checking in.

**Comment by nozzlegear** [comment]
Okay, no problem! I think this might be a common issue that I’ve seen when working with product options. If you search the issues on this repository for “product options” you might find the solution, otherwise I’ll look for it later this evening once I’m back home. 

--
Josh Harms

**Comment by nozzlegear** [comment]
Just in case a search brings somebody here in the future, the solution is here: https://github.com/nozzlegear/ShopifySharp/issues/412
