### ISSUE TITLE
Using Graph documentation?

### ISSUE THREAD

**Issue by chadwixk** [nozzlegear/ShopifySharp#615]
I'm looking to convert some of my REST Api calls to GraphQL. I see you have a GraphService, but where is the documentation that it refers to or any other examples of how to use it?

> <param name="body">The query you would like to execute. Please see documentation for formatting.</param>

**Comment by foxandrewj** [comment]
The documentation it is referring to is Shopify's GraphQL reference [https://shopify.dev/docs/admin-api/graphql/reference](https://shopify.dev/docs/admin-api/graphql/reference)

Shopify also provides this app for testing queries:
[https://shopify-graphiql-app.shopifycloud.com/](https://shopify-graphiql-app.shopifycloud.com/)

Good luck!

**Comment by chadwixk** [comment]
Ah, I see. That has proven not very successful in how it translates to ASP.Net. I'll post another question with specific syntax issues.
