### ISSUE TITLE
Help with GraphQL mutation syntax

### ISSUE THREAD

**Issue by chadwixk** [nozzlegear/ShopifySharp#616]
Hello all,

I've been banging my head for the last 2 days trying to get a simple graph update to work in ASP.NET MVC. I can get it to work in Postman, but not in my code.

In Postman, I'm trying to use the raw json body format to emulate as much as possible how I need to structure my request body. I have the content-type set to application/json, and it works:

`{"query": "mutation { item1: inventoryActivate (locationId:\"gid://shopify/Location/18330746950\",inventoryItemId:\"gid://shopify/InventoryItem/21137213849670\",available:0) { ...inventoryFields } item2: inventoryActivate (locationId:\"gid://shopify/Location/35866968134\",inventoryItemId:\"gid://shopify/InventoryItem/21137213849670\",available:0) { ...inventoryFields } } \r\n fragment inventoryFields on InventoryActivatePayload { \r\n userErrors { \r\n field \r\n message \r\n } }",
    "variables": {}}`

![image](https://user-images.githubusercontent.com/5115308/108112441-56747000-7053-11eb-801b-c880a10a4651.png)

I also tried it using the GraphQL body type, but again using the Content-Type as application/json, and it still works:

![image](https://user-images.githubusercontent.com/5115308/108112633-9c313880-7053-11eb-94a2-ee352fe717d0.png)

Interestingly, as per some posts on the Shopify forum to change the content type to application/graphql, it fails with:
`"Parse error on \"query\" (STRING) at [1, 2]"`

Fine, I'd rather work in json format anyway in ASP.NET, so I attempt to post this string with the content-type as application/json:

`{"query":"mutation { item1: inventoryActivate (locationId:\"gid://shopify/Location/18330746950\",inventoryItemId:\"gid://shopify/InventoryItem/21137213849670\",available:0) { ...inventoryFields } item2: inventoryActivate (locationId:\"gid://shopify/Location/35866968134\",inventoryItemId:\"gid://shopify/InventoryItem/21137213849670\",available:0) { ...inventoryFields }  } 
fragment inventoryFields on InventoryActivatePayload { 
userErrors {
field
message
}
}","variables":{}}`

And I get a 400 - Bad Request error.

I change the Content-Type to application/graphql 
Yeah: I got a 200 response! But...
Booo: I get this error:
`{"errors":[{"message":"Parse error on \"query\" (STRING) at [1, 2]","locations":[{"line":1,"column":2}]}]}`

I tried fiddling with different syntax to no avail. So after finding this [other issue](https://github.com/nozzlegear/ShopifySharp/issues/573), I see @drovani  was not including the "query" part, etc and making the string more look like the graphql you see in Postman above. So I try that route and post this, again with the content-type of application/graphql:
`{mutation { item1: inventoryActivate (locationId:"gid://shopify/Location/18330746950",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0) { ...inventoryFields } item2: inventoryActivate (locationId:"gid://shopify/Location/35866968134",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0) { ...inventoryFields }  } 
fragment inventoryFields on InventoryActivatePayload { 
userErrors {
field
message
}
},variables:{}}`

And get this error:
`{"errors":[{"message":"Parse error on \"{\" (LCURLY) at [13, 13]","locations":[{"line":13,"column":13}]}]}`

I'm not sure how they determine the line and position, because if you paste my string above in Notepad ++ without wrapping, there are only 7 lines, so not sure how they are getting to an error on line 13. They must be doing some pre-formatting first, then validating...but they don't return that formatted query so you can't correlate the [line,col] where the error occurred back to what you submit.

Any pointers? Can you use content type json? What am I missing?

Thanks in advance!

**Comment by chadwixk** [comment]
Of course, 15 min after posting this, I stumbled across the winning combination:

Using Content-Type: application/graphql

And removing the outer "{    }" bracket set:
`mutation { 
	item1: inventoryActivate (
		locationId:"gid://shopify/Location/18330746950",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0
	) { ...inventoryFields } 
	
	item2: inventoryActivate (
		locationId:"gid://shopify/Location/35866968134",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0
	) { ...inventoryFields } 
 } 

fragment inventoryFields on InventoryActivatePayload { 
	userErrors {
		field
		message
	}
}`

Though I am curious how to get a json format could work and how @drovani got [his](https://github.com/nozzlegear/ShopifySharp/issues/573) to work with the outer "{}" wrapper.

**Comment by nozzlegear** [comment]
Haha glad you got it working! I ran into that outer "{}" issue a lot when I first started writing this package. It's not always obvious and their error messages can be less than helpful sometimes. 

--
Josh Harms


On Tue, Feb 16, 2021, at 14:29, Chad Richardson wrote:
> 

> Of course, 15 min after posting this, I stumbled across the winning combination:

> Using Content-Type: application/graphql


> And removing the outer "{ }" bracket set:
> `mutation {
> item1: inventoryActivate (
> locationId:"gid://shopify/Location/18330746950",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0
> ) { ...inventoryFields }

> `item2: inventoryActivate (
	locationId:"gid://shopify/Location/35866968134",inventoryItemId:"gid://shopify/InventoryItem/21137213849670",available:0
) { ...inventoryFields } 
`
