### ISSUE TITLE
Can't send line item properties when creating Draft Order

### ISSUE THREAD

**Issue by stjjelic** [nozzlegear/ShopifySharp#617]
I'm trying to create a draft order with line item properties, but I'm getting this error:

> ShopifySharp.ShopifyException: (400 Bad Request) name: expected Hash to be a String

These are the properties:

`            Properties = new List<LineItemProperty> {
                    new LineItemProperty() { Name = "test", Value = "ha" },
                    new LineItemProperty() { Name = "test2", Value = "ha2" },
                    new LineItemProperty() { Name = "test3", Value = "ha3" },
                }`

On a side note, I can create a draft order when I'm not sending line item properties, so the error is clearly connected to them.

**Comment by nozzlegear** [comment]
Interesting, I use line item properties with my draft orders in production and don't think I've had any issues with it. I'll investigate and see if I can spot a problem.

**Comment by nozzlegear** [comment]
Can you tell me which version of ShopifySharp you're using, and possibly post an example of the code you're using to create the draft order with line item properties?

**Comment by stjjelic** [comment]
Hi, I found the problem, I guess it is actually C# to blame. When I'm passing Properties (LineItemProperty list) from service to controller, the values Name and Value of LineItemProperty changes. For example, if the value of Name property is "test", when it comes to the controller it changes to ValueKind = string : "test", and that ValueKind messes up everything.

**Comment by nozzlegear** [comment]
Great, glad you got it figured out!
