### ISSUE TITLE
Id missing from Product Variant

### ISSUE THREAD

**Issue by jvoce** [nozzlegear/ShopifySharp#625]
Good afternoon,

I can't see that the id property exists for the ProductVariant Entity so it's not possible to update a product variant assigned to a product in Shopify?

As with my other query over Address Ids I may missing something obvious?

Cheers,
Jules

**Comment by clement911** [comment]
It's on the base class, `ShopifyObject.Id`

**Comment by jvoce** [comment]
Ah {insert mild expletive here}, sorry yeah so it is. Thanks for that @clement911, I was being a muppet then.

Cheers,
Jules
