### ISSUE TITLE
indetifier_exist, How can se set this property from the API

### ISSUE THREAD

**Issue by shafaqat309** [nozzlegear/ShopifySharp#626]
Google expects if there is no GTIN available, then identifier_exists=false should be set on the product/variant. I could not find this property in the API.

Is this or equivalent functionality available?

**Comment by nozzlegear** [comment]
Hmm, I believe this kind of thing is usually set with the metafields on a product. You'd need to use the `MetafieldService` class, but I'm not exactly sure what you would use as the key to get it to show up in the page's HTML (if I understand your question correctly). There is a metafields property on the `Product` class, but that will only be used when creating a new product, so make sure you're using the `MetafieldService` to update existing products.
