### ISSUE TITLE
Newtonsoft.Json version 10.0.0.0 dependency

### ISSUE THREAD

**Issue by hillsydev** [nozzlegear/ShopifySharp#630]
Hi, I'm getting dependency errors with Newtonsoft when trying to deploy an application with ShopifySharp to another non-development machine.

The type initializer for 'ShopifySharp.ShopifyService' threw an exception.. 
InnerException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.. 

When the ShopifySharp package is downloaded from NuGet, Newtonsoft 10.0.1 is installed by default.  I tried updating to Newtonsoft 12.0.3, but the above error occurs.

Is there a strict dependency on Newtonsoft 10.0.1 with ShopifySharp?  If so, can that strict dependency be removed so that we can upgrade to a later version of Newtonsoft?

Application is running on .Net framework 4.6.2.

Using latest version of ShopifySharp, 5.9.0

**Comment by nozzlegear** [comment]
Hey! The package does have a dependency on Newtonsoft.Json v10.0.1 or higher, so anything above that _should_ work. We're planning to remove that dependency and use System.Text.Json instead, but I don't currently have an estimated date for when that change might happen. 

![image](https://user-images.githubusercontent.com/2417276/113165824-d7ed1f80-9207-11eb-9847-15ee1bacbd69.png)

**Comment by nozzlegear** [comment]
I'm not the most skilled at figuring out dependency issues (I usually just get very grumpy when they happen to me 😅), so if anyone else happens to see this issue and might know how to fix it, that would be appreciated!

**Comment by hillsydev** [comment]
Thanks for the reply.  I've worked around the dependency problem by downloading the ShopifySharp source, updating Newtonsoft to version 12.0.3, building it, then referencing the ShopifySharp.dll directly from the project bin folder.  Since my core project is still in .NET framework 4.x, I don't have access to System.Text.Json namespace.  Will be a while before I can transition to .NET 5/6.

**Comment by nozzlegear** [comment]
Just a note, Newtonsoft.Json has been updated to v13 in ShopifySharp v5.14.0. I'm going to close this and hope no further dependency issues arise!

**Comment by cemerson** [comment]
My apologies to reply to a closed thread but I'm trying to get past this Newtonsoft 10.0.0 thing as well. I've tried ShopifySharp 4.0.0 all the way up to 5.14.0 but every time I access it in my code I get the error (below). I have to keep my Newtonsoft at 11.0.2 for my other projects in the solution and my .NET framework version has to stay at 4.52 for now. Am I screwed or is there a way to get ShopifySharp working in my setup? Thank you for any help/tips anyone can share. 

My error fwiw:
```
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

[FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   ShopifySharp.ShopifyService..cctor() +0

[TypeInitializationException: The type initializer for 'ShopifySharp.ShopifyService' threw an exception.]
   ShopifySharp.ShopifyService..ctor(String myShopifyUrl, String shopAccessToken) +48
   ShopifySharp.OrderService..ctor(String myShopifyUrl, String shopAccessToken) +9
   MyCLSNET.test.<GetOrders>d__5.MoveNext() in C:\Projects\MyApp\ShopifySharpTest.aspx.cs:81
   System.Runtime.CompilerServices.<>c.<ThrowAsync>b__6_0(Object state) +54
   System.Web.<>c__DisplayClass22_0.<Post>b__0() +20
   System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action) +92
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Web.Util.WithinCancellableCallbackTaskAwaiter.GetResult() +32
   System.Web.UI.<ProcessRequestMainAsync>d__523.MoveNext() +6135
```

**Comment by cemerson** [comment]
FWIW for now I have, like hillsydev, grabbed an older source (5.0.4), changed the Newtonsoft version to what I needed (11.0.2) and will just use the generated DLL for now. So I guess I'm set now but if/when there is a way to use the nuget-provided version of ShopifySharp please let us know. Thank you by the way for a really amazing library!

**Comment by nozzlegear** [comment]
Hey, glad you got it working! I'd be careful though, v5.0.4 uses an outdated version of Shopify's API that's no longer supported by them. It may not work anymore. 

Dependency conflicts are sadly something that I don't really know much about. I'm not sure if you can create binding redirects to make your project think Newtonsoft.Json v11 is also v10 or not, but I'd start there. You could also clone the current version of this repository and include it with your project where you can then update its Newtonsoft.Json dependency.

--
Josh Harms

**Comment by nozzlegear** [comment]
Support for .NET 4.5 was removed in version 5.14.0, so the latest version you could use would be 5.13.1. It's using a version of Shopify's API that will still be supported until July 2022, after that you'd need to upgrade to the latest version which only supports .NET 4.6.1 and above. 

Version 5.13.1 still uses that older version of Newtonsoft.Json though, so if you want to clone it from source and modify the project [you can use this release here](https://github.com/nozzlegear/ShopifySharp/releases/tag/5.13.1).

**Comment by cemerson** [comment]
Thanks for that version information - guess my 4.52 will have to get moving soon too. Thank you again.
