### ISSUE TITLE
Product page/preview URL

### ISSUE THREAD

**Issue by elegault** [nozzlegear/ShopifySharp#632]
I see from the Shopify API reference that there is a Product.onlineStorePreviewUrl property, but I don't see something similar in ShopifySharp's Product object.  Is there a way to get that data?  Or the URL that is generated when you click the "Preview" button when viewing the Product's page in the store's admin dashboard?

**Comment by nozzlegear** [comment]
Ah most likely it's a property that was added at some point after the Product class was last reviewed. If you want to submit a pull request for it, I'd be happy to review it! Otherwise I'll get it added in as soon as I have a chance.

--
Josh Harms

**Comment by nozzlegear** [comment]
Hey @elegault, sorry it took me so long to get to this. Looking at the [Shopify REST API reference for products](https://shopify.dev/api/admin/rest/reference/products/product), it doesn't look like this is a property that we can use. Sadly it might be a storefront API or graphQL API only. If it does come to the REST API I'd be happy to add it!
