### ISSUE TITLE
ProductListFilter - Missing Property

### ISSUE THREAD

**Issue by mark-jeanswhse** [nozzlegear/ShopifySharp#634]
Hi,

Would it be possible to add the "status" property for ProductListFilter for a future release? This would be incredibly useful for listing drafted products. 

Also, the "handle" property can return a list of products so maybe the property should be `IEnumerable<string>` instead. Although, a comma-separated string works just fine.

Reference: https://shopify.dev/docs/admin-api/rest/reference/products/product?api%5Bversion%5D=2021-01

**Comment by nozzlegear** [comment]
Looks like we've added this at some point! You should be able to use the `Status` property with `ProductListFilter` if you haven't already.
