### ISSUE TITLE
Order Edited - Missing Property

### ISSUE THREAD

**Issue by Fashionepaul** [nozzlegear/ShopifySharp#635]
Hi,

Can you please add the edited property to the Order?

https://shopify.dev/docs/storefront-api/reference/orders/order?api[version]=2020-10

**Comment by nozzlegear** [comment]
Hey @Fashionepaul, sorry it took so long to get to this. Unfortunately it looks like the `Edited` property only exists on the Storefront and GraphQL APIs. [According to Shopify's REST API documentation](https://shopify.dev/api/admin/rest/reference/orders/order), there's no `Edited` property that we can access.

**Comment by Fashionepaul** [comment]
Sorry about that.  😉

**Comment by nozzlegear** [comment]
All good! It’d be nice if we could use that property, but Shopify is sadly in the habit of making some things only available on their graph api. 

--
Josh Harms
