### ISSUE TITLE
Using the ListAsync method in a webpage

### ISSUE THREAD

**Issue by florin-r** [nozzlegear/ShopifySharp#636]
Hi,

I have a issues with the library - I'm using it on a ASP.NET  and it's hanging on ListAsync  method
The sample code is below

`public IList<Order> GetByOrderNumber(string orderNumber)
        {
            GetOrderByNameAsync(orderNumber).GetAwaiter().GetResult();

            return _orders;
        }

        public async Task GetOrderByNameAsync(string orderName)
        {
            System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            var service = new OrderService(_domain, _accessToken);

            var filter = new OrderFilterWithName
            {
                Name = orderName.Replace("#", ""),
                Limit = 1
            };

            ListResult<Order> orders = await service.ListAsync(filter);
            _orders = orders.Items.ToList();
        }`

Please let me know if you have any idea why would happen

**Comment by nozzlegear** [comment]
Hey @florin-r, are you still having this problem? I use the order list API frequently and haven't had any issues with it.
