### ISSUE TITLE
Analytics / Report API

### ISSUE THREAD

**Issue by andrekat** [nozzlegear/ShopifySharp#637]
Hey, is the Reports / Analytics API already included in this package? 

See more: https://shopify.dev/docs/admin-api/rest/reference/analytics/report

**Comment by timeframederek** [comment]
Hi - Just suggesting this is not important The Analytics API is deprecated. Please use our other APIs to get Sales, Payments, Taxes, and Customer data. Visits data is no longer available.

https://shopify.dev/docs/admin-api/rest/reference/analytics/shopify-ql

**Comment by nozzlegear** [comment]
Closing this since as @timeframederek indicated, the Shopify analytics API is deprecated and unsupported. Thanks!
