### ISSUE TITLE
API Version update coming in July 2021

### ISSUE THREAD

**Issue by ThatBrianK** [nozzlegear/ShopifySharp#644]
Hi there, I was just looking at the source code for the current version and noticed that the API version is still set to 2020-10.
Come July 1st, any calls made with this version will be flagged as deprecated and Shopify will notify all your merchants that you are using out-of-date calls. I learned this info here: https://www.shopify.ca/partners/blog/api-deprecation-update-2021-07

I would love it if there could be another release published to NuGet with an API version update - it would certainly make my and many others' lives easier as well. In any case, I thought I should mention it, so that other developers aren't caught off-guard.

Thanks again for the awesome library!!

Brian

**Comment by nozzlegear** [comment]
Oh shoot, thanks for letting me know! For some reason I thought we had until October to update. I'll get a new version published as soon as possible.

--
Josh Harms

**Comment by clement911** [comment]
I'm pretty sure we have till October first actually.
But it would be good to pin the lib now to a more recent version anyway.

**Comment by nozzlegear** [comment]
Yes I think you’re right, they pushed the date back to October due to a mistake on their part iirc. I’ll get a new version published ASAP though.

--
Josh Harms

**Comment by nozzlegear** [comment]
Version 5.11.0 is now published on Nuget, which targets Shopify's API version 2021-07. Let me know if you have any issues using it!
