### ISSUE TITLE
Is is possible to create a monthly flat recurring and usage charge in a single call?

### ISSUE THREAD

**Issue by chadwixk** [nozzlegear/ShopifySharp#645]
This is possible via their [api,](https://shopify.dev/tutorials/implement-your-app-business-model-with-billing-api) but didn't see how this could be accomplished via ShopifySharp...just wanted to see if if was possible.

i.e.
`mutation {
  appSubscriptionCreate(
    name: "Super Duper Capped Pricing Plan",
    returnUrl: "http://super-duper.shopifyapps.com",
    lineItems: [{
      plan: {
        appUsagePricingDetails: {
          terms: "$1 for 100 emails"
          cappedAmount: { amount: 20.00, currencyCode: USD }
          interval: EVERY_30_DAYS
        }
      }
    },
    {
      plan: {
        appRecurringPricingDetails: {
          price: { amount: 10.00, currencyCode: USD }
        }
      }
    }]
  ){
    userErrors {
      field
      message
    }
    confirmationUrl
    appSubscription {
      id
      lineItems {
        id
        plan {
          pricingDetails {
            __typename
          }
        }
      }
    }
  }
}`

**Comment by nozzlegear** [comment]
I wasn't aware that you could create a usage charge with a base recurring price, so this might be something new that's not yet implemented. I'll check it out and get back to you!
