### ISSUE TITLE
Not working on a WPF .NET Framework ( 4.7.2 ) Application

### ISSUE THREAD

**Issue by Stefano0871** [nozzlegear/ShopifySharp#646]
I suppose for this same kind of problem
[https://stackoverflow.com/questions/37641993/using-await-on-httpclient-in-wpf-project](url)

I need to do this kind of code to see it work

    private void Page_Loaded(object sender, RoutedEventArgs e)
    {
      productService = new ProductService(
        ShopifyHelper.CurrentShop.URL,
        ShopifyHelper.CurrentShop.Password
      );

      Task.Run(() =>
      {
        var result = productService.CountAsync();
        result.Wait();
      }
      ).Wait();
    }

**Comment by nozzlegear** [comment]
Just to be clear, the example code you posted does work or does not work? Unfortunately all of our HTTP calls in this package are async, but you could write a wrapper that does what you're doing in the background, so you don't have to manually do that for every single call you make:

```cs
public class SyncProductService : ShopifySharp.ProductService
{
	public SyncProductService(string domain, string accessToken) : base (domain, accessToken) { }
	
	/// <summary>
	/// Counts the number of products on a store. 
	/// </summary>
	public int Count()
	{
		int result = 0;
    	var countTask = base.CountAsync().ContinueWith(task => 
    	{
    		result = task.Result;
    	});
    	countTask.Wait();
    	
    	return result;
	}
}
```

Disclaimer: I'm not positive if this code above will work or result in a deadlock, this is just off the top of my head. I'd recommend [reading this article to make sure you don't run into deadlocks or UI freezing](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

**Comment by nozzlegear** [comment]
I should also add, I think your event handler can be converted to async right? I don't really work with WPF so I might be wrong, but I think you can change your example code to this:

```cs
private async void Page_Loaded(object sender, RoutedEventArgs e)
{
  productService = new ProductService(
    ShopifyHelper.CurrentShop.URL,
    ShopifyHelper.CurrentShop.Password
  );

  var result = await productService.CountAsync();

  // Do something with the result here
}
```

Which would avoid deadlocks by using pure async code.

**Comment by Stefano0871** [comment]
> Just to be clear, the example code you posted does work or does not work? Unfortunately all of our HTTP calls in this package are async, but you could write a wrapper that does what you're doing in the background, so you don't have to manually do that for every single call you make:
> 
> ```cs
> public class SyncProductService : ShopifySharp.ProductService
> {
> 	public SyncProductService(string domain, string accessToken) : base (domain, accessToken) { }
> 	
> 	/// <summary>
> 	/// Counts the number of products on a store. 
> 	/// </summary>
> 	public int Count()
> 	{
> 		int result = 0;
>     	var countTask = base.CountAsync().ContinueWith(task => 
>     	{
>     		result = task.Result;
>     	});
>     	countTask.Wait();
>     	
>     	return result;
> 	}
> }
> ```
> 
> Disclaimer: I'm not positive if this code above will work or result in a deadlock, this is just off the top of my head. I'd recommend [reading this article to make sure you don't run into deadlocks or UI freezing](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

My code work.
I made a simple wrapper of functions that are of interest to me, like this...

    static public int GetProductCount(ProductCountFilter filter = null, CancellationToken cancellationToken = default)
    {
      var service = new ProductService(
        ShopifyHelper.CurrentShop.URL,
        ShopifyHelper.CurrentShop.Password
      );

      var task = Task.Run(async () => {
        return await service.CountAsync(filter, cancellationToken);
      });
      task.Wait();

      return task.Result;
    }

**Comment by nozzlegear** [comment]
Okay, glad you got it working! At the moment I don't have any plans to add synchronous methods, so sadly WPF applications will have to continue using these kinds of wrappers around async. If you're able to upgrade to the latest version of .NET Framework I believe you can make your event handlers async though, which will make the package a lot easier to use.
