### ISSUE TITLE
List product variants based on filter

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#647]
Is it possible to list product variants on title or best is displayName on product variant ?

I want to present a list of product variants (not products) to the user. If he search on "Battery" he should be presented with all product variants that has battery in their title (including the title from product). So that Battery AAA - 5 pack will be shown.

The Battery is in the product title, but I want show all product variants that belong to these products.

**Comment by nozzlegear** [comment]
Hmm, I'm not sure if this is possible with the REST API, but I might be wrong. Some of the search stuff is undocumented so it's hard to discover what works, what doesn't work, and what works but isn't supposed to work/will be removed eventually. 

I could be wrong but I think you might be able to do this with the GraphQL API instead. If there's a way to do partial string searches with GraphQL (I'm not actually sure at the moment as I don't use it very much), then you'd be able to query those variants using ShopifySharp's GraphService class.
