### ISSUE TITLE
Deserialise Triggered Shopify Webhook Payload

### ISSUE THREAD

**Issue by stephenstroud** [nozzlegear/ShopifySharp#648]
After setting up a Shopify Webhook for any topic - which objects are used to deserialise the incoming triggered webhook request?

Can I use the below? However, it seems to be lacking properties received in the JSON payload... Perhaps something I need to create?

https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Entities/Order.cs

**Comment by nozzlegear** [comment]
Hey! You should be able to use the `Order` class to deserialize the webhook body, so long as the webhook you're dealing with is the "orders/updated" or "orders/created" webhook. Those send the full order object. If you're dealing with the "orders/deleted" webhook, then you're only going to get a partial object instead. 

What I typically do in my applications is deserialize the body into a `ShopifyObject` instance which only contains an `Id` property. Then I use the OrderService class to pull in the latest version of the order from Shopify's API. Doing it this way just ensures that I have the latest version of the order according to Shopify's API (just in case the webhooks are delivering slowly or out of order). 

```cs
var body = await Request.Body.ReadAsStringAsync();
var shopifyObject = ShopifySharp.Infrastructure.Serializer.Deserialize<ShopifySharp.ShopifyObject>(body);

// Pull in the order from the Shopify API
var orders = new OrderService(domain, accessToken);
var order = await orders.GetAsync(body.Id.Value);
```

Like I said though, you should be able to deserialize it directly into an Order if you prefer:

```cs
var order = ShopifySharp.Infrastructure.Serializer.Deserialize<Order>(body);
```

The choice in how you do it is really up to you. Let me know if that helps!

**Comment by stephenstroud** [comment]
@nozzlegear This was very helpful, thank you for your time and library!
