### ISSUE TITLE
origin location missing

### ISSUE THREAD

**Issue by mercu23sh** [nozzlegear/ShopifySharp#652]
Hi,

Can you please add the origin_location to the line_items?

"line_items": [
            {
                "id": 10144399229080,
                "admin_graphql_api_id": "gid://shopify/LineItem/10144399229080",
                "destination_location": {
                    "id": 3022198898840,
                    "country_code": "MX",
                    "province_code": "DF",
                    "name": "Pedro El Malo",
                    "address1": "Calle Veracruz",
                    "address2": "",
                    "city": "Ciudad de México",
                    "zip": "06140"
                },
                "fulfillable_quantity": 0,
                "fulfillment_service": "manual",
                "fulfillment_status": "fulfilled",
                "gift_card": false,
                "grams": 200,
                "name": "Minitablero Spalding",
                "origin_location": {
                    "id": 3022198866072,
                    "country_code": "MX",
                    "province_code": "MEX",
                    "name": "humanfactortest2",
                    "address1": "Bajío 360",
                    "address2": "",
                    "city": "México",
                    "zip": "06760"
                },
                "price": "850.00",
                "price_set": {
                    "shop_money": {
                        "amount": "850.00",
                        "currency_code": "MXN"
                    },
                    "presentment_money": {
                        "amount": "850.00",
                        "currency_code": "MXN"
                    }
                },
                "product_exists": true,
                "product_id": 6874811531416,
                "properties": [],
                "quantity": 1,
                "requires_shipping": true,
                "sku": "",
                "taxable": true,
                "title": "Minitablero Spalding",
                "total_discount": "0.00",
                "total_discount_set": {
                    "shop_money": {
                        "amount": "0.00",
                        "currency_code": "MXN"
                    },
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "MXN"
                    }
                },
                "variant_id": 40412629696664,
                "variant_inventory_management": "shopify",
                "variant_title": "",
                "vendor": "humanfactortest2",
                "tax_lines": [
                    {
                        "channel_liable": false,
                        "price": "136.00",
                        "price_set": {
                            "shop_money": {
                                "amount": "136.00",
                                "currency_code": "MXN"
                            },
                            "presentment_money": {
                                "amount": "136.00",
                                "currency_code": "MXN"
                            }
                        },
                        "rate": 0.16,
                        "title": "VAT"
                    }
                ],
                "duties": [],
                "discount_allocations": []
            },
            {
                "id": 10144399261848,
                "admin_graphql_api_id": "gid://shopify/LineItem/10144399261848",
                "destination_location": {
                    "id": 3022198898840,
                    "country_code": "MX",
                    "province_code": "DF",
                    "name": "Pedro El Malo",
                    "address1": "Calle Veracruz",
                    "address2": "",
                    "city": "Ciudad de México",
                    "zip": "06140"
                },
                "fulfillable_quantity": 0,
                "fulfillment_service": "manual",
                "fulfillment_status": "fulfilled",
                "gift_card": false,
                "grams": 15000,
                "name": "Balón Molten",
                "origin_location": {
                    "id": 3022198866072,
                    "country_code": "MX",
                    "province_code": "MEX",
                    "name": "humanfactortest2",
                    "address1": "Bajío 360",
                    "address2": "",
                    "city": "México",
                    "zip": "06760"
                },
                "price": "2800.00",
                "price_set": {
                    "shop_money": {
                        "amount": "2800.00",
                        "currency_code": "MXN"
                    },
                    "presentment_money": {
                        "amount": "2800.00",
                        "currency_code": "MXN"
                    }
                },
                "product_exists": true,
                "product_id": 6848670564504,
                "properties": [],
                "quantity": 1,
                "requires_shipping": true,
                "sku": "",
                "taxable": true,
                "title": "Balón Molten",
                "total_discount": "0.00",
                "total_discount_set": {
                    "shop_money": {
                        "amount": "0.00",
                        "currency_code": "MXN"
                    },
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "MXN"
                    }
                },
                "variant_id": 40326163529880,
                "variant_inventory_management": "shopify",
                "variant_title": "",
                "vendor": "humanfactortest2",
                "tax_lines": [
                    {
                        "channel_liable": false,
                        "price": "448.00",
                        "price_set": {
                            "shop_money": {
                                "amount": "448.00",
                                "currency_code": "MXN"
                            },
                            "presentment_money": {
                                "amount": "448.00",
                                "currency_code": "MXN"
                            }
                        },
                        "rate": 0.16,
                        "title": "VAT"
                    }
                ],
                "duties": [],
                "discount_allocations": []
            }
        ]

**Comment by nozzlegear** [comment]
`LineItem.OriginLocation` has been added in ShopifySharp v 5.12.0 on nuget!
