### ISSUE TITLE
Missing Shop property Address2

### ISSUE THREAD

**Issue by mercu23sh** [nozzlegear/ShopifySharp#653]
Hi,

Can you please add address2 property to the shop data?

https://shopify.dev/api/admin/rest/reference/store-properties/shop

HTTP/1.1 200 OK
{
  "shop": {
    "id": 690933842,
    "name": "Apple Computers",
    "email": "steve@apple.com",
    "domain": "shop.apple.com",
    "province": "California",
    "country": "US",
    "address1": "1 Infinite Loop",
    "zip": "95014",
    "city": "Cupertino",
    "source": null,
    "phone": "1231231234",
    "latitude": 45.45,
    "longitude": -75.43,
    "primary_locale": "en",
    **"address2": "Suite 100",**
    "created_at": "2007-12-31T19:00:00-05:00",
    "updated_at": "2021-07-01T14:27:35-04:00",
    "country_code": "US",
    "country_name": "United States",
    "currency": "USD",
    "customer_email": "customers@apple.com",
    "timezone": "(GMT-05:00) Eastern Time (US & Canada)",
    "iana_timezone": "America/New_York",
    "shop_owner": "Steve Jobs",
    "money_format": "${{amount}}",
    "money_with_currency_format": "${{amount}} USD",
    "weight_unit": "lb",
    "province_code": "CA",
    "taxes_included": null,
    "auto_configure_tax_inclusivity": null,
    "tax_shipping": null,
    "county_taxes": true,
    "plan_display_name": "Shopify Plus",
    "plan_name": "enterprise",
    "has_discounts": true,
    "has_gift_cards": true,
    "myshopify_domain": "apple.myshopify.com",
    "google_apps_domain": null,
    "google_apps_login_enabled": null,
    "money_in_emails_format": "${{amount}}",
    "money_with_currency_in_emails_format": "${{amount}} USD",
    "eligible_for_payments": true,
    "requires_extra_payments_agreement": false,
    "password_enabled": false,
    "has_storefront": true,
    "eligible_for_card_reader_giveaway": false,
    "finances": true,
    "primary_location_id": 905684977,
    "cookie_consent_level": "implicit",
    "visitor_tracking_consent_preference": "allow_all",
    "checkout_api_supported": true,
    "multi_location_enabled": false,
    "setup_required": false,
    "pre_launch_enabled": false,
    "enabled_presentment_currencies": [
      "USD"
    ]
  }
}

**Comment by nozzlegear** [comment]
Fixed in v5.14.0!
