### ISSUE TITLE
How can I mock/substitute/stub Shopifysharp services during unit tests ?

### ISSUE THREAD

**Issue by bilalyasin1616** [nozzlegear/ShopifySharp#654]
I am trying to write unit tests for an application that uses Shopifysharp for managing API calls to Shopify stores.
I am wandering how I can do the unit tests without actually calling the Shopify API. I have been looking into mocking using some mocking frameworks like NSubstitue or MOQ but I have read in few articles that mocking external types is not the best idea.
[Careful mocking types we don't own.](https://davesquared.net/2011/04/dont-mock-types-you-dont-own.html)
So I would like to know thoughts from someone in Shopifysharp's team that what will be the best approach for this. Thanks

**Comment by nozzlegear** [comment]
I'm currently working on adding an `IHttpClientFactory` to all ShopifySharp services, which would let you change the `HttpClient` and inject whatever responses you need for unit tests. Tracking in #369

**Comment by nozzlegear** [comment]
@bilalyasin1616 As for how to mock/substitute ShopifySharp, at the moment that's somewhat difficult because the package doesn't use interfaces for its API classes. That's something I want to add, it's just a lot of tedious copy/pasting of existing method signatures that I haven't had the time to do yet (tracking it here: #362).

In the meantime, you should be able to override any *Service class and make the methods return whatever you want for testing purposes. Then you'd be able to skip the calls to Shopify's API. Something like this:

```cs
public class MockOrderService : ShopifySharp.OrderService
{
    public MockOrderService() : base ("https://example.com", "fake access token")
    {
    
    }
    
    public override async Task<ShopifySharp.Order> GetAsync(long orderId, CancellationToken token = default)
    {
        // Skip the calls to Shopify's API and just return whatever you need for your tests
        return new ShopifySharp.Order
        {
            // ...
        };
    }
}
```

This still doesn't work very well for dependency injection, though, since all *Service classes are scoped to individual domains/access tokens.

**Comment by nozzlegear** [comment]
You can now use a global `IHttpClientFactory` and set instance-specific `HttpClient` with ShopifySharp v5.14.0 on Nuget. Let me know if you have any further questions!

**Comment by bilalyasin1616** [comment]
@nozzlegear thanks, appreciate the help. For the time being I substituted the Shopifysharp services using NSubstitute and override the virtual functions to return dummy object. Will try it out soon.

**Comment by akashvekariya** [comment]
@bilalyasin1616 It seems you found a workaround to mock it using NSubstitute, we're using the same library and I am struggling with logic. Can you please give me some idea how you mocked it? Here's my function

```C#
public async Task<Response<CustomerList>> GetCustomerDetailsAsync(
        CustomerDetailsRequest customerDetailsRequest,
        AuthorizedRequest authorizedRequest)
    {
        var customerService = new CustomerService(
            authorizedRequest.Configurations?.InstanceUrl,
            authorizedRequest.Credentials?.AccessToken)

        var filter = new CustomerSearchListFilter
        {
            Query = QueryBuilder.GenerateQueryStringEmailPhone(customerDetailsRequest.EmailAddress,
                customerDetailsRequest.PhoneNumber)
        };

        var customerResponse = await customerService.SearchAsync(filter);
        return new CustomerList() {
               Customers = customerResponse.Items
        };
    }
```

I was trying to mock CustomerService Initially
