### ISSUE TITLE
Deprecated field on Metafield object

### ISSUE THREAD

**Issue by Stefano0871** [nozzlegear/ShopifySharp#656]
As of API version 2021-07, the value_type field on the Metafield object was deprecated.

You should use the type field instead of the value_type field to access or set the type of a Metafield object. For more information about this transition, refer to this changelog entry.

**Your Metafiled entity does not respect this change.**

 /// <summary>
        /// States whether the information in the value is stored as a 'string' or 'integer.'
        /// </summary>
        [JsonProperty("value_type")]
        public string ValueType { get; set; }

**Comment by nozzlegear** [comment]
Marked as deprecated in v5.14.0 on nuget. Thanks!
