### ISSUE TITLE
Apps not working on Safari - BUG

### ISSUE THREAD

**Issue by zeshan-xeesoft** [nozzlegear/ShopifySharp#659]
@nozzlegear embedded apps are not working in Safari browser, I have mentioned this issue few weeks back but we still do not find any luck in solving this issue. It was marked as question but in actual it is bug which we need to fix earliest possible. 

If you have updated your book please share latest version of book so we can follow if any new changes are required. 

Last issue reported for same issue : [Cookie based authentication not working in safari](https://github.com/nozzlegear/ShopifySharp/issues/650)

**Comment by nozzlegear** [comment]
Hey Zeshan! I got your email previously, I'll send you the link to the latest material. The sample projects I have in there work on Safari. 

--
Josh Harms

**Comment by Uffman** [comment]
I get the following error in Safari when I wanna redirect the user to the authorization URL. Chrome, Edge, Firefox work fine

![image](https://user-images.githubusercontent.com/1281907/134868095-0a476400-cd1c-4d1c-a5ef-cd7b112ef95e.png)

**Comment by clement911** [comment]
Are you using Bridge or EASDK? If so you need to redirect the top window.
See https://shopify.dev/apps/auth/oauth

![image](https://user-images.githubusercontent.com/3426504/134883806-7289a362-9517-4289-8998-8e910b0d6913.png)

**Comment by Uffman** [comment]
AppBridge,
found out that the problem was because I was redirecting user with code
`return new RedirectResult(authUrlCheck.AbsoluteUri)`

my flow is like this:
/Install -> 
build authorize url and redirect to
/Authorize
check if user is authorized and redirect to ->
/Dashboard
get some info and load Razor page view

The problem I am facing now is that the view gets loaded outside of Shopify and not as embeded

**Comment by clement911** [comment]
You must use https://shopify.dev/apps/tools/app-bridge/actions/navigation/redirect

**Comment by clement911** [comment]
See https://shopify.dev/apps/tools/app-bridge/getting-started#authenticate-with-oauth

**Comment by Uffman** [comment]
Hi @clement911 
thank you for the help
this was the solution:

`
Redirect.create(app).dispatch(Redirect.Action.APP, "/wwwroot/index.html");    
`

**Comment by clement911** [comment]
no worries, please close if the issue is fixed.

**Comment by zeshan-xeesoft** [comment]
> Hi @clement911
> thank you for the help
> this was the solution:
> 
> `Redirect.create(app).dispatch(Redirect.Action.APP, "/wwwroot/index.html"); `

@Uffman is your app working fine in safari now ?

**Comment by Uffman** [comment]
@zeshan-xeesoft yes it is.
Problem was, that when I called app bridge second time, I still called it like this
`Redirect.create(app).dispatch(Redirect.Action.REMOTE, "@ViewBag.IndexUrl");`
this has to be done only the first time you call for authorize

**Comment by zeshan-xeesoft** [comment]
awesome, it seems you are using app bridge here, correct me if I am wrong as we have not yet shifted our app to app bridge change due to which we are unable to use it on safari

**Comment by zeshan-xeesoft** [comment]
what changes we need to made in app in order to use app bridge and kill this safari issue forever

**Comment by Uffman** [comment]
can really say cause I don't know how your app is structured. In our case this change and removing Redirect to authorization url was all it needed

**Comment by zeshan-xeesoft** [comment]
just dropped you an email, I hope we can discuss details and then I will write some public app as well so it can help other developers
