### ISSUE TITLE
ListFilter<Customer> is inaccessible due to its protection level

### ISSUE THREAD

**Issue by kattgsilva** [nozzlegear/ShopifySharp#660]
Hi,
I'm trying to use `IEnumerable<Customer> customers = await service.SearchAsync (new ListFilter<Customer> { })` however i get a inaccessible error due to its protection level. Is there any way i can filter customers by name and phone using this method?

**Comment by nozzlegear** [comment]
Hey @kattgsilva, sorry for the late reply. Did you get this working? The `ListFilter` was made public recently, so you should be able to invoke a new instance of it with one of the latest versions of ShopifySharp. I'd recommend you use the `CustomerListFilter` instead, which has some supported properties for filtering customers built in already.
