### ISSUE TITLE
Get List of All Order 

### ISSUE THREAD

**Issue by shafaqat309** [nozzlegear/ShopifySharp#661]
Hi, I need some help in getting all orders.
I am using following code and trying to get all orders.

`
      public class OrderController
      {
        private OrderService service = null;

        public OrderController(string shopURL, string shopAccessToken)
        {
            service = new OrderService(shopURL, shopAccessToken);
        }
        public List<Order> GetAllOrders()
        {
            List<Order> allOrders = new List<Order>();

            var all_orders = service.ListAsync().Result; //return only 1

            //following code also return only 1
            ListResult<Order> batch = service.ListAsync(new ListFilter<Order>("", 250)).Result;
            while (true)
            {
                allOrders.AddRange(batch.Items);
                if (!batch.HasNextPage)
                {
                    break;
                }
                batch = service.ListAsync(batch.GetNextPageFilter()).Result;
            }
            return allOrders;
        }
    }

`

but it returns only unfulfilled orders. I need list of all order does not matter what the status is

**Comment by clement911** [comment]
You need to filter with status="any"

**Comment by shafaqat309** [comment]
Where do I need to apply that filter? List filter has these 3 options..

![image](https://user-images.githubusercontent.com/2289283/129445022-37222e43-a05a-43f7-aa3a-1de52247abe5.png)

**Comment by shafaqat309** [comment]
Got it

this worked

var of = new OrderListFilter() { Status = "any", Limit = 250 };
            ListResult<Order> batch = service.ListAsync(of).Result;

**Comment by xplertor** [comment]
Filter status doesn't work and in an item, the variable doesn't find a status variable. (I try found orders open and paid for insert in another system)
