### ISSUE TITLE
IRequestExecutionPolicy is synchronous, but LeakyBucketExecutionPolicy is asynchronous

### ISSUE THREAD

**Issue by cannunziello** [nozzlegear/ShopifySharp#670]
I'm trying to implement the LeackyBucketExecutionPolicy, but I'm getting a compilation error because the signature of the Run Task is not async. I don't have extensive experience in this arena so I could just be missing something.

#669

**Comment by clement911** [comment]
How do you use it?
You're not supposed to call Run directly.

Just do this: `ShopifyService.SetGlobalExecutionPolicy(new LeakyBucketExecutionPolicy())`

**Comment by cannunziello** [comment]
Sorry I didn't mention the actual error. I am just trying to add a global execution policy, but  I'm getting a compilation error in LeakyBucketExecutionPolicy. "'LeakyBucketExecutionPolicy' does not implement interface member IRequestExecutionPolicy.Run<T>(CloneableRequestMessage requestMessage, ExecuteRequestAsync<T> executeRequestAsync, CancellationToken cancellationToken)"

![image](https://user-images.githubusercontent.com/84792292/135468984-9299e4b2-1428-4f32-adb0-aea9bdbe4c80.png)

Why wouldn't it be recognizing that as the interface member?

**Comment by clement911** [comment]
Have you copied the code of the LeakyBucketPolicy into your project? Why don't use it from the library itself?

**Comment by cannunziello** [comment]
I was using version 5.09 which didn't have the LeakyBucketPolicy classes yet, but I updated the package and am now referencing the library directly. When I updated to the current version the "not implemented" error disappeared. as well.

I'm not exactly what has changed to cause it to work, but thank you for your help and prompt responses!
