### ISSUE TITLE
List of all Orders is now returning 0 after upgrading NUGET package to 5.13.1

### ISSUE THREAD

**Issue by vince760** [nozzlegear/ShopifySharp#679]
Hi everyone, 

Ran into an issue after upgrading nuget package to 5.13.1 with all orders, which was previously working. 

Now it returns 0 orders, anyone else see this issue or know what is going on with it? 

Thanks. 

`[HttpGet("orders/shopifyShopName")]
        public async Task<ActionResult<ItemResponse<int>>> ListAllOrders(string shopifyShopName)
        {

            int code = 200;
            BaseResponse response = null;
            try
            {
                string accessToken = _shopify.GetTokenByShopName(shopifyShopName);

                if (shopifyShopName != null)
                {
                    var filter = new OrderListFilter();
                    filter.Status = "any";
                    filter.Limit = 250;
                    var orders = new List<Order>();
                    var service = new OrderService(shopifyShopName, accessToken);
                    var page = await service.ListAsync(filter);

                    while (true)
                    {
                        orders.AddRange(page.Items);

                        if (!page.HasNextPage)
                        {
                            break;
                        }

                        page = await service.ListAsync(page.GetNextPageFilter());
                    }

                   
                    if (page != null)
                    {

                        response = new ItemResponse<ListResult<Order>> { Item = page };

                    }
                    else
                    {
                        code = 404;
                        response = new ErrorResponse("No orders found. ");
                    }

                }
            }
            catch (Exception ex)
            {
                code = 500;
                Logger.LogError(ex.ToString());
                response = new ErrorResponse(ex.Message);
            }
            return StatusCode(code, response);

        }

`
![orders](https://user-images.githubusercontent.com/26665765/138563317-6044b101-9c3d-4bc8-8105-6e633eac3299.JPG)

**Comment by vince760** [comment]
> Hey @vince760, are you still having this problem? I tried to replicate it but it seems to be working for me.

Thanks for getting back to me. Unfortunately I am still having this issue, I have tried several different ways of doing this per the previous questions I read through.

**Comment by nozzlegear** [comment]
Okay, let's see if we can get to the bottom of it. The first thing I'd do is confirm that the store you're connecting to has open orders to list. If they're all closed/archived, they won't show up in the result unless you set the `Status = "any"` property. On top of that, if all the orders are older than 60 days, Shopify will not let you access them unless you have a special API permission for which you need to be approved by contacting their support team.

--
Josh Harms

**Comment by vince760** [comment]
I have verified that the test shop I am using has permissions, and has orders that are less than 60 days. It was gathering the list and displaying it fine, but as soon as I upgraded my Nuget package, the list just shows null. Ill verify everything again today just to make sure I did not skip over anything and share some screenshots.
