### ISSUE TITLE
Requesting only specified fields

### ISSUE THREAD

**Issue by MalikDrako** [nozzlegear/ShopifySharp#68]
Is there a way to request only a subset of fields?
The API docs give this example:
`GET /admin/orders.json?fields=created_at,id,name,total-price`

Edit: After looking through the code, I found at least some have a fields parameter for the Get function, but not for the List function. In my case, I want to get basic info about all paid & unfulfilled orders, then get full info from specific orders on that list.

**Comment by nozzlegear** [comment]
Hey @MalikDrako, like you said, you should be able to pass an extra "fields" parameter to most Get functions. For List functions, the "fields" parameter is moved into whichever filter (e.g. `ShopifyOrderFilter`) the function accepts.
