### ISSUE TITLE
Is ShopifySharp compatible with App Bridge 2.0?

### ISSUE THREAD

**Issue by dgivoni** [nozzlegear/ShopifySharp#680]
Hi,
We've received an email from Shopify saying that our app is using the Embedded App SDK and that we need to change and use the App Bridge 2.0 before end of year otherwise the app will be delisted.
Since our app is implemented with ShopifySharp my question is if ShopifySharp is compatible with this upgrade as it's not clear to me how we're using the Embedded App SDK ourselves.
Regards,
David

**Comment by nozzlegear** [comment]
Hey! I got the same email. ShopifySharp itself is compatible and you won’t have to change anything. The embedded app sdk is something that’s used on the front end when your app is loaded inside a merchant’s admin dashboard — it’s the JavaScript script that’s used to show things like loading dialogs, buttons, etc. 

Basically that script needs to be replaced with their app bridge 2.0 script, and if your app uses cookies in the admin dashboard it’ll have to start using their session stuff instead. I’m planning on writing a migration guide for this soon, but that’s the gist of it.

--
Josh Harms

**Comment by dgivoni** [comment]
Ok, thank you very much, that was very helpful.
