### ISSUE TITLE
Application closes executing the fulfill CreateAsync method

### ISSUE THREAD

**Issue by VerdaderoKiwi** [nozzlegear/ShopifySharp#681]
Hello, and first of all, congrats for you ShopyfySharp. Thanks to it and to you, i can make the application that i need.

I'm using different methods to get information from Shopyfy using your ShopifySharp module, and it works perfect! I'm using the ProductService, the LocationService, the InventoryLevelService (to list and set), the OrderService,... but now, i'm trying to fulfill an order and when i execute the CreateAsync method, de application closes and stop the execution. Can you help me?

My code is here:
```
public async Task<string> fulfill(Order order)
{
        FulfillmentService service = new FulfillmentService(url, pass);
        List<LineItem> lines = new List<LineItem>();

        foreach (OrderLine line in order.lines) {
            lines.Add(new LineItem { Id = line.id, Quantity = (int)line.quantity });
        }
       Fulfillment fulfillment = new Fulfillment()
       {
          TrackingCompany = order.tracking_comp,
          TrackingUrl = order.tracking_url,
          TrackingNumber = order.trackin_number,
           LineItems = lines
       };
       /***************** \/ HERE IS WHERE THE EXECUTION STOPS \/ ****************/
       fulfillment = await service.CreateAsync(order.id, fulfillment);
}
```
The order.id field is filled with the long number returned previously when y got the orders in the id field in order to import to the local application.

After that i tried to do a simple call only with your example
```
            Fulfillment fulfillment = new Fulfillment()
            {
                TrackingCompany = "Jack Black's Pack, Stack and Track",
                TrackingUrl = "https://example.com/123456789",
                TrackingNumber = "123456789"
            };
            fulfillment = await service.CreateAsync(order.id, fulfillment);
```
But with identical results, the application out when executes the CreateAsync method without any response (no Exception catched either). I tested that with breakpoints.

Can you help me please?

Thanks,

Marcos.

**Comment by VerdaderoKiwi** [comment]
Hello again, after writting this issue i was searching in this forum for an issue like this and i found another that has a problem quite similar and it works!

The problem was that i must complete OrderId and LocationId fields INSIDE the Fulfillment objet.

Until now, i saw the order id like a parameter in the CreateSync method, but i must include this in de Fulfillment object that i send in the CreateAsync too. In the code above, i delete the LocationId, but i was sending too.

Thanks for all!

Marcos

**Comment by nozzlegear** [comment]
Glad you got it working!
