### ISSUE TITLE
missing cutomer id in customer object and no address id in address object

### ISSUE THREAD

**Issue by nob2b** [nozzlegear/ShopifySharp#688]
I can't find cutomer id in customer object:
https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Entities/Customer.cs

I can't find address id in address object:
https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Entities/Address.cs

are these bugs?

**Comment by nozzlegear** [comment]
Hey! Almost all of the entity classes in ShopifySharp will extend a base `ShopifyObject` class, which has the `Id` and the `AdminGraphQLAPIId` properties. [You can see that class here.](https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Entities/ShopifyObject.cs)
