### ISSUE TITLE
Strange compile error when upgrading to 5.14

### ISSUE THREAD

**Issue by clement911** [nozzlegear/ShopifySharp#689]
I'm getting a pretty strange error when upgrading to 5.14.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8032	An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from C:\Users\cleme\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\analyzers\dotnet\roslyn4.0\cs\Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	NitroCharts.Plugin	C:\Dev\BetterReports\NitroCharts.Plugin\CSC	1	N/A

![image](https://user-images.githubusercontent.com/3426504/142375605-f1deaa30-8e38-42a9-9ea9-27f683e8a552.png)

**Comment by clement911** [comment]
My project is set up to treat warning as errors. If I remove this, it compiles ok. These warnings seem to somehow come from ShopifySharp. 😕

**Comment by clement911** [comment]
That was in VS 2019 by the way.
I just installed VS 2022 and the warning goes away when building with 2022... The issue persists in 2019 though...

**Comment by nozzlegear** [comment]
How bizarre! Do you know if using the dotnet CLI to build the project does the same thing?

**Comment by clement911** [comment]
I'm not really sure. I never use the CLI and always build from VS. 
I guess it must be some code analyzer magic thing...
