### ISSUE TITLE
Update Json.NET dependency to newer version

### ISSUE THREAD

**Issue by oleksii-vynnychenko** [nozzlegear/ShopifySharp#69]
This ShopifySharp library (btw, it's good and helpful, thank you) currently references Newtonsoft.Json v7.0 . It's kind of an old version (at this point 9.0.1 is up) and makes it impossible to use newer version of Json.NET if you add ShopifySharp as NuGet package. Maybe you can update Json.NET version dependency in future releases.

**Comment by oleksii-vynnychenko** [comment]
I just found out that you can actually specify version range in NuGet package dependency, so others can actually use newer versions of libraries even when other Nuget package that uses stops development.

http://stackoverflow.com/questions/7772346/how-to-specify-specific-dependency-version-in-nuspec

https://docs.nuget.org/ndocs/create-packages/dependency-versions

If you would specify version range for ShopifySharp dependencies - I'd be very glad. Thank you

**Comment by nozzlegear** [comment]
Thanks for the suggestion! I can't think of any problems with at least allowing a range of versions. I'll need to test it first, and if it all goes well I'll publish an update in the next week or so.

**Comment by oleksii-vynnychenko** [comment]
I haven't actually created Nuget package myself and not a Nuget expert, but it seems like you don't have dependency specified in `nuspec` at all, so it just expects `Newtonsoft.Json.dll` in bin directory with version specified in your lib project. And if it doesn't find needed version - it just breaks.
You need specify your external references in `nuspec`. If I'll have time I'll try to test it myself on this or next weekend.

**Comment by nozzlegear** [comment]
Newtonsoft.Json dependency has been updated to 10.0.1 in the 4.0 branch.
