### ISSUE TITLE
Missing access-scopes in AuthorizationScope enum

### ISSUE THREAD

**Issue by bantikyan** [nozzlegear/ShopifySharp#692]
Hello, I need to have access to `read_discounts, write_discounts` from GraphQL
Those scopes are missing from `enum AuthorizationScope`, and I have a problem with `AuthorizationService.BuildAuthorizationUrl`
Can you please add missing scopes?

**Comment by nozzlegear** [comment]
Hey @bantikyan I'm adding them in right now, but just in case you haven't been able to work around this yet, there's an overload for `AuthorizationService.BuildAuthorizationUrl` that will accept the authorization scopes as strings instead of enums:

```cs
var scopes = new List<string>{ "read_discounts", "write_discounts" };
var authUrl = AuthorizationService.BuildAuthorizationUrl(scopes, myShopifyUrl, shopifyApiKey, redirectUrl, state);
```

**Comment by nozzlegear** [comment]
These enums have been added in 5.14.3 on Nuget.
