### ISSUE TITLE
Shopify FulFilment Cart Hook Orders 

### ISSUE THREAD

**Issue by shmoulana** [nozzlegear/ShopifySharp#694]
Dear Guys

I have one orders which has two fulfilment open and was trying to partially fulfil the orders our API since the whole order api is not working for two fulfillments  but it gives the following issue

ShopifySharp.ShopifyException: (422 Unprocessable Entity) base: An error occurred, please try again
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass27_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.DefaultRequestExecutionPolicy.Run[T](CloneableRequestMessage request, ExecuteRequestAsync`1 executeRequestAsync, CancellationToken cancellationToken, Nullable`1 graphqlQueryCost)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, CancellationToken cancellationToken, HttpContent content, String rootElement, Dictionary`2 headers)
   at ShopifySharp.FulfillmentService.CreateAsync(Int64 orderId, Fulfillment fulfillment, CancellationToken cancellationToken)
   at ShopifyConsole.Program.Main(String[] args) in

do you have any idea ?

The code will be like one below

``

var myOrderId = 4594190778583;

            try
            {

                var fulService = new FulfillmentService(StoreUrl, StoreKey);

                var fulOrderService = new FulfillmentOrderService(StoreUrl, StoreKey);
                var allFulfillments = fulOrderService.ListAsync(myOrderId).GetAwaiter().GetResult();

                foreach (var fulfillmentOrder in allFulfillments)
                {
                    if (fulfillmentOrder.Status.Equals("open"))
                    {
                        var fulfillment = new Fulfillment
                        {
                            TrackingUrl = "https://www.fedex.com/fedextrack/?trknbr=547502448758",
                            TrackingNumber = "547502448758",
                            LocationId = 35207512150,
                            OrderId = fulfillmentOrder.Id,
                            NotifyCustomer = true
                        };
                        fulfillment = fulService.CreateAsync(Convert.ToInt64(myOrderId), fulfillment).GetAwaiter()
                            .GetResult();
                    }
                }

            }
            catch (Exception exception)
            {
                var myMessage = "Test";
            }

**Comment by nozzlegear** [comment]
@shmoulana Hey, sorry it took so long to get back to you. Are you still having this issue? I'm not sure what the problem might be except that Shopify is complaining about something being wrong with the request body. 

If you're still having the problem, could you please post the exception's `RawBody` value here? That should shed some light on the issue.

```cs
try
{
	// Create fulfillment here
}
catch (ShopifyException ex)
{
	Console.WriteLine(ex.RawBody);
}
```
