### ISSUE TITLE
Free of charge plan

### ISSUE THREAD

**Issue by aboodh95** [nozzlegear/ShopifySharp#696]
Hi,

In the App plan, I do have free of charge one with limited access, but onece I'm selecting this one I'm getting an error that price can't be 0.

Any ideas

**Comment by Matt-Kaminski** [comment]
You don't have to create a charge at all if your app can work without it. App itself should determine if and what charge was accepted and work accordingly.

**Comment by aboodh95** [comment]
Thanks a lot for these details, I was doing it wrong as charge with 0 value
