### ISSUE TITLE
Updating inventory

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#697]
When using the InventoryLevelService ListAsync, will it return the locations sorted?

This because we want to update the default location (if more than one location).

Anyone who knows how this works?

**Comment by davidkdb** [comment]
Anyone

**Comment by nozzlegear** [comment]
Hey @davidkdb, they should be sorted by their id, I think newest to oldest. However, if you're looking for the shop's default location, you'll want to first get the shop's details with the `ShopService` and then look at the shop's `PrimaryLocationId`:

```cs
var shopService = new ShopService(domain, token);
var shop = await shopService.GetAsync();
var primaryLocationId = shop.PrimaryLocationId.Value;
```
