### ISSUE TITLE
Fulfillment Update exception (404 Not Found)

### ISSUE THREAD

**Issue by VerdaderoKiwi** [nozzlegear/ShopifySharp#703]
Hello, i am having a problem updating fulfillments. All is working fine (create, get orders, completing fulfillments,,...) excepts this. I need to update the tracking info but i can't. Here is the code:

            FulfillmentService service = new FulfillmentService(url, pass);
            Fulfillment fulfillment;
            
            fulfillment = await service.UpdateAsync(order_id, fulfillment_id, new Fulfillment { 
                    TrackingCompany = trkComp,
                    TrackingNumber = trkNum,
                    TrackingUrl = trkUrl
             });

It throws an exception: 404 Not Found

Could i modify a fulfillment line items with this? I need sometimes to cancel some fulfillment lines and i don't see any method to do that.

Thanks!

Marcos,

**Comment by jeffyzxc** [comment]
Have u resolved this? I am having the same issue but with metafiled Service

**Comment by nozzlegear** [comment]
@jeffyzxc Were you able to get your metafields working? If not, please open a new issue here and I'd be happy to help!

**Comment by VerdaderoKiwi** [comment]
Hello and thanks for the answer. I solved it @jeffyzxc, thanks so much. The problem was the id of the order i was trying to update. I was sending the order number, instead of the order id.

This was the same problem in other functions.

Thanks!

**Comment by nozzlegear** [comment]
Awesome, glad you got it working!
