### ISSUE TITLE
Event object de-serialization error due to Arguments property

### ISSUE THREAD

**Issue by moxplod** [nozzlegear/ShopifySharp#705]
Shopify event object's property [argument ](https://github.com/nozzlegear/ShopifySharp/blob/22c0998f9defabb68165511efaa57c1b92e15f7a/ShopifySharp/Entities/Event.cs#L16) is specified as `IEnumerable<string>` but can have a nested structure. 
Which throws JSON serialization errors. In my case the following error:  

`{"Error reading string. Unexpected token: StartObject. Path 'events[0].arguments[0]'."}`

This is the json that is throwing this error: 

![image](https://user-images.githubusercontent.com/4554395/147862277-ab12253c-15cb-4735-95b7-eedab82b26d4.png)

**Comment by nozzlegear** [comment]
Ah that’s definitely a bug. Good catch! I’ll write a fix for this once I’m back from vacation this coming week.

--
Josh Harms

**Comment by moxplod** [comment]
Thank you,
I have changed that to IEnumerable<object> for now locally to unblock.

**Comment by nozzlegear** [comment]
Fixed in 5.14.3!
