### ISSUE TITLE
Is there a way to update the inventory level using SKU and location Id?

### ISSUE THREAD

**Issue by jhunexjun** [nozzlegear/ShopifySharp#718]
We have new requirement to update the inventory level by SKU and location id not by InventoryItemId. How can I achieve that?

**Comment by nozzlegear** [comment]
Hey @jhunexjun, sorry for the extremely late reply. Did you ever manage to get this working?

**Comment by amerina** [comment]
no you can‘t,see [Shopify Doc](https://shopify.dev/api/admin-rest/2022-10/resources/inventorylevel) 
inventory qty only care about InventoryItemId

**Comment by jhunexjun** [comment]
This is how I do it.

```
InventoryLevel response = await _inventoryLevelService.SetAsync(new InventoryLevel
 {
          LocationId = location.Id,
          Available = 100,
          InventoryItemId = productVariant.InventoryItemId
});
```

I wrote this [here](https://github.com/nozzlegear/ShopifySharp/issues/731#issuecomment-1108996273)
