### ISSUE TITLE
SmartCollection Support

### ISSUE THREAD

**Issue by ripteqdavid** [nozzlegear/ShopifySharp#72]
Hi All,

I'm just trying your library for the first time and I'm trying to get a list of CustomCollections and SmartColections.  Is there any support for SmartCollections in the library or am I missing something?

Great work!

Cheers,
Dave

**Comment by nozzlegear** [comment]
Hey Dave, I could have sworn we already had support for SmartCollections, but it looks like that's not correct. I'll make sure it gets in the lib, probably over the weekend.

**Comment by ripteqdavid** [comment]
Hi Joshua,

That is awesome!  Thanks so much.

Cheers,
Dave

​David Archer  |  +61 (0) 411 888-840  |   www.ripteq.com.au<http://www.ripteq.com.au>      |     Enterprise Software Solutions

**Comment by ripteqdavid** [comment]
Hi Joshua,

Just wondering how you went with the SmartCollections?  

Cheers,
Dave

**Comment by nozzlegear** [comment]
Hi Dave, I've just finished implementing the SmartCollections service. It's going to be merged in with PR #75 within the next day or two, I just want to finish adding one more feature to the PR first.

**Comment by nozzlegear** [comment]
Smart Collections are now available on Nuget with ShopifySharp v3.1.0. Thanks for the feature request!
