### ISSUE TITLE
Missing properties in Order object

### ISSUE THREAD

**Issue by Fengnnn** [nozzlegear/ShopifySharp#720]
In the Order object, it's missing two properties we need:
GateWay and SourceUrl

We need those two proerties in order to switch to use shopifysharp in our production.
Can you please help us to add support to those two properties? or is there a way we can contribute ?

Thank you.
Feng

**Comment by nozzlegear** [comment]
Hey @Fengnnn! As long as the properties are documented by Shopify on their order api documentation page, I'd be happy to add the missing properties. If you're interested you can send a pull request for this package that adds the new properties and I'll merge it in, otherwise I'll add them myself as soon as I have time!

**Comment by Fengnnn** [comment]
@nozzlegear I would love to make contribution to this Repro. i will try to create a pull request for this.
BTW, we are really looking forward to use shopifysharp in our project (with .netcore 3.1 function). However, we couldn't make it work due to the httpclient 6 dependecy. 
is that possible we can have a seperate version which allow us to inject the httpclient ourself ?
Thank you .

**Comment by Fengnnn** [comment]
@nozzlegear After I check the order model with the shopify model version 2021-10. 
 
I found the shopifysharp model has all the properties except two deprecated one(which what we was looking for).
After dicusssed with the team, we decided to give up those two deprecate properties on our project as well. 
Which mean you can close this issue here.
We will still looking forward to use this library and make contribution to this repro. 
Thanks so much.

**Comment by jegtugado** [comment]
Excuse me for adding to this but I noticed that on https://shopify.dev/api/storefront/2022-01/objects/Order#field-order-totalpricev2 there are several **v2** fields that I do not see on the current ShopifySharp Order entity. Leaving this here in case someone knows better as I've just started looking into Shopify.

**Comment by nozzlegear** [comment]
Thanks for the tip @jegtugado! Sorry for the very late reply. I just had a look at the docs and it looks like those properties are for the graph API. ShopifySharp can use the graph API, but most of its services and entities use the rest API by default, so we're good in this case!
