### ISSUE TITLE
Is there any way to know that there are API changes in the currently installed package version?

### ISSUE THREAD

**Issue by Smartisa** [nozzlegear/ShopifySharp#725]
For example: [https://github.com/nozzlegear/ShopifySharp/issues/514#issuecomment -647780033](https://github.com/nozzlegear/ShopifySharp/issues/514#issuecomment-647780033)
API changes have been made in version 5.0. How can developers know which version is correct and which version is wrong?

**Comment by nozzlegear** [comment]
Hey @Smartisa! Can you clarify what you mean by API changes? Do you mean API changes to ShopifySharp itself (e.g. methods are added/changed/removed), or Shopify's own API changes? 

If you mean changes to ShopifySharp, I try to always add release notes [on the releases page here on GitHub](https://github.com/nozzlegear/ShopifySharp/releases) with all of the included changes and the issues/pull requests behind them. 

For changes to the Shopify API, you'll have to [look at the table on the readme](https://github.com/nozzlegear/ShopifySharp#api-support) which is updated whenever ShopifySharp begins targeting a new version of Shopify's API.

**Comment by Smartisa** [comment]
> Hey @Smartisa! Can you clarify what you mean by API changes? Do you mean API changes to ShopifySharp itself (e.g. methods are added/changed/removed), or Shopify's own API changes?
> 
> If you mean changes to ShopifySharp, I try to always add release notes [on the releases page here on GitHub](https://github.com/nozzlegear/ShopifySharp/releases) with all of the included changes and the issues/pull requests behind them.
> 
> For changes to the Shopify API, you'll have to [look at the table on the readme](https://github.com/nozzlegear/ShopifySharp#api-support) which is updated whenever ShopifySharp begins targeting a new version of Shopify's API.

Thanks!
