### ISSUE TITLE
CreateAsync Order fails api rate after 4 orders are added

### ISSUE THREAD

**Issue by Jusbal16** [nozzlegear/ShopifySharp#726]
I'm trying to add orders to Shopify via API (with ShopifySharp), but after 4 orders are added I always get an error.
```
System.AggregateException: 'One or more errors occurred. ((429 Too Many Requests) Exceeded order API rate limit, please try again in a minute. Upgrade to a paid account to remove this limit.)'

```
code:
```
        public async Task AddOrder(Order order)
        {
            try
            {
                Thread.Sleep(1000);
                await orderService.CreateAsync(order);
            }
            catch (ShopifyRateLimitException e)
            {
                await Task.Delay(10000);
                await orderService.CreateAsync(order);
            }

        }
```
```
var taskOrders = AddOrder(order);
taskOrders.Wait();
```

I know there is a rate that allows 2 requests/second, that's why I have Thread.Sleep(1000) (also tried Task.Delay).

Before this call, no API call is made to Shopify.
And it always lets you add 3-4 orders and then error pops up.

But for example, when I'm deleting orders one by one, everything works fine (50 orders in 1 min) with the same implementation, just for deleting.

Also, I tried changing policy to "RetryExecutionPolicy" or "SmartRetryExecutionPolicy" provided by ShopifySharp. 

Tried changing delay times, but even after 10-sec error still pop up.

App on shopify has all rights.

**Comment by clement911** [comment]
If I recall, dev stores have quite stringent limits on how many orders can be created, so I'd say it's likely you're hitting dev stores limits that don't apply to paid stores.

**Comment by Jusbal16** [comment]
> If I recall, dev stores have quite stringent limits on how many orders can be created, so I'd say it's likely you're hitting dev stores limits that don't apply to paid stores.

mhh, quite strange, because I have 0 orders. then run a program, 4 are added and an error pops up. then run it again and the same 4 orders were added (total 8 now.)
I tried also some looping for more understanding; (printing loop means error pop up)
![image](https://user-images.githubusercontent.com/61379675/156917132-069a2caf-ada9-4c92-9275-8f6633e634bb.png)

results:
![image](https://user-images.githubusercontent.com/61379675/156917043-a8d77216-928a-4a79-ac9b-28e150fe8254.png)

**Comment by Jusbal16** [comment]
for more info: 
I'm still stuck on this stuff, but it's not this lib.
tried making a request with the postman, same error, 4 orders are allowed to add, then on 5 error pops up

**Comment by Jusbal16** [comment]
Problem not solved, but not this libs problem
