### ISSUE TITLE
InventoryQuantity

### ISSUE THREAD

**Issue by nturini-cascinanet** [nozzlegear/ShopifySharp#729]
Hi everybody, maybe this is a stupid question but i'm not able to find a solution..
I'm using ShopifySharp from about 2 year to sincronize products and orders with my application, to set the stock quantity of a product i'm using the InventoryQuantity field in product, it works when you have only one location but didn't work when you have more, furthermore i understand that this field will be deprecated, so i'm trying to improve my integration but i'm not able to find the correct way to sincronize the quantity, can you explain it to me?

**Comment by darkstar74** [comment]
The InventoryItem, InventoryLevel and Location is what you want to start working with to update inventory.

https://shopify.dev/api/admin-rest/2022-01/resources/inventoryitem#top
https://shopify.dev/api/admin-rest/2022-01/resources/inventorylevel#top

**Comment by nturini-cascinanet** [comment]
> The InventoryItem, InventoryLevel and Location is what you want to start working with to update inventory.
> 
> https://shopify.dev/api/admin-rest/2022-01/resources/inventoryitem#top https://shopify.dev/api/admin-rest/2022-01/resources/inventorylevel#top

Thank you
