### ISSUE TITLE
Product Variant

### ISSUE THREAD

**Issue by primal-jeff** [nozzlegear/ShopifySharp#73]
Feature Request - Just checking to see if there is an ETA on adding Product Variant to the library. In particular, inventory management.

**Comment by nozzlegear** [comment]
Thanks for the request! We currently have the ProductVariant object in the lib, but no service for it yet. I'll get it in as soon as possible — probably over next week or two.

**Comment by primal-jeff** [comment]
Joshua-

Thanks for the quick response. I look forward to seeing it in the next week or 2.

Thanks again

**Comment by nozzlegear** [comment]
Product Variants are now available on Nuget with version 3.1.0. Thanks for the feature request!
