### ISSUE TITLE
Can't update inventory quantity

### ISSUE THREAD

**Issue by jla8902** [nozzlegear/ShopifySharp#731]
Code:
var service = new ProductVariantService(url, password);
var productvariant = await service.GetAsync(id);
productvariant.InventoryQuantity = 5;
var response = await service.UpdateAsync(id,productvariant);

Error response:
Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API.

**Comment by thomotron** [comment]
Inventory quantities cannot be updated using a product variant.

As per the [Shopify API documentation](https://shopify.dev/api/admin-rest/2022-04/resources/product-variant):
> Apps can no longer set inventory using `inventory_quantity` or `inventory_quantity_adjustment`.
> For more information, see [Updating inventory](https://shopify.dev/tutorials/manage-product-inventory-with-admin-api).

To get around this you'll have to get the `InventoryLevel` of the product variant and update it using an instance of `InventoryLevelService`.

I've been working around this myself lately. There are some good examples on how you can go about this in #286.

**Comment by jhunexjun** [comment]
This is how I do it.

```
InventoryLevel response = await _inventoryLevelService.SetAsync(new InventoryLevel
 {
          LocationId = location.Id,
          Available = 100,
          InventoryItemId = productVariant.InventoryItemId
});
```

**Comment by nozzlegear** [comment]
It looks like this has been answered so I'm going to close the issue. Let me know if you're still having problems @jla8902!
