### ISSUE TITLE
Fulfillment Orders Update  Apr. 05

### ISSUE THREAD

**Issue by cannunziello772** [nozzlegear/ShopifySharp#732]
I was looking at the [update](https://shopify.dev/apps/fulfillment/migrate?utm_source=exacttarget&utm_medium=email&utm_campaign=Partners_WhatsNewNL_April_20220405#update-your-apps-permissions) that Shopify posted in regards to fulfillments and orders. In the current AuthorizationScope we have "ReadMerchantManagedFulfillmentOrders" which seems to corelate to one of the changes, but not the other two. I'm not sure if the update was anticipated and so the three new scopes have already been added or if the matching scope is just coincidence?

**Comment by nozzlegear** [comment]
Sorry, I somehow missed this question. For anyone looking at this now or in the future, the authorization scopes for fulfillment orders have indeed been added to ShopifySharp!
