### ISSUE TITLE
Detected bugs in PageListFilter.cs and SmartCollectionListFilter.cs

### ISSUE THREAD

**Issue by thuongmhh** [nozzlegear/ShopifySharp#736]
Please make this update ASAP:

**Change**
[JsonProperty("**status**")]
public string? PublishedStatus { get; set; }

**To**
[JsonProperty("**published_status**")]
public string? PublishedStatus { get; set; }

At the moment I cannot filter pages and smart collections with the wrongly assigned JSON propety.

**Comment by nozzlegear** [comment]
Fixed in 5.18.4 on nuget. Sorry for the delay!
