### ISSUE TITLE
Is it possible to get customer return Item SKU And Qty when Refund not Create yet

### ISSUE THREAD

**Issue by amerina** [nozzlegear/ShopifySharp#739]
https://community.shopify.com/c/shopify-apis-and-sdks/return-api/m-p/640771

I just find this article about return order when return status=Return in progress

**Comment by nozzlegear** [comment]
I had just received a similar question about this same thing the other day and it reminded me of this question. Unfortunately it's still not possible at the moment, but [it looks like Shopify is finally implementing a Returns API](https://www.shopify.com/return-api-beta). Once it comes out of beta we'll add support to ShopifySharp and it should then be possible to do this!
