### ISSUE TITLE
Price (and other monetary properties) in models should not be type double

### ISSUE THREAD

**Issue by oleksii-vynnychenko** [nozzlegear/ShopifySharp#74]
It's generally a very-very bad idea to save money (prices, etc) in `double` type. There's a `decimal` C# type just for mostly monetary purposes that won't give you calculation, casting, rounding, comparing mistakes that `real` types will give from time to time.
From what I see it's classes:
- ShopifyCharge,
- ShopifyProductVariant,
- ShopifyCustomer,
- ShopifyLineItem,
- ShopifyOrder,
- ShopifyRecurringCharge,
- ShopifyShippingLine,
- ShopifyTaxLine,
- ShopifyTransaction,
- ShopifyUsageCharge

In case you have other things to do I can fix it on this or next weekend and pull-request.

**Comment by nozzlegear** [comment]
Thanks for reporting this! I tend to get doubles and decimals confused, I don't use them much in anything I've built for production. A pull request would certainly be welcome, otherwise I'll get it when I have the chance.

**Comment by thj-dk** [comment]
Decimals are definately the most appropriate type for this. This this might create breaking changes for some. What do you think?

**Comment by nozzlegear** [comment]
I would agree that changing these types to decimal is probably a breaking change, and would warrant waiting until 4.0 for the change to make it in.

**Comment by clement911** [comment]
@nozzlegear how can I contribute to 4.0?
Should you create a branch?

**Comment by nozzlegear** [comment]
All doubles have been change to decimals in the 4.0 branch.
