### ISSUE TITLE
service.GetAsync causes EF db context to be disposed

### ISSUE THREAD

**Issue by zxed** [nozzlegear/ShopifySharp#744]
Running into a strange issue

I'm using EF + Sql with Dependency Injection in an azure functions project; just added ShopifySharp and noticed that after calling something like var customer = await service.GetAsync the db context is disposed....

I have no idea why this would be the case, or what I need to look at any thoughts on what I could look at to trouble shoot this?

**Comment by zxed** [comment]
I was able to dig into this a bit deeper and using restsharp causes the same behaviour.

I swapped it out for WebClient and this doesn't cause the context to be disposed of.

It seems like the single context around HttpWebRequest maybe causes some of this? esp when used with DI and azure functions.

**Comment by nozzlegear** [comment]
Thanks for digging in! I’m at a wedding tonight and tomorrow but once I’m back I’ll be working on this library. I’ll take a look as soon as possible!

--
Josh Harms

**Comment by zxed** [comment]
Intermittently - yesterday I went ahead and made sure all my async’s were
awaited as someone said that this could be an issue.

It isn’t just this lib though - sendgrid api caused the same issue…. So I’m
thinking maybe it is the async callers…. Will known soon in the next few
days.

Zee

**Comment by zxed** [comment]
It looks like this is not just limited to azure functions.

I have a core .net API project that uses DI + entity framework for
dbcontext.

After calling the Metafield service - the next call to SaveChanges (db
context) results in an error, before calling metafield, it's all fine.

Makes zero sense.

**Comment by nozzlegear** [comment]
Thanks for looking into it! I'm going to close this because it sounds like an issue somewhere outside of this package. If I'm wrong please let me know and I'll reopen!
