### ISSUE TITLE
Can't connect - getting ShopifyException: (401 Unauthorized) [API] Invalid API key or access token (unrecognized login or wrong password)

### ISSUE THREAD

**Issue by ap22220010** [nozzlegear/ShopifySharp#747]
Sorry if this is the wrong "forum" to post - I'm quite new to this. 
Have just starting to use ShopifySharp for connection to a customers Shopify installation. Customer have create a private App and provided me with the Private app secret key and the URL for their site.

The private app have been granted access to the fololowing:
read_analytics, read_customers, read_discounts, read_draft_orders, read_fulfillments, read_inventory, read_gift_cards, read_legal_policies, read_locations, read_marketing_events, read_orders, read_payment_terms, read_price_rules, read_products, read_reports, read_shipping, read_locales, read_script_tags, read_markets, read_third_party_fulfillment_orders

But no mather what i do, i get the exception 401.

can anyone guide me in the right direction ?

thanks in advance

**Comment by ap22220010** [comment]
Customer had provided wrong key - sorry

**Comment by ap22220010** [comment]
Customer had provided wrong key - sorry

**Comment by nozzlegear** [comment]
No problem, glad you got it sorted!

--
Josh Harms

**Comment by arthur2** [comment]
@nozzlegear hey sorry just started using ShopifySharp and ran into the same issue.

I got my access token from API Credentials page of my private shopify app (already installed), but no matter what I do the library keeps giving me 401 when I try to list products. 

would you be so kind to give me some pointers?
