### ISSUE TITLE
api doesnt hae any way to set Inventory Item and cost per variant

### ISSUE THREAD

**Issue by amrender** [nozzlegear/ShopifySharp#751]
ProductVariant object is missing InventoryItem property, so no way to set cost for variant.
InventoryService only have Update,Get and List functions.

**Comment by amrender** [comment]
If I add new InventoryItem object, it does add the inventory but still doesn't set the cost for the product variant.

**Comment by amrender** [comment]
Also any idea how to get ProductMetaFields and ProductVariantMetaFields?

**Comment by Fashionepaul** [comment]
Hi, the InventoryLevel and InventoryItem can be a little confusing.  Here is an image from the [Shopify API documentation](https://shopify.dev/api/admin-rest/2022-07/resources/inventorylevel), explaining the relationship

![inventory](https://user-images.githubusercontent.com/6555636/177136399-df536d76-20b1-49f2-91b5-ad501001c36d.png)

> ProductVariant object is missing InventoryItem property, so no way to set cost for variant. InventoryService only have Update,Get and List functions.

You have to use the inventory_item_id from the product variant, to update the cost.
Example: https://shopify.dev/api/examples/product-inventory

> If I add new InventoryItem object, it does add the inventory but still doesn't set the cost for the product variant.

You need to use the InventoryLevel to set the available quantity,
