### ISSUE TITLE
CheckoutService not working, missing s in checkouts.json

### ISSUE THREAD

**Issue by Ducki** [nozzlegear/ShopifySharp#754]
Hey there,

when trying to use the CheckoutService in the current version 5.15.0, the server always responds Not Acceptable errors.
When debugging this, I found out, that the CheckoutService uses the URI `[…]/api/2021-10/checkout.json`, which returns a 404 when accessed. Turns out, that there is simply an "s" missing in `checkout.json`, the correct URI is: `[…]/api/2021-10/checkouts.json`

Also, the methods are marked as obsolete, because they are allegedly undocumented, but as far as I see, they are officially documented: [https://shopify.dev/api/admin-rest/2022-04/resources/checkout](https://shopify.dev/api/admin-rest/2022-04/resources/checkout)

Thank you and best regards,
Alex

**Comment by nozzlegear** [comment]
Thanks for reporting this! I've fixed it in 5.18.1 on nuget. Could you give it a try whenever you have time and confirm that the fix worked?
