### ISSUE TITLE
Test `RetryExecutionPolicy_Tests.ForegroundRequestsMustRunBeforeBackgroundRequests` fails on .NET Framework

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#755]
[This test](https://github.com/nozzlegear/ShopifySharp/blob/a85db0d3c7eed667f4f3d166ecdf8afbfdf355ee/ShopifySharp.Tests/RetryExecutionPolicies_Tests.cs#L137) fails on .NET Framework but succeeds without issue on dotnet core. I've even [cleaned it up in the `setup-github-actions` branch](https://github.com/nozzlegear/ShopifySharp/blob/d0176ce1f45382850bd5b6f6afe6bf98c6a1fc9e/ShopifySharp.Tests/RetryExecutionPolicies_Tests.cs#L141) hoping it was just a hidden race condition, but it still fails. 

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Foreground completed at 6/30/2022 3:38:32 AM
Background completed at 6/30/2022 3:38:27 AM
[xUnit.net 00:02:16.50]     ShopifySharp.Tests.RetryExecutionPolicies_Tests.ForegroundRequestsMustRunBeforeBackgroundRequests [FAIL]
  Failed ShopifySharp.Tests.RetryExecutionPolicies_Tests.ForegroundRequestsMustRunBeforeBackgroundRequests [10 s]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at ShopifySharp.Tests.RetryExecutionPolicies_Tests.<ForegroundRequestsMustRunBeforeBackgroundRequests>d__7.MoveNext() in D:\a\ShopifySharp\ShopifySharp\ShopifySharp.Tests\RetryExecutionPolicies_Tests.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

@clement911 Any idea why this might fail on .NET Framework?

**Comment by nozzlegear** [comment]
Just thinking out loud here, maybe it's because the .NET Framework tests all get run in one command? The dotnet core tests do not get run with one command, each file/category gets run separately, one after the other. The .NET Framework tests are all in an [xunit collection](https://xunit.net/docs/running-tests-in-parallel) though, so they shouldn't be running in parallel, but maybe there's something going on when the rate limit has already been hit before this test even starts?

**Comment by clement911** [comment]
Hi @nozzlegear 
Looks like you've been  busy refactoring the CI stuff!
Regarding this test, I would suggest you leave it disabled for now. I will investigate once I returned to work in 10 days or so.

**Comment by nozzlegear** [comment]
I’ve been very busy with it! No worries though, I’m not in a hurry to get this test fixed, I’m happy to leave it disabled for now. Enjoy your time away from work!

--
Josh Harms

**Comment by clement911** [comment]
I can't reproduce this.
It succeeds for me on both .net core and .net 4.7

**Comment by nozzlegear** [comment]
@clement911 thanks! It still manages to fail for me on both targets, so might be something with my test store. I'm not super worried about it though, thanks for confirming!
