### ISSUE TITLE
Plans for supporting future API versions.

### ISSUE THREAD

**Issue by PaulLiamAG** [nozzlegear/ShopifySharp#756]
Hey, 

Thanks for making this great package, do you have any plans to add support for the 2022 api versions, or is this something you are waiting for contributors to achieve?

**Comment by nozzlegear** [comment]
Hey thanks for the kind words! We do have plans to support the 2022 api versions, in fact there's an open pull request contributing that support right now. I'm just working on some extra details for automating future releases of this package and then I'll get that merged and published right afterwards.

--
Josh Harms
