### ISSUE TITLE
Add guide on how to contribute

### ISSUE THREAD

**Issue by nebula2** [nozzlegear/ShopifySharp#758]
Can you please add contribution guidelines along with steps needed to run the solution locally (especially the tests)?

**Comment by nozzlegear** [comment]
Hey @nebula2, thanks for the suggestion! I'll add a contribution guide this week that covers running and testing the solution.

**Comment by nozzlegear** [comment]
Alrighty, a contribution guide has been [added right here](https://github.com/nozzlegear/ShopifySharp/blob/master/docs/contribution-guide.md). Let me know if I've missed anything!
