### ISSUE TITLE
ShopifySharp.AuthorizationService.IsAuthenticProxyRequest fails if QueryString has blank space in it

### ISSUE THREAD

**Issue by iKishanSojitra** [nozzlegear/ShopifySharp#762]
ShopifySharp.AuthorizationService.IsAuthenticProxyRequest returns false if there's a blank space character in QueryString

**Comment by nozzlegear** [comment]
Thanks for the report @iKishanSojitra! Looks like #761 is reporting the same issue and has a temporary workaround solution there. I'm going to close this issue and track the fix in #761.
