### ISSUE TITLE
Property deprecations in the REST Admin API Order resource

### ISSUE THREAD

**Issue by cannunziello** [nozzlegear/ShopifySharp#763]
I received notice about using deprecated fields in the order -> customer object. Will this be addressed in the next API version?

From Shopify:

EFFECTIVE DECEMBER 21, 2021 ACTION REQUIRED
The following customer object properties on the REST Admin API's [Order](https://shopify.dev/api/admin-rest/2021-10/resources/order#top) resource are deprecated:

last_order_id
last_order_name
orders_count
total_spent
These properties will still be available in the [Customer](https://shopify.dev/api/admin-rest/2021-10/resources/customer#top) resource.

These deprecated properties will be removed from unstable in early 2022. The change will be made official in the 2022-04 REST Admin API version.

**Comment by nozzlegear** [comment]
Hey @cannunziello! Thanks for the heads up about this. So if I understand it correctly, those properties are still going to be available on the `Customer` object, but they'll be removed from the `Order.Customer` object. Unfortunately we use the same class for both of these, so at the moment I don't have any plans to deprecate or remove them. The fix will be creating a new `OrderCustomer` class that has the pared down properties. That'd probably be a breaking change, so I probably won't address it until a 6.0.0 release where breaking changes can be safely made. 

In the mean time, I'll add some notes to those properties that they'll be null when returned via the Order API.

**Comment by nozzlegear** [comment]
I should mention that if Shopify is complaining that these values are being used by an application via ShopifySharp (such as in cases where you're updating an order or something), then we'll definitely have to remove these properties before 6.0. Reading the email you received, I think they're just warning that those properties will be deprecated but not complaining that you're using them.

**Comment by cannunziello** [comment]
Thanks for your response. Is there an expected date for version 6.0?
________________________________
