### ISSUE TITLE
The OrderTransactionId and UserId should be a long type in the GiftCardAdjustment

### ISSUE THREAD

**Issue by brian-winfield** [nozzlegear/ShopifySharp#764]
Both of these fields are ints in the GiftCardAdjustment class, which is now throwing exceptions because Shopify is now up to larger values for those fields. 

For example, I'm getting a cast exception:

`Could not convert to integer: 5756037562530. Path 'adjustments[0].order_transaction_id'.
`

The pull request for this fix is https://github.com/nozzlegear/ShopifySharp/pull/765

**Comment by nozzlegear** [comment]
Fixed in 5.16.0 on nuget. Thanks!
