### ISSUE TITLE
search customer by email address

### ISSUE THREAD

**Issue by zxed** [nozzlegear/ShopifySharp#769]
Has this code to search by fields changed?

`var service =  new CustomerService(myShopifyUrl, shopAccessToken);
IEnumerable<Customer> customers = await Service.SearchAsync("Jane country:United States");`

Trying to figure out how to search by email address, but the above requires a filter

**Comment by nozzlegear** [comment]
@zxed thanks for opening this issue! It looks like the documentation for searching was out of date. The code should now look like this:

```cs
var service = new CustomerService(myShopifyUrl, shopAccessToken); 
var filter = new CustomerSearchListFilter
{
  Query = "Jane country:United States"
};
IEnumerable<Customer> customers = await Service.SearchAsync(filter);
```

Let me know if that works for you!

**Comment by BorisDNK** [comment]
This code return all customers with are almost the same email. But how to get customer definitely the same email
