### ISSUE TITLE
Shipping address field needs to be nullable

### ISSUE THREAD

**Issue by John-Streckfuss** [nozzlegear/ShopifySharp#77]
The current data model requires a non nullable shipping address and it is possible that Shopify will send orders via webhooks that do not have shipping addresses. Typically these are orders that are submitted via a POS system and therefore there is no shipping address.

**Comment by nozzlegear** [comment]
Hey @John-Streckfuss, thanks for creating this issue. Could you provide a little more background on what errors you're getting? The class should already be nullable by default and I'm not seeing any exceptions on my end when testing it.

**Comment by John-Streckfuss** [comment]
In the shopify order shipping address shouldn't the shipping address be defined like this?

Original Not Nullable:
/// <summary>
/// The mailing address to where the order will be shipped. This address is optional and will not be available on orders that do not require one.
/// </summary>
[JsonProperty("shipping_address")]
public ShopifyAddress ShippingAddress { get; set; }

Nullable:
/// <summary>
/// The mailing address to where the order will be shipped. This address is optional and will not be available on orders that do not require one.
/// </summary>
[JsonProperty("shipping_address")]
public ShopifyAddress? ShippingAddress { get; set; }

**Comment by nozzlegear** [comment]
Sorry it took so long to get back to you @John-Streckfuss, I've been super busy and haven't had a chance to get much work done on this lib. Classes in C# are already nullable, and the compiler won't actually let you mark one as explicitly nullable with `?`. If the `shipping_address` field is null, the `ShippingAddress` property should automatically be null too. 

Do you have a screenshot or log for the errors you're getting from this? Right now I'm not able to pinpoint anything, but it's possible I'm not quite understanding the problem.
