### ISSUE TITLE
New orders since a datetime

### ISSUE THREAD

**Issue by Yahya0007** [nozzlegear/ShopifySharp#773]
Hi

How can I apply a filter to download new orders since a given datetime? I can only see examples of exact date match.

Thanks

Regards

**Comment by nozzlegear** [comment]
Hey @Yahya0007, thanks for the question! You should be able to use the `OrderListFilter` to do this:

```cs
var filter = new ShopifySharp.Filters.OrderListFilter
{
  CreatedAtMin = DateTimeOffset.UtcNow
};
var result = await orderService.ListAsync(filter);
```

Let me know if that works for you!
