### ISSUE TITLE
Plus APIs

### ISSUE THREAD

**Issue by MalikDrako** [nozzlegear/ShopifySharp#78]
Do you have access to a Plus account to test the Plus APIs against?

If not, the company I work for has a Plus account and is OK with me running tests against one of our development stores

**Comment by nozzlegear** [comment]
Hey @MalikDrako, thanks for the offer! I don't currently have access to a Plus account, but I'll be contacting Shopify soon to see if I can get one specifically for testing ShopifySharp. Depending on what their answer is, I'd be happy to discuss this with you further in the future to see if we can get automated tests running on something like Travis-CI.
