### ISSUE TITLE
Product Option Update/Create

### ISSUE THREAD

**Issue by Your-Space** [nozzlegear/ShopifySharp#782]
Is it possible to create a new product option and attach it to an existing product?  Thanks!

**Comment by nozzlegear** [comment]
@Your-Space Hey! This should be possible, but it's a little bit convoluted. You need to update both the product itself to add the option, and you need to update all of the product's variants to add values for the new option, all in the same request. So you'd do something like this:

```cs
using System.Linq;

var product = await productService.GetAsync(existingProductId);
var productOptions = new List<ProductOption>();

// Add the existing product options to the list so they don't get dropped
productOptions.AddRange(product.Options);

// Add a new option named Color
productOptions.Add(new ProductOption
{
  Name = "Color"
});

// Iterate over each variant and assign a value for the new product option
foreach (var variant in product.Variants)
{
  // This example assumes the new option is option #3
  // TODO: assign your option value here
  variant.Option3 = "Blue";
}

product = await productService.UpdateAsync(existingProductId, product);
```

**Comment by nozzlegear** [comment]
Give that a try and let me know how it works! Also be sure you're pulling in the full product and variant from Shopify using `GetAsync` before you attempt to update the product.

**Comment by Your-Space** [comment]
> Give that a try and let me know how it works! Also be sure you're pulling in the full product and variant from Shopify using `GetAsync` before you attempt to update the product.

Thanks, everything is working great
