### ISSUE TITLE
Archive order

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#784]
Hi,

How can we archive an order?

The order has been fulfilled and captured.

**Comment by amerina** [comment]
May be you can try close the order,shopify will auto archive order

**Comment by davidkdb** [comment]
Yes, this is what we found out also. We're doing it with GraphQL, because we could not find a function in ShopifySharp for this.

**Comment by nozzlegear** [comment]
Hey @davidkdb, one of my own hobby apps archives orders using ShopifySharp! Archiving is called closing in Shopify. ShopifySharp's OrderService class has `CloseAsync` and `OpenAsync` methods for archiving and unarchiving orders, all you need is the order id:

```cs
var orderService = new OrderService(shopDomain, accessToken);

// Archive the order by closing it
await orderService.CloseAsync(orderId);

// Unarchive the order by opening it
await orderService.OpenAsync(orderId);
```
