### ISSUE TITLE
Update product publish issue

### ISSUE THREAD

**Issue by ElijahDev** [nozzlegear/ShopifySharp#787]
Not sure if I'm missing something but every time I update a product it is no longer available on the online store channel.

                var product = await service.UpdateAsync(Original.Id, new Product()
                {
                    Status = Updated.Status,
                    Title = Updated.Title,
                    Tags = Updated.Tags,
                    Vendor = Updated.Vendor,
                    ProductType = Updated.ProductType,
                });

**Comment by ElijahDev** [comment]
Found the issue, PublishedScope and PublishedAt need to sent with the update, otherwise it unpublishes

Thanks

**Comment by nozzlegear** [comment]
Glad you found the problem @ElijahDev! This is an issue that pops up often, it's unfortunately an artifact of how default property values get serialized in dotnet. We've got a couple issues (#388, #642) discussing new methods for better control of property serialization that would prevent this exact issue. 

In the meantime, I've added an FAQ entry to the readme regarding this particular issue.

**Comment by Coder7777** [comment]
> Found the issue, PublishedScope and PublishedAt need to sent with the update, otherwise it unpublishes
> 
> Thanks

Thanks guy. Save my day. 

Once I update product, I will disappear from the page. Super annoying.

**Comment by nozzlegear** [comment]
Glad you found this @Coder7777, sorry you had trouble with it in the first place though! I'm planning out a 7.0 release right now and this is one of the big problems that I want to tackle with it. So hopefully things will improve soon!

**Comment by Coder7777** [comment]
> Glad you found this @Coder7777, sorry you had trouble with it in the first place though! I'm planning out a 7.0 release right now and this is one of the big problems that I want to tackle with it. So hopefully things will improve soon!

Thanks to you also. Great project, save time, save energy.

**Comment by dooferorg** [comment]
Whenever I've had issues like these on other API/systems just setting the JSON serializer to ignore nulls usually takes care of it. Given how long this issue has gone on I assume that approach does not work?
