### ISSUE TITLE
Cannot create meta field for order

### ISSUE THREAD

**Issue by Medo199** [nozzlegear/ShopifySharp#788]
I'm geting error Not Found when trying to create a meta field for order
Here is the code:
                             List<MetaField> metaFieldList = (await orderService.GetMetaFieldsAsync(Convert.ToInt64(order.Id))).ToList();
                             MetaField metaField = metaFieldList.FirstOrDefault(m => m.Key == "SalesOrderId");
                            if (metaField == null)
                            {
                                metaField = new MetaField() { Key = "SalesOrderId", Value = salesOrder.Code, ValueType = "integer", Type = "number_integer", Namespace = "abc" };
                                metaField = await metaFieldService.CreateAsync(metaField, Convert.ToInt64(order.Id), "Orders");
                            }

**Comment by nozzlegear** [comment]
Hey @Medo199, thanks for the report! Can you post the full exception and stack trace?

**Comment by nozzlegear** [comment]
@Medo199 Nevermind, not necessary! I've run your code and found the problem, it looks like the resource string is case-sensitive. If you change `"Orders"` to `"orders"` it should start working!

**Comment by nozzlegear** [comment]
These will now be automatically downcased by ShopifySharp starting in 5.18.6!
