### ISSUE TITLE
Synchronous implementation of Shopify service methods

### ISSUE THREAD

**Issue by oleksii-vynnychenko** [nozzlegear/ShopifySharp#79]
We've got some legacy framework here that ...  long story short, I can't use async service method implementations. Task.Run() is not an option too. 
I'm actually already using this library in production and already implemented synchronous methods for several services that I used (luckily RestSharp has synchronous calls) - it's basically removing `async` from signature and `await` in method body + ExecuteRequest() insted of ExecuteRequestAsync().
It's more of a question if you'll pull synchronous implementations if I'll create pull-request?
In my eyes, those still could be useful in legacy projects (like mine) and they're demand nothing in support, since they're basically duplicates of Async methods.
If yes - I'd wrote other services too, but I won't cover it with tests - reason is I don't know that testing framework you use, nor have time to learn it, sadly. 

p.s. I remember other issues #69, #74 I said I'll fix and pull-request. I already fixed them in my production, just didn't have time to check everything and pull-request. Hope this weekend I'll have time to finally work a bit at home.

**Comment by nozzlegear** [comment]
Thanks for the offer! It'd be a lot of work, but if you can get a matching synchronous call for every API method I'd be happy to merge a pull request and require synchronous methods for future feature implementations.
