### ISSUE TITLE
update variant cost not working

### ISSUE THREAD

**Issue by vinrena** [nozzlegear/ShopifySharp#798]
I'm trying to update variant cost using InventoryItemService: I read inventoryitem, change cost and then update again inventoryitem.
I have no error, but on shopify there is no update on variant cost.
I'm using shopifysharp 5.17.0 and this is my function for update variant cost:

public static void AggiornaCostiVariante(ProductVariant v,decimal costo, int sleep)
        {
            
            long variantId = v.Id.Value;
            long inventoryItemId = v.InventoryItemId.Value;

            String myShopifyUrl = ConfigurationManager.AppSettings["shopify_url"];
            String privateAppPassword = ConfigurationManager.AppSettings["shopify_private_app"];
            InventoryItemService invService = new InventoryItemService(myShopifyUrl, privateAppPassword);                
            InventoryItem invItem = Task.Run(() => invService.GetAsync(inventoryItemId)).Result;
            invItem.Cost = costo;
            Thread.Sleep(sleep);
            Task.Run(() => invService.UpdateAsync(inventoryItemId, invItem));    
        }

thank you very much!

**Comment by vinrena** [comment]
sorry, in my shopify test enviroment i was duplicating products, so i'm checking wrong variants.
Variant cost is updated as expected.

**Comment by nozzlegear** [comment]
Glad you got it figured out!
