### ISSUE TITLE
Metafield valueType field deprecated. Please use type field.

### ISSUE THREAD

**Issue by FlySociety** [nozzlegear/ShopifySharp#799]
Recieved this from Shopify email

"One or more of your apps have made deprecated API calls in the last 30 days. Support for this version will be removed on January 1, 2023. Please update the apps listed below to API version 2022-04 or later to ensure they continue to function correctly.

Store: xxxx

App: xxxx
Breaking Changes:

`Metafield.valueType` has been removed. See `Metafield.type` for type information."

Will ShopifySharp make the change to just use the type field?

**Comment by nozzlegear** [comment]
Hey @FlySociety! This change has already been made in version 5.16.0. If you update to the latest version of ShopifySharp you should be able to swap everything over to `Metafield.Type` and this warning will go away. Let me know if you have any issues with upgrading.
