### ISSUE TITLE
Blog API Support

### ISSUE THREAD

**Issue by ripteqdavid** [nozzlegear/ShopifySharp#80]
Hi All,

Are there any plans to implement the Blog API?

Regards,
Dave.

**Comment by nozzlegear** [comment]
Definitely! I've got a need for this too, so it'll be the next feature I work on.

**Comment by nozzlegear** [comment]
ShopifySharp now supports the Blog API with version 3.2.0. Note that this is for blogs themselves, not blog post support. Editing blog posts will require the Article API, which I'm going to be working on next.
