### ISSUE TITLE
Metafield definitions - how to create?

### ISSUE THREAD

**Issue by thenik** [nozzlegear/ShopifySharp#807]
Hey,

Thanks for your amazing library!
At [psqqq.com](https://psqqq.com) ShopifySharp   is used for export.

I see ShopifySharp does not support metafieldDefinitionCreate , right?

**about Metafield definitions**
https://shopify.dev/apps/metafields/definitions#how-it-works
https://shopify.dev/api/admin-graphql/2022-10/mutations/metafieldDefinitionCreate

Any ideas how to create "Metafield definitions" it via ShopifySharp   ?

(I need to create Metafield definitions for **list.single_line_text_field**

**Comment by clement911** [comment]
Yes you can use the `GraphService` class to issue arbitrary graphql queries and mutations to the API.

Something like this:

```
var graphSvc = new GraphService(<shopId>, <token>);
var res = await graphSvc.PostAsync(<query_or_mutation>)
```
