### ISSUE TITLE
Missing doc of new versions

### ISSUE THREAD

**Issue by davidkdb** [nozzlegear/ShopifySharp#809]
Hi,

I see that in the Code tab it lists 5.18.8 as the latest version, but the latest published is 5.18.10.

Where can we see what's new in 5.18.9/5.18.10?

**Comment by nozzlegear** [comment]
Oh yes, thank you for the reminder! Creating new GitHub releases is still a manual process for me and I sometimes forget to do it after we push new versions to nuget. I think I’m going to update our release process to create the GitHub releases automatically, but in the meantime I’ll add these two missing ones as soon as I have some free time today.

--
Josh Harms

**Comment by davidkdb** [comment]
Still no documentation......
