### ISSUE TITLE
Unable to install Nuget in VS 2022 Mac

### ISSUE THREAD

**Issue by kmostofi** [nozzlegear/ShopifySharp#818]
Hi,
I am trying to install your NuGets in a Xamarin forms Mobile project. I am wondering if it is compatible. It keeps failing to install it.

I appreciate your help.

Kind Regards,
Kamal

**Comment by nozzlegear** [comment]
Hey Kamal! I'm not sure if it's compatible, it should be if your project is compatible with .NET Standard or .NET 5/6. Are you receiving an error message of any kind?

--
Josh Harms

**Comment by kmostofi** [comment]
Hi. The project is compatible with .NET Standard 2.1. I also tried it with .NET Standard 2.0. I will try to install it on a VS Windows version and will keep you posted on the result and errors.
Currently, it says "Could not add ShopifySharp".

**Comment by nozzlegear** [comment]
Hmm it should work with the project then. I'm not very familiar with Xamarin Forms though, I've never used it before. Are you using Visual Studio to develop that project? Is it possible to use the dotnet CLI to try to install ShopifySharp? It might give you an error that's more clear if so:

```
# Run this command from your project directory
dotnet add package shopifysharp
```

**Comment by kmostofi** [comment]
Thank you for the tip. It did the trick and installed the NuGet in VS Mac. 

One last question: is your API support payment for the products? or I should handle it outside your API?

Thank you and wish you A Happy New Year :-)

**Comment by kmostofi** [comment]
It is strange that Nuget fails on a new project again, I tried both CLI and Nuget manager. Actually, it doesn't allow us to update or add any other packages. :-(

**Comment by nozzlegear** [comment]
@kmostofi Sorry, missed your question about the payments for products. You can use the DraftOrderService to create a draft order and fill it with line items that a customer wants to purchase. The draft order will have a ConfirmationUrl property on it that you can then redirect the customer to where they'll go through checkout like a regular order. There's no way to do actual credit card payments via the API though.
