### ISSUE TITLE
Partial functionality when creating product with options

### ISSUE THREAD

**Issue by nokturnal** [nozzlegear/ShopifySharp#819]
I am deep into the rabbit hole of product options and how those relate to product variants (to be honest, very confused).

That said, I think I come across an issue - attempting to create a product with options:

	var product = new Product {
		Title = "Some Title",
		Handle = "some-title",
		Vendor = "A Cool Vendor",
		BodyHtml = "Some Body Html",
		ProductType = "SomeCoolProduct",
		Options = new List<ProductOption> {
			new ProductOption{
				Name = "Choose An Option",
				Position = 1,
				Values = new string[] {
					"Option1 / Some secondary details", "Option 2", "Option 3"
				}
			}
		}
	};

	var newProduct = await productService.CreateAsync(product);

The previous code creates a product that has an option (with the correct name of "Choose An Option"), but the only option value is "Default Title" instead of the provided array of values. Additionally it creates a variant that also has the title of "Default Title":

![shopifysharp-issue](https://user-images.githubusercontent.com/3364596/209257882-f15f0565-fe37-41e3-b18e-a6208c5f9d6e.png)

I am using 5.18.11 & .NET 5 (and have tested in .NET 6 as well)

Please help!

**Comment by nozzlegear** [comment]
Hey @nokturnal! This is a somewhat common problem that everyone runs into at least once. Shopify doesn't make it very clear in my opinion, but in their API the product variants create the options, not the other way around. That is to say, if you want to add options for your product, you need to create the product variants using the `ProductVariantService` class: 

```
var productService = new ProductService(domain, accessToken);
var variantService = new ProductVariantService(domain, accessToken);

var variant1 = await variantService.CreateAsync(new ProductVariant
{
   // .. other details here
   Option1 = "Option1 / Some secondary details",
   Option2 = "Option 2",
   Option3 = "Option 3"
});

var variant2 = await variantService.CreateAsync(new ProductVariant
{
   // and so on
});
```

Let me know how that works for you!

**Comment by nokturnal** [comment]
@nozzlegear 100% (and thanks for the quick reply!)... I did end up solving this today after inspecting some API product responses from other active stores I have access to.

I initially tried to create the variants inline when defining a "Product" but was faced with the same "Default title" error. I pivoted to the option route as a last resort. 

The key takeaway from this is when defining the variants you need to assign a value for ".Option1" in addition to the properties I deemed as "required"... I missed that which resulted in the misleading (but now accurate to me) "default title" error.

Hopefully this helps out someone (or even me again) when faced with this "issue" :)
