### ISSUE TITLE
Shopify API version upgrade

### ISSUE THREAD

**Issue by ThatBrianK** [nozzlegear/ShopifySharp#824]
Hi there, I wonder when can we expect the next API version upgrade? the current version (2022-04) will expire by April and I expect we will get reports from our users about using an out-of-date version within the next month or two.
Also, if there's any way I can help with getting the project to this goal, I'd like to help - especially if it involves testing. 

Thanks!

Brian

**Comment by nozzlegear** [comment]
Working on that right now! Aiming to get a new version published today, but if not today then it will be this week for sure. As for contributing, I'm always accepting pull requests! If there's any Shopify rest API that's missing from this package that you find those are always good candidates.

--
Josh Harms

**Comment by clement911** [comment]
Related PR https://github.com/nozzlegear/ShopifySharp/pull/801

**Comment by clement911** [comment]
A [new package was released ](https://github.com/nozzlegear/ShopifySharp/releases/tag/5.19.0) pinned to API version 2022-07

Thanks @nozzlegear !
