### ISSUE TITLE
Shopify API 2022-10

### ISSUE THREAD

**Issue by Pietercal1** [nozzlegear/ShopifySharp#829]
Hi,

First of all.. fantastic library! Thanks!

A question..is a new release on the cards for Shopify version 2022-10 and later?

Thanks!

**Comment by nozzlegear** [comment]
Yep! It has some large changes from Shopify's side though which developers won't want to upgrade to until they're ready to do so, so I think it's going to be a 6.0 release for ShopifySharp.

--
Josh Harms

**Comment by Pietercal1** [comment]
Great news! Thanks!

I tried using the 2023-01 Shopify Release and there are quite a few major changes.
In any case, thanks for the great news! I will wait.
