### ISSUE TITLE
Readme.md example wrong

### ISSUE THREAD

**Issue by hvandenborn** [nozzlegear/ShopifySharp#830]
ShopifyAddress class should be Address, 

and a ; was forgotten.

please change:
https://github.com/nozzlegear/ShopifySharp#customers

var customer = new Customer()
{
    FirstName = "John",
    LastName = "Doe",
    Email = "john.doe@example.com",
    Addresses = new List<ShopifyAddress>()
    {
        new ShopifyAddress()
        {
            Address1 = "123 4th Street",
            City = "Minneapolis",
            Province = "Minnesota",
            ProvinceCode = "MN",
            Zip = "55401",
            Phone = "555-555-5555",
            FirstName = "John",
            LastName = "Doe",
            Company = "Tomorrow Corporation",
            Country = "United States",
            CountryCode = "US",
            Default = true,
        }
    },
    VerifiedEmail = true,
    Note = "Test note about the customer.",
    State = "enabled"
}

to 
var customer = new Customer()
	{
		FirstName = "John",
		LastName = "Doe",
		Email = "john.doe@example.com",
		Addresses = new List<Address>()
		{
			new Address()
			{
				Address1 = "123 4th Street",
				City = "Minneapolis",
				Province = "Minnesota",
				ProvinceCode = "MN",
				Zip = "55401",
				Phone = "555-555-5555",
				FirstName = "John",
				LastName = "Doe",
				Company = "Tomorrow Corporation",
				Country = "United States",
				CountryCode = "US",
				Default = true,
			}
		},

		VerifiedEmail = true,
		Note = "Test note about the customer.",
		State = "enabled"
	};

**Comment by nozzlegear** [comment]
Thanks! I need to get the documentation updated. I'm open to pull requests if you're interested! Otherwise I'll get it updated as soon as I have some extra time.
