### ISSUE TITLE
Shopify admin domain changed

### ISSUE THREAD

**Issue by ashyrobin** [nozzlegear/ShopifySharp#837]
Shopify keeps reminding me my app is outdated and I can't log into my app successfully.

> This app does not appear to be loading and may be outdated. Try reloading the app in the legacy admin or 
 to update the app.

According to this, Shopify admin is changed(https://shopify.dev/changelog/updates-required-for-embedded-apps-to-work-on-the-new-shopify-admin-domain). 
It seems that some  declaration should  be added to the response header. And can I still use the existing IsValidShopDomainAsync action to validate domains?
Thank you!

**Comment by nozzlegear** [comment]
Hey @ashyrobin! I don't think this is an issue with ShopifySharp itself unless I'm misunderstanding. It sounds like you're using an embedded app and you need to update the underlying Shopify App Bridge package. As far as the `IsValidShopDomainAsync` method, you should be able to keep using it!

Let me know if you continue to have this problem and I'd be happy to look into it further.

**Comment by ashyrobin** [comment]
Hey Joshua, Thanks for the reply.  I do use an embedded app which based on the code copied from The Shopify Development Handbook.  I don't think it has anything to do with App Bridge. Am I misunderstanding it?

**Comment by nozzlegear** [comment]
Oh I see, you're likely using the code from the book that uses the app bridge script directly from an MVC view. I'm going to close this since it's more an issue with the book -- I need to open up a repository where readers can ask questions for that -- but I'd be glad to help you out if you send me an email at joshua@nozzlegear.com! I've updated the sample projects for the book since then, and the embedded app project is the one with the most changes. If you send me an email I'll get you that project and point you in the right direction for migrating  Shopify's embedded admin changes.

**Comment by nozzlegear** [comment]
@ashyrobin Just wanted to let you know that I just replied to your email. I attached the latest sample projects from the book as a zip file, which might trigger your spam/junk filter, so keep an eye out!

**Comment by tig66208** [comment]
Hi @nozzlegear - wanted to pile on to this. I’m also using the app embed example from the handbook, and I think I’m fairly up to date. Just setting the X-Frame-Option etc in the startup. 

However today I received an email from Shopify saying my app will stop working on Sep 20 and pointing to this guidance: https://shopify.dev/docs/api/app-bridge/previous-versions/updating-overview?syclid=cr2gn8l4ddbs73e3ihrg#ensure-compatibility-with-the-new-shopify-admin-domain

Considering I’m not using app bridge specifically, I would imagine this issue has more to do with one of the sub-topics of that guidance: https://shopify.dev/docs/api/app-bridge/previous-versions/app-bridge-from-npm/app-setup#set-the-frame-ancestors-directive

Is there any guidance for updating to be compliant?
