### ISSUE TITLE
Fulfillment Request Message not showing in merchant admin

### ISSUE THREAD

**Issue by lucasabond** [nozzlegear/ShopifySharp#839]
While implementing a Cancellation Request Service, I noticed that the message and reason for accepting or rejecting a fulfillment request was not showing in the Shopify Admin. The use case for us is to be able to communicate to the merchant the reason that we are denying a fulfillment request. 

I just submitted a pull request that includes the implementation of a Cancellation Request Service and the fix for the Fulfillment Request message.

https://github.com/nozzlegear/ShopifySharp/pull/838

**Comment by nozzlegear** [comment]
Fixed in v6.1.0+ on Nuget, thanks!
