### ISSUE TITLE
Granular Access Scopes

### ISSUE THREAD

**Issue by ericgeorgeriley** [nozzlegear/ShopifySharp#840]
in the migration to fulfilment orders documentation (https://shopify.dev/docs/apps/fulfillment/migrate) an endpoint is mentioned called request_granular_access_scopes which is needed to add additional permissions to an existing installation. 

Could I suggest the following be added to the AccessScopesService - I did this in my own project by extending the class;

` 
/// <summary>
///  Requests a subset of granular access scopes for an individual shop installation.
/// </summary>
public virtual async Task<IEnumerable<AccessScope>> RequestGranularAccessScopesAsync(string[] requested_scopes, CancellationToken cancellationToken = default)
        {
            return await ExecutePostAsync<IEnumerable<AccessScope>>("request_granular_access_scopes.json", "access_scopes", cancellationToken: cancellationToken, new { requested_scopes });
        }`

**Comment by lucasabond** [comment]
Thanks, this was helpful. I added support for the AuthorizationScope enums as well.

```csharp

/// <summary> 
///  Requests a subset of granular access scopes for an individual shop installation. 
/// </summary> 
public virtual async Task<IEnumerable<AccessScope>> RequestGranularAccessScopesAsync(IEnumerable<AuthorizationScope> requestedScopes, CancellationToken cancellationToken = default) 
{
    return await RequestGranularAccessScopesAsync(requestedScopes.Select(s => s.ToSerializedString()), cancellationToken); 
}

/// <summary> 
///  Requests a subset of granular access scopes for an individual shop installation. 
/// </summary> 
public virtual async Task<IEnumerable<AccessScope>> RequestGranularAccessScopesAsync(IEnumerable<string> requestedScopes, CancellationToken cancellationToken = default)
{
    var content = new
    {
        requested_scopes = requestedScopes,
    };
    return await ExecutePostAsync<IEnumerable<AccessScope>>("request_granular_access_scopes.json", "access_scopes", cancellationToken: cancellationToken, content);
}

```

**Comment by lucasabond** [comment]
@nozzlegear I can submit a pull request for this addition if you want. I don't think it is worth its own GranularAccessService, but I can toss that together if you would prefer as well.
