### ISSUE TITLE
Tracking: ShopifySharp 6.0 and API version 2022-10 support

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#844]
## Overview

This issue is tracking the work that remains for ShopifySharp's 6.0 release, which adds support for Shopify's API version 2022-10. This API version has major implications for apps using [protected customer data](https://shopify.dev/docs/apps/store/data-protection/protected-customer-data). As a reminder, since this is a major version change for ShopifySharp, we may take the opportunity to make changes to the code that may not be backwards compatible.

I'll update this issue in the next few days with actual tasks that need to be done for 6.0. In the meantime, there are a tiny few issues labeled with [revisit in 6.0](https://github.com/nozzlegear/ShopifySharp/issues?q=is%3Aopen+label%3A%22revisit+in+6.0%22+sort%3Aupdated-desc) that are candidates for this update. 

## Branches

We've split off ShopifySharp 5.x into [the `2022-07` branch](https://github.com/nozzlegear/ShopifySharp/tree/2022-07). Any further bugfixes for 5.x should be contributed to this branch. 

Work on ShopifySharp 6.0 and API version 2022-10 will be contributed directly to the `master` branch. The build pipeline will publish these changes to Nuget as 6.0 prereleases, which you'll be able to install and test in your projects. As usual with prereleases though, we can't guarantee they'll be stable.

## Tasks

- TODO

**Comment by clement911** [comment]
Cool, I'll get started on a PR.
It probably makes sense to go straight to 2023-01 since I don't believe there are any major changes between 2022-10 and 2023-01

**Comment by clement911** [comment]
@nozzlegear I've merged https://github.com/nozzlegear/ShopifySharp/pull/848 to upgrade ShopifySharp to API version 2023-01.
As far as I can tell, the only thing that is left is for you to augment the build process:
- Must be able to produce 6.x packages from master branch and 5.x packages from 2022-07 branch. This may not be necessary. It's only necessary if we do need to make fixes to 2022-07. We could potentially not do anything for now and see if/when the need arises to release a new 5.x package
- Must add new secrets to run tests for the Shopify Partners API See https://github.com/nozzlegear/ShopifySharp/pull/836

I'm quite keen to be able to move on to a new API version to use the new capabilities.
Are you able to work on this? Can I help with anything?

**Comment by clement911** [comment]
Something to keep in mind is the following [key date](https://shopify.dev/docs/apps/store/data-protection/protected-customer-data#key-dates): April 2, 2023	New apps must use API version 2022-10 or later
This is just one month away.

**Comment by clement911** [comment]
@nozzlegear it sounds like you are quite busy.
If you want to give me access to the build settings, I'm happy to jump in and sort things out.

**Comment by nozzlegear** [comment]
@clement Yes unfortunately I'm very busy right now, and it couldn't have come at a worse time with this new API version! That sounds good, I'll give you access to the build settings ASAP.

--
Josh Harms

**Comment by clement911** [comment]
@nozzlegear I'm still not able to access the settings.

**Comment by nozzlegear** [comment]
@clement911 You should be able to access it now, let me know if it still isn't working! I've given you the ability to approve full releases from the release pipeline; once you approve a release pipeline run it will publish the package to Nuget, assuming the run builds successfully.

**Comment by clement911** [comment]
@nozzlegear  I still can't see the settings tab.
![image](https://user-images.githubusercontent.com/3426504/223862921-79d951c5-edd5-4e25-a183-44fa82476c8c.png)

**Comment by nozzlegear** [comment]
Hmm okay, I’m not sure how to do that then. I’ve given you the highest access I can grant I think, maybe I’m missing a setting somewhere.

--
Josh Harms

**Comment by clement911** [comment]
I guess I could disable the failing tests. I'll look into it tomorrow

**Comment by nozzlegear** [comment]
No worries, I've got a lot of free time this afternoon so I'm making it my goal to get the tests unblocked! I'll make sure the builds are going and publishing again by the end of the day.

**Comment by nozzlegear** [comment]
@clement911 So just to be clear, you believe the master branch is ready for a public 6.0 release on Nuget once these PartnerClient tests start passing?

**Comment by clement911** [comment]
Please be careful not to publish the current master as a 5.x package though (since it is pinned to 2023-01, which includes the customer data protection)

**Comment by nozzlegear** [comment]
Okay, will do! I'll make sure I don't publish to 5.x. I'm going to run these PartnerClient tests locally and see if I can't get them fixed, but otherwise I'm planning on publishing 6.0 this evening or late tonight.

**Comment by clement911** [comment]
Music to my ears 😀

**Comment by nozzlegear** [comment]
I feel a little silly, I spent longer than I'd like to admit trying to debug why the PartnerService tests were passing locally but failing on Github. Turns out I just [forgot to pass the Org ID and Org Token to the test script](https://github.com/nozzlegear/ShopifySharp/commit/323ce3eb865a271bf975d6c4277523af27914ce0). 😛 

It's a little too late in the evening for me to review everything and trust that I've done it without making a mistake. I'll review the test results and publish first thing in the morning!

**Comment by nozzlegear** [comment]
Alright, ready to go! I've started the deployment to Nuget. It'll be 6.0.1, since I had apparently released ShopifySharp 6.0 at some point and then immediately reverted that release and hid it on nuget. 

It's waiting for approval if you'd like to review everything one final time and do the honors of releasing it!

**Comment by clement911** [comment]
Awesome. Arf, sorry I can't really help with the build as I've never investigated how it's all working.
I approved the build and 6.0.1 is now live!

**Comment by nozzlegear** [comment]
Awesome, thanks for all the work you put into this release! I'll start going through the open issues and pull requests to clean things up soon. I think my next big task for ShopifySharp is updating the documentation which has started to fall behind after the changes to fulfillments.
