### ISSUE TITLE
Support cancelling orders

### ISSUE THREAD

**Issue by thj-dk** [nozzlegear/ShopifySharp#85]
I haven't been able to find any information on how to cancel orders using this API endpoint:
https://help.shopify.com/api/reference/order#cancel

Am I missing something, or is it not supported?

**Comment by nozzlegear** [comment]
Thanks for reporting this! Looks like the cancel orders endpoint was added some time after the order service was written.

**Comment by thj-dk** [comment]
@nozzlegear is it possible to get a new nuget release with this?

**Comment by nozzlegear** [comment]
Sorry, took a little longer to get a couple other changes in with this release. Should be on Nuget now with version 3.3.0.
