### ISSUE TITLE
SmartRetryExecutionPolicy removed without noticeable replacement/explaination

### ISSUE THREAD

**Issue by Skyhighjinks-Dev** [nozzlegear/ShopifySharp#853]
Basically - I am upgrading an application that used ShopifySharp 5.8.1 (or something old like that) and upgrading it to 6.0.1. I've noticed quite a few changes however I am most concerned about the `SmartRetryExecutionPolicy` removal in 6.0.0+

https://github.com/nozzlegear/ShopifySharp/commit/fda0977d58270ee4268701aa5b0164f9faa993e8

I am wondering if `ShopifyService.SetGlobalExecutionPolicy` is even needed anymore or if there are other objects that I have missed which would replace the functionality of `SmartRetryExecutionPolicy` object?

**Comment by nozzlegear** [comment]
Hey! The LeakyBucketExecutionPolicy is our replacement for the SmartRetryExecutionPolicy. It should handle everything the old policy did, along with handling graphQL requests and other edge cases.

--
Josh Harms
