### ISSUE TITLE
ShopifySharp SearchAsync does not bring updated data

### ISSUE THREAD

**Issue by TulikaP41** [nozzlegear/ShopifySharp#854]
I have tried to get the updated data using the SearchAsync function but it brings back stale data even if I try after 30 mins of updating the information. Looks like it only happens with tags.
I have to use SearchAsync because I need filtered data. Is there any fix or alternative? Need some help urgently.

**Comment by TulikaP41** [comment]
After more research, I found that only when the Customer's information is updated, we get updated tags. Can we get a fix to bring the updated tags in ever SearchAsync request

**Comment by clement911** [comment]
This sounds like a bug of the API itself rather than ShopifySharp, which is just a client for the API.
Only Shopify themselves will be able to help with API bugs so you'll have to reach out to them
