### ISSUE TITLE
Can't find support for CancellationRequest and CancellationRequestService

### ISSUE THREAD

**Issue by patrick-lachance** [nozzlegear/ShopifySharp#855]
https://shopify.dev/docs/api/admin-rest/2022-07/resources/cancellationrequest

https://shopify.dev/docs/apps/fulfillment/fulfillment-service-apps/manage-fulfillments#accept-a-cancellation-request

I will implement these myself, but I find curious the fact that it doesn't seem implemented in this library.

**Comment by patrick-lachance** [comment]
Thank you.  It is already implemented on my side.  Same as yours.  I'll remove mine on your next release.

**Comment by nozzlegear** [comment]
Released in 6.1.0+ on Nuget. Thank you!
