### ISSUE TITLE
Trying to buy the Shopify Developer Handbook 

### ISSUE THREAD

**Issue by candreouTrade** [nozzlegear/ShopifySharp#861]
Hi,

I am trying to buy the shopify Developer Handbook but it doesn't seem to accept payments.

Is there a known issue?

Thanks

**Comment by nozzlegear** [comment]
Hey @candreouTrade, sorry to hear you're having trouble! This repo's for the ShopifySharp package so only tangentially related to the book. Could you send me an email at joshua @ nozzlegear.com? I'll try to help you out.

**Comment by candreouTrade** [comment]
Hi Joshua,

I have sent the email as requested.

Thanks,
Chris
