### ISSUE TITLE
ShopifyScriptTag

### ISSUE THREAD

**Issue by Saquibadil** [nozzlegear/ShopifySharp#87]
ShopifyScriptTag does not have display_scope property.

Are you handling it internally. I couldn't create one.

Thanks

**Comment by nozzlegear** [comment]
Thanks for reporting this! The `display_scope` property was added relatively recently. I'll get it in the lib and push out an update either tonight or tomorrow.

**Comment by Saquibadil** [comment]
Hello nozzlegear,

Did you get a chance to fix this yet?

Thanks

**Comment by nozzlegear** [comment]
`DisplayScope` should now be available on the ShopifyScriptTag class with ShopifySharp version 3.4.1. Thanks again for reporting this!
