### ISSUE TITLE
Help with FulfillmentService

### ISSUE THREAD

**Issue by swalsh88** [nozzlegear/ShopifySharp#871]
I'm trying to convert my fulfillment code over to the 2022-07 API.  I've read through the comments on issue #828 and attempted to work with the sample code that was provided.  However, when I execute the code below, I receive a 404 error.  

```
var fulfillment = await fulfillments.CreateAsync(new FulfillmentShipping
{
  Message = "items are shipping!",
  FulfillmentRequestOrderLineItems = lineItems,
  NotifyCustomer = true,
  TrackingInfo = new TrackingInfo
  {
    Company = "UPS",
    Url = "...",
    Number = "..."
  }
});
```

I'm not using a third party fulfilment service.  I (the merchant) want to fulfill our own orders as mentioned in [https://shopify.dev/docs/apps/fulfillment/order-management-apps](url)

Can anyone help me understand what I might be missing?

**Comment by smart222zx** [comment]
Hi.I also have the same problem. Have you solved your problem?

**Comment by nozzlegear** [comment]
Hey, sorry I missed this. This should be possible still after Shopify's fulfillment changes. I'm not at my computer at the moment, but I'll post some example code for you later today that should help.

**Comment by nozzlegear** [comment]
Looks like I forgot to get that example code, @swalsh88 and @smart222zx did you get this working yet?

**Comment by smart222zx** [comment]
> Looks like I forgot to get that example code, @swalsh88 and @smart222zx did you get this working yet?

Yes, I am using HttpClient to directly call the API, but this is just a temporary workaround.

**Comment by nozzlegear** [comment]
Thanks! Can you post the code you're using to create a fulfillment with the HttpClient? I'm curious what it might be doing differently.

**Comment by nozzlegear** [comment]
Here's an example for using ShopifySharp's `FulfillmentOrderService` and `FulfillmentService` to create a fulfillment with ShopifySharp v6.1.2:

```cs
var fulfillments = new FulfillmentService(domain, accessToken);
var fulfillmentOrders = new FulfillmentOrderService(domain, accessToken);
var orderId = 123456;

// Find open fulfillment orders for this order
var openFulfillmentOrders = await fulfillmentOrders.ListAsync(orderId);
openFulfillmentOrders = openFulfillmentOrders.Where(f => f.Status == "open").ToList();

// Fulfill the line items
var lineItems = openFulfillmentOrders.Select(o => new LineItemsByFulfillmentOrder
{
  FulfillmentOrderId = o.Id.Value
  // Optionally specify a list of line items if you're doing a partial fulfillment
  // FulfillmentRequestOrderLineItems = ...
});
var fulfillment = await fulfillments.CreateAsync(new FulfillmentShipping
{
  Message = "items are shipping!",
  FulfillmentRequestOrderLineItems = lineItems,
  NotifyCustomer = true,
  TrackingInfo = new TrackingInfo
  {
    Company = "UPS",
    Url = "...",
    Number = "..."
  }
});
```

Can everyone in here try that and let me know how it works? **Note that you need to have the `write_merchant_managed_fulfillment_orders` permission or else the `fulfillmentOrders.ListAsync` is going to return an empty list or it's going to 404.

**Comment by James-Jackson-South** [comment]
@nozzlegear  I had to enable  `write_third_party_fulfillment_orders` for `FulfillmentOrderService.ListAsync(...)` to work since the location is externally managed. 

Your code has an error. 

```c#
var lineItems = openFulfillmentOrders.Select(o => new LineItemsByFulfillmentOrder
{
  FulfillmentOrderId = o.Id.Value
  // Optionally specify a list of line items if you're doing a partial fulfillment
  // FulfillmentRequestOrderLineItems = ...
});
```
Should be...

```c#
var lineItems = openFulfillmentOrders.Select(o => new LineItemsByFulfillmentOrder
{
  FulfillmentOrderId = o.FulfillmentOrderId.Value
  // Optionally specify a list of line items if you're doing a partial fulfillment
  // FulfillmentRequestOrderLineItems = ...
});
```

I can hit the API successfully following those changes.

**Comment by themultiv3rs3** [comment]
I've set the write_merchant_managed_fulfillment_orders permission and I'm still receiving the 404. I'm running version v6.2. Has anyone been able to get this working?

**Comment by nozzlegear** [comment]
Hey @themultiv3rs3, sorry you're having issues. What specifically is giving you a 404: trying to list fulfillment orders, getting the order itself, or something else?

**Comment by themultiv3rs3** [comment]
when calling:

`var fulfillment = await fulfillments.CreateAsync(new FulfillmentShipping
{
  Message = "items are shipping!",
  FulfillmentRequestOrderLineItems = lineItems,
  NotifyCustomer = true,
  TrackingInfo = new TrackingInfo
  {
    Company = "UPS",
    Url = "...",
    Number = "..."
  }
});`

**Comment by nozzlegear** [comment]
@davitgr @themultiv3rs3 [Solution posted here](https://github.com/nozzlegear/ShopifySharp/issues/914#issuecomment-1678290701)! You need to add the specific fulfillment order line items to the `LineItemsFulfillmentOrder` object.
