### ISSUE TITLE
Reading x-request-id from headers using shopifysharp

### ISSUE THREAD

**Issue by Kai2040** [nozzlegear/ShopifySharp#873]
Hi,
for diagnostic purposes, the Shopify-Support askes us for the “x-request-id” from the request headers of a product update.

Using ShopifySharp, I have no idea where to find those header data.
I can step through my c# code and investigate the returned objects after a product update, but can’t find a x-request-id.

Can you advise how to retrieve the x-request-id?

Thanks a lot!

**Comment by clement911** [comment]
If the API returns an error, then an exception should be thrown and you can use `ShopifyException.RequestId`, which should contain the value from the 'x-request-id' header.

However if no exception is thrown, it's trickier. You will have to create a custom execution policy to access the full HTTP response and inspect the headers.

Here is a sample code for a custom execution policy that you could use (not tested)

```
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ShopifySharp.Infrastructure;

namespace ShopifySharp
{
    public class MyRequestExecutionPolicy : IRequestExecutionPolicy
    {
        public async Task<RequestResult<T>> Run<T>(CloneableRequestMessage request, ExecuteRequestAsync<T> executeRequestAsync, CancellationToken cancellationToken, int? graphqlQueryCost = null)
        {
            var fullResult = await executeRequestAsync(request);

            var requestIdHeader = fullResult.Response.Headers.FirstOrDefault(h => h.Key.Equals("X-Request-Id", StringComparison.OrdinalIgnoreCase));
            var requestId = requestIdHeader.Value?.FirstOrDefault();

            return fullResult;
        }
    }
}

```

You could use it like so:
```
 var productSvc = new ProductService(shop, token);
productSvc.SetExecutionPolicy(new MyRequestExecutionPolicy());
....
```

Then you should be able to put a breakpoint to view the value of the request id.

**Comment by Kai2040** [comment]
Thanks a lot!

 

Your code works like charm and I was able to retrieve the required header data 😊 

 

Thanks again!

 

 

 

Best Regards / Mit freundlichen Grüßen,

 

Kai-Uwe Bracklo

 

===========================

BEO-Systems

Zum Herrenholz 6

26160 Bad Zwischenahn

Tel:  04403 602 16 85

Fax: 04403 602 16 86

Mobil: 0162 2387 396

===========================

Diese E-Mail (und sämtliche Anhänge) enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der bestimmungsgemäße Adressat sind, oder diese E-Mail irrtümlich erhalten haben, informieren Sie uns bitte sofort und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe (auch teilweise) dieser Mail und der darin enthaltenen Informationen ist nicht gestattet. Wenn personenbezogene Daten übermitteln, haben Sie das Recht auf Auskunft, Berichtigung, Löschung Ihrer Daten. Zur Wahrnehmung dieser Rechte können Sie uns jederzeit kontaktieren unter: ***@***.***

 

Von: Clement Gutel ***@***.***> 
Gesendet: Mittwoch, 26. April 2023 23:36
An: nozzlegear/ShopifySharp ***@***.***>
Cc: Kai2040 ***@***.***>; Author ***@***.***>
Betreff: Re: [nozzlegear/ShopifySharp] Reading x-request-id from headers using shopifysharp (Issue #873)

 

If the API returns an error, then an exception should be thrown and you can use ShopifyException.RequestId, which should contain the value from the 'x-request-id' header.

However if no exception is thrown, it's trickier. You will have to create a custom execution policy to access the full HTTP response and inspect the headers.

Here is a sample code for a custom execution policy that you could use (not tested)

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ShopifySharp.Infrastructure;
 
namespace ShopifySharp
{
    public class MyRequestExecutionPolicy : IRequestExecutionPolicy
    {
        public async Task<RequestResult<T>> Run<T>(CloneableRequestMessage request, ExecuteRequestAsync<T> executeRequestAsync, CancellationToken cancellationToken, int? graphqlQueryCost = null)
        {
            var fullResult = await executeRequestAsync(request);
 
            var requestIdHeader = fullResult.Response.Headers.FirstOrDefault(h => h.Key.Equals("X-Request-Id", StringComparison.OrdinalIgnoreCase));
            var requestId = requestIdHeader.Value?.FirstOrDefault();
 
            return fullResult;
        }
    }
}
 

You could use it like so:

 var productSvc = new ProductService(shop, token);
productSvc.SetExecutionPolicy(new MyRequestExecutionPolicy());
....

Then you should be able to put a breakpoint to view the value of the request id.

**Comment by clement911** [comment]
Glad to hear it 🙂
