### ISSUE TITLE
Question about PublishedAt property

### ISSUE THREAD

**Issue by Ni-coco** [nozzlegear/ShopifySharp#874]
Hi! I'm trying to create a product in my shopify store. My issue is that after setting my PublishedAt property and creating the product in my store, the PublishedAt property is changed by the actual time. So i'm not able to publish a product in the future. I've tried to create the product and update the PublishedAt property but it still set the property to the exact time when the "CreateAsync" or "UpdateAsync" method is called. I'm expecting to create a product where his publishing date match the PublishedAt property. The product is well created but published at the time i run the script. Hope i'm clear enough. Thanks for the help.

    var product = new Product()
    {
        Title = "title",
        Vendor = "vendor",
        BodyHtml = "<strong>Good snowboard!</strong>",
        ProductType = "none",
        Tags = "test",
        Variants = new List<ProductVariant> {
            new ProductVariant {
                Price = (decimal)20.00,
                Weight = (decimal)0.45,
                InventoryQuantity = 1,
                InventoryManagement = "shopify",
                }
            },
        PublishedAt = new DateTimeOffset(2023, 04, 27, 19, 0, 0, TimeSpan.FromHours(2))
    };
    Console.WriteLine("1 = " + product.PublishedAt); // return "27/04/2023 19:00:00 +02:00"

    product = await service.CreateAsync(product);
    Console.WriteLine("2 = " + product.PublishedAt); // return "26/04/2023 16:32:34 +02:00"

    product.PublishedAt = new DateTimeOffset(2023, 04, 27, 19, 0, 0, TimeSpan.FromHours(2));
    Console.WriteLine("3 = " + product.PublishedAt); // return "27/04/2023 19:00:00 +02:00"

    product = await service.UpdateAsync((long)product.Id, product);
    Console.WriteLine("4 = " + product.PublishedAt); // return "26/04/2023 16:32:35 +02:00"
}

**Comment by Ni-coco** [comment]
Thanks for your quick reply! If I use the GetAsync method I also get the time and date where i created the product and not the desired DateTimeOffset. I hope I'm not missing something and again thanks for the help.

`var product = new Product()
            {
                Title = "title",
                Vendor = "vendor",
                BodyHtml = "<strong>Good snowboard!</strong>",
                ProductType = "none",
                Tags = "test",
                Variants = new List<ProductVariant> {
                    new ProductVariant {
                        Price = (decimal)20.00,
                        Weight = (decimal)0.45,
                        InventoryQuantity = 1,
                        InventoryManagement = "shopify",
                        }
                    },
                PublishedAt = new DateTimeOffset(2023, 04, 27, 19, 0, 0, TimeSpan.FromHours(2))
            };
            Console.WriteLine(product.PublishedAt); // return "27/04/2023 19:00:00 +02:00"
            product = await service.CreateAsync(product);
            Console.WriteLine(product.PublishedAt); // return "26/04/2023 18:21:12 +02:00"
            product = await service.GetAsync((long)product.Id);
            Console.WriteLine(product.PublishedAt); // return "26/04/2023 18:21:12 +02:00"`

**Comment by nozzlegear** [comment]
Thanks! Just so I understand, are you trying to schedule the product to be published in the future? I’m not sure if that’s possible unless Shopify has changed something recently. I’d assume if you try to set it to a date in the future that Shopify would just roll it back to effectively `DateTime.Now`.

--
Joshua Harms

**Comment by Ni-coco** [comment]
Yes that's what i've wanted to do! Oh ok i thought that the `PublishedAt` property was made for that. Thanks!

**Comment by nozzlegear** [comment]
No problem! Yeah unfortunately the PublishedAt property tells Shopify that, if it has a value, it is currently published and available on the store.

--
Joshua Harms
