### ISSUE TITLE
Refund Object missing the Return Object for Return Webhook

### ISSUE THREAD

**Issue by MicahBredenhorst** [nozzlegear/ShopifySharp#878]
Hello there,

The refund/create webhook contains a Return object that contains an identifier and an admin graphl api id.
However this is not present in the Refund entity.

Am I missing something or is this to be implemented?

An example of what the data looks like as part of the Refund Webhook.
````json
{
    "return": {
        "id": 000000000,
        "admin_graphql_api_id": "gid://shopify/Return/000000000"
    },
}
````

**Comment by nozzlegear** [comment]
Hey! Thanks for letting me know about this. I took a look and it seems like this simply isn’t implemented yet. Most likely the Return object was added to the Refund object at some point after we implemented it, and it just hasn’t been updated yet on our side. If you’re interested in contributing to the library I’d be happy to review and merge a pull request to get this added in! No worries if not though, I’ll make sure this gets implemented as soon.

--
Joshua Harms
