### ISSUE TITLE
PriceRule Property Names Issue

### ISSUE THREAD

**Issue by CrimsonOrion** [nozzlegear/ShopifySharp#889]
Property names are formatted like their json counterparts:
https://github.com/nozzlegear/ShopifySharp/blob/d78c252dd6cd1476d772c99bc754fec842d209e4/ShopifySharp/Entities/PriceRule.cs#L91-L109

PR is pushed with fixes for this file:
https://github.com/nozzlegear/ShopifySharp/pull/888

**Comment by nozzlegear** [comment]
Fixed in 6.1.0
