### ISSUE TITLE
FulfillmentService.CreateAsync has been returning an error 404

### ISSUE THREAD

**Issue by ahmad-qamar** [nozzlegear/ShopifySharp#898]
I've been using the library to process orders for several months now with no issues usually, however about 5-6 days there I've been experiencing the following error while using FulfillmentService.CreateAsync:
 `Error (404 Not Found) Not Found`

I think this is in relation to the [July API changes](https://shopify.dev/docs/api/release-notes/2023-07) from Shopify which has some mentions of mutations to the order fulfillment as well, however I am not too sure what exactly is the cause. 

It is also important to mention that I was using an older version of the library to fulfill the orders beforehand and upon receiving the error, knowing that there were mentions that the previous fulfillment service was going to be deprecated in the near future beforehand, I updated the library to use line items instead. However this too creates a similar error as well.
Previous Error for reference:
`Error (404 Not Found) Shopify returned 404 Not Found, but there was no JSON to parse into an error message.`

Code with the current latest version to reproduce issue:
```cs
var lineItems = new LineItemsByFulfillmentOrder
{
    FulfillmentOrderId = order.Id.Value
};
var fulfillmentShipping = new FulfillmentShipping
{
    NotifyCustomer = true,
    Message = "Test",
    FulfillmentRequestOrderLineItems = new List<LineItemsByFulfillmentOrder> { lineItems }
};
var result = await fulfillmentService.CreateAsync(fulfillmentShipping);
```

The user @smart222zx also seems to be facing a similar issue in #871 around the same time as me. It's been causing downtime for a while now, so it'd be quite helpful to be able to find a resolution as soon as it is possible for you to look into it. Thanks!

**Comment by nozzlegear** [comment]
Sorry, I've been very sidetracked with putting out some Shopify fires of my own as well. Just to be sure, are you aware of Shopify's protected customer data changes they made on July 1st? If you're using API version 2022-10 or later, you need to request access to certain types of customer data. Without that access, the customers, orders and fulfillments endpoints will not return data and their corresponding webhooks will not send either.

**Comment by nozzlegear** [comment]
(I think that's only for public apps though, if you're using a custom app it may not have that restriction. I need to confirm.)

**Comment by nozzlegear** [comment]
@ahmad-qamar I'm going to move this to #871 as there are several issues open right now about the fulfillment service returning 404 and it's getting hard for me to track who I've asked about permissions and code and other things. Please head there! I'll be posting some example code and potential solutions/debugging there soon.
