### ISSUE TITLE
PONumber in Order object

### ISSUE THREAD

**Issue by ihorkolucky** [nozzlegear/ShopifySharp#904]
Lately Shopify added PO Number property to Order object, could it be added to ShopifySharp Order object? https://shopify.dev/changelog/purchase-order-numbers-added-to-orders-draftorders-object.

Thank you!

**Comment by nozzlegear** [comment]
Sure! We can definitely add that. If you want to create a pull request for it I’d be happy to merge it in, otherwise I’ll add it myself in the next few days.

--
Joshua Harms

**Comment by clement911** [comment]
This field is now available in the latest package.

**Comment by ihorkolucky** [comment]
> This field is now available in the latest package.

Thank you very much!
