### ISSUE TITLE
Use Postgresql or Mysql/MariaDB

### ISSUE THREAD

**Issue by vonj** [nozzlegear/ShopifySharp#909]
In the guide mssql is used, but could one use some other database?

**Comment by nozzlegear** [comment]
Hey @vonj! Thanks for the question. I think you should be able to use anything that can hook up to Entity Framework, so MySQL and Postgres would work fine for example. I'm not familiar with MariaDB though and can't say for sure. 

That said, this repository is for the ShopifySharp package and only tangentially related to the book. If you've got any other questions about the book feel free to send me an email instead! [It's in my Github profile](https://github.com/nozzlegear), I try to answer questions about the book or about Shopify in general whenever I have spare time.

**Comment by vonj** [comment]
@nozzlegear I emailed you, might wanna check the spam folder since I run my own email server.
