### ISSUE TITLE
Adding new SKU to Shopify adds to 2 zeros.

### ISSUE THREAD

**Issue by jhunexjun** [nozzlegear/ShopifySharp#911]
Does anyone encountered the same as my issue like when adding new item to Shopify it adds 2 more zeros.
I checked the source code until the time it sends request to Shopify but item no is just the same, i.e. no additional zeros.

Say in my source database, item no. 10004 but when the item is sent to Shopify, the SKU adds 2 more zeros, so it becomes 1000400.
But when downloading the orders, the zeros are not present. So kinda weird.

**Comment by nozzlegear** [comment]
Hey @jhunexjun, I haven't heard about anyone else with this issue, and I don't often work with SKUs myself. It's been a week or so, did you find the source of the problem or is it still an issue for you?

**Comment by jhunexjun** [comment]
I am going to close this ticket as I found out the issue was just in the source code.
