### ISSUE TITLE
Fulfillments

### ISSUE THREAD

**Issue by davitgr** [nozzlegear/ShopifySharp#914]
We are migrating to the new Fulfillment flow, and this is what code we have right now. Please let me know if it is correct to use it and also what permissions are needed. Currently when we use it, we get an error that we don't have the correct permissions. The goal is to fulfill the order and provide the tracking details. Thank you.

Current Code:
`
var service = new FulfillmentService(shop, accessToken);

        var item = new List<LineItemsByFulfillmentOrder>
        {
            new()
            {
                FulfillmentOrderId = orderId
            }
        };

        await service.CreateAsync(
            new FulfillmentShipping
            {
                TrackingInfo = new TrackingInfo
                {
                    Company = carrier,
                    Number = trackingNumber,
                    Url = trackingUrl
                },
                FulfillmentRequestOrderLineItems = item
            });
`

Old Code:

`
var service = new FulfillmentService(shop, accessToken);

await service.CreateAsync(orderId,
            new Fulfillment
            {
                TrackingCompany = carrier,
                TrackingUrl = trackingUrl,
                TrackingNumber = trackingNumber,
                LocationId = locationId
            });
`

**Comment by nozzlegear** [comment]
Hey @davitgr, your code looks correct to me. Does Shopify tell you which permission you're missing? If I had to guess, you probably need the `write_merchant_managed_fulfillment_orders` scope, which is a new one introduced with this fulfillment order-based flow we've all had to migrate to.

**Comment by davitgr** [comment]
The error does not say which one is missing, and I already have that one. Is there any others that I might need? Thank you.

**Comment by nozzlegear** [comment]
They typically tell you which permission scope you need in the error message, so perhaps something else is going on. Let’s start with the basics then:  

 • Which version of ShopifySharp are you using? 
 • Are you getting an exception when you try to run this code? If so could you post the stack trace? 
 • There’s also a RawBody property on the ShopifyException that will contain the entire response Shopify returns when an exception is thrown, that may be useful to look at as well.

--
Joshua Harms

**Comment by davitgr** [comment]
I am getting an exception when I run this code, and the nuget version I have is 6.3.3, below is the stack trace:

`
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass26_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__26`1.MoveNext()
   at ShopifySharp.FulfillmentService.<CreateAsync>d__6.MoveNext()
   at ApiAccessors.Shopify.FulfillmentAccessors.<FulfillOrder>d__0.MoveNext() in C:\parcelrobin\parcelrobin-api\ApiAccessors\Shopify\FulfillmentAccessors.cs:line 25
   at EasyPost.Api.Helpers.ImportFulfillmentEngine.<FulfillShopifyOrder>d__6.MoveNext() in C:\parcelrobin\parcelrobin-api\EasyPost.Api\Helpers\ImportFulfillmentEngine.cs:line 81
`

This is the RawBody property: {"errors":"The api_client does not have the required permission(s)."}

I would really appreciate your help. Thank you.

**Comment by nozzlegear** [comment]
Thanks! Nothing crazy there then, just an unhelpful message from Shopify. It looks like there are a couple other fulfillment access scopes you could add that might resolve this issue, depending on what kind of app you're building and where these fulfillment orders are coming from. I found this post on the Shopify forum that lists a few of them: https://community.shopify.com/c/fulfillment-and-inventory/fulfillment-orders-returning-quot-errors-quot-quot-the-api/m-p/821245#M479

I'm thinking you need `read_assigned_fulfillment_orders` or `read_third_party_fulfillment_orders`, or both.

**Comment by davitgr** [comment]
I have both of them added, and still getting the access error. It's odd because the guide in the Shopify docs seems to show those same permissions. Do you have any ideas of why this might be happening?

**Comment by nozzlegear** [comment]
Unfortunately I don't at the moment, I can only take guesses. It sounds like you're working on a private/custom app, is that correct?

**Comment by davitgr** [comment]
Yes

**Comment by davitgr** [comment]
I got the permissions figured out, but I am getting a 404 error when making that call.

**Comment by nozzlegear** [comment]
Okay, glad you got the permissions working! How did you fix it?

Regarding the 404, I’m pretty sure I know what the problem is there but I’ll need to get back to my computer to find the right code. When you’re creating one of the fulfillment items, one of the objects has a line item property named `item.LineItemId` or something like that, which sounds like the thing you need to use but it is *not* and causes a 404. Instead you need to use `item.Id`.

I think I even added a note to that in the xml/intellisense docs for one of the more recent releases of ShopifySharp.

--
Joshua Harms

**Comment by davitgr** [comment]
I was not updating the scopes in the URL. This is the code I have for creating a fulfilment. Do I need to add line items to the order? Thank you so much for all the help.

`
var service = new FulfillmentService(shop, accessToken);

        var item = new List<LineItemsByFulfillmentOrder>
        {
            new()
            {
                FulfillmentOrderId = orderId
            }
        };

        await service.CreateAsync(
            new FulfillmentShipping
            {
                TrackingInfo = new TrackingInfo
                {
                    Company = carrier,
                    Number = trackingNumber,
                    Url = trackingUrl
                },
                FulfillmentRequestOrderLineItems = item
            });
`

**Comment by nozzlegear** [comment]
No problem! Yes I think you need to add the line items to the `LineItemsByFulfillmentOrder` object here. What you're doing in that code you've provided is telling Shopify you want to create a fulfillment for one fulfillment order, but you're not telling it which line items in the fulfillment order you want to include. I believe that's why they're returning a 404.

Here's what your code should look like:

```cs
var service = new FulfillmentService(shop, accessToken);
var fulfillmentOrder = await SomeFulfillmentOrderLookupMethod(fulfillmentOrderId);

var items = new List<LineItemsByFulfillmentOrder>
{
    new()
    {
        FulfillmentOrderId = fulfillmentOrderId,
        // Add this fulfillment order's line items to the fulfillment
        FulfillmentRequestOrderLineItems = fulfillmentOrder.FulfillmentOrderLineItems.Select(item => new FulfillmentRequestOrderLineItem
        {
            Id = item.Id.Value,
            // You can partially fulfill the line item by setting the quantity, or you can leave it null to fulfill the entire line item
            // Use item.FulfillableQuantity to determine how much of the line item is left to fulfill
            Quantity = item.FulfillableQuantity 
        })
    }
};

await service.CreateAsync(
    new FulfillmentShipping
    {
        TrackingInfo = new TrackingInfo
        {
            Company = carrier,
            Number = trackingNumber,
            Url = trackingUrl
        },
        FulfillmentRequestOrderLineItems = items
    });
```

**Comment by davitgr** [comment]
I tried the code you have, and again I'm getting a 400 Not Found. Is there anything else that I can try?

This is the code:

```
public static async Task FulfillOrder(long orderId,
        string shop,
        string accessToken,
        string? carrier,
        string? trackingNumber,
        string? trackingUrl,
        List<FulfillmentLineItem> lineItems)
    {
        var fulfillmentRequestOrderLineItems = new List<FulfillmentRequestOrderLineItem>();
        foreach (var lineItem in lineItems)
        {
            if (long.TryParse(lineItem.LineItemId, out var lineItemId))
                fulfillmentRequestOrderLineItems.Add(
                    new FulfillmentRequestOrderLineItem
                    {
                        Id = lineItemId,
                        Quantity = lineItem.Quantity
                    });
        }

        var service = new FulfillmentService(shop, accessToken);

        await service.CreateAsync(
            new FulfillmentShipping
            {
                TrackingInfo = new TrackingInfo
                {
                    Company = carrier,
                    Number = trackingNumber,
                    Url = trackingUrl
                },
                FulfillmentRequestOrderLineItems = new List<LineItemsByFulfillmentOrder>
                {
                    new()
                    {
                        FulfillmentOrderId = orderId,
                        FulfillmentRequestOrderLineItems = fulfillmentRequestOrderLineItems
                    }
                }
            });
    }
```

**Comment by nozzlegear** [comment]
Everything here looks correct, but if anything's "wrong" I'd bet that it's this line:

`Id = lineItemId`

I see you're doing a parse to get that value, so it must be a string; I'm guessing it's coming from a form or something, but do you know where the original value is being set? If it's the [`FulfillmentOrderLineItem.LineItemId`](https://github.com/nozzlegear/ShopifySharp/blob/236a3704db6f0b2cdd69c3bae38c15d749c85b8a/ShopifySharp/Entities/FulfillmentOrderLineItem.cs#L25), that will cause a 404. It sounds like exactly what Shopify _wants_ you to send, but to create a fulfillment you actually need to send `FulfillmentOrderLineItem.Id`.

**Comment by davitgr** [comment]
I am using LineItem.Id. Isn't that the correct value?

**Comment by nozzlegear** [comment]
Hmm I don't think it is but I'm not positive, maybe it works. What I do is list the fulfillment orders for the order (one order can have multiple fulfillment orders) and then loop over each fulfillment order's `FulfillmentOrderLineItems` list:

```cs
foreach (var lineItem in fulfillmentOrder.FulfillmentOrderLineItems)
{
  // Use the main Shopify order's product/variant list to look up the actual name/title of the line item
  var itemName = LookUpLineItemName(item.VariantId);
  // Note: This object has a LineItemId property -- this is not what Shopify's API wants when fulfilling a fufillment order.
  // Shopify wants the line item's API Id. Very confusing!
  var itemId = item.Id;

  <li>
    <label>@itemName</label>
    <input type="checkbox" name="lineItems[]" value="@item.Id" />
  <li>
}
```

**Comment by davitgr** [comment]
Thank you for bearing with me. From the response below, I am using the id for the line item to create the fulfillment. Is that the Id that should be used?


"line_items": [
        {
            "id": 10549561163982,
            "admin_graphql_api_id": "gid://shopify/LineItem/10549561163982",
            "fulfillable_quantity": 1,
            "fulfillment_service": "manual",
            "fulfillment_status": null,
            "gift_card": false,
            "grams": 1542,
            "name": "rough brook (has weight)",
            "price": "8.00",
            "price_set": {
                "shop_money": {
                    "amount": "8.00",
                    "currency_code": "USD"
                },
                "presentment_money": {
                    "amount": "8.00",
                    "currency_code": "USD"
                }
            },
            "product_exists": true,
            "product_id": 6807575625934,
            "properties": [],
            "quantity": 1,
            "requires_shipping": true,
            "sku": "",
            "taxable": true,
            "title": "rough brook (has weight)",
            "total_discount": "0.00",
            "total_discount_set": {
                "shop_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                },
                "presentment_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                }
            },
            "variant_id": 40434314215630,
            "variant_inventory_management": null,
            "variant_title": null,
            "vendor": "ParcelRobin",
            "tax_lines": [
                {
                    "channel_liable": false,
                    "price": "0.50",
                    "price_set": {
                        "shop_money": {
                            "amount": "0.50",
                            "currency_code": "USD"
                        },
                        "presentment_money": {
                            "amount": "0.50",
                            "currency_code": "USD"
                        }
                    },
                    "rate": 0.0625,
                    "title": "Massachusetts State Tax"
                }
            ],
            "duties": [],
            "discount_allocations": []
        }
    ]

**Comment by nozzlegear** [comment]
No problem, I'm happy to help! That response is from the order object, right? I don't believe these are the same line items, I'm thinking that in Shopify's API the `Order.LineItem.Id` and `FulfillmentOrder.LineItem.Id` have different values, even though they both refer to the same line item. 

Can you try to use the fulfillment order's API to list the fulfillment orders for this same order, and look at the line items on the fulfillment order? That should tell us if the values for the two IDs are different.

```cs
var fulfillmentOrderService = new FulfillmentOrderService(domain, accessToken);
var fulfillmentOrders = await fulfillmentOrderService.ListAsync(shopifyOrderId);

// Inspect the fulfillment orders here and the FulfillmentOrderLineItems properties on each
```

**Comment by davitgr** [comment]
When checking the fulfillmentOrders, I see that the response I posted above was using the LineItemId for the Id, but the Id is different in this response. Should I be using the Id from this response?

<img width="1891" alt="image" src="https://github.com/nozzlegear/ShopifySharp/assets/1237362/1b3a1d62-a5fe-4a05-8b0c-87943885051e">

**Comment by nozzlegear** [comment]
Yes, try the one from this latest response! I think that will work. 

--
Joshua Harms

**Comment by davitgr** [comment]
Thank you so much for all your help @nozzlegear, it works now. Just to point out for anyone who references this issue, you need to use the FulfillmentOrderId and not the regular order Id when fulfilling an order, otherwise that will also return a not found error.

**Comment by nozzlegear** [comment]
Awesome, so glad you got it working! Let me know if you have trouble with anything else, I'm always happy to help.
