### ISSUE TITLE
How can i provide option for store selection during install app?

### ISSUE THREAD

**Issue by ysunil702** [nozzlegear/ShopifySharp#915]
From shopify store how can i provide shopify shop selection option as follow. 

Currently I have prepared following URL for installation app.
redirect ="https://" + shop +  "myshopify.com" + "/admin/oauth/authorize?client_id=" + clientId + "&scope=" + appScope +
                    "&redirect_uri=" + redirectUri;

Kindly see the attachment for the expected output.
https://prnt.sc/IE3T84N9zr8e

**Comment by nozzlegear** [comment]
Hey @ysunil702, unfortunately this isn't possible. The store selection you see in that screenshot is part of the Shopify App Store website, and not anything we can do as app developers. However, once you publish your app to the Shopify App Store, a user who presses the Install App button from the app store page will see that store selection.

By the way, if you're looking to build an OAuthinstallation URL, ShopifySharp can do that for you:

```cs
var scopes = new [] { "read_orders", "read_products" };
var redirectUri = "https://example.com/shopify/handle-redirect";
var userShopifyDomain = model.MyShopifyDomain;

// Create OAuth installation url
var installationUrl = AuthorizationService.BuildAuthorizationUrl(
  scopes,
  userShopifyDomain,
  myShopifyAppKey,
  redirectUrl
);
```
