### ISSUE TITLE
API Versioning Strategy / v7.0 Release Planning

### ISSUE THREAD

**Issue by StrangeWill** [nozzlegear/ShopifySharp#918]
First off, amazing library, makes using Shopify much easier, we got some plans to throw some PRs up for some stuff we need, can't wait to give back. My team appreciates everyone's contributions to this project.

I was going over some access policy changes (mostly with the Assets API and the headache that causes), and realized I don't really know when we'll be able to move from 2023-01

Shopify's 12 month lifespan of their API are a bit rough, leaving us in almost a constant state of moving forward -- leaving ShopifySharp an even shorter window of validity on a specific version. Is there any sort of a rough plan on when we'll see 7.0 and which API version it will cover? If so it would be _super_ awesome to have that in the readme (and if I've missed the ticket some kind of wiki link to it or something? Just better visibility).

Funny enough it isn't the API changes between versions that bite us, but the constant access policy changes (and in our case, the completely lackluster method of being able to request it -- we got a Google Form link, no ability to do it through the Partner Portal).

**Comment by clement911** [comment]
Welcome @StrangeWill .

The readme should be updated. The current version of ShopifySharp (6.3.3) is actually using the API version 2023-07 and we try to stay as close to the latest stable version as possible.

If you use the `GraphService`, you can use whatever API version you want by specifying the version in the constructor.

**Comment by StrangeWill** [comment]
Sounds good, thanks for the feedback on that, it at least lets me know we're pushing ahead with new versions pretty rapidly so that works for us, we can eyeball whatever the version is in the code if we need to.
