### ISSUE TITLE
SmartCollectionRules: Add ConditionObjectId Property

### ISSUE THREAD

**Issue by alonghurst** [nozzlegear/ShopifySharp#933]
Hi

I'm trying to create a `SmartCollection` via the `SmartCollectionService` but I'm having trouble setting `SmartCollection.Rules` to use a value from a product metafield.

When I set the properties on newly created `SmartCollectionRules` objects the API returns `'(422 Unprocessable Entity) base: metafield definition id is invalid or missing.`.

The Shopify documentation (https://shopify.dev/docs/api/admin-rest/2023-07/resources/smartcollection) refers to a `condition_object_id` property:

_condition_object_id: The object id that points to additional attributes for the collection rule. This is only required when using metafield definition rules._

Adding the following property to `SmartCollectionRules` has solved the issue for me (both read and write of SmartRules referring to product metafields):

```
[JsonProperty("condition_object_id")] 
public long? ConditionObjectId { get; set; }
```

Do you have any plans to add a feature like this into an upcoming release? Would you like me to raise a PR for the change?

Thanks

**Comment by alonghurst** [comment]
@nozzlegear want me to raise a PR for this change?

**Comment by nozzlegear** [comment]
@alonghurst Sure! That'd be great.
