### ISSUE TITLE
Shipping Line ID (missing property)

### ISSUE THREAD

**Issue by onyamegatron** [nozzlegear/ShopifySharp#957]
Hi there, I have seen a question from 2018 that asked about the shipping line not having the property for shipping line ID,
The reasoning back then is that the property was not officially documented by shopify. I think the latest version [documents it](https://shopify.dev/docs/api/admin-graphql/2023-10/objects/ShippingLine)
I was wondering if it's possible to add to shopifysharp.  

Thank you!

**Comment by nozzlegear** [comment]
Thanks for the request! Looks like it's documented now so I'd be happy to add it.

**Comment by clement911** [comment]
This will be available in the next release.
