### ISSUE TITLE
Shopify issues 

### ISSUE THREAD

**Issue by Cybermoth866** [nozzlegear/ShopifySharp#959]
I am wondering can a shopify store be packed up then opened under a new email to avoid the fees?

I have had multiple people review my store promising sales. I still havent had a sale

**Comment by nozzlegear** [comment]
Hey @Cybermoth866. Theoretically I suppose you could use the api to export most of your store's data and then import it into a new store, but you'd have to write a lot of code to get that right. I'm not sure it'd be worth your time. I'd check the Shopify App Store to see if anyone else has already made an app for exporting and importing stores, or try reaching out to Shopify's support staff to see if they'll help you out with your problem.

Good luck!
