### ISSUE TITLE
Add comment to an order

### ISSUE THREAD

**Issue by stiankraggerud** [nozzlegear/ShopifySharp#96]
Is it possible to get this feature?

**Comment by ernestogutierrez** [comment]
Do you mean adding notes to an order?


This example taken from the [Shopify Sharp Documentation](https://github.com/nozzlegear/ShopifySharp#orders)
```
var service = new ShopifyOrderService(myShopifyUrl, shopAccessToken);
var order = await service.GetAsync(orderId);

order.Notes = "Test notes.";
order = await service.UpdateAsync(order);
```

**Comment by nozzlegear** [comment]
@ernestogutierrez has it right, the preferred way to add a comment to an order is to use the `Notes` property.
