### ISSUE TITLE
Listing products in English 

### ISSUE THREAD

**Issue by jakenuts** [nozzlegear/ShopifySharp#962]
I tried adding /en to my shopify url but it gets stripped out in BuildShopUri. Is there any way to pass the language path to ShopifySharp such that calls like ListAsync use the /en path in the request?

**Comment by nozzlegear** [comment]
Hey! That behavior is expected based on how I wrote the base ShopifyService class. I might be wrong, but I don't think the REST API can be localized using those language paths like the storefront API can. Happy to be wrong about that though, I'll give it a test and see what happens.

**Comment by jakenuts** [comment]
Oh, that would make sense. Thanks!

**Comment by jakenuts** [comment]
Sorry to bother you again, but I was wondering how you generated the graphql entities? When I learned that I would need to switch apis to get translations I went looking for a graphql schema for products/variants/related to feed into various tools and all my attempts at introspection produce massive files with some special (non-standard?) bits that break each tool in their own way (ZeroQL, Apollo, etc). 

Thanks!

**Comment by nozzlegear** [comment]
Ah actually all of the generated schemas are handled by Clement. @clement911 would you mind giving a brief overview on how you generate those schemas? I think you explained it somewhere here in the repo but I haven't been able to find it back, and I've been meaning to ask you just for my own curiousity.

**Comment by nozzlegear** [comment]
Ah that’s awesome, thanks! I could definitely use that in other projects. I’ll set up a Github Action so you and I can trigger the regeneration from the actions page, so you don’t have to run the test manually to get the changes.

--
Joshua Harms

**Comment by clement911** [comment]
Oh ok, I'm not too sure how you will set this action but honestly using the unit test to trigger the regeneration has been working quite well. All you need to do is remove the `Skip` attribute and run it. Then add the `Skip` attribute again so that it doesn't run on each CI build.

**Comment by nozzlegear** [comment]
I think I can do it if I mess around with the test category, like we use to exclude/include dotnet framework tests. I'll give it a shot tonight and create a pull request for it.

@jakenuts Let us know if you have any questions about the schema generation!

**Comment by jakenuts** [comment]
That absolutely does, thank you @clement911  & @nozzlegear 😊
