### ISSUE TITLE
Updating Product Variant Inventory Quantity Fails

### ISSUE THREAD

**Issue by mchandschuh** [nozzlegear/ShopifySharp#97]
#### Context
I want to set the inventory quantity of a single product variant. To do this, I first fetched the variant, updated the inventory quantity property, and then used the service's update method.

Here's a snippet of what my code actually does:
```csharp
var variantService = new ShopifySharp.ShopifyProductVariantService(credentials.ShopUrl, credentials.Token);
var variant = await variantService.GetAsync(message.ShopifyProductVariantId);
variant.InventoryQuantity = message.NewQuantity;
await variantService.UpdateAsync(variant);
```

---
#### Error
Shopify's API complains about `inventory_quantity_adjustment` being sent and it not equaling the difference between `old_inventory_quantity` and `inventory_quantity`. I suspect the issue here is that we're serializing the zero values and Shopify's API is seeing this as us *specifying* a value, but in reality we didn't want to send those values.

---
#### Potential Solution
My first thought at a solution is to update the `ShopifyProductVariant` entity to have `OldInventoryQuantity` and `InventoryQuantityAdjustment` be `int?` and then we can tell JSON.Net to not serialize default values for these properties. Figured I'd check with @nozzlegear before going too far down this path, perhaps I'm doing something incorrectly?

Thanks!

**Comment by mchandschuh** [comment]
#### Work around
An easy work around is to compute the correct values for `OldInventoryQuantity` and `InventoryQuantityAdjustmen` as follows:
```csharp
variant.OldInventoryQuantity = variant.InventoryQuantity;
variant.InventoryQuantityAdjustment = message.NewQuantity - variant.InventoryQuantity;
```

**Comment by nozzlegear** [comment]
Thanks for the report and the work around! This is discussed more in-depth in #62, where I'm planning to change almost all `int` properties to `int?` to better support object updates. Changing the types is a breaking change though, so it's scheduled for the 4.0 release of ShopifySharp – starting that soon!
